### ISSUE TITLE
Media Library: App spontaneously cycling through media items 

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-iOS#14938] opened 2020-09-17 21:21 UTC
### Expected behavior

Opening the a site's media library should display a grid of media items.

### Actual behavior

Opening the a site's media library causes multiple screens to be pushed onto the stack (the app seems to cycle through each media item until it reaches the last item).

| <img alt="Screen recording showing that upon navigating to the Media Library, the app starts cycling through the items in the library" width="300" src="https://user-images.githubusercontent.com/1898325/93609457-e5446a00-f999-11ea-9cdc-bd56bc7bb243.gif"> |
| - |

### Steps to reproduce the behavior

This can only be reproduced using a app built using Xcode 12 (that is to say, using the iOS 14 SDK). It's not reproducible using a build made using Xcode 11, even if the app is running on a device with iOS 14 installed.
- I've seen it on multiple WordPress.com account and on multiple WordPress.com sites
- It's not 100% reproducible, sometimes I only see it on the 2nd or 3rd visit to the Media Library screen (that said, it's quite easy to reproduce for me)
- I've only tested on one iOS device

**Comment by frosty** [comment] 2020-09-18 12:45
I'm currently unable to reproduce this one... do you literally just open Media and then tap an item in the library?

**Comment by guarani** [comment] 2020-09-18 14:26
I wasn't able to reproduce again on the Test Flight 15.7 build (strangely enough), but then I compiled from Xcode 12 using the following commit and was able to get it working: https://github.com/wordpress-mobile/WordPress-iOS/commit/e37dce417fb7ca59cd2aaeb5014fee5b76974c94

**Comment by guarani** [comment] 2020-09-18 14:33
> I'm currently unable to reproduce this one... do you literally just open Media and then tap an item in the library?

@frosty yes, although today I could only reproduce building from Xcode 12 (not when using the Test Flight build, see comment above). I've also added a screen recording to the issue.

**Comment by rehpa** [comment] 2020-12-28 22:39
I suffer from this with the current 16.3 app in the app store.  Makes the app unusable for me without the ability to add media.


![WP_app_issue](https://user-images.githubusercontent.com/31808563/103247056-c94e4e00-4922-11eb-95f6-052e28d1b5b8.gif)

**Comment by guarani** [comment] 2020-12-28 23:17
Thanks for reporting, @rehpa!

**Comment by startuptester** [comment] 2021-01-08 23:04
I am not able to replicate this on iPhone 12 Pro with either the 16.3 App Store or 16.4.0.3 TestFlight build. I'll keep trying to hunt down specifics.

**Comment by guarani** [comment] 2021-04-06 14:01
> If you open media it starts scrolling through all the images like a slide show. Basic things like tables aren’t supported…

<sub>Source: https://link.reviewbot.io/review/sbCqmjhx5</sub>

**Comment by frosty** [comment] 2021-04-08 09:18
@guarani Are you able to tell which method might be responsible for pushing the new view controllers? There's a single push in `MediaLibraryViewController`, and there's also `displayPreviewController` in `WPMediaPickerViewController` that performs a push of a preview VC.

**Comment by guarani** [comment] 2021-05-19 20:05
Apologies @frosty for the super late reply here. I debugged this once in the past and the triggering of push view controller seemed to be coming from inside the `MediaPicker-iOS` library. Specifically, I think the `tableView:didSelectRowAtIndexPath:` delegate method of the table view was being called repeatedly IIRC, which was strange 🤔.

I tried today to reproduce but had no luck. I'm on an iPhone 11 with iOS 14.5 running WPiOS 17.3 from the App Store. I tried the same site I used in the issue above, as well as a number of other sites.

Below is a video of me trying to reproduce today and failing. I'm not sure if this bug has gone away or if it's just hard to reproduce.

https://user-images.githubusercontent.com/1898325/118877072-fd1f1580-b8bb-11eb-9ad1-bd25d181a7a2.MP4

**Comment by guarani** [comment] 2021-05-19 20:11
I also did a quick search looking for app reviews that report this issue, using words like "media" or "slide show" and turned up nothing (except the one reported in an [above comment](https://github.com/wordpress-mobile/WordPress-iOS/issues/14938#issuecomment-814145356)).

**Comment by fluiddot** [comment] 2021-10-19 13:55
I'm experiencing the exact same issue on version `18.4` using an iPhone 11 (iOS 14.2), right after entering the media library, it automatically navigates to each single media item.

https://user-images.githubusercontent.com/14905380/137924311-dda8e7d9-48d1-4a91-8462-8d4d41a21e0d.MP4

**Comment by fluiddot** [comment] 2021-10-19 15:55
After debugging the issue, I found out that in my case, [the `shouldSelectItemAtIndexPath` method](https://github.com/wordpress-mobile/MediaPicker-iOS/blob/4b34a7f7031c6b95476857f53f390948c811025a/Pod/Classes/WPMediaPickerViewController.m#L1030) is being called for every media item in the list of [`WPMediaPickerViewController`](https://github.com/wordpress-mobile/MediaPicker-iOS/blob/develop/Pod/Classes/WPMediaPickerViewController.m) which leads to navigation when calling the delegate:
https://github.com/wordpress-mobile/WordPress-iOS/blob/f7fdc17eb3f72a99572c1e5c761c349974d53942/WordPress/Classes/ViewRelated/Media/MediaLibraryViewController.swift#L539

From the Apple documentation about the `shouldSelectItemAtIndexPath` method it's stated the following:

> The collection view calls this method when the user tries to select an item in the collection view. It does not call this method when you programmatically set the selection.

So looks like the app is actually receiving tapping events and therefore the navigations are expected. I'm wondering what's doing the OS to simulate the user is tapping all the elements 🤔 .

**Stacktrace:**
<img width="565" alt="Screenshot 2021-10-19 at 17 49 48" src="https://user-images.githubusercontent.com/14905380/137947596-9a6decf1-6e4a-4d07-a34d-58bb2874b4b4.png">

**Comment by kean** [comment] 2023-11-09 22:10
It was re-implemented from the ground up in https://github.com/wordpress-mobile/WordPress-iOS/issues/21457; closing. Shipping the fix in 23.7.

**Closed as completed by kean** 2023-11-09 22:10 UTC
Labels: [Pri] Low, [Pri] Medium, Media
