### ISSUE TITLE
Jetpack: Not all site sections appear when first viewing Jetpack site in My Sites

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#6230] opened 2016-11-24 11:46 UTC
### Expected behavior

I expect that when I select a Jetpack-connected site on the My Sites tab, I'll see all of the sections for that site in the menu, including:

- Menus
- Sharing
- People

### Actual behavior

After logging in to a WordPress.com account with a Jetpack-connected site and opening that site on the My Sites tab, the sections listed in the site's menu are the same as a non-Jetpack self-hosted site:

![photo 23-11-2016 19 24 05](https://cloud.githubusercontent.com/assets/8658164/20597355/03c136fc-b23b-11e6-814c-e026cf49be2b.png)

After I went back to the site picker and reselected the site, the full menu appeared:

![photo 23-11-2016 19 24 13](https://cloud.githubusercontent.com/assets/8658164/20597358/0cfac288-b23b-11e6-9f98-a7621558ab2f.png)

Note that this also causes a strange state where the "Menus" section is selected in the sidebar but it's showing the "Settings" section (the section that was open before I went back to the site picker).

### Steps to reproduce the behavior

1. Open the app logged out
2. Log in to a WordPress.com account with a Jetpack-connected site
3. Open the My Sites tab
4. Select the Jetpack site. Result: The site's menu (the sidebar on an iPad) does not include the Menus, Sharing, or People sections.
5. Go back to the site picker
6. Reselect the Jetpack site. Result: The full site menu appears with all expected sections.

##### Tested on iPad mini, iOS 10.1, WPiOS 6.7 beta (TestFlight)

**Comment by elibud** [comment] 2017-05-19 16:16
Hi @rachelmcr, I was unable to replicate this on 7.6, I even set up my Jetpack blog as primary so it would go straight to that one after logging in, but all the options were there. Can you check if this is still a problem for you with the current version?
Thanks a lot.

**Comment by elibud** [comment] 2017-05-23 17:29
@hoverduck since @rachelmcr is AFK, could you double check this one for me? Tahnks

**Comment by hoverduck** [comment] 2017-05-23 17:33
Yeah, I can't reproduce this on 7.7.0.20170522.  I'll go ahead and close it.

Thanks!

**Closed by hoverduck** 2017-05-23 17:33 UTC
Labels: Jetpack, [Pri] Low, [Type] Broken Window, [Type] Bug

**Comment by elibud** [comment] 2017-05-23 17:37
Thank you @hoverduck for checking that so super fast :)
