### ISSUE TITLE
NSMallocException: Failed to grow buffer

### ISSUE THREAD

**Issue by loremattei** [wordpress-mobile/WordPress-iOS#14178] opened 2020-05-25 07:48 UTC
**Sentry Url**: https://sentry.io/share/issue/f9e98652222541a4b2680cb4345dc8f0/
**User Count**: 95
**Count**: 378
**First Release**: 14.7.0.3
**First Seen**: 2020-05-05T07:43:36Z
**Last Seen**: 2020-05-25T05:03:33Z
**24 Hours**: 7
**30 Days**: 371

```
NSMallocException: Failed to grow buffer
  File "UIImage+AlamofireImage.swift", line 103, in UIImage.af_inflate
  File "Request+AlamofireImage.swift", line 204, in DataRequest.image
  File "Request+AlamofireImage.swift", line 96, in DataRequest.imageResponseSerializer
  File "<compiler-generated>", line null, in @callee_guaranteed
  File "ResponseSerialization.swift", line 150, in DataRequest.response<T>
  File "<compiler-generated>", line null, in @callee_guaranteed
...
(22 additional frame(s) were not displayed)
```

**Comment by bummytime** [comment] 2020-05-25 17:04
A handful of AF Image malloc exceptions centered around `ReaderDetailViewController` starting on May 5th. @yaelirub could this be related to Private atomic support in #13770?

**Comment by yaelirub** [comment] 2020-05-25 18:46
@bummytime , since AFImage framework was added during private Atomic it could be related. Will investigate

**Comment by yaelirub** [comment] 2020-05-25 18:53
Priority high as it is a new crash

**Comment by yaelirub** [comment] 2020-05-27 01:06
Updating status here before creating a PR for a workaround:
This is a known issue (since 2018) in AlamofireImage. It happens when trying to inflate images with really large sizes. They recommend a workaround [here](https://github.com/Alamofire/AlamofireImage/issues/332#issuecomment-590014391)

**Comment by bummytime** [comment] 2020-05-28 11:37
@yaelirub thanks for the update. Out of curiosity, were you able to quantify what a large image is?

**Comment by yaelirub** [comment] 2020-05-28 17:04
@bummytime , I was not. I was however able to see multiple memory warnings in the events

**Comment by designsimply** [comment] 2020-06-13 02:04
**Events in the last 90d:** 398
**Events in the last 11d for 14.9:** [zero](https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=release&field=os&field=device&field=culprit&name=All+Events&project=1438083&query=issue.id%3A1647770657+release%3A14.9.0.4&sort=-timestamp&statsPeriod=30d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1) in 14.9 since it was released on 2020-06-01
**Users affected in the last 90d:** 100
<sub>https://sentry.io/share/issue/f9e98652222541a4b2680cb4345dc8f0/</sub>

I noticed the crash [for this specific issue](https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=release&field=os&field=device&field=culprit&name=All+Events&project=1438083&query=issue.id%3A1647770657&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1) has come and gone:

<img width="1026" alt="Screen Shot 2020-06-12 at Jun 12 7 59 27 PM" src="https://user-images.githubusercontent.com/1119271/84557319-439ce500-ace7-11ea-94f6-73af9a62b183.png">

There is another one that seems to have come up in it's place, but the numbers of crashes are still pretty low:

**Events in the last 90d:** 98
**Events in the last 11d for 14.9:** [10](https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=release&field=os&field=device&field=culprit&name=All+Events&project=1438083&query=issue.id%3A1695131933+release%3A14.9.0.4&sort=-timestamp&statsPeriod=30d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1) in 14.9 since it was released on 2020-06-01
**Users affected in the last 90d:** 34
<sub>https://sentry.io/share/issue/14014cc5a0b34630bf23a7a466d687f9/</sub>

[90-day graph for issue.id:1695131933](https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=release&field=os&field=device&field=culprit&name=All+Events&project=1438083&query=issue.id%3A1695131933&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1):

<img width="1022" alt="Screen Shot 2020-06-12 at Jun 12 8 02 11 PM" src="https://user-images.githubusercontent.com/1119271/84557365-cd4cb280-ace7-11ea-87b2-33169d4acb2e.png">

@yaelirub is it still worth keeping this GitHub issue open for this crash?

**Comment by yaelirub** [comment] 2020-06-13 03:27
Probably not @designsimply

**Comment by designsimply** [comment] 2020-09-02 19:04
Decided to keep this one open to explore the workaround because the issue is related to media uploads which are an important part of the app experience even though we're currently seeing low volume and it's a known issue in AlamofireImage and has been flagged by AFI as low priority. We can close it later if it's deemed not worth the effort to try the workaround but I am hoping someone with experience managing media in our apps can help give a 2nd opinion.

**Events in the last 90d:** 385
**Users affected in the last 90d:** 126
<sub>WORDPRESS-IOS-37XR: https://sentry.io/share/issue/14014cc5a0b34630bf23a7a466d687f9/</sub>

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=release&field=os&field=device&field=culprit&name=All+Events&project=1438083&query=issue.id%3A1695131933&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1">![image](https://user-images.githubusercontent.com/1119271/92024187-af08b880-ed12-11ea-8dad-f3f8ac19ce22.png)</a>

<sup>(also see internal reference: pbArwn-Lo-p2)</sup>

**Comment by designsimply** [comment] 2020-09-30 23:28
Low numbers are holding steady for this one.

**Events in the last 90d:** 312
**Users affected in the last 90d:** 86
<sub>WORDPRESS-IOS-37XR: https://sentry.io/share/issue/14014cc5a0b34630bf23a7a466d687f9/</sub>

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=release&field=os&field=device&field=culprit&name=All+Events&project=1438083&query=issue.id%3A1695131933&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1">![image](https://user-images.githubusercontent.com/1119271/94749995-598bef80-0342-11eb-9224-cb24bd549041.png)</a>

**Comment by designsimply** [comment] 2020-12-10 01:20
Checked the numbers again and there are no recorded cases past v15.9 but we're still seeing a few crashes in 15.9 and below.

<sub>WORDPRESS-IOS-37XR: https://sentry.io/share/issue/14014cc5a0b34630bf23a7a466d687f9/</sub>

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=release&field=os&field=device&field=culprit&name=All+Events&project=1438083&query=issue.id%3A1695131933&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1">![image](https://user-images.githubusercontent.com/1119271/101708722-18ebd900-3a4b-11eb-8b7a-b2fd03334791.png)</a>

**Closed** 2024-12-20 13:08 UTC
Labels: [Type] Crash, [Pri] Low, Media
