### ISSUE TITLE
Plugins: There is a message `Error loading plugins` when we try to search for plugins or check the popular category

### ISSUE THREAD

**Issue by poojashetty18** [wordpress-mobile/WordPress-iOS#16056] opened 2021-03-10 10:19 UTC
### Expected behavior
The plugin page should load without any errors

### Actual behavior
The popular plugin are and the search option throws the `Error loading plugins` message even though the site is connected to Jetpack

### Steps to reproduce the behavior
1. Head to My Site> Plugins 
2. Scroll down to 'Popular' plugins and you will see the error
3. Enter any random plugin on the search bar and the error occurs

##### Tested on [device], iOS [version], WPiOS [version]
Tested on 
- iPhone X
- iOS version 14.4
- WPiOS 16.8

![IMG_1092](https://user-images.githubusercontent.com/44837596/110614167-1159de80-81b8-11eb-816e-b6181d56b161.PNG)
![IMG_1093](https://user-images.githubusercontent.com/44837596/110614176-1323a200-81b8-11eb-97ec-54591d35165c.PNG)

**Comment by poojashetty18** [comment] 2021-03-10 10:20
Also reported on 3808103-zen

**Comment by iamgabrielma** [comment] 2021-03-11 03:03
Another case on 3800511-zen

**Comment by yaelirub** [comment] 2021-03-11 04:23
@leandroalonso , we will need a hotfix for this most likely. Can you please address this?
From my investigation it seems that this https://github.com/wordpress-mobile/WordPressKit-iOS/blob/c8faa1585050f6937f9315b78356a03f7f40189e/WordPressKit/PluginDirectoryServiceRemote.swift#L122

returns:
` - debugDescription : "Expected to decode Dictionary<String, Any> but found an array instead."`

Since it's not happening on Android, I would check to see how they are making the call. Not sure what changed in the last release. Call on Android if that matters https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/a097f94c384cc146c9a187144ea73eb1ab64c893/example/src/androidTest/java/org/wordpress/android/fluxc/release/ReleaseStack_WPOrgPluginTest.java#L74

**Comment by leandroalonso** [comment] 2021-03-11 14:19
@yaelirub I'm pretty sure something changed on the API side. This affects older versions of the app and this code wasn't touched for quite some time.

@emilylaguna will help us with it.

**Comment by yaelirub** [comment] 2021-03-11 15:18
>This affects older versions of the app and this code wasn't touched for quite some time.

It affects production and beta as well

**Comment by emilylaguna** [comment] 2021-03-11 16:48
**What's going on?**
Looked into this, found that the real error is: `"Parsed JSON number <81.84055644729803> does not fit in Int.`

which happens when processing the `PluginDirectoryEntry.rating` property. 

The rating property is set to Int and some of the other plugin API's return the rating as an Int still.  

**The Fix** 
~Changing it to a Double fixes this issue and still supports the other plugin API's whose ratings are returned as Ints ([Example](https://public-api.wordpress.com/wpcom/v2/plugins/featured))~

I am reaching out to .org to see if we can fix this on the API side of things.

**Causes**
I also looked into any recent changes that could have caused this:
- The API file has not be updated since 2018. 
- I don't see any to WordPressKit or the plugin code that could cause this.

I suspect maybe something was changed in Elasticsearch that could have caused this. Not sure at this time.

**Comment by dd32** [comment] 2021-03-12 02:44
> I am reaching out to .org to see if we can fix this on the API side of things.

Just noting that I've corrected the root issue and it looks like the API is returning correctly again.

The average rating on dotorg is a x.y number, like 4.1, which is then converted to a percentage for this API.. Unfortunately, I had changed something that while it worked in theory, had resulted in extra precision, so a raw 4.11 would be converted to 82.2% instead of 4.1 => 82%.

I've additionally added a int cast to the API code to ensure that this field value never changes again: https://github.com/WordPress/wordpress.org/commit/1ed8c6633ed3b6aec56d246c209320c3fcc12a53

**Comment by leandroalonso** [comment] 2021-03-12 12:15
Thanks, @dd32 and @emilylaguna for fixing that!

Tested in the current WPiOS version and older versions and the issue is now fixed.

**Closed as completed by leandroalonso** 2021-03-12 12:15 UTC
Labels: [Pri] High, Jetpack Plugins
