### ISSUE TITLE
Empty stats when app is brought to foreground from a background state

### ISSUE THREAD

**Issue by twstokes** [wordpress-mobile/WordPress-iOS#18260] opened 2022-04-02 21:18 UTC
### Expected behavior
Stats to show actual values.

### Actual behavior
Stats show zeroed values.

### Steps to reproduce the behavior
I could reproduce this with days, weeks, months, and years.

**Preconditions:** A website that has more than zero views for the unit of time selected.

1. Go to Stats
2. Tap Days at the top (or Weeks, Months, Years)
3. Observe the values for the current day
4. Tap the < arrow to go back in time one day
5. Switch to another app or the Home screen (don't force-exit WPiOS)
6. Bring WPiOS to the foreground
7. Observe that the stats for the day in step 4 are shown and accurate
8. Tap the > arrow to go to the current day
9. Observe that the stats show zeroed values

**First load**

| Yesterday | Today |
| ---------- | ------ |
| <img width="622" alt="Screen Shot 2022-04-02 at 16 56 52" src="https://user-images.githubusercontent.com/2092798/161401449-ebd50a49-8e4b-4793-b5de-26866a1c3457.png"> | <img width="622" alt="Screen Shot 2022-04-02 at 16 57 03" src="https://user-images.githubusercontent.com/2092798/161401451-d6e043e3-8a1f-4661-a350-70d17a6f9c62.png"> |

**After switching to another app and then bringing WPiOS into the foreground**

| Yesterday | Today |
| ---------- | ------ |
| <img width="622" alt="Screen Shot 2022-04-02 at 16 57 12" src="https://user-images.githubusercontent.com/2092798/161401477-04986d82-93aa-4e0b-a3c5-1f14f67547a3.png"> | <img width="622" alt="Screen Shot 2022-04-02 at 16 57 17" src="https://user-images.githubusercontent.com/2092798/161401483-8104c715-ec9d-4f8d-8594-bec17a8f9f96.png"> |

**Comment by staskus** [comment] 2023-01-19 13:24
Looks to be the duplicate of https://github.com/wordpress-mobile/WordPress-iOS/issues/19688, closing this particular issue, linking the issues together

**Closed as completed by staskus** 2023-01-19 13:24 UTC
Labels: [Pri] Low, Stats
