### ISSUE TITLE
Clicking on block inserter pushes UI off the screen

### ISSUE THREAD

**Issue by thabotswana** [wordpress-mobile/WordPress-iOS#16470] opened 2021-05-11 10:20 UTC
It was reported in 3977960-zen that when user clicks the block inserter button to try to add an image, the editor is pushed off the top of the screen.

### Expected behavior
You should be able to click the block inserter and add any block.

### Actual behavior
When the block inserter button is clicked, the UI is pushed off the screen.

### Steps to reproduce the behavior
I wasn't able to reproduce this on iPhone SE, iOS 14.5.1, WPiOS 17.2

Screen recording provided by the user:

https://user-images.githubusercontent.com/35628116/117792127-4b447100-b24b-11eb-8c51-3402d9bc3281.mov

**Comment by startuptester** [comment] 2021-05-12 01:59
Thank you for reporting. Like you, I am not able to repro this at all on iPhone 12 Pro. I'll leave it open for a bit to see if we get more reports/ details

**Comment by hypest** [comment] 2021-05-12 07:37
Can't reproduce on iPhone 12 and iPhone SE simulators either. Yeah, let's leave it open for a few days as @startuptester mentioned.

**Comment by mchowning** [comment] 2021-06-24 17:50
Closing this since we can't reproduce it, but if it pops up for anyone else please go ahead and reopen this.

**Closed as completed by mchowning** 2021-06-24 17:50 UTC
Labels: Posting/Editing
