### ISSUE TITLE
Login error screen does not resize on rotation

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#4921] opened 2016-03-08 13:35 UTC
### Expected behavior
The error screen should layout properly after a rotation like so:
![img_9461](https://cloud.githubusercontent.com/assets/373903/13603051/19632e06-e500-11e5-86df-52b74999a7e1.PNG)

### Actual behavior
The error screen does not layout properly after a rotation:
![img_9460](https://cloud.githubusercontent.com/assets/373903/13603053/1b7da108-e500-11e5-9b56-ac361004aaeb.PNG)

### Steps to reproduce the behavior
1. Attempt to log in with the device in portrait.
2. Receive error message for whatever reason.
3. Rotate device.
4. Error screen does not resize/layout.

##### Tested on iPhone 6s Plus, iOS 9.2.1, WPiOS 6.0 beta

cc: @kurzee, @kwonye as I'm not sure if this is from #4442 or will be resolved with #4474.

**Comment by aerych** [comment] 2016-03-08 14:19
Lots of changes happening in the login/signin code with #4912.  This is something that can be addressed there.

**Comment by kurzee** [comment] 2016-03-08 16:53
This is definitely the same issue I found in https://github.com/wordpress-mobile/WordPress-iOS/pull/4442. I believe @kwonye ran into the same issues @aerych saw with how the frames of the views were nearly hardcoded. Since his work is moving to autolayout and UIStackViews, it should take care of itself.

**Comment by aerych** [comment] 2016-06-27 17:12
The issue is resolved in the new NUX implemented in #5126. Since we'll be switching to the new flow (eventually) marking this one closed.

**Closed by aerych** 2016-06-27 17:13 UTC
Labels: NUX, [Type] Bug
