### ISSUE TITLE
Discover: cannot follow recently deleted tag 

### ISSUE THREAD

**Issue by startuptester** [wordpress-mobile/WordPress-iOS#14901] opened 2020-09-15 04:37 UTC
### Expected behavior
A user deleting their tags from the list of followed tags should be able to re-add one they deleted by mistake 

### Actual behavior
An error message says they are already following the tag. The only way to re-add it is to return to the new screen on the Discover tab. 

### Steps to reproduce the behavior
1. Use an account that is not following any tags

2. In Discover, follow a list of tags
![IMG_8FFC9F4225A1-1](https://user-images.githubusercontent.com/66104034/93165601-b9935c80-f6d9-11ea-9406-72906277e287.jpeg)

3. Delete each tag on the list of followed tags 
![IMG_B84B4CF84621-1](https://user-images.githubusercontent.com/66104034/93165615-bf893d80-f6d9-11ea-8beb-a405e95afb73.jpeg)

4. Re-add one you just deleted 
![IMG_346AEE6DB1AE-1](https://user-images.githubusercontent.com/66104034/93165846-5f46cb80-f6da-11ea-8100-d7f3219c3959.jpeg)
![IMG_10953B548D67-1](https://user-images.githubusercontent.com/66104034/93165862-666dd980-f6da-11ea-9b3d-da993b803701.jpeg)

##### Tested on [device], iOS [version], WPiOS [version]
iPad (2019), iOS 13.7, WPiOS 15.7 beta

**Comment by yaelirub** [comment] 2020-09-15 23:14
@emilylaguna , can you please look into this one ?

**Comment by emilylaguna** [comment] 2020-09-17 13:48
I was able to reproduce this using the steps above, and I believe this issue is related to: https://github.com/wordpress-mobile/WordPress-iOS/issues/14900

The reason is because if you rapidly delete all your local followed tags, and they still exist on the server, when you go to add them again the API will error out and tell us it already exists.

**Comment by leandroalonso** [comment] 2021-03-25 17:26
Given this issue is also related to removing tags faster, I'm closing it.

If we get any reports from our users we can reassess them.

**Closed as completed by leandroalonso** 2021-03-25 17:26 UTC
Labels: [Pri] Low, Reader
