### ISSUE TITLE
Aztec: Editing an existing published post & canceling removes post from list

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#6515] opened 2017-01-31 15:48 UTC
I don't remember the exact cause for this but it does temporarily remove it from the list.

**Comment by jleandroperez** [comment] 2017-02-01 13:12
Closing this one since it's actually a duplicate of #6534 (already fixed via #6539 / pending review).

Thanks!!

**Closed by jleandroperez** 2017-02-01 13:12 UTC
Labels: Aztec, [Type] Bug
