### ISSUE TITLE
Unhelpful error screen when creating a new account.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#3117] opened 2015-01-28 20:59 UTC
When walking though the new acct NUX I encountered an error. The error screen tells me nothing about what kind of error it was.
 
![img_0051](https://cloud.githubusercontent.com/assets/1435271/5946812/2e9f4598-a6fe-11e4-9af3-cf29925be6f3.PNG)

Yep.

**Comment by sendhil** [comment] 2015-02-12 02:19
@aerych - do you remember how you reproduced it?

**Comment by aerych** [comment] 2015-02-12 02:22
I think I was entering some bad values in the form. I didn't recall at the time exactly what they were :(  I can try to reproduce

**Comment by sendhil** [comment] 2015-02-14 01:52
@aerych :+1:

**Comment by SergioEstevao** [comment] 2015-04-30 08:58
Unable to reproduce so I'm going to close this down.

**Closed by SergioEstevao** 2015-04-30 08:58 UTC
Labels: bug, nux
