### ISSUE TITLE
[GlobalStep] Adding a Self-Hosted Site results in a Login screen for the entered credentials.

### ISSUE THREAD

**Issue by wptester9845** [wordpress-mobile/WordPress-iOS#13992] opened 2020-04-24 14:35 UTC
### Description
After the user successfully adds a Self-Hosted Site, the Login confirmation screen is displayed as if the user had just logged in to the credentials of the Self-Hosted Site rather than showing a confirmation screen that the Self-Hosted Site was added successfully.

### Reproduction Rate
4/4 100%

### Expected behaviour
Adding a Self-Hosted Site successfully should result in an accurate confirmation screen.

### Actual behaviour
Adding a Self-Hosted Site successfully displays a Login confirmation screen.

### Steps to reproduce the behaviour
1. Install and launch WordPress 14.7
2. Login to a valid account.
3. Navigate to the “My Site” tab.
4. Press the + (plus) button.
5. Select the “Add self-hosted site” option.
6. Enter a valid Self-Hosted site and its credentials.
##### Tested on the following
iPhone 7+ (12.0.1)

#### Please see the attached video for more information
[iOSAddSiteLogin.zip](https://github.com/wordpress-mobile/WordPress-iOS/files/4529502/iOSAddSiteLogin.zip)

### Submitted by:
Luis Pimenta

**Comment by designsimply** [comment] 2020-04-25 05:04
@ScoutHarris I checked Unified Login & Signup project designs and it shows a different login confirmation screen which I think solved this problem. If you agree, let's close this issue since the design will be updated soon as part of the Unified Login & Signup project.

14.7.0.2 TestFlight beta | Unified Login & Signup i3
---|---
<img src="https://user-images.githubusercontent.com/1119271/80271671-92cb7f80-867f-11ea-8b33-cd3cdb25e6b8.PNG" width="200" alt="IMG_3935">|<img width="300" alt="Screen Shot 2020-04-24 at Apr 24 10 56 22 PM" src="https://user-images.githubusercontent.com/1119271/80271643-513ad480-867f-11ea-85c9-a8ac74221ad4.png">
<p style="clear:both;"><sup>Design source: "Site Address" section at pbArwn-mA-p2.</sup></p>

**Comment by ScoutHarris** [comment] 2020-04-27 17:52
Hey @designsimply .

I'm not real clear what the issue is here. This isn't a bug. The login epilogue displays because, when adding a self-hosted site this way, you still go through the login process for that site.

This flow isn't changing with the new auth, so this view will still be displayed. It will just look different as you noted.

| Old | New |
|--------|-------|
| ![old_login_epilogue](https://user-images.githubusercontent.com/1816888/80403780-69784280-887d-11ea-9f85-667566fd8e3c.png) | ![new_login_epilogue](https://user-images.githubusercontent.com/1816888/80403789-6e3cf680-887d-11ea-83f2-374d696ba5c4.png) |

In any case, I am still closing this as a non-issue.

**Closed by ScoutHarris** 2020-04-27 17:52 UTC
Labels: Login, [Type] Bug
