### ISSUE TITLE
EXC_BREAKPOINT: scrollViewToTop

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-iOS#20519] opened 2023-04-12 19:54 UTC
**Sentry Url**: https://sentry.io/share/issue/7921b55110284e07a9244bd525c1aa66/
**User Count**: 109
**Count**: 189
**First Release**: 21.5.1.0
**First Seen**: 2023-01-24T10:49:43Z
**Last Seen**: 2023-04-12T14:32:21Z
**24 Hours**: 4
**30 Days**: 95
**LogID:** C285A2FA-3C3D-45C2-9175-A6D4D47711DF

```
EXC_BREAKPOINT: scrollViewToTop
  File "NotificationsViewController.swift", line null, in value
  File "NotificationsViewController.swift", line 2074, in NotificationsViewController.scrollViewToTop
  File "<compiler-generated>", line 2073, in NotificationsViewController.scrollViewToTop
  File "<compiler-generated>", line null, in NotificationsViewController.tableView.getter
  File "NotificationsViewController.swift", line 2074, in NotificationsViewController.scrollViewToTop
  File "<compiler-generated>", line 2073, in NotificationsViewController.scrollViewToTop
  File "UINavigationController+Helpers.swift", line 19, in UINavigationController.scrollContentToTopAnimated
  File "<compiler-generated>", line null, in UINavigationController.scrollContentToTopAnimated
  File "WPSplitViewController.swift", line 405, in WPSplitViewController.popToRootViewControllersAnimated
  File "WPSplitViewController.swift", line 411, in WPSplitViewController.popToRootViewControllersAnimated
  File "<compiler-generated>", line null, in WPSplitViewController.popToRootViewControllersAnimated
  File "WPTabBarController.m", line 410, in -[WPTabBarController tabBarController:shouldSelectViewController:]
  File "main.swift", line 7, in main
...
(30 additional frame(s) were not displayed)
```

**Comment by dcalhoun** [comment] 2023-04-17 15:40
@vanessamaartinstt I'm looking to catch up on this issue that appears to have been partially triaged. Would you please share the rationale for the `[Pri] High` labeling? Merely looking to gain context and improve my understanding. Thanks! 🙇🏻 

@hassaanelgarem from reviewing the stack trace and the first occurrence 3 months ago
in release 21.5.1.0, I wonder if this crash originates from changes in https://github.com/wordpress-mobile/WordPress-iOS/pull/19817. Would you please be willing to investigate this issue given it is labeled as high priority? Thank you! 🙇🏻 

Removing the `Requires Triage` label now that this has a priority label and assignee.

**Comment by hassaanelgarem** [comment] 2023-04-18 02:22
@dcalhoun Upon further examination, I don't think it's related to #19817. I found [another sentry crash](https://a8c.sentry.io/share/issue/5ac722d1efd149158c48112e33698b11/) that shows this issue occurring as early as 20.8.

I am unable to reproduce this, but I think I understand why this crash is happening. I'll create a fix for this soon.

**Comment by vanessamaartinstt** [comment] 2023-04-19 14:18
> [dcalhoun](/dcalhoun)

Hi David! Explaining a little more about the priority, I've consider the area affected "Notifications" and the type of issue "Crash". Even with the low~medium number of users affected, the crash is the worst experience a user could have. Now, with @hassaanelgarem's further investigation and difficulty to reproduce on https://github.com/wordpress-mobile/WordPress-iOS/pull/20556, and also considering it has been around for a while, I will change the priority label to medium. Thanks for tagging me on this! And let me know if you would consider a different method to attribute priority. 🙇‍♀️

**Comment by guarani** [comment] 2023-04-19 20:35
> this issue that appears to have been partially triaged.

Good catch! I forgot to finish triaging this. Thanks for the follow-up, @dcalhoun!

**Comment by jkmassel** [comment] 2024-08-27 23:18
This issue is no longer being reported by Sentry

**Closed as completed by jkmassel** 2024-08-27 23:18 UTC
Labels: [Type] Crash, [Pri] Medium, Notifications
