### ISSUE TITLE
Reader Comments: In dark mode, sometimes the comment text is a dark rather than light color. 

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#15650] opened 2021-01-15 15:33 UTC
Reported in p1610649717000800-slack-p2-mobile.

Sometimes reader comment text color is not updated for dark mode.  
<img width="383" alt="Screen Shot 2021-01-15 at 9 15 23 AM" src="https://user-images.githubusercontent.com/1435271/104744295-51e63000-5712-11eb-8a95-56ba98b01710.png">

In this case, the iOS device is configured to automatically update it's appearance between light and dark, and the app follows the system default.  Per the report this has been happening in the evenings.  Given these two things it might be that the system's automatic switch between light and dark is not being picked up correctly by the comment cells.

**Comment by kean** [comment] 2024-11-15 14:57
Closing as duplicate of https://github.com/wordpress-mobile/WordPress-iOS/issues/23536

**Closed as completed by kean** 2024-11-15 14:57 UTC
Labels: [Pri] Medium, Comments
