### ISSUE TITLE
Post format can be set to `false` in My Sites > Settings > Default Post Format

### ISSUE THREAD

**Issue by lancewillett** [wordpress-mobile/WordPress-iOS#4323] opened 2015-09-30 17:22 UTC
Site:
ryan.boren.me 

Screenshot:
<img src="https://cloud.githubusercontent.com/assets/66797/10200776/26bbdcb8-675d-11e5-80b2-177d6fce40da.png" width="480" />

> ryan.boren.me pre-dates post formats. Looks like it doesn’t have a default post format set, resulting in false being displayed instead of Standard.

Could this be a REST API issue maybe?

**Comment by rachelmcr** [comment] 2015-12-20 16:52
Thanks for the note about the REST API. :) I queried the REST API for this blog and confirmed that this is an issue with the API returning a "false" value for the default post format (rather than an issue in the app). I opened a REST API issue at wpcom-7644 and am closing this issue, since it needs to be resolved in the API itself.

**Closed by rachelmcr** 2015-12-20 16:52 UTC
Labels: Site Settings, [Type] Bug
