### ISSUE TITLE
[Offline Posting] Duplicate posts may appear in the Post List

### ISSUE THREAD

**Issue by shiki** [wordpress-mobile/WordPress-iOS#12800] opened 2019-10-29 17:49 UTC
## Expected behavior

Only one post is shown. 

## Actual behavior

Two posts are shown. The other one disappears after pulling to refresh. 

### Steps to reproduce the behavior

1. Go offline.
2. Create a post and save it as a draft. 
3. While still in the Post List, go online.
4. As soon as you see that the draft is getting uploaded, tap between Published and Drafts lists multiple times. Do this until it finishes uploading. 
5. Go back to the Drafts list and look for the duplicated post. 

It may take a few tries to reproduce the issue. 

<img src="https://user-images.githubusercontent.com/198826/67794282-0464a100-fa42-11e9-826d-96c27c2f67e1.png" width="320">

Tested on iPhone XS, iOS 12.4.1, WPiOS `develop` (d2d9ada)

## Notes 

This may be related to https://github.com/wordpress-mobile/WordPress-iOS/issues/5364 and https://github.com/wordpress-mobile/WordPress-iOS/pull/6102. 

As far as I can tell, only one post is created on the server. This looks like a Core Data concurrency issue.

**Comment by designsimply** [comment] 2019-10-30 18:55
I think this is a duplicate of https://github.com/wordpress-mobile/WordPress-iOS/issues/12164. @jklausa should we close https://github.com/wordpress-mobile/WordPress-iOS/issues/12164 since this issue is already in an `In Progress` list in the `Offline Support: Posting [iOS]` project?

**Comment by yaelirub** [comment] 2019-10-31 02:47
Thanks @designsimply, you're right. I'm closing the other issue as duplicate.

**Comment by jklausa** [comment] 2019-10-31 13:09
@designsimply ah, I knew that issue seemed familiar but I couldn't find #12164 in my cursory search. Glad someone here has better memory and/or search skills :)

@yaelirub Thanks for closing the other one!

**Comment by jklausa** [comment] 2019-10-31 13:57
So, I was looking into this yesterday and today morning and I'm pretty sure now that @shiki was correct and this is indeed a Core Data issue, as no duplicate posts get made on the backend.

What's going on here, is that _sometimes_ when a post is being uploaded, from the _main thread context_'s point of view, there are suddenly now _two_ posts — with the same contents, but otherwise separate objects. This usually get's fixed on relaunch if the post gets uploaded succesfully, but I also once saw it persist across relaunches. So this screams multi-thread Core Data weirdness to me.

I spend some time trying to change the posting logic to change how they handle the multi-threaded nature of them, but mostly made things worse. 

If I can't make the root-cause disappear by the end of day, I'll write a workaround to just filter out the post in the post list.

**Comment by shiki** [comment] 2019-10-31 17:19
@jklausa I'm not well versed with how `AbstractPost.revision`works but I wonder if we're seeing 2 posts because the first one is the `original`, and the other is the `original.revision`. 

Perhaps the deleted revision on this block was not synchronized to the main context right away? 

https://github.com/wordpress-mobile/WordPress-iOS/blob/d9d5e904b76aeffee9c60f396b09d8aa2cffb919/WordPress/Classes/Services/PostService.m#L270-L276

**Comment by designsimply** [comment] 2020-04-10 23:31
While testing 14.6 beta, I found that duplicates appear in the Pages List as well and when publishing online, particularly, if you use the X at top left to leave a new draft then tap "Save Draft" in the bottom sheet. ([1m47s](https://cloudup.com/c87pHd7AvYO))

<img src="https://user-images.githubusercontent.com/1119271/79029264-e05cce00-7b50-11ea-8395-4910914795c3.PNG" width="200" alt="IMG_3628">
<p style="clear:both;"><sup>Tested with WPiOS 14.6.0.1 TestFlight beta on iPhone 6S iOS 13.3.1.</sup></p>

@shiki or @leandroalonso, should this note be filed as a separate issue since it's online vs offline and Pages not Posts?

**Comment by guarani** [comment] 2020-08-10 12:39
This bug seems to occur when the device is online as well, using these steps to reproduce:

1. Navigate to the site screen
2. Tap the create button (the floating action button) and select blog post
3. Add any content and tap Publish followed by Publish Now
4. Immediately tap the Posts button to show the post list screen
5. Notice that the newly added post appears twice in the post list

<kbd><img width="250" src="https://user-images.githubusercontent.com/1898325/89352462-2bf83200-d682-11ea-9a0d-d7c786868d2d.gif"></kbd>

@shiki or @designsimply do you agree I can add the above to the main issue comment? Would it be appropriate to remove this from offline posting or leave it as-is?

**Comment by leandroalonso** [comment] 2020-08-10 12:48
@guarani I'd say that a new issue for online makes more sense IMHO.

Anyway, duplicated posts it's something that I've seen popping up on different occasions and multiple times. :( This one apparently involves the FAB button... so maybe the prev fixes doesn't apply to it somehow?

**Comment by yaelirub** [comment] 2020-08-10 18:06
+1 to what Leandro said. 
> do you agree I can add the above to the main issue comment? 

I say yes. 

>Would it be appropriate to remove this from offline posting or leave it as-is?

I'd say remove it

**Comment by shiki** [comment] 2020-08-11 21:08
I agree with Yael and Leandro. 😄 Thanks, @guarani!

**Comment by guarani** [comment] 2020-08-12 02:55
Thanks for the input, y'all! I've reopened the separate issue, https://github.com/wordpress-mobile/WordPress-iOS/issues/14572 👍

**Comment by kean** [comment] 2024-05-04 16:05
Fixed in https://github.com/wordpress-mobile/WordPress-iOS/pull/23152

**Closed by kean** 2024-05-04 16:05 UTC
Labels: [Type] Bug, Posts List, [Status] Needs Testing
