### ISSUE TITLE
Comments: markup is showing for dynamically updated comments in the Comments list

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-iOS#13260] opened 2020-01-22 09:44 UTC
Steps to reproduce:

1. Go to Comments.
1. Pick any comment and leave a reply.
1. Go back to the Comments screen and wait for the list to dynamically update.
1. Tap on the new comment.

**Result:** comments that are dynamically updated while viewing the Comments list show markup surrounding the comment unless you pull-to-refresh the list before opening it. ([1m1s](https://cloudup.com/c_5myifzN5N))

<img src="https://user-images.githubusercontent.com/1119271/72883132-00eb5980-3cc1-11ea-8d0a-d97057557829.png" width="270" alt="markup-showing-for-dynamically-updated-comments-wpios-14 0 0 0-testflight-beta">
<sup>Tested with WPiOS 14.0.0.0 TestFlight beta on iPhone 6S iOS 13.3.</sup>

**Comment by emilylaguna** [comment] 2020-01-28 21:23
Related issue: https://github.com/wordpress-mobile/WordPress-iOS/issues/10015

**Comment by emilylaguna** [comment] 2020-01-30 19:29
Closing as a duplicate of https://github.com/wordpress-mobile/WordPress-iOS/issues/10015

**Closed by emilylaguna** 2020-01-30 19:29 UTC
Labels: Beta Request, Comments, [Status] Duplicate, [Type] Bug
