### ISSUE TITLE
Site Icon / Gravatar: Unable to proceed from cropping screen

### ISSUE THREAD

**Issue by frosty** [wordpress-mobile/WordPress-iOS#11297] opened 2019-03-19 15:02 UTC
### Expected behavior

When I'm setting a site icon or gravatar and I take a photo, I expect to be able to crop the image and then use it.

### Actual behavior

After taking a photo through the site icon or gravatar media picker, I'm taken to the cropping screen, but the "Use" button in the top right instantly disappears. I then can only go back and select another image.

![ScreenRecording_03-19-2019 14-55-03 2019-03-19 14_59_35](https://user-images.githubusercontent.com/4780/54616697-f7b5ae80-4a57-11e9-8e19-cf1fca19eeef.gif)

### Steps to reproduce the behavior

* Tap a blog's site icon, or the gravatar on the Me screen
* From the media picker, tap the camera cell to take a photo.
* Take a photo. When you're taken to the cropping screen, notice the Use button disappear in the top right.

It looks like this is happening due to the initial `if` statement at the top of `updateSelectionAction` in `WPNavigationMediaPickerViewController`, so the bug may need fixing there. But I opened the issue here as it primarily affects WPiOS.

##### Tested on iPhone X, iOS 12, WPiOS 12.0

**Comment by rachelmcr** [comment] 2019-03-27 17:01
This is a duplicate of https://github.com/wordpress-mobile/WordPress-iOS/issues/9685. I'm going to close this duplicate but add some of the details to that report.

**Closed by rachelmcr** 2019-03-27 17:01 UTC
Labels: Media, [Type] Bug
