### ISSUE TITLE
Page Order Always Set to 0

### ISSUE THREAD

**Issue by sandymcfadden** [wordpress-mobile/WordPress-iOS#4157] opened 2015-08-14 14:31 UTC
When you edit a Page in the iOS app it will always change the Page Order for that page back to 0.
I used wp-admin to set the page order or a page went to the app and edited the page and saved it. When I checked in wp-admin again the page order was back to 0.

**Comment by rachelmcr** [comment] 2015-12-01 14:24
I tested this in the latest 5.8 beta and couldn't reproduce the issue on a wp.com or self-hosted site. In both cases, I edited a page in WP Admin and set the page order, saved the page, edited the page in the app, saved it in the app, and the page order was retained.

I'm closing this issue, but please reopen if the issue persists for you.

**Closed by rachelmcr** 2015-12-01 14:24 UTC
Labels: Editor, [Type] Bug
