### ISSUE TITLE
Editor: 404 when previewing scheduled post on site with mapped domain

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#3350] opened 2015-02-27 00:06 UTC
Documenting an [issue reported in the forums](https://ios.forums.wordpress.org/topic/preview-of-scheduled-posts) and reproduced courtesy of @sendhil and one of his sites with a mapped domain. 

Steps to reproduce:
1. Be signed into the app with a WordPress.com site with a mapped domain.
2. Create a new post with a title and some content
3. Schedule the post for a future date. 
4. Publish the scheduled post. 
5. Tap on the post and then tap the Preview button.

You expect to see a preview of the scheduled post. Instead you see your site's 404 page. 

`WPPostPreviewController` tries to display a post's preview via the post's permalink.  If the post is private, a draft, or scheduled, `WPPostPreviewController` first tries to authenticate to the site by making a POST request to login.php, passing login credentials and redirecting to the post's permalink.  

In the case of a site with a mapped domain, the domain of the site's login URL might be different from the domain of the post's permalink. 

You can reproduce the 404 error in a desktop browser by taking the following steps:
1. Create a new post and schedule it for a future publish date. 
2. Copy the post's permalink.  Notice that the permalink points to the mapped domain. 
3. Sign out.
3. Open a new browser tab, then browse to a URL pointing to your login.php with a redirect to the scheduled post's permalink:

> http://example.wordpress.com/login.php?redirect_to=http://example.com/a/scheduled/post-path

Notice that you see the 404 page, but you did successfully login. 

If you view the scheduled post in wp-admin and click the preview link you'll notice that the mapped domain is _not_ used.  Interesting that. 

Its been a while [since there was a significant change](https://github.com/wordpress-mobile/WordPress-iOS/blame/develop/WordPress/Classes/ViewRelated/Post/PostPreviewViewController.m#L189) to the relevant code making it difficult to believe this bug could have been unnoticed for so long. 

I'm not sure if the bug is more of a routing issue on the server side or if the client should check that the permalink's domain matches the login URLs domain.  The latter would seem strange since the permalink is supposed to be ... well ... canonical.

@bummytime @diegoreymendez thoughts?

**Comment by aerych** [comment] 2015-02-27 00:11
Quick follow up, I mentioned in the forum thread that I was not able to reproduce the behavior on every mapped site I tested.  To clarify I tested two sites apart from Sendhil's.  One of these two sites has some rather hackish redirects applied to it so I don't feel like it was a good test case. It was going to be broken regardless, and the error I got was not a 404 error.  The other of these two sites did not seem to have the error the first time I tested, but on a subsequent test (paranoia ftw!) I did get the 404 error.

**Comment by rachelmcr** [comment] 2015-11-27 15:35
I tested this in the latest 5.8 beta and couldn't reproduce, but I'm hesitant to close this issue since the previous tests didn't all reproduce the issue. @aerych what do you think? Can you still reproduce this?

**Comment by aerych** [comment] 2015-11-30 16:50
@sendhil, might need your help to test this one again.

**Comment by designsimply** [comment] 2020-05-29 18:02
Re-opening because this was recently reported again by a user:

> I am currently unable to use the View and Preview functions on my Wordpress App on iPad. I receive a 404 page not found error each time.

* WPiOS 14.8.2
* WordPress.com Premium with a custom domain
* iOS 13.4.1
* iPad Pro 9.7-inch (WiFi/Cellular) (iPad6,4)

<sup>(internal references: p4a5px-2zK-p2 2987505-zen h/t melindahelt)</sup>

**Comment by designsimply** [comment] 2020-05-30 14:39
Closing because `WPPostPreviewController` doesn't exist any more and noting we should re-investigate. (p4a5px-2zK-p2#comment-11010)

Moved to https://github.com/wordpress-mobile/WordPress-iOS/issues/14220.

**Closed by designsimply** 2020-05-30 14:39 UTC
Labels: Mobile Request, Posting/Editing, [Type] Bug
