### ISSUE TITLE
Reblog with only self-hosted site crashes

### ISSUE THREAD

**Issue by kwonye** [wordpress-mobile/WordPress-iOS#3374] opened 2015-03-08 04:30 UTC
In `[RebloggingViewController configureNavbar]`, `[BlogService lastUsedOrFirstWPcomBlog]` is nil and is being passed into `NSMutableAttributedString` resulting in an NSInvalidArgumentException.

My suggested fix is to disable the reblog action button throughout the app if the user does not have a visible WPcom blog.

**Comment by aerych** [comment] 2015-03-09 20:10
Hi @kwonye Thanks for opening this!  Looks like we either forgot to hide the buttons on the post list or there was a regression somewhere.

**Comment by kwonye** [comment] 2015-03-09 20:26
@aerych, no problem at all! I actually found out that it's not quite as simple as I originally posted.

What happened was I added two types of accounts: WPCom and self-hosted. I then disabled the WPCom accounts in the 'My Sites' sitepicker. So when I go back to the reader, I am still logged-in to a WPCom account, but none of them are visible, which is what the `RebloggingViewController` looks for.

I have submitted a pull-request as a possible fix for this.

**Comment by aerych** [comment] 2015-03-09 20:52
> What happened was I added two types of accounts: WPCom and self-hosted. I then disabled the WPCom accounts in the 'My Sites' sitepicker. So when I go back to the reader, I am still logged-in to a WPCom account, but none of them are visible

That's a great bug to find!

> I have submitted a pull-request as a possible fix for this.

Yah, #3375 :). I'll leave some feedback there. 

This issue reminded me that we'd meant to keep the comment and like buttons visible for self-hosted users, and just disable the features  I'll be making a few edits too. ;)

**Comment by aerych** [comment] 2015-03-11 14:11
Closed in #3388

**Closed by aerych** 2015-03-11 14:11 UTC
Labels: bug, Reader
