### ISSUE TITLE
Connecting to Jetpack /  Signing in from Stats appears partially broken.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#7339] opened 2017-06-06 22:38 UTC
It seems that attempting to sign in / connect to Jetpack via the stats screen fails to properly reconcile the self-hosted flavor of the blog with its wpcom shadow blog. The result is being logged in to wpcom with two copies of the self-hosted blog being present in the app and the user is left on the stats screen prompting for credentials. 

To reproduce: 

0. Start from a fresh install.
1. Sign into the app with self-hosted crendentials for a blog that is using Jetpack. 
2. Switch to the Stats feature and enter your credentials for the wpcom account used with Jetpack. 
3. Notice that after attempting to connect you remain on the stats screen showing the credentials prompt. 
4. Tap back until you reach the sites list.  Notice that any wpcom sites belonging to the account you entered on the stats screen are present. 
5. Notice that the self-hosted site appears twice in the list. 
6. Switch to the Me tab.  Notice it shows you are logged in to wpcom.

**Comment by koke** [comment] 2017-06-28 14:27
I can't reproduce this. Anything special about the site where it happened?

**Comment by koke** [comment] 2017-06-28 14:32
The sync code tries to match the xmlrpc field. Any differences in http/https, or different case would not match. Maybe that's the case?

**Comment by koke** [comment] 2017-07-25 07:37
Closing in favor of #5911

**Closed by koke** 2017-07-25 07:37 UTC
Labels: Jetpack, Login, [Pri] Medium
