### ISSUE TITLE
Editor: Backdated posts show publish date as "Immediately"

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#14113] opened 2020-05-13 15:12 UTC
### Expected behavior

I expect the post's publish date (in post settings and the pre-publishing nudge) to reflect the selected date and time for a post.

When I backdate a post, I expect to see that in the UI to confirm that my selected date/time will be used on the post.

### Actual behavior

When I backdate a post, the publish date always shows as "Immediately." This makes me think that my selected date/time wasn't saved.

This is most obvious in the pre-publishing nudge, but it is also visible in the "Date and Time" field under Post Settings > Publish Date.

### Steps to reproduce the behavior

1. Create a new post.
2. Add some content.
3. Open the Post Settings (in the ellipsis menu).
4. Select Publish (set to "Immediately" by default).
5. Select Date and Time.
6. In the date and time picker, select a day and/or time in the past.
7. Notice that the text under Date and Time now says "Post was published on ..." but the Date and Time field still says "Immediately."
8. Go back to the post editor.
9. Tap "Publish."
10. When the pre-publishing nudge (bottom sheet) appears, notice that the Publish field says "Immediately."
11. Select Publish and notice that the correct date/time is selected, but the Publish field remains at "Immediately."
12. Select Publish Now and confirm that your post is published with the correct date/time.

**Screencast:** https://cloudup.com/ckr1V8fWXhf

<img src="https://user-images.githubusercontent.com/8658164/81830090-8e361080-9533-11ea-95d2-1d4a9e538e71.PNG" width="300px">

**Comment by ScoutHarris** [comment] 2020-05-13 16:42
ping @bjtitus

**Comment by dcalhoun** [comment] 2021-03-30 18:26
I was unable to reproduce this on iPhone SE, iOS 14.4.2, WPiOS 16.9 (16.9.0.13). It also appears #14117 merged and was marked as addressing this issue.

Closing this, but please feel free to reopen if I am mistaken.

**Closed by dcalhoun** 2021-03-30 18:26 UTC
Labels: Posting/Editing, [Pri] Medium, [Type] Bug
