### ISSUE TITLE
Crash editing/ adding media after failed upload

### ISSUE THREAD

**Issue by etoledom** [wordpress-mobile/WordPress-iOS#12282] opened 2019-07-08 05:46 UTC
Editing a media or adding media after a failed upload crashes the app in both block and classic editors if some steps where previously followed:

**Block editor:**
- Create a new Post with Block editor
- Add a video block
- Add a video from camera roll
- While is uploading, turn off networking to make the upload fail
- When the retry UI is visible, Save as Draft from the contextual menu (...)
- Restore networking and wait until the upload is completed
- You will see a toast message saying `Post draft uploaded`
- Press the pencil button on the toolbar to edit the video block
- Choose another video from the camera roll
- 💥

**Classic Editor:**
- Create a new Post with classic editor
- Add a video from camera roll
- While is uploading, turn off networking to make the upload fail
- When the retry UI is visible, Save as Draft from the contextual menu (...)
- Restore networking and wait until the upload is completed
- You will see a toast message saying `Post draft uploaded`
- Press the "+" and add another video
- 💥

### Important - notes from testing 

Even before editing the failed media or adding a new one we get a Core Data error:
```CoreData: error: Mutating a managed object 0xdca9e3e660a95b1c <x-coredata://1265ED26-DEDD-489C-BAA2-4ECC6FB57332/Post/p147> (0x28307aa70) after it has been removed from its context.```
When the media upload is resumed upon regaining connectivity we get the following error while uploading media (From debugger log):
```
2019-08-07 16:37:32:361 WordPress[2879:632003] Post Coordinator -> Media state: Progress: 0.27630826012452603
2019-08-07 16:37:32:361 WordPress[2879:632003] Post Coordinator -> Media state: Progress: 0.5622316851709562
2019-08-07 16:37:32.632596-0700 WordPress[2879:632003] [error] error: Mutating a managed object 0xdca9e3e660a95b1c <x-coredata://1265ED26-DEDD-489C-BAA2-4ECC6FB57332/Post/p147> (0x28307aa70) after it has been removed from its context.
CoreData: error: Mutating a managed object 0xdca9e3e660a95b1c <x-coredata://1265ED26-DEDD-489C-BAA2-4ECC6FB57332/Post/p147> (0x28307aa70) after it has been removed from its context.
2019-08-07 16:37:33:461 WordPress[2879:632003] Post Coordinator -> Media state: Progress: 0.48592142297761476
2019-08-07 16:37:33:463 WordPress[2879:632003] Post Coordinator -> Media state: Progress: 0.5622316851709562
```

The crash happens here:
https://github.com/wordpress-mobile/WordPress-iOS/blob/c6a101fe4e3af08e57f1249b44d48a45e2e01c0f/WordPress/Classes/Extensions/Media%2BBlog.swift#L18
Due to the blog object being nil while force unwrapping its managedObjectContext

When we choose to "Save as draft", we upload the post. 
On `uploadPost` completion, we call `createRevisionOfPost` which sets the post with the value returned from `createRevision()` and then we save it to the context.

This only happens if we choose "Save As Draft" while offline. If the draft was already previously uploaded and we choose to update, it works.

This might be related to https://github.com/wordpress-mobile/gutenberg-mobile/issues/1204

**Comment by jklausa** [comment] 2019-08-12 21:41
here's a brief round-up of my discussion with @yaelirub about this bug, and what we've been able to figure out so far:

* it happens both in Gutenberg and Aztec
* we're pretty sure it involves a post getting duplicated, _somehow_
* a running theory is that, for whatever reason, saving the post as a draft causes it to create a new one
* we wondered whether saving the post as draft here: https://github.com/wordpress-mobile/WordPress-iOS/blob/1d57a3dbeddda3fccbd0db6413d0c0e501c1d0fc/WordPress/Classes/Services/PostService.m#L260-L267 might have been a cause, but this seems like a dead end
* another seemingly dead end, from yael: 

>For some reason when the post and the media are uploaded on a reconnect, the createMediaWith method is fetching the post by doing: 
```
NSManagedObject *existingObject = [self.managedObjectContext existingObjectWithID:objectID error:&error];
``` 
>and then cast it to a post  `post = (AbstractPost *)existingObject` but the post blog is nil and so we get the crash.
>I thought that simply removing the force unwrapping will help solve the problem, but that just introduces more issues with returning optional media object

* i've manage to _somehow_, *once* make an editor show up _on top_ of another editor when going thru repro steps — like, whole modal on modal, which would explain why we're seeing two different post, but haven't been able to reproduce it ever again
* similarily, i was thinking that the weird blinking in the video might have been a new editor being loaded and presented, and was real excited when i saw the modal-on-modal thing happen once, but i think that's a dead end
* i've spend a good chunk of time doing weird things to `PostEditor+Publish.swift` trying to force it  to create another post, but without too much success

**Comment by designsimply** [comment] 2019-08-30 20:58
I checked in with @jkmassel and the Sentry crash report I found is not a match. "The stack trace above looks like it’s trying to create media while drawing the toolbar? I have no idea why it’d do that tbh. Whereas the GitHub issue seems related to core data issues of some kind."

So I'll leave this issue without a linked crash report for now since I searched but couldn't find a really good match.

**Comment by designsimply** [comment] 2019-09-27 23:11
**72-day impact:** ~2 per day
**Users affected in the last 72 days:** 82
**First seen in:** 12.8

<sup>https://sentry.io/share/issue/d092ae4dcdc1458990065da2873538e2/</sup>

**Comment by etoledom** [comment] 2019-12-17 10:02
I have noticed that the underlying issue is related to "Saving" the post while offline.
After doing that, there are many issues and crashes in Gutenberg, not only related to Media.

This is because the post instance referenced by `GutenbergViewController` seems to not be valid anymore. It gets its Blog reference nullified and some other fields too.

We probably need to update this reference to continue using the editor.

@yaelirub any idea where can we start looking at solving this issue?

**Comment by yaelirub** [comment] 2019-12-17 14:14
@shiki , @leandroalonso , can you please work with @etoledom to solve these issues?

**Closed** 2019-12-20 13:30 UTC
Labels: Offline Support, Posting/Editing, [Pri] High, [Type] Bug, [Type] Crash
