### ISSUE TITLE
Password field misaligned while typing

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/WordPress-iOS#4415] opened 2015-11-04 15:40 UTC
This might be the same issue or related to #1096 but when you are typing a password in the login screen, the vertical alignment is off

![password-misaligned-sbs](https://cloud.githubusercontent.com/assets/8739/10942967/a37db782-8312-11e5-944f-de6e57ab76c2.png)

I don't see any difference in font size though

**Comment by pypt** [comment] 2015-11-11 18:56
One possible way to improve the situation is to set password field's font to system font when it's non-empty [as per this SO suggestion](http://stackoverflow.com/a/21670181/200603); see my commit 9cfce43.

Before (both placeholder and actual text use `[WPNUXUtility textFieldFont]`, bullets move up and down):

![](https://i.giphy.com/3oEduK0o9d8kZzQ6B2.gif)

After (only placeholder text is shown in `[WPNUXUtility textFieldFont]`, actual password is in system font):

![](http://i.giphy.com/l41lM7J1JhphQNSo0.gif)

I've found no way to stop the password field bullet points moving up and down, even the iTunes Connect app does this. There's a [proposed workaround on SO](http://stackoverflow.com/a/32996503/200603) but it didn't work for me.

**Comment by koke** [comment] 2015-11-12 16:06
Even if not perfect, that still looks much better

**Comment by jleandroperez** [comment] 2016-11-29 17:26
Closing this one since i cannot reproduce it anymore. The Login sequence was refactored not long ago, and this issue was, apparently, fixed as well.

Please, feel free to reopen if needed. Thanks!

**Closed by jleandroperez** 2016-11-29 17:26 UTC
Labels: NUX, [Type] Enhancement
