### ISSUE TITLE
Reader: Gutenberg gallery images can't be viewed properly on post detail

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#10206] opened 2018-09-28 13:52 UTC
### Expected behavior

I expect that all images, including galleries, will be resized to fit on screen in the Reader post detail and generally be formatted in a way that is understandable/readable.

### Actual behavior

Galleries created in Gutenberg are displayed in a bulleted list, and they aren't resized to fit the screen. If the gallery images aren't linked to the media file or attachment page, there's no way to view the full image in the Reader.

### Steps to reproduce the behavior

1. On the web, create a new post in the Gutenberg editor.
2. Add a gallery to the post and publish it.
3. Open the Reader in the app.
4. Find the post and open the post detail.

Screenshot showing the result:

![2018-09-28 14 41 13](https://user-images.githubusercontent.com/8658164/46212511-0d121180-c32e-11e8-9f6a-a58736063bb8.png)

**Comment by etoledom** [comment] 2018-11-07 19:57
Hey @rachelmcr !
I'm able to see the dots, but I can't reproduce the image sizing problem.
Do you have a procedure or the html code (from Gutenberg-web) that reproduce the issue?

Thank you!

**Comment by rachelmcr** [comment] 2018-11-08 11:34
All I did was create a new Gutenberg web gallery, with no changes to the block settings. Here's an example post that shows the issue: https://rachel-test-domain.com/2018/11/08/gallery-post/

Here's the post content, copied from the Gutenberg editor (includes all the Gutenberg-specific notation):
```
<!-- wp:paragraph -->
<p>This post has a gallery:</p>
<!-- /wp:paragraph -->

<!-- wp:gallery -->
<ul class="wp-block-gallery columns-3 is-cropped"><li class="blocks-gallery-item"><figure><img src="https://doalittletest.files.wordpress.com/2017/09/image3.jpg" alt="" data-id="1239" data-link="http://rachel-test-domain.com/?attachment_id=1239" class="wp-image-1239"/></figure></li><li class="blocks-gallery-item"><figure><img src="https://doalittletest.files.wordpress.com/2017/09/image2.jpg" alt="" data-id="1237" data-link="http://rachel-test-domain.com/?attachment_id=1237" class="wp-image-1237"/></figure></li><li class="blocks-gallery-item"><figure><img src="https://doalittletest.files.wordpress.com/2017/09/image.jpg" alt="" data-id="1232" data-link="http://rachel-test-domain.com/?attachment_id=1232" class="wp-image-1232"/></figure></li><li class="blocks-gallery-item"><figure><img src="https://doalittletest.files.wordpress.com/2017/08/wp-image-2090539792.jpg" alt="" data-id="1201" data-link="http://rachel-test-domain.com/wp-image-2090539792/" class="wp-image-1201"/></figure></li><li class="blocks-gallery-item"><figure><img src="https://doalittletest.files.wordpress.com/2017/08/wp-image-1169219647.jpg" alt="" data-id="1197" data-link="http://rachel-test-domain.com/wp-image-1169219647/" class="wp-image-1197"/></figure></li></ul>
<!-- /wp:gallery -->
```

**Comment by etoledom** [comment] 2018-11-08 11:57
I can see the problem now. Thank you!

**Comment by aerych** [comment] 2018-11-12 17:23
Related underlying issue:
https://github.com/wordpress-mobile/WordPress-iOS/issues/10245#issuecomment-429461754

**Comment by aerych** [comment] 2018-11-18 20:32
Resolved in https://github.com/wordpress-mobile/WordPress-iOS-Shared/pull/165

**Closed** 2018-11-18 20:32 UTC
Labels: Gutenberg compatibility, Reader, [Type] Bug
