### ISSUE TITLE
Sometimes the selected blog gets reset to your default blog.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-iOS#5272] opened 2016-05-03 12:04 UTC
### Expected behavior

The selected blog should be maintained when quitting and re-opening the app.
### Actual behavior

https://lookback.io/watch/hcs6QMfwnFdhGd82y
### Steps to reproduce the behavior
1. Launch the app
2. Select a blog, open it
3. Quit the app
4. Relaunch the app

**Comment by frosty** [comment] 2016-05-31 15:45
I've just re-tested this and it seems to work okay for me. I select a site, quit the app from the app switcher, then re-open the app, and the same site was still selected (showing me site details). 

@diegoreymendez: Can you confirm?

**Comment by diegoreymendez** [comment] 2016-06-08 13:43
@frosty - Confirmed!

Although it seems not to happen if you close the app quickly after getting into the new blog.  It seems like it's necessary to wait a bit once you open a blog.

The video includes some waiting time for this reason.  https://cloudup.com/cA9xdJn02Td

**Comment by diegoreymendez** [comment] 2016-06-08 13:45
I've updated the title to reflect it does not happen every single time.

**Comment by diegoreymendez** [comment] 2016-07-20 20:31
Clearing my assignation for now as I can't tackle it at this time.

**Comment by yaelirub** [comment] 2020-06-11 00:30
I waited for some time like the description suggest and couldn't reproduce.
since its hard to reproduce, no action or alarming user reports, I'm going to close this. Please reopen if you feel its necessary

**Closed by yaelirub** 2020-06-11 00:30 UTC
Labels: General, [Pri] Low, [Type] Bug
