### ISSUE TITLE
The Learn more at jetpack.com blog link only displays an empty web view when selected

### ISSUE THREAD

**Issue by JB184351** [wordpress-mobile/WordPress-iOS#20043] opened 2023-02-01 00:40 UTC
### Expected behavior
When selecting the `Learn more at jetpack.com` text on the overlay I expect it to open up to the blog.

### Actual behavior
Currently selecting the `Learn more at jetpack.com` text only opens an empty web view.

### Steps to reproduce the behavior
1. Enable Phase 4 on WP iOS 21.6, you can do that by logging into the account provided for [here](https://jetpackmobile.wordpress.com/2023/01/18/new-test-users-for-the-feature-removal-testing-phases/).
2. Select the `Switch to Jetpack` menu item.
3. The overlay should appear
4. Select the `Learn more at Jetpack.com` text and notice the empty web view appears.

##### Tested on [device], iOS [version], WPiOS [version]
iPhone 13 Mini (iOS 15.7), iPad Mini (iOS 15.7), iPhone 14 Pro (iOS 16.3) WPiOS 21.6

##### Screen Recording of Issue
https://user-images.githubusercontent.com/36495451/215916531-d96226ed-ecbc-450a-a80a-dbd8a982ed7d.MP4

**Comment by hassaanelgarem** [comment] 2023-02-01 01:03
This is expected because the blog post URL is not yet remotely configured.
For more details: pbArwn-5Bk-p2#comment-7147

**Comment by hassaanelgarem** [comment] 2023-02-02 02:40
@JB184351 I'm closing this as not a bug.

**Closed as not planned by hassaanelgarem** 2023-02-02 02:40 UTC
