### ISSUE TITLE
P2 emoji are extra big

### ISSUE THREAD

**Issue by mindgraffiti** [wordpress-mobile/WordPress-iOS#16868] opened 2021-07-14 20:41 UTC
### Screenshot
<kbd><img src="https://user-images.githubusercontent.com/1062444/125689605-b69a7a72-0fdc-423a-9ede-5246c3dcdacc.PNG" width="350" /></kbd>

### Expected behavior
I would like to see the P2 emoji to be the same size or nearly the same size as emoji that are native to iOS.

### Actual behavior
They look extra big right now, almost 4x larger than they should display.

### Steps to reproduce the behavior
1. Write a P2 comment and include P2 emoji by using :code-test: or :trial: or :eyes: 
2. Visit the comment from Notifications > Comments view.
3. The comment will display with extra big emoji.

Note: This is also reproducible on posts (not just comments)

Previously known and previously fixed issues:
- 1106-gh-Automattic/p2
- https://github.com/wordpress-mobile/WordPress-iOS/issues/15341
- https://github.com/wordpress-mobile/WordPress-iOS/issues/15523
- pbArwn-1v1-p2#comment-2201

##### Tested on iPhone 12 Pro, iOS 14.6, WPiOS 17.7

**Comment by aerych** [comment] 2021-08-06 22:21
Took a look into this. The notifications code loads the emoji images at their natural size. I'm thinking we might add logic to detect the emoji by their URL path, and then use a custom NSTextAttachment to ensure they are scaled to fit their text container's current line height.

**Comment by designsimply** [comment] 2021-10-27 07:35
It was repotted internally that if one of the custom emojis is a version that shakes (i.e. usually has intensified in the emoji name) then the whole screen will also shake. @aerych do you think that scaling them properly will also fix the screen shaking issue?

<sup>(internal reference: p4a5px-2MM-p2 /hat tip @reginabally)</sup>

**Comment by aerych** [comment] 2021-10-27 14:57
> do you think that scaling them properly will also fix the screen shaking issue

I also replied in the internal thread. Sharing here as well: 

From a close look at the video:

- The cell with the ghost emoji seems to shake more than just the ghost.
- The cell with the thinking emoji seems like only the thinking emoji shakes.
- The cell with the thinking emoji never actually is scrolled past – even when reaching the last comment part of that cell is still visible.
- When scrolling back up suddenly the cell with the thinking emoji vanishes. That’s very interesting and unexpected. The cell was never removed from view so it shouldn’t be recycled or reloaded or anything like that. The behavior is almost like the cell was reloaded.
- The shaking at the end of the video looks like it could be from a cell that is rapidly being reloaded over and over and the table view trying to adjust the placement of other cells accordingly. 

I’m not sure it’s specifically the emoji that are responsible for the shaking at the end. In the past we’ve seen something similar when other media are loaded in a comment cell. Those cases were infrequent and hard to reproduce. 😦 All that said, constraining the height of the emoji could help as cell geometry would more likely be consistent before and after media is loaded, but it’s not guaranteed to fix the shake. I’d be curious to know why that cell vanished the way it did and if its related or not to the emoji loading.

**Comment by twstokes** [comment] 2022-03-07 18:18
Removing my assignment as it sounds like this will be resolved by work produced by @dvdchr and team. 🎉

**Comment by dvdchr** [comment] 2023-03-13 12:50
Reopening this issue. This issue is still happening in the comment threads. Refs p1678658531769769-slack-C029GBT2R

**Comment by guarani** [comment] 2023-08-07 19:10
This happens not only in P2 comments but also when reading P2s in the Reader (and likely when reading them in Notifications, too). I updated the title to reflect this.

**Comment by twstokes** [comment] 2023-11-23 00:47
I took a shot at this with some workarounds in https://github.com/wordpress-mobile/WordPress-iOS/pull/22080.

**Closed as completed** 2023-11-23 03:00 UTC
Labels: [Pri] Medium, Reader, Comments
