### ISSUE TITLE
Mentions: user-mentions suggestions list is displayed with empty values

### ISSUE THREAD

**Issue by igoriols** [wordpress-mobile/WordPress-iOS#19249] opened 2022-08-26 03:10 UTC
### Expected behavior
1. Tap the "My Site" tab.
2. Tap on "Menu".
3. Tap on "Comments" row.
4. Tap any comment.
5. Tap "Reply" button.
6. Type "@" and you should see the user-mentions suggestions list.

<p float="left">
  <img src="https://user-images.githubusercontent.com/8026597/186804359-02d725c5-bf18-4e06-a6a8-c06ee653093a.png" width="300" />
</p>

### Actual behavior

<p float="left">
  <img src="https://user-images.githubusercontent.com/8026597/186804438-01bfbc37-69b4-44bc-a616-bc63b6b93794.png" width="300" />
  <img src="https://user-images.githubusercontent.com/8026597/186805224-aebcd0a7-8249-403d-8e84-e82157c90c3f.jpg" width="300" />
</p>

### Steps to reproduce the behavior
This is an intermittent error, and I don't know the steps to reproduce it for sure.
I make the suggestions list visible by typing "@" + any string, then I click on the `^` to expand the text area.
The suggestions list disappears, but I make it visible again by typing any string.  
I keep changing the text to keep the list visible.  
Then I press the `⌄` button to collapse the text area.
When I erase all the text except for the "@", the list with empty values is displayed. 
See the gif below for more details.

<p float="left">
  <img src="https://user-images.githubusercontent.com/8026597/186808827-49fb186b-a876-4c33-83c6-22682a0e400b.gif" width="300" />
</p>

##### Tested on iPhone 13 Pro, iOS 15.6.1, WPiOS 20.5.
The picture in dark mode was taken on my real device (iPhone 13 Pro).
The pictures in light mode were taken from the simulator.

**Comment by hassaanelgarem** [comment] 2022-09-04 23:22
Looks like a duplicate of #18988

**Closed as not planned by hassaanelgarem** 2022-09-04 23:22 UTC
Labels: [Pri] Low, Mentions
