### ISSUE TITLE
Error Domain=kCFErrorDomainCFNetwork Code=-1202 "(null)" UserInfo={_kCFStreamPropertySSLClientCer...

### ISSUE THREAD

**Issue by mokagio** [wordpress-mobile/WordPress-iOS#19165] opened 2022-08-10 01:21 UTC
## Sentry-generated report

**Sentry Url**: https://sentry.io/share/issue/c9ef8c074e2e4207b674f31ba284550f/
**User Count**: 35
**Count**: 223
**First Release**: 20.4.0.3
**First Seen**: 2022-08-08T08:54:40.785000Z
**Last Seen**: 2022-08-10T01:05:20Z
**24 Hours**: 122
**30 Days**: 223

```
Error Domain=kCFErrorDomainCFNetwork 
Code=-1202 "(null)"
UserInfo={
  _kCFStreamPropertySSLClientCertificateState=0,
  kCFStreamPropertySSLPeerTrust=<SecTrustRef: 0x28360b690>,
  _kCFNetworkCFStreamSSLErrorOriginalValue=-9813, 
  _kCFStreamErrorDomainKey=3,
  _kCFStreamErrorCodeKey=-9813, 
  kCFStreamPropertySSLPeerCertificates=( REDACTED )
}
```

## Additional information

Sentry marks this as a new issue in 20.4.0.3, but if you open Discover you'll see it isn't. Maybe Sentry's behavior has to do with the some of the `UserInfo` properties?

I queried for crashes with error domain `kCFErrorDomainCFNetwork` and code `-1202` and got the following:

![image](https://user-images.githubusercontent.com/1218433/183790449-a9af840d-5313-4a0a-ace9-20e81cf024f2.png)

---

I'm tentatively assigning this to the 20.5 milestone. The impact seems to be limited at the moment, but we'll have to wait and see how it increases as the rollout progresses.

**Comment by hassaanelgarem** [comment] 2022-08-10 13:30
Looks like a duplicate of #18555

It's the same network error but with a slightly different stack trace.

**Closed as completed by hassaanelgarem** 2022-08-10 13:30 UTC
Labels: [Pri] Low, Login, Webviews
