### ISSUE TITLE
Layout: "Great! Could you leave us a nice revie..." is truncated (iPhone 6+)

### ISSUE THREAD

**Issue by alisterscott** [wordpress-mobile/WordPress-iOS#4392] opened 2015-10-30 00:54 UTC
What I did: saw a message asking if I liked WordPress, of course I do, clicked that, saw this message

What I saw: A message "Great! Could you leave us a nice revie..."

What I expected: Doesn't need truncation, can fit the 'w'. So I would expect "Great! Could you leave us a nice review

![ios iphone 6 - 1 1](https://cloud.githubusercontent.com/assets/128826/10836025/a4239b24-7ef4-11e5-8337-e5e6c5fb79e8.jpg)
"

**Comment by aerych** [comment] 2015-11-04 20:47
Hi @alisterscott.   I took a peek at this one but I haven't been able to reproduce it. Do you recall any steps taken leading up to the glitch? Was maybe something else on screen animating or transitioning? 

@jleandroperez  is some series of steps we can take to get the prompt to reappear on demand vs a code hack?

**Comment by alisterscott** [comment] 2015-11-04 22:48
Hi @aerych 
All I remember was a message asking if I like the app? (Yes/No), I tapped Yes, then it showed me this message. I haven't seen this message (or the first one) since, as I guess it will only ask once, which is why it's hard to reproduce.
It was on an iPhone 6 plus (big screen) so not sure if it is specific to this sized screen?
Sorry I can't be of more help

**Comment by aerych** [comment] 2015-11-04 23:05
@alisterscott one more question (sorry) was this the app store version or the beta?

**Comment by alisterscott** [comment] 2015-11-04 23:24
@aerych It was the app store version.

**Comment by jleandroperez** [comment] 2015-11-06 14:44
@aerych the logic behind definitely forces us to hack it. Once the *Ratings* view is displayed, we may skip several versions before it actually appears again, depending on which button you've clicked.

Easiest way is to just comment out [this return statement](https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.m#L320).

What's strange about this glitch is... the label size [is actually harcoded](https://github.com/wordpress-mobile/appbotx/blob/master/Classes/Views/ABXPromptView.m#L53), and the `ABXPromptView` instance is generated via storyboard. That view has a minimum height constraint set to 100.

There is no flow in which this label would get resized.

I'm unable to repro as well. Only card on the table i've got is... how about if we just reset the control(s)'s size(s) in `layoutSubviews`? (Re: ABXPromptView).

**Comment by aerych** [comment] 2015-11-06 14:54
> It was the app store version.

Thanks @alisterscott :)

@jleandroperez I think that the glitch was happening in the app store version might be significant.  Multiline UILabel sizing could be a bit wonky since iOS 7. Remember how we had to be tricky with `preferedMaxLayoutWidth` or text could render on a single line. (Granted that was mostly a .xib issue.)  Perhaps the problem is fixed with iOS 9.

Perhaps we should sit on this one a bit and see if it happens in 5.7 before attempting a patch?

**Comment by jleandroperez** [comment] 2015-11-06 14:59
@aerych sounds good... (all) i can come up are just hacks to enforce the size that's already getting set, and (supposedly) never being updated.

This is definitely a strange glitch!

**Comment by jleandroperez** [comment] 2016-01-06 16:30
I'm closing this one as cannot repro. Let's reopen, if needed!

**Closed by jleandroperez** 2016-01-06 16:30 UTC
Labels: Notifications, [Type] Bug
