### ISSUE TITLE
Building not generating Credentials.m

### ISSUE THREAD

**Issue by alexnaldo** [wordpress-mobile/WordPress-iOS#5503] opened 2016-06-03 12:47 UTC
### Expected behavior

Generate the Credentials.m
### Actual behavior

Config not found
### Steps to reproduce the behavior

Put .wpcom_app_credentials at ~/
## Workaround

Edit "Generate API credentials" on "Build Phases" and replace $WPCOM_CONFIG to ~/.wpcom_app_credentials

**Comment by RuofeiLv** [comment] 2016-08-12 16:47
After i implement your wordaround, the ApiCredentials.m in Derived Sources appears the client and secret string, but when i create an account, it still shows the invalid client_id error message.

**Comment by hoverduck** [comment] 2017-01-25 20:42
@alexnaldo - Are you still having problems building the app?  I'm unable to reproduce the problem with the latest versions of Xcode and WPiOS, so I'm going to close this out, but feel free to re-open it.

If you'd like to chat with other folks working on the app we invite you to [join the WordPress Slack](https://make.wordpress.org/chat/).  You can find us in the #mobile channel.

**Closed by hoverduck** 2017-01-25 20:42 UTC
Labels: General, [Pri] Low, [Type] Question
