### ISSUE TITLE
Tap targets broken on Plugins View

### ISSUE THREAD

**Issue by osullivanchris** [wordpress-mobile/WordPress-iOS#16482] opened 2021-05-12 11:02 UTC
### Expected behavior
If I tap on a plugin, it will bring me to the plug in details

### Actual behavior
- For items in the 'Featured' carousel section, nothing happens when I tap them
- For items in the 'Popular' carousel section, if I tap on one it brings me to the list of all of them, rather than directly to the Plugin I tapped

### Steps to reproduce the behavior
- Have a site with Plugins available
- Tap on 'Plugins' in My Site
- Tap on a Plugin under 'installed' and it works normally
- Tap on any item in 'Featured' and nothing happens
- Tap on an item in 'Popular' and be brought to the list view

##### Tested on iPhone 12 Pro, iOS 14.5.1, WPiOS 17.3

![IMG_1132](https://user-images.githubusercontent.com/50576199/117964368-6d0c2980-b319-11eb-9b42-b9eda77d5c6b.PNG)

**Comment by eduardozulian** [comment] 2021-05-12 19:32
Seems similar to #16246

**Comment by osullivanchris** [comment] 2021-05-13 08:59
Yeah that's the same issue I'm seeing, thanks for spotting that @eduardozulian !

Great minds think (file bugs) alike @mattmiklic  😆

**Comment by frosty** [comment] 2021-05-19 16:27
Closing as a duplicate of #16087

**Closed as completed by frosty** 2021-05-19 16:27 UTC
Labels: Jetpack Plugins
