### ISSUE TITLE
Login: Edit error message to reference self-hosted site

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#8080] opened 2017-10-31 20:42 UTC
The error message shown after entering an email address that is not associated with a WordPress.com account reads:
"This email is not registered on WordPress.com."

Assuming the user is not in a wpcom-only flow, let's edit the message to ask if the user is trying to log in to their self-hosted site.
Something like: "Are you trying to log in to your self-hosted site?" might work, but would it also make sense to reference the button to the site address screen?

Refs p4a5px-20t-p2
cc @folletto

**Comment by michelleweber** [comment] 2017-10-31 21:40
"Are you trying to log in to your self-hosted site?" sounds fine, but could I see a screenshot of the whole thing in context?

**Comment by folletto** [comment] 2017-11-01 11:46
I would do something with a tappable link inside (the whole text can be tappable, even if only part of the text is underlined):

![artboard](https://user-images.githubusercontent.com/4389/32273375-298715c4-befa-11e7-87f6-da8bce9a7a26.png)

> This email is not registered on WordPress.com.
> Are you trying to access a _WordPress.org site_ instead?

The link accesses the same screen as the button below switching to .org. It would be great if the email typed in is preserved in the screen switch.

Also, this message must be in sync with the other one for Android: https://github.com/wordpress-mobile/WordPress-Android/issues/6812

**Comment by michelleweber** [comment] 2017-11-01 17:22
Thanks, @aerych! I think there should be as much detail we we can provide with the error message, and I also like the idea of making it tappable. I might go with something like:

> Hmm, this email address isn't registered with WordPress.com.
> 
> Are you trying to access a self-hosted site? Log in with your site address.

Where "Log in with your site address" is underlined, and the whole thing is tappable.

**Comment by designsimply** [comment] 2019-12-16 20:34
Still valid and there are other login flows we can consider. I think we could use the same flow currently used on the Google sign in flow where it offers you some options for what to do next. 

@rachelmcr can you weigh in on this one with your input? Should we just change the error message as noted above if someone enters a non-WP.com email into the WP.com login flow or should we adopt the same flow the Google login flow uses with those extra options for what to do next?

## Continue with WordPress.com login flow:

1. Go to the Log In screen in the app.
1. Tap "Log In".
1. Tap "Continue with WordPress.com".
1. Enter an email address that is not associated with a WordPress.com account.

**Result:** an error appears that says, "This email address is not registered on WordPress.com."

<img src="https://user-images.githubusercontent.com/1119271/70936181-076e1d80-1fff-11ea-9eca-8c89d4c037e2.png" width="200" alt="log-in"> <img src="https://user-images.githubusercontent.com/1119271/70936179-06d58700-1fff-11ea-9ba5-9978261e7a23.png" width="200" alt="continue-with-wordpresscom"> <img src="https://user-images.githubusercontent.com/1119271/70936178-06d58700-1fff-11ea-8038-6213352be35b.png" width="200" alt="this-email-address-is-not-registered-on-wpcom"> 
<sup>Tested with WPiOS 13.8 App Store version on iPhone 6S iOS 13.2.3.</sup>

## Continue with Google login flow:

1. Go to the Log In screen in the app.
1. Tap "Log In".
1. Tap "Continue with Google".
1. Select an email address that is not associated with a WordPress.com account.

**Result:** a message appears that says, "Connected but… The Google account "example_email" doesn't match any account on WordPress.com" and gives three options:

1. Try with another email
1. Try with the site address
1. Sign up

<img src="https://user-images.githubusercontent.com/1119271/70936181-076e1d80-1fff-11ea-9eca-8c89d4c037e2.png" width="200" alt="log-in"> <img src="https://user-images.githubusercontent.com/1119271/70936179-06d58700-1fff-11ea-9ba5-9978261e7a23.png" width="200" alt="continue-with-wordpresscom"> <img src="https://user-images.githubusercontent.com/1119271/70939431-7ea6b000-2005-11ea-8488-ec471766a838.png" width="200" alt="connected-but">
<sup>Tested with WPiOS 13.8 App Store version on iPhone 6S iOS 13.2.3.</sup>

## Continue with Apple login flow:

1. To prep, [create an Apple ID](https://appleid.apple.com/account#!&page=create) with an email not already associated with WordPress.com
1. On the device, go to Settings > Sign in to your iPhone (log out first if necessary).
1. Complete the step to Turn On Two-Factor Authentication.
1. On the app, go to the Log In screen.
1. Tap "Log In".
1. Tap "Continue with Apple".
1. Select the email address and continue with Touch ID.

**Result:** a WordPress.com account is automatically created for you since the email address wasn't already associated with WordPress.com. ([56s](https://cloudup.com/cEjV7LurKv6))

<img src="https://user-images.githubusercontent.com/1119271/70940511-b9a9e300-2007-11ea-9315-7ef8aa75906a.png" width="200" alt="continuing-with-apple"> <img src="https://user-images.githubusercontent.com/1119271/70940683-19a08980-2008-11ea-8863-7d464dc33d7e.png" width="200" alt="new-account-screen"> <img src="https://user-images.githubusercontent.com/1119271/70940681-19a08980-2008-11ea-90d9-4c9c1461d8fb.png" width="200" alt="post-siwa-screen">
<sup>Tested with WPiOS 13.8 App Store version on iPhone 6S iOS 13.2.3.</sup>

**Comment by rachelmcr** [comment] 2020-01-03 14:32
> Should we just change the error message as noted above if someone enters a non-WP.com email into the WP.com login flow or should we adopt the same flow the Google login flow uses with those extra options for what to do next?

I'd lean toward the suggested tweak, although the prompt to log in with the site address is more prominent now than when this issue first came up, so I wonder if it's even a point of confusion anymore. That said, I'd defer to a designer's perspective on the best direction to take at this point.

**Comment by rachelmcr** [comment] 2020-03-17 13:16
This should be resolved with the Unified Login & Signup project (internal ref: pbArwn-2W-p2). The first decision users will make is to continue with WordPress.com or enter a site address (for self-hosted sites), and once someone enters the WordPress.com flow they'll be automatically directed to log in or sign up based on whether an account already exists.

That said, I'm inclined to leave this issue open until the project is complete, so we can test and confirm that there isn't any lingering confusion about this or dead ends with the flows and error messages.

**Comment by ScoutHarris** [comment] 2020-09-16 16:58
Hey @rachelmcr @designsimply . Now that Unified Login & Signup are done, can this be reviewed to see if the changes are sufficient, or if you think more changes are needed? Thanks!

**Comment by mindgraffiti** [comment] 2020-09-17 16:34
Moving to Blocked status until we have verification that the UL&S project has solved this issue.

**Comment by rachelmcr** [comment] 2020-09-18 15:54
Sorry for the delay! I've had my hands full this week but I'll test/review this issue and update it as soon as I have a chance next week (early- to mid-week).

**Comment by rachelmcr** [comment] 2020-09-25 15:17
I confirmed the UL&S project has solved this issue:

1. If you select "Continue with WordPress.com" you are automatically directed to log in or sign up depending on whether you have a WordPress.com account, which makes sense for a WordPress.com-specific flow.
2. If you select "Enter your site address":
   1. You are directed to the WordPress.com login flow (same as above) if you enter a WordPress.com-hosted site.
   2. Otherwise you are directed to the username/password flow where you can enter your site credentials and get an appropriate (non-wp.com) error if the credentials aren't recognized.

Closing as resolved.

**Closed by rachelmcr** 2020-09-25 15:17 UTC
Labels: Login, [Type] Enhancement
