### ISSUE TITLE
Editor: High energy impact during post edition

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-iOS#6801] opened 2017-03-02 12:32 UTC
@frosty did a quick and dirty profiling with both Hybrid and Aztec editors. It shows both editor are using abnormal battery resources:

<img width="1034" alt="screen shot 2017-03-02 at 11 57 54" src="https://cloud.githubusercontent.com/assets/40213/23507170/0cc31834-ff4c-11e6-9c9a-0db4fe8f957f.png">

Might be the "auto save on every keystroke" feature that causes this problem. cc @diegoreymendez 

Would be great to:

1. Profile post edition and find the culprit.
2. Fix it / workaround it to use less energy.

Note: we got user reports of abnormal battery usage during edition.

**Comment by diegoreymendez** [comment] 2017-03-02 12:42
Tagging for Aztec since it's relevant.

**Comment by koke** [comment] 2017-03-13 10:54
Tagged `Low Hanging Fruit` as it shouldn't be hard to at least figure out the cause.

**Comment by diegoreymendez** [comment] 2017-03-14 15:53
I'm moving this to low priority.  This is something we'll want to tackle once we reach beta.

**Comment by elibud** [comment] 2018-03-01 21:37
I'm closing this one as we haven't received any reports about it recently.

**Closed by elibud** 2018-03-01 21:37 UTC
Labels: Aztec, Low Hanging Fruit, Posting/Editing, [Pri] Medium, [Type] Broken Window
