### ISSUE TITLE
[Notifications] "Edit" button not localised in notification details screen

### ISSUE THREAD

**Issue by ctarda** [wordpress-mobile/WordPress-iOS#10616] opened 2018-12-07 05:12 UTC
### Expected behavior
The title of the Edit button should be localised
![img_2923](https://user-images.githubusercontent.com/2722505/49628788-3a132c80-fa21-11e8-9d6f-13745a7498fc.PNG)

### Actual behavior
The title of the Edit button when presenting the content of a single notification. All other buttons are localised.

The accessibility description (consumed by voiceover) is localised, and the button itself, generated and configured in `EditComment` is localised as well, so the title is likely being overwritten when the button is inserted in the UI

### Steps to reproduce the behavior
On a device setup in a language other than English, Navigate to Notifications > Comments > Tap a comment. Notice how all action buttons except Edit are localised

##### Tested on [device], iOS [version], WPiOS [version]
iPhone 6s+, iOS 12.1, WPiOS 11.4

**Comment by rachelmcr** [comment] 2019-01-04 16:48
Closing this as a duplicate of https://github.com/wordpress-mobile/WordPress-iOS/issues/10247. :)

**Closed by rachelmcr** 2019-01-04 16:48 UTC
Labels: Project Glot, [Type] Bug, i18n
