### ISSUE TITLE
Notifications show incorrect author Gravatars on first load

### ISSUE THREAD

**Issue by cagrimmett** [wordpress-mobile/WordPress-iOS#14926] opened 2020-09-17 00:53 UTC
### Expected behavior
Notifications should show the correct author Gravatar for each notification.

### Actual behavior
When tapping on Notifications and new notifications load, sometimes the new unread notifications in the list have an incorrect author Gravatar on the first load. Pulling down to reload the view will update the notifications to the correct author Gravatar. 

Examples, incorrect Gravatars circled.

Example 1|Example 2|Example 3
---|---|---
![CleanShot 2020-09-16 at 20 58 09@2x](https://user-images.githubusercontent.com/8738771/93407346-f12c1100-f85f-11ea-8913-c594960deac8.png)|![CleanShot 2020-09-16 at 20 57 59@2x](https://user-images.githubusercontent.com/8738771/93407347-f12c1100-f85f-11ea-9d93-5ed40976ac71.png)|![CleanShot 2020-09-16 at 20 57 29@2x](https://user-images.githubusercontent.com/8738771/93407348-f1c4a780-f85f-11ea-8a77-8b612a5f6b10.png)

### Steps to reproduce the behavior
1. Open WPiOS app
2. Tap on Notifications
3. Let new notifications load
4. Look to see if any of your friends' names don't match their Gravatars
5. Pull down to refresh and the incorrect author Gravatars will update to the correct ones

##### Tested on iPhone X, iOS 13.7, WPiOS 15.3-15.6

**Comment by designsimply** [comment] 2020-09-21 21:11
Thanks for reporting this @cagrimmett! I haven't been able to replicate it so far, but I'm still looking into it. 🤔

I noticed all of the examples you circled are for user mentions on private P2 blogs—is there any chance you recall seeing this on _any_ other type of notification or would you say this problem has been limited to @ mention notifications for you?

<sup>(internal reference to note some data about the examples, for reference: 1/ blog_id 70172480 post_id 13955 comment_id 14910 2/ blog_id 70172480 post_id 14026 comment_id 14813, 3/ blog_id 144624568 post_id 2419 comment_id 5469)</sup>

**Comment by designsimply** [comment] 2020-09-21 22:25
Some additional notes: 

There has been some recent work on @-mentions, except on the editor side (internal reference: p9ugOq-1db-p2) though if this has been happening since as early as WPiOS 15.3 as the bug report mentions, then https://github.com/wordpress-mobile/WordPress-iOS/pull/14743 is most likely not the culprit. Also, it might not be limited to @mentions but that happened to be the examples that were used for the first report.

It would be worth testing whether this problem is limited to the native apps or if it happens on the web as well.

Might be a regression (see https://github.com/wordpress-mobile/WordPress-iOS/issues/4858) and it might be happening on WPAndroid as well (see [these issues](https://github.com/wordpress-mobile/WordPress-Android/issues?q=is%3Aissue+label%3Anotifications+in%3Atitle+gravatar+is%3Aclosed)).

**Comment by cagrimmett** [comment] 2020-09-21 23:34
Hi, @designsimply! @elibud asked me to delete the app and reinstall it to see if I could keep replicating the issue. I haven't seen the issue again since reinstalling. That is strange to me because I was on the latest version before reinstalling 🤷 

If no one else can replicate this, I'd be fine with closing it.

**Comment by designsimply** [comment] 2020-09-24 18:15
Ace. Yes, I have not been able to replicate the bug and since a reinstall fixed the problem in your case it sounds like something went awry with the data locally or the cache—we will indeed want to look into it more deeply if we see it reported again. I would like to close this issue for now with an ask to re-open it if anyone sees the same problem reported again. Thanks for the follow-up!

**Comment by designsimply** [comment] 2021-01-08 01:39
Re-opening as this was reported again in Slack. I've paraphrased the report:

> I just got an avatar mismatch in the notifications screen. Pull to refresh fixed it.
> I noticed that if I scroll just enough to make only the first top cell disappear, the new cell that appears at the bottom of the screen is a notification which contains the same avatar than the one I was wrongly seeing in the top one. In other words, the topmost cell was [avatarA, userB], but the cell that appears next if I scroll – i.e likely the cell that got recycled (`dequeueReusableCell`) when the top one got inserted – was [avatarA, userA]; so correct, but also coincidentally about the user whose avatar got misused in the topmost cell… 🤔 

> The problem happened when I opened the app by tapping on a push notification, so I think what might have happened is I was already on that screen last time I closed the app, and it reloaded the avatar from the last cell on the screen when the app came back to foreground… only just before reusing it (incorrectly) as the cell for the new notification.

* App version: WP Internal 16.4.0.20201222@c34fac5
* iPhone is 11 Pro 
* iOS 14.3

<sup>(internal reference: T024FN1V2/C02Q9GACF-slack-apple-dev /ht @AliSoftware)</sup>

**Comment by aerych** [comment] 2021-01-26 22:13
> Re-opening as this was reported again in Slack. I've paraphrased the report

Reopening :)

**Comment by aerych** [comment] 2021-01-26 22:14
Mentioned again in p1611696087001700-slack-p2-mobile

**Comment by ceyhun** [comment] 2021-03-05 19:27
I also tried to reproduce this with the information here but I couldn't. 

1. Backgrounded the app on the notifications tab
1. Created a new post on web
1. Used a second new user to like the post
1. Pressed notification to open the app
1. New user's avatar was loaded correctly

And with these other varieties:
- Tried while the app is running and the notifications tab is open
- Tried with a cached user's avatar
- Tried with a newly created P2 site
- Tried with a new Gravatar
- Tried with an avatar I uploaded to the wpcom site
- Tried with network link conditioner on slow internet (edge speed)

Checking the code I thought of setting the cell image to `nil` before cell reuse [here](https://github.com/wordpress-mobile/WordPress-iOS/blob/a8e34234b67d5e3bcf5ce5a238c3e37dbcab9a2d/WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.swift#L1094) and before the image download, but I saw that the image is set to placeholder in any case after [downloadIconWithURL](https://github.com/wordpress-mobile/WordPress-iOS/blob/a8e34234b67d5e3bcf5ce5a238c3e37dbcab9a2d/WordPress/Classes/ViewRelated/Notifications/Views/NoteTableViewCell.swift#L85) function is called later [here](https://github.com/wordpress-mobile/WordPressUI-iOS/blob/fd6f923035c655bd5c0214997b7cc08902f326e9/WordPressUI/Extensions/UIImageView%2BNetworking.swift#L93), so didn't proceed with that.

**Comment by AliSoftware** [comment] 2021-03-08 20:00
Encountered this today with WPiOS Internal 16.8 (build 16.8.0.20210304). You can see that on 5th row, notification about Jeremy's post have Tiffany's Gravatar.

![image](https://user-images.githubusercontent.com/216089/110374596-22d4a680-8051-11eb-84ea-b451b8bb4db9.png)

[EDIT] Wait, actually pull-to-refresh does not fix the issue this time. That used to fix it last time I saw this issue… but this time, even if I pull-to-refresh the screen multiple times, Jeremy's notification still has Tiffany's avatar 😱 

Only when I scroll past the row (to force a cell reuse, I guess?) did the cell finally update with the right avatar — see video below:

https://user-images.githubusercontent.com/216089/110375258-07b66680-8052-11eb-9d0e-43897b4480dc.MP4

**Comment by yaelirub** [comment] 2021-08-13 20:24
![IMG_E69AB529AFD9-1](https://user-images.githubusercontent.com/1335657/129414465-2a38569d-2a79-4611-a4a8-106afd4f6e15.jpeg)

Probably due to the same underline issue, Avatars can look duplicate @diegoreymendez think you can look into this when you have some time?

**Comment by diegoreymendez** [comment] 2021-08-14 08:04
Hey @yaelirub, just seen this.  I'm AFK this upcoming week and I'm already in the process of leaving.

That said I still tried looking into this but found nothing relevant.  In my humble opinion the code we're using to download images for that list could use a review.

As a side note, it seems we're now downloading images differently to what was reported by @ceyhun.  This seems to be in relation to "unified list" changes by @dvdchr .  I really don't think the culprit is the new code since this has been present for a while, but maybe you can give this a look while I'm away @dvdchr ?

**Comment by dvdchr** [comment] 2021-08-16 04:17
Hey @diegoreymendez. Sure, no problem! I'll take a look at it today. 🙂

---
**Update**: I took a look and wasn't able to reproduce the issue. However: 

> ... the code we're using to download images for that list could use a review.

@diegoreymendez 's assumption makes sense, since currently the image requests aren't cancelled when the cell is reused for another row. This way, the image view may be assigned with the old image _after_ the cell is reused for another row.

**Comment by startuptester** [comment] 2021-09-15 06:36
Mentioned again in p1631638725106000-slack-wpmobile

**Comment by diegoreymendez** [comment] 2021-09-20 11:29
Tentative fix pushed: https://github.com/wordpress-mobile/WordPress-iOS/pull/17197

**Closed as completed** 2021-09-20 22:44 UTC
Labels: Notifications

**Comment by joashrajin** [comment] 2022-08-08 09:38
I'm still replicating this on our Jetpack App but only noticed it start happening recently. Using JP v20.3 (20.3.0.2), iOS 15.6, iPhone 13

More context can be found at p1659950679857109-slack-C03MHJFF58A

**Comment by joashrajin** [comment] 2022-08-08 09:38
I'm still replicating this on our Jetpack App but only noticed it start happening recently. Using JP v20.3 (20.3.0.2), iOS 15.6, iPhone 13

More context can be found at p1659950679857109-slack-C03MHJFF58A

cc: @diegoreymendez
