### ISSUE TITLE
Individual post stats are displaying stats counts for posts all the way back to 1970

### ISSUE THREAD

**Issue by charliescheer** [wordpress-mobile/WordPress-iOS#9435] opened 2018-05-22 19:30 UTC
Hey y'all, while poking around in 10.1.  If you are exploring your posts in the WordPress app and you click on the stats button that appears on My Site > Blog Posts, the stats page that appears shows all of the posts history back through time, and currently it goes all the way back to 1970.  This seems a little odd to me if the post was created in 2018.  Should these years of stats only show the available history for that post?

To see this behavior:
1. Go to My Site > Blog Posts
2. Pick a post and click on Stats
3. Should see something like this (note this post was created in 2018)

<img src='http://cld.wthms.co/HsXwhY+'>

WordPress 10.1
iOS 11.3
iPhone 6s

**Comment by elibud** [comment] 2018-05-28 13:48
@charliescheer we are going to revamp this whole section really soon.

cc: @SylvesterWilmott

**Comment by charliescheer** [comment] 2018-05-28 21:49
cool @elibud 
thanks for letting me know

**Comment by rachelmcr** [comment] 2018-09-11 10:31
Closing as a duplicate of https://github.com/wordpress-mobile/WordPress-iOS/issues/7171.

**Closed by rachelmcr** 2018-09-11 10:31 UTC
Labels: Stats
