### ISSUE TITLE
Unable to change date of a published post

### ISSUE THREAD

**Issue by alinclamba** [wordpress-mobile/WordPress-iOS#23369] opened 2024-06-18 09:39 UTC
### Expected behavior

If I want to change the date of a published post, I expect to see the new date, but it's not happening.

### Actual behavior

Edit a published post, and before updating/publishing, I change the publish date but the date isn't updating. 

### Steps to reproduce the behavior

1. Open a previously published post and make some changes
2. Before saving the changes, choose change the publish date and then update the post.
3. See that the publish date didn't change. 

This happens on mobile app only. I am able to change the post on Web. 

##### Tested on [device], Android [version], JPAndroid / WPAndroid [version]

I tested on my Google Pixel phone with Android, but it was also reported 8323256-zd-a8c and [here](https://link.reviewbot.io/notification?action=share&review=b5dDFzdaAzqC2Pdqno08).

Issue initially opened [here]( https://github.com/Automattic/jetpack/issues/37851)

**Comment by dangermattic** [comment] 2024-06-18 09:40
Thanks for reporting! 👍

**Comment by kean** [comment] 2024-06-18 12:59
I'm not able to reproduce this in the iOS app, and the initial report was also for Android, so I'm going to close it.

**Closed as completed by kean** 2024-06-18 12:59 UTC
