### ISSUE TITLE
Deleting a media object that's failed to upload because of a missing local file.

### ISSUE THREAD

**Issue by AliSoftware** [wordpress-mobile/WordPress-iOS#18554] opened 2022-05-10 17:03 UTC
**Sentry Url**: https://sentry.io/share/issue/892de0b5b0cc46c08f830ae347e70d51/
**User Count**: 7085
**Count**: 148073
**First Release**: 18.0.0.1
**First Seen**: 2021-08-16T07:48:08.860000Z
**Last Seen**: 2022-05-10T16:49:03Z
**24 Hours**: 681
**30 Days**: 17100

```
Deleting a media object that's failed to upload because of a missing local file. Error Domain=MediaServiceErrorDomain Code=0 "Media doesn't have an associated file to upload." UserInfo={NSLocalizedDescription=Media doesn't have an associated file to upload.}
```

**Comment by hypest** [comment] 2022-05-11 08:04
Possibly duplicate of https://github.com/wordpress-mobile/WordPress-iOS/issues/15096?

**Comment by alpavanoglu** [comment] 2022-05-18 14:49
Closing due to duplication as mentioned.

See #15096

**Closed as completed by alpavanoglu** 2022-05-18 14:49 UTC
Labels: [Type] Crash, [Pri] Low
