### ISSUE TITLE
Whatsapp Share button hard to see

### ISSUE THREAD

**Issue by charliescheer** [wordpress-mobile/WordPress-iOS#8912] opened 2018-03-15 16:48 UTC
I was alerted to this issue from a user in this issue https://automattic.helpshift.com/admin/issue/267452/  If you try to share a post from the WordPress app to Whatsapp, the blue color of the share button is so close to the blue color of the WordPress app header it makes seeing the button difficult.  
<img src='http://cld.wthms.co/PVBZ4X+'>

I tried a few other share options in the WordPress app and didn't see the same problem, I think that this color is chosen by Whatsapp.  I also tested sharing to Whatsapp from Applenotes and the same blue appears, but since the notes header is light brown so visibility is not a problem.  

To Reproduce:
1. Go to My Site > Blog Post > Share > WhatsApp
2. Choose a chat to share the post to.  On the page where you can modify the message the share button appears.

WordPress 9.4
iOS 11.2.6
iPhone 6s

**Comment by nheagy** [comment] 2018-12-21 06:46
I haven't yet found a solution, but I have discovered this also happens when sharing via Mail.app:

![image](https://user-images.githubusercontent.com/517257/50328695-00263980-04a9-11e9-8e79-80b8b4a2e9c9.jpeg)

**Comment by thehenrybyrd** [comment] 2018-12-23 17:39
Another report of this in #1649150-zen, pertaining to the Whatsapp sharing button.

**Comment by thehenrybyrd** [comment] 2019-02-11 08:55
Another report in #1786562-zen - the user didn't realize the button was there at all.
I've rectangled the send button in this image:
![sendbutton](https://user-images.githubusercontent.com/15107387/52553208-78471680-2deb-11e9-89b8-5066447b1d6f.png)

**Comment by designsimply** [comment] 2019-02-14 20:23
Tested and confirmed with iPhone 6S, iOS 12.1.4, WP Internal 11.8.0.20190211. Accidentally reported this as a duplicate (bah!) at https://github.com/wordpress-mobile/WordPress-iOS/issues/11037 when it came up in feedback on the WPiOS 11.8 call for testing. 

Closing this issue and consolidating to https://github.com/wordpress-mobile/WordPress-iOS/issues/11037 because that one managed to get reply/explanation from a developer first. @nheagy @thehenrybyrd check out the notes there about the <em>Send</em> button in Mail being dimmed because a `To:` address has not been entered yet.

**Closed by designsimply** 2019-02-14 20:23 UTC
Labels: Sharing, [Type] Broken Window, [Type] Bug
