### ISSUE TITLE
HTML for Images with Captions + Links Is "Jumbled" Within the App

### ISSUE THREAD

**Issue by SiobhyB** [wordpress-mobile/WordPress-iOS#9934] opened 2018-08-08 11:36 UTC
### Expected behavior

If I add a caption to an image within a web browser, I expect that caption to remain in place when I edit the post within the mobile app.

### Actual behavior

If an image's caption includes a link at the very end, then the HTML for the image will "jumble" up when the post is opened in the app. 

The following screenshot shows an example of this:

![attachment_2018-08-05t17_22_29z](https://user-images.githubusercontent.com/2998162/43834529-4d5dfc5e-9b06-11e8-9d00-e1325d0648cc.png)

In the above screenshot, "Pexels.com" is the last part of the caption, and it's been moved to the beginning of the image.

### Steps to reproduce the behavior

1. Upload a new image to a post within a web browser.
2. Add a caption to the image and make sure that the caption ends with a hyperlink.
3. Save your changes and navigate away from the post editor within the web browser.
4. Open the post within the WordPress mobile app.
5. View how the caption looks within the app's post editor. Update the post, without making any other changes, and confirm that the HTML for the images is jumbled up within the actual post too.

Example code to replicate behaviour:

```
[caption id="attachment_112849" align="aligncenter" width="1000"]<img class="wp-image-112849 size-full" src="https://images.pexels.com/photos/1302883/pexels-photo-1302883.jpeg" width="1000" height="668" /> Image from <a href="http://www.pexels.com">pexels.com</a>[/caption]
```

**Note:** To replicate this issue, the hyperlink must be at the end of the caption. It's not possible to replicate is the hyperlink is at the beginning or end.

##### Tested on iPad Mini, iOS 11.4.1, WPiOS 10.5

**Comment by SiobhyB** [comment] 2018-08-08 11:36
This was reported in 1324398-z.

**Comment by rachelmcr** [comment] 2018-12-19 13:46
I tested this in the Gutenberg mobile alpha and confirmed that the image + caption with a link works as expected when edited in the app. Since this is not a high-occurrence issue, I'm going to close it given that editor development is focused on Gutenberg with only critical fixes in Aztec. It will be resolves when Gutenberg launches publicly.

**Closed by rachelmcr** 2018-12-19 13:46 UTC
Labels: Posting/Editing, [Type] Bug
