### ISSUE TITLE
File Download Stats being counted by usage in the app

### ISSUE THREAD

**Issue by azollafox** [wordpress-mobile/WordPress-iOS#12738] opened 2019-10-21 17:35 UTC
### Expected behavior

When I view a video in the app from my media library or preview it in a page in the app that view shouldn't count on my stats

### Actual behavior

My file download stats go up from work I do on my Android App

### Steps to reproduce the behavior

1. Add a video to your media library
2. Preview a page and play the video or watch the video after selecting it in your media library
3. Wait a bit and check your stats. The file downloads will have increased by at least 2.

##### Tested on iPad, iPadOS 13.1.3 , WPiOS 13.3

Reported by user in #2403740-zen

**Comment by ScoutHarris** [comment] 2019-10-21 17:53
Hi @sarahfg .

Can you confirm this also happens in Calypso? It probably happens on Android as well. The mobile apps are simply using an API endpoint to get this data, so I would expect the same behavior on all platforms. 

> My file download stats go up from work I do on my Android App

This makes sense - _File Downloads_ counts all activity, not just on iOS. (Whether is it accurate or not, whatever increases the count in Calypso or Android will be reflected on all platforms).

Once confirmed this is not an iOS specific problem, I'll report it accordingly.

Thanks!

**Comment by sarahfg** [comment] 2019-10-22 17:58
I have not been able to get the file download stats to increase while using Calypso in the same way.

**Comment by ravishanker** [comment] 2024-04-05 01:28
A duplicate of https://github.com/wordpress-mobile/WordPress-Android/issues/10653 on Android

**Comment by ravishanker** [comment] 2024-04-05 04:23
This is duplicate issue of one on WPAndroid.  See https://github.com/wordpress-mobile/WordPress-Android/issues/10653

**Closed by ravishanker** 2024-04-05 04:23 UTC
Labels: [Type] Bug, Stats
