### ISSUE TITLE
Image layout in comment detail can be off.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#2264] opened 2014-08-20 15:15 UTC
I noticed we have images in the comment detail now. (Yay!)  I also noticed that the image placement can be off after changing orientation. (Boo!)

## Before
![ios simulator screen shot aug 20 2014 9 54 19 am](https://cloud.githubusercontent.com/assets/1435271/3983080/a17e8ab6-287c-11e4-81e2-b02b5295ea9e.png)

## After
![ios simulator screen shot aug 20 2014 9 54 56 am](https://cloud.githubusercontent.com/assets/1435271/3983083/a58f1b7a-287c-11e4-973e-3b4b56471f76.png)

**Comment by rachelmcr** [comment] 2015-11-26 14:19
I tried to test/reproduce this in the latest beta (5.8.0.20151124) and couldn't. If I'm looking at comment detail on the site (My Sites > Select site > Comments > Select the comment) I see the HTML for the image rather than the image itself.

In other places (e.g. the Reader or Notifications) the image placement is correct after changing orientation.

I'm going to close this as it seems things have changed since the original report, but please reopen if I missed something.

**Closed by rachelmcr** 2015-11-26 14:19 UTC
Labels: General, [Type] Bug

**Comment by aerych** [comment] 2015-11-30 16:14
Thanks for following up on this one!
