### ISSUE TITLE
Signup: gray background shouldn't appear behind grouped table header and footer.

### ISSUE THREAD

**Issue by mattmiklic** [wordpress-mobile/WordPress-iOS#16073] opened 2021-03-11 22:48 UTC
On the account confirmation screen (epilogue), there is a gray background behind the Account Details header and password footer. These elements should not have a background color of their own (it should be white in light mode, black in dark mode).

![IMG_4437](https://user-images.githubusercontent.com/1396552/110865629-e643bd80-8291-11eb-84d1-9a18c88537b4.PNG)
![IMG_4438](https://user-images.githubusercontent.com/1396552/110865631-e643bd80-8291-11eb-9213-1fc7cc3c8d4e.PNG)

This is in version 16.8.

**Comment by mindgraffiti** [comment] 2022-05-03 18:57
Hey @mattmiklic 👋 
I can't reproduce the gray background color in version 19.8 on an iPhone 12 Pro simulator. Do you have any details on the device this was found on? 

| Light | Dark |
| --- | --- |
| ![Simulator Screen Shot - iPhone 12 Pro - 2022-05-03 at 13 24 04](https://user-images.githubusercontent.com/1062444/166523456-218a45bb-5317-4dd6-9dff-787a8e9fa100.png) | ![Simulator Screen Shot - iPhone 12 Pro - 2022-05-03 at 13 24 38](https://user-images.githubusercontent.com/1062444/166523462-c0badf36-f404-4495-b9ac-800bb30d565e.png) |

**Comment by mattmiklic** [comment] 2022-05-03 19:01
Hey @mindgraffiti -- I just tested this and can no longer reproduce it either. Looks like it was fixed or it fixed itself at some point since this issue was opened. 🎉

**Comment by mindgraffiti** [comment] 2022-05-03 19:03
Verified fixed as of WPiOS version 19.8.

**Closed as completed by mindgraffiti** 2022-05-03 19:03 UTC
