### ISSUE TITLE
Bug: Keyboard Flickering

### ISSUE THREAD

**Issue by bsanevans** [wordpress-mobile/WordPress-iOS#11583] opened 2019-04-29 01:16 UTC
### Expected behavior
The keyboard should appear and stay.

### Actual behavior
The keyboard appears, then disappears, endlessly.
Video: https://d.pr/free/v/LDBntN

### Steps to reproduce the behavior
1. Create new post
2. Type title
3. **Double-tap** below the title to enter text.

I could only reproduce it when making a new post, not when editing that post after saving it once or editing an existing post.

##### Tested on [device], iOS [version], WPiOS [version]
iPad Air (from 2013), iOS 12.2, WPiOS 12.3.0.2

**Comment by designsimply** [comment] 2019-04-29 18:13
Thank you for testing and for including a short video! I tried testing this today using WP Internal 12.3.0.20190422 on iPad Mini 4 (WiFi) (iPad5,1) iOS 12.2 with several different site types and was able to reproduce the problem only once and only on a self-hosted site—after I spotted the bug, the editor got stuck and I had to force close the app to get it working again and then the editor worked normally for me after that. ([5m28s](https://cloudup.com/cNZRiJthyG6))

@bsanevans does this problem happen for you for every site in your account and does it happen every single time you start a new post? If you close and re-open the app, does the problem go away?

**Comment by designsimply** [comment] 2019-04-29 21:55
Quick update to note I asked for help testing and @etoledom & @iamthomasbishop both tried but couldn't replicate the bug. Because of that, I'm not sure yet whether this one should go to `[Pri] High` and I will loop back to check in on this issue again tomorrow.

**Comment by bsanevans** [comment] 2019-04-30 01:07
Hi @designsimply , here's an update on the bug.
I did a hard restart on my iPad and reopened the app and could not replicate the bug any longer. I tried the same steps on sites with different WP.com plans and also self-hosted. I tried on new pages/posts and saved/published pages/posts and couldn't replicate the bug any more.
Sorry for the false alarm... Perhaps it was just a device resource issue.

**Comment by pinarol** [comment] 2019-04-30 15:15
I couldn't reproduce this either, tried on the latest develop. I could only reproduce it with AppStore version. So it looks like it's been fixed with some other fix lately. Let's see if it'll be back, un-assigning from myself for now.

**Comment by rachelmcr** [comment] 2019-05-24 10:31
I experienced this on the latest internal beta, on different WordPress.com Simple sites, reliably reproducing it with these steps:

1. I started a new post and entered a title.
2. I tapped Enter twice in quick succession. (I knew I wanted to write an intro paragraph, but I wanted to start by writing the second paragraph of the post, so my intent was to leave a blank paragraph block at the top of the post to come back to later.)
3. The cursor started flipping back and forth between the two empty paragraph blocks. No attempt to tap in those blocks or elsewhere in the editor (e.g. on the title block) stopped that behavior.
4. I tried entering text in the blocks. This stopped the cursor from moving back and forth between blocks, but the keyboard immediately started flashing/hiding/disappearing.
5. I tried tapping on the close button and the ellipsis menu in the top nav bar, to either exit the editor or switch screens. I saw the buttons highlighted but the menus didn’t open.
6. I force-closed the app to escape the situation. When I reopened the app, I was able to find my local draft and reopen it to continue (but if I tap Enter twice again the problem reoccurs).

I restarted my device, tried the same steps again, and continued to get the same results. Restarting the app and/or the device did not resolve the issue for me.

Tested on my iPad Mini, iOS 12.2, WPiOS 12.5.0.20190520

**Comment by etoledom** [comment] 2019-05-24 11:11
This is most probably related to process speed.
I'm not able to reproduce it in the latest models of iPhone or iPad, but I'm able to reproduce it on an iPhone 7 (trying very hard to do so).

We also have been able to reproduce this issue in dev mode, where the speed is slower.

**Comment by etoledom** [comment] 2019-06-04 10:09
Tracking on gutenberg-mobile: https://github.com/wordpress-mobile/gutenberg-mobile/issues/1063

**Closed** 2019-06-05 07:58 UTC
Labels: Beta Request, Gutenberg compatibility, Posting/Editing, [Type] Bug
