### ISSUE TITLE
Post title encoding issues on Insights tab

### ISSUE THREAD

**Issue by jeremeylduvall** [wordpress-mobile/WordPress-iOS#4731] opened 2016-01-24 23:04 UTC
When I view the Insights tab for my self-hosted site on 5.8, the characters in the title are not encoding properly. The correct title is "Deep Work in Practice – Applying Cal’s Concepts":

![img_2946 1](https://cloud.githubusercontent.com/assets/7240478/12539599/176a68ee-c2b4-11e5-8dc3-59f2b7c64748.jpg)

I tested the same title in BlueStacks (not sure if that's 100% accurate) in 4.9, but didn't experience the issue. Interestingly enough, I didn't experience the issue on a WP.com site with the same title (perhaps just Jetpack?). Perhaps this is a one-off issue, but wanted to log just in case.

I'll be using some apostrophes in my next post title so will make sure to double-check this.

**Comment by rachelmcr** [comment] 2016-01-25 17:42
I confirmed that HTML entities are showing up on the Insights tab for posts on WordPress.com sites as well in app beta v. 5.9.0.20160113.

**Comment by hoverduck** [comment] 2017-01-25 15:38
Closing, unable to reproduce in v6.8.0.20170112 (checked on both a WP.com and a Jetpack site)

**Closed by hoverduck** 2017-01-25 15:38 UTC
Labels: Stats, [Type] Bug
