### ISSUE TITLE
[Stats Refresh] Insights Comments details doesn't show all 

### ISSUE THREAD

**Issue by ScoutHarris** [wordpress-mobile/WordPress-iOS#11713] opened 2019-05-16 17:46 UTC
For Insights > Comments, the API only returns 7 Authors and 11 Posts and Pages. Always. For any site. The Insights card looks fine since it is limited to 6 rows. However, when `View more` is selected, only 7 Authors and 11 Posts and Pages are displayed. 

The old Stats does this, as well as the new Android Stats and Calypso. However, the old Stats didn't have a `View more` option, so it wasn't obvious that it was limited.

Checking Calypso, Comments is a bit different. It doesn't have a `View All` option like Followers, that lists all for a given filter. 

<img width="300" alt="followers" src="https://user-images.githubusercontent.com/1816888/57874036-e2959b80-77cc-11e9-9931-4407f092dad6.png">

Comments has one link that shows `Total posts with comment followers`, with no filters.

<img width="300" alt="comments" src="https://user-images.githubusercontent.com/1816888/57874063-f0e3b780-77cc-11e9-86c7-480e73410064.png">

To note, the endpoint we're using is `/sites/<siteID>/stats/comments`. 

There doesn't appear to be an endpoint that provide all Comments filtered by Authors and Posts. There should be an endpoint that will give us all Comments in one list, as Calypso displays them.

**Comment by SylvesterWilmott** [comment] 2019-05-17 14:53
This explains a lot!

This shouldn't change anything in the way we display this data. We should still show a `View more` button to deliver all the data we have to the user.

**Comment by ScoutHarris** [comment] 2019-05-17 19:16
@SylvesterWilmott - sorry I wasn't clear. I'm proposing:
- We leave Insights Comments card just like it is, including the `View more`.
- However, on the details view, since we don't have a way to get all filtered comments, _don't_ have a filter tab bar. Instead, show the full combined list like Calypso does when you click on the 'Total posts' link.

One caveat. Regarding this statement:
> There should be an endpoint that will give us all Comments in one list, as Calypso displays them.

I haven't had a chance to explore this. My suggestion is based on the _assumption_ this enpdoint exists and does what I think it will.

**Comment by ScoutHarris** [comment] 2019-05-20 19:23
`/sites/$site/stats/comment-followers` is the endpoint that returns the unfiltered Comments list. However, it only returns 20 results. Per the [documentation](https://developer.wordpress.com/docs/api/1.1/get/sites/%24site/stats/comment-followers/):

<img width="607" alt="max_param" src="https://user-images.githubusercontent.com/1816888/58046222-ecd3d480-7b01-11e9-9732-8590473078c2.png">

It does have these response params:

<img width="678" alt="response_params" src="https://user-images.githubusercontent.com/1816888/58046316-27d60800-7b02-11e9-9288-bfcdd9406f21.png">

I don't know if there's some way we can repeatedly call the endpoint and compile all (or a certain max) results, but at the very least, if we add a new call, we can 20 results. 

@SylvesterWilmott - what are your thoughts on showing an unfiltered details list?

@jklausa - what are your thoughts on the endpoint?

**Comment by SylvesterWilmott** [comment] 2019-05-22 12:53
>what are your thoughts on showing an unfiltered details list?

I'm on board.

**Comment by ScoutHarris** [comment] 2019-06-04 23:26
Hey @SylvesterWilmott - In Calypso, when you click the `Total posts with comment followers` link and it shows all Comments Followers, the very first row is a total row.

<img width="1178" alt="calypso_all_comments" src="https://user-images.githubusercontent.com/1816888/58920080-cad77600-86ed-11e9-88ac-483ccb5cc88c.png">


Do we want to show that, or just show the list of Posts?

cc @planarvoid

**Comment by ScoutHarris** [comment] 2019-06-04 23:46
@SylvesterWilmott sorry, I just noticed in the API response that total row is actually the Home page. 

<img width="325" alt="api_response" src="https://user-images.githubusercontent.com/1816888/58920681-8bf6ef80-86f0-11e9-94de-d2f5b5ad53d9.png">

If we don't like the 'All Posts' row as shown above, we could alternatively display it as 'Home Page', and tappable like all the other post rows.

**Comment by ScoutHarris** [comment] 2019-06-07 17:07
Per a Slack conversation with @SylvesterWilmott , we've decide just to not show the `View more` option for _Comments_ until he has a chance to consider this issue.

**Comment by staskus** [comment] 2024-04-04 09:31
I'm closing this Task since it belongs to an outdated project. If we ever recognize a need for this functionality, we can create a new project or a new task.

I can confirm that the limitation of 7 authors and 11 posts & pages still exists on `/sites/<siteID>/stats/comments` endpoint.

Both the app (Insights -> Total Comments -> Top Commenters -> View More) and WP.com (Insights -> Comments) display the same information with the same limitation. 

cc @guarani

**Closed by staskus** 2024-04-04 09:31 UTC
Labels: [Type] Enhancement, Stats
