### ISSUE TITLE
Post/Pages: Extra animation when deleting an entry and undoing the deletion.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-iOS#3895] opened 2015-06-19 00:04 UTC
To reproduce:
1. Trash a post from the middle of the list.
2. Undo the operation.
3. Let the post come back up, don't touch anything.  Wait.
4. The post trash animation will be repeated.  Wait some more.
5. The post restore animation will be repeated.

**Comment by aerych** [comment] 2015-06-19 00:09
Could that be a timing thing? We optimistically save changes.  If the undo was triggered before the delete http call had finished I could see this happening.

**Comment by rachelmcr** [comment] 2015-11-30 18:17
I do think this is a timing thing. I tested this with my phone connected to EDGE and reproduced the issue with the steps above. (I couldn't reproduce it while connected to a fast wifi network.)

**Comment by designsimply** [comment] 2017-07-12 22:42
I tested and was also unable to reproduce the problem on a fast connection:

1. Go to My Site > Blog Posts.
1. Scroll to a post in the middle of the list.
1. Tap "More."
1. Tap "Trash."
1. Tap "Undo."

<strong>Result:</strong> after tapping "Undo," a red trashcan icon and the word "Trashed" and some of the post content appear under the post. Sometimes the extra content and red trash icon disappear after a few seconds and sometimes they 

<strong>Video:</strong> [36s](https://cloudup.com/cnUTsFENLTv)

<img alt="screen shot 2017-07-12 at wed jul 12 4 19 59 pm" src="https://user-images.githubusercontent.com/1119271/28142467-37b96478-671e-11e7-9712-dac6260330e1.png" width="270" />
<sup>Tested using iPhone 6S, iOS 10.3.2, WP Internal 8.0.0.20170712 on a fast connection (50mbs).</sup>

<strong>Video:</strong> [40s](https://cloudup.com/c06H2OwPzEE)

<img alt="screen shot 2017-07-12 at wed jul 12 4 36 18 pm" src="https://user-images.githubusercontent.com/1119271/28143044-d73b836c-6720-11e7-8fe6-dc1a8ae9011a.png" width="270" />
<sup>Tested using iPhone 6S, iOS 10.3.2, WP Internal 8.0.0.20170712 on a fast connection (50mbs).</sup>

Closing due to the issue having been open for over 2 years without activity. Please re-open if this comes up again or if you feel it should be re-tested on a slow internet connection.

**Closed by designsimply** 2017-07-12 22:42 UTC
Labels: Pages List, Posts List, [Pri] Low, [Type] Bug
