### ISSUE TITLE
Allow users to make a post sticky within the post options screen

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-iOS#3968] opened 2015-07-03 00:45 UTC
From a user:

> Suggestion for the app. Allow to turn on/off the Sticky feature on the posts. Right now, I have to keep going to the Wp Admin to turn it back on when I update a post in the app. It turns it off. Thanks!

**Comment by rachelmcr** [comment] 2016-02-04 17:00
Closing this issue as a dupe of https://github.com/wordpress-mobile/WordPress-Editor-iOS/issues/197.

**Closed by rachelmcr** 2016-02-04 17:00 UTC
Labels: Editor, [Type] Enhancement
