### ISSUE TITLE
Reader: Empty space at top of some post detail views

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#10834] opened 2019-01-16 12:01 UTC
### Expected behavior

I expect that when I view the post detail in the Reader, the post content will begin directly below the title and author/timestamp for the post.

### Actual behavior

Some posts show a large gap of empty space at the top of the post detail view.

This consistently happens with certain posts that begin with an image: posts created in the Calypso classic editor with the Calypso Reader's Share button (e.g. [this one](https://rachel-test-domain.com/2019/01/16/photo-post-do-a-little-test/)) and posts created in the iOS block editor (Gutenberg) starting with an image block (e.g. [this one](https://rachel-test-domain.com/2019/01/16/photo-post-ios-block-editor/)).

It _doesn't_ consistently happen with posts created in Aztec (e.g. [this one](https://rachel-test-domain.com/2019/01/16/photo-post-2/)) or the Calypso block editor (e.g. [this one](https://rachel-test-domain.com/2019/01/02/photos-calypso-block-editor/)).

The empty space goes away after swiping up (a fast scroll down the post).

Example of the empty space in a post created in iOS Gutenberg:

![2019-01-16 11 40 34](https://user-images.githubusercontent.com/8658164/51247690-d6681180-1985-11e9-9314-a9c88521f5fd.png)

### Steps to reproduce the behavior

1. Enable Gutenberg in the app (internal only).
2. Add an image block at the top of the post. (Other post content can be optionally included.)
3. Publish the post.
4. View the post detail in the Reader.

**Comment by yaelirub** [comment] 2019-01-21 20:37
hey @elibud , @jkmassel. I was investigating #10848 a bit yesterday and it seems like reverting this code:
`attachment.maxSize = CGSize(width: proposedSize.width, height: proposedSize.height)`
back to:
`attachment.maxSize = CGSize(width: finalSize.width, height: finalSize.width / 2.0)`
as it was before #10351 seems to fix the issue.
![simulator screen shot - iphone 8 - 2019-01-21 at 12 35 46](https://user-images.githubusercontent.com/1335657/51497810-29bcd400-1d79-11e9-8e34-ea7d3cfbb9f7.png)

![Uploading Simulator Screen Shot - iPhone 8 - 2019-01-21 at 12.33.20.png…]()
@rachelmcr , I was unable to reproduce the issue from your post:
![simulator screen shot - iphone 8 - 2019-01-21 at 12 37 01](https://user-images.githubusercontent.com/1335657/51497841-4527df00-1d79-11e9-8936-b02e7085ce9a.png)

**Comment by jkmassel** [comment] 2019-01-21 21:31
It _does_ seem to fix the issue, but I'm curious _why_ it fixes the issue. Setting the height to 50% of the width might make things look right, but it seems like a weird fix – what happens if you have a portrait aspect ratio image? Will it be squished? Why aren't we using the proposed image height? Why does this (IIRC) only happen with gifs, and not other image types?

I could totally be missing something, but I'd imagine this is masking another underlying bug. Worth looking into, IMHO, anyway :)

**Comment by yaelirub** [comment] 2019-01-21 21:50
I think the fix is not about setting the height to half the width. I think the issue is that sizeForAttachment returns maxDisplaySize.height for the height since the height in the attachment is 0.

**Comment by yaelirub** [comment] 2019-01-21 22:58
@jkmassel , any suggestion on what to set the height to when its 0 in the attachment attributes?
Also, when do we expect to get those values in an attachment (the only value I currently get is the url)

**Comment by jkmassel** [comment] 2019-01-22 16:16
Hey – I didn't see that you'd filed a PR for this! :( 

I put some thoughts on a fix here (doesn't need to be merged, just the easiest way to share it): https://github.com/wordpress-mobile/WordPress-iOS/pull/10878

>any suggestion on what to set the height to when its 0 in the attachment attributes
My thought is we just handle the special-case height of zero, then once we have the image data, update the layout if needed. 

>when do we expect to get those values in an attachment
Ideally they'd be set in the `<img>` tag attributes, but if not, we have to wait for the image data to come in to _really_ know how big it is 😞

**Closed** 2019-01-22 22:49 UTC
Labels: Reader, [Type] Bug
