### ISSUE TITLE
Reader: Race condition toggling "block site" can get post state out of sync

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#4265] opened 2015-09-09 16:21 UTC
This is easiest to reproduce on a slow connection.

Pick a post card and quickly toggle its "block site"  / "undo" behavior. The block vs unblock state in the app can get out of sync with the state on the server.  Its tricky to mitigate this race condition but let's at least make sure that the last call to finish is what we treat as the canonical state and update things to reflect it. 

Kudos @diegoreymendez for the testing that shined a light on this one.

**Comment by hoverduck** [comment] 2017-01-24 19:08
> This is easiest to reproduce on a slow connection

@aerych - I'm unable to reproduce this with the new Reader UI, but maybe my connection just isn't slow enough ;)

Closing, but feel free to reopen if there's something else you want to fix here

**Closed by hoverduck** 2017-01-24 19:08 UTC
Labels: Reader, [Type] Bug
