### ISSUE TITLE
Stats: Post List in the "View more" view doesn't load after previewing Stats for one post

### ISSUE THREAD

**Issue by erricgunawan** [wordpress-mobile/WordPress-iOS#14377] opened 2020-06-24 02:51 UTC
### Expected behavior

The Post list in the "View more" view would always display the list after previewing the post' Stat.

### Actual behavior

The Post list view just stuck on the loading screen where the list is greyed out. (See screenshot).

<img src="https://user-images.githubusercontent.com/1813857/85492909-24178d80-b600-11ea-97a7-f94cef4c3c5f.png" width="270" alt="IMG_2511">

### Steps to reproduce the behavior

1. Go to My Site > Stats
2. We can pick any of Days, Weeks, Months, Years, but make sure to pick a period where it would have more than 6 posts/pages under the "Posts and Pages" section.
3. Tap "View more".
4. Check all the posts/pages are listed fine.
5. Choose any random post from the list. 
6. Make sure all the data loads fine, but don't tap anything there.
7. Tap Back (on the top left).
8. The Post Lists would be greyed out and it stuck on the loading screen (see screenshot above).

Additional steps: 

From the stuck loading screen, if we go back by tapping the "Stats" on the top left, then do the pull-down to refresh the screen, if we tap "View more", the list would load fine.

If we don't do the pull-down/up, tapping "View more" would just display the stuck loading post list again.

Reported on 3076696-zen with a Video screencast and 1225 lines of Log. 
I didn't include them here but let me know if I should.

**Comment by designsimply** [comment] 2020-06-24 20:35
Thanks for the well-written bug report @erricgunawan!

Tested and confirmed that pressing back after viewing Post Stats on a screen with more than 6 or 7 Posts and Pages listed on the View More page results in the paginated results stuck loading.

<img src="https://user-images.githubusercontent.com/1119271/85624868-ca2abe00-b627-11ea-8d90-ff9910b8ca69.gif" width="270" alt="14377-stats-posts-and-pages-stuck-after-viewing-post-stats-then-going-back-to-view-more">

<p style="clear:both;"><sup>Tested with WPiOS 15.1.0.2 TestFlight beta on iPhone 6S iOS 13.3.1.</sup></p>

**Comment by staskus** [comment] 2023-01-19 13:45
Note: Still reproducible

**Comment by guarani** [comment] 2024-03-18 09:45
I couldn't reproduce this. On JPiOS 24.4.0.4, I did these steps:
1. Tapped Stats
2. Switched to the Traffic tab and chose Months 
3. Tapped "View more" under Posts and Pages
4. Tapped the first result to get to the Post Stats screen
5. Tapped back and landed back on the Posts and Pages list
6. The app isn't stuck loading like shown in the screenshot or screen recording above

@staskus, would you be able to check this again please? It's been a year since you reproduce this and it may have been fixed.

**Comment by staskus** [comment] 2024-03-18 12:31
@guarani thanks, I'll try to reproduce as well.

**Comment by staskus** [comment] 2024-03-18 14:13
@guarani 

Yes, this issue is not reproducible anymore 🎉 .

However, I remember testing and reproducing this issue. I downloaded 23.9 and reproduced the issue. Since I made a couple of improvements to `StatsPeriodStore` and other common places, it looks like it addressed this issue. 👍

**Closed by staskus** 2024-03-18 14:13 UTC
Labels: [Type] Bug, [Pri] Low, Stats

**Comment by guarani** [comment] 2024-03-27 19:01
Closing this as not planned instead of completed since we couldn't reproduce. I think that better captures the result here, especially in the context of the "Stats Bug Hunt" project. 

> Since I made a couple of improvements to StatsPeriodStore and other common places, it looks like it addressed this issue. 

I appreciate the improvements you made here that fixed this bug 🙇
