### ISSUE TITLE
Sharing shows old connections

### ISSUE THREAD

**Issue by kwonye** [wordpress-mobile/WordPress-iOS#6024] opened 2016-09-29 16:01 UTC
There has been a report where a user removed their connection, but it still shows on the app. The user's verified that on the web the account doesn't show.

When adding again, the mobile app showed two connections (both the same account, just one was old)

**Comment by aerych** [comment] 2016-10-07 18:31
(h/t @allendav for the report)

**Comment by astralbodies** [comment] 2016-11-23 21:14
@kwonye @allendav Is this with the share extension, Jetpack, or something else?

**Comment by aerych** [comment] 2016-11-28 15:31
@astralbodies This is regarding Publicize connections under the My Sites > Site name > Sharing feature.

**Comment by aerych** [comment] 2016-11-28 15:32
@allendav have you seen this lately?

**Comment by astralbodies** [comment] 2016-11-28 17:16
@aerych Ahha okay! For some reason I didn't realize this was there. I was expecting to see it under post options. 

More coffee required.

**Comment by hoverduck** [comment] 2017-01-27 15:54
I was unable to reproduce this with a Facebook connection (didn't try others).  Have there been any other reports of this kind of problem?

@allendav - Do you remember any more details about what exactly went wrong?

Which connection was it?
Approximately how long was it disconnected?
Had it been connected for a long time previously, or was it new?
Did you disconnect it from the web, or the mobile app?
How did you notice that it still showed connected, were you manually looking at your sharing settings, or did a post get shared when it wasn't supposed to?

**Comment by elibud** [comment] 2018-03-30 20:21
I'm closing this one as we haven't been able to replicate, please reopen the issue if it happens again.

**Closed by elibud** 2018-03-30 20:21 UTC
Labels: Sharing, [Pri] Low, [Type] Bug
