### ISSUE TITLE
Notifications: Provide better text formatting on the lockscreen if possible

### ISSUE THREAD

**Issue by hoverduck** [wordpress-mobile/WordPress-iOS#6570] opened 2017-02-03 19:43 UTC
Here's a mockup of a potential new design for better notification formatting on the lockscreen.  As it is now, post titles and names of blogs can be confusing when included in the text of a notification.

![image](https://cloud.githubusercontent.com/assets/7233112/22605652/cf185158-ea1e-11e6-8977-46e11a33593c.png)

cc: @mattmiklic

**Comment by jleandroperez** [comment] 2017-10-13 17:25
Closing as duplicate of #5893. Lockscreen UI can (and must!) be modified via a System Extension (Widget).

Thanks!

**Closed by jleandroperez** 2017-10-13 17:25 UTC
Labels: good first issue, Notifications, [Pri] Low, [Type] Enhancement
