### ISSUE TITLE
Content: "Link To" shows always the same list of posts and pages

### ISSUE THREAD

**Issue by eduardozulian** [wordpress-mobile/WordPress-iOS#15695] opened 2021-01-22 20:14 UTC
The option to link a text is currently showing the same results over and over when you try to search for a published post or page.

### Expected behavior
To see results related to what I typed. 

### Actual behavior
I see always the same posts and pages. In my case, two posts and one page.

It's apparently impossible to search for published posts or pages.

### Steps to reproduce the behavior
1. Start a post or page
2. Add some text to the body
3. Click the Link icon
4. Choose the Link To option
5. On the search field, type something

##### Tested on iPhone 7, iOS 14.3, WPiOS 16.4 and 16.5

Internal reference: p4a5px-2HH-p2

**Comment by fluiddot** [comment] 2021-04-14 15:35
Looks like this issue is a duplicate of https://github.com/wordpress-mobile/gutenberg-mobile/issues/3047 which is already solved.

I tried to reproduce it but it's no longer happening, I'm getting different results depending on what I search so I'm closing it.

_Tested on iPhone 11, iOS 14.2, WPiOS 17.0 (17.0.0.6)._

**Closed as completed by fluiddot** 2021-04-14 15:35 UTC
Labels: [Pri] Medium, Posting/Editing
