### ISSUE TITLE
Lost draft "Post failed to update"

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-iOS#12829] opened 2019-11-01 16:54 UTC
Reported in a live chat:

> I was working on a post on my phone this morning and then updated and saved it. I just tried accessing it from both my phone and my computer and the post is completely gone. I also checked published, scheduled and trash and it's just MIA. It was already a saved Draft so you would have thought at worst I would have only lost the work I did today. I can see in my activity for today where I uploaded photos while I was writing the post. The photos I uploaded are still in my media folder.

> I just tried restarting my phone and the post briefly popped up saying "Post failed to update" then disappeared.

<sup>(internal reference: 13607596-hc)</sup>

* WPiOS 13.4.1
* iOS 13.1.3
* iPhone 6S
* Type of site: WordPress.com Personal

<sub>/hat tip @sophiegyo for the report, p4a5px-2sz-p2</sub>

**Comment by designsimply** [comment] 2019-11-01 16:59
Noting that a few of us tested and we have been unable to reproduce this problem. Also, some offline support updates including improvements to autosaving and auto-uploading are coming up in 13.6 which should help.

For any future reports of the same problem, it would be helpful to note:

* App version
* iOS version
* Type of site
* Editor used
* Was the draft saved previously or created in the same session where it was lost?
* Was the draft edited from a different computer or device at any point?
* Is their network connection stable or were they having any connectivity issues?

**Comment by illusaen** [comment] 2021-03-31 15:03
Unable to reproduce.

**Comment by illusaen** [comment] 2021-04-01 15:27
Closing this as non reproducible but, please feel free to reopen if it still occurs, thanks!

**Closed by illusaen** 2021-04-01 15:27 UTC
Labels: Posting/Editing, [Type] Bug, [Type] Content Loss
