### ISSUE TITLE
Posts List: Draft post missing after undo from trash

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#4968] opened 2016-03-17 16:35 UTC
To reproduce:
- Open the post list and select the draft filter. 
- Trash a draft post. 
- Click on the undo cell to restore the draft. 
- The app prompts the draft was restored, but its missing until the draft filtered list is refreshed.

**Comment by hoverduck** [comment] 2017-01-25 16:27
Closing; I'm unable to reproduce on v6.8.0.20170112

**Closed by hoverduck** 2017-01-25 16:27 UTC
Labels: Posts List, [Type] Bug
