### ISSUE TITLE
Share options missing for drafts

### ISSUE THREAD

**Issue by startuptester** [wordpress-mobile/WordPress-iOS#17288] opened 2021-10-08 20:17 UTC
### Expected behavior
I am pretty sure this used to exist in iOS but went as far back as 17.7 and it's not there. 
In Android, I can share from a draft. 

| <img src="https://user-images.githubusercontent.com/66104034/136619727-efb4d356-030e-4712-a22b-9530a505970a.png" alt="" width="300"> | <img src="https://user-images.githubusercontent.com/66104034/136619687-8dc987fe-c09c-45f3-ac27-d2d8c39a748c.png" alt="" width="300"> |
| - | - |

### Actual behavior
In iOS, either in the "more" menu from the card or the preview, I have no share options. 
| <img src="https://user-images.githubusercontent.com/66104034/136619800-11dd8bf9-747d-4757-9a08-70a41ecd6ab6.png" alt="" width="300"> | <img src="https://user-images.githubusercontent.com/66104034/136619775-18ebc659-6acc-45d7-ac45-465fc23633ce.png" alt="" width="300"> |
| - | - |

### Steps to reproduce the behavior
1. Create a draft post and view the "Drafts" tab on the Posts List 
2. Open the "More" options from the Posts List, note no share options 
3. View the post preview, note no share options. 
4. Publish the post and notice the same menus in the "Published" list have share options.

**Comment by guarani** [comment] 2021-10-21 13:50
Unfortunately I didn't make it very far on this. In testing, the Share button did show up once for one draft post, but I couldn't determine what caused it to appear. As soon as I opened and closed the draft in the editor, the share button no longer appeared. The code that handles displaying the share button is [here](https://github.com/wordpress-mobile/WordPress-iOS/issues/17288), so this will need further digging to understand under what circumstances this is shown.

I'll leave my assignment here because I still hope to find the issue soon.

**Comment by guarani** [comment] 2021-11-23 22:15
I'm un-assigning myself because I didn't find the time to continue the investigation.
cc @startuptester

**Comment by kean** [comment] 2024-12-20 10:24
It works as designed, so I'm going to close it for now.

**Closed as completed by kean** 2024-12-20 10:24 UTC
Labels: Sharing, [Status] Needs Testing
