### ISSUE TITLE
Plugins: Include separate links to WordPress.org plugin page and plugin homepage

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#8374] opened 2017-12-21 16:54 UTC
### Expected behavior

When I view a plugin's details in the app, I expect to see two separate links to the WordPress.org plugin page and the plugin homepage.

### Actual behavior

I only see a link to the Plugin homepage, and this is inconsistent (sometimes taking me to the WordPress.org plugin page and other times taking me to the plugin homepage).

### Steps to reproduce the behavior

1. Install the [Hello Dolly](https://wordpress.org/plugins/hello-dolly/) plugin on a Jetpack site.
2. Under My Sites > Plugins, select the Hello Dolly plugin.
3. Select "Plugin homepage" and note that you are taken to the WordPress.org plugin page here: https://wordpress.org/plugins/hello-dolly/
4. Go back to the Plugins list and select the Jetpack plugin.
5. Select "Plugin homepage" and note that you are taken to the Jetpack homepage at https://jetpack.com/. There is no link to the WordPress.org plugin page: https://wordpress.org/plugins/jetpack/

##### Tested on iPhone 6, iOS 11.2, WPiOS 9.1.0.20171220

**Comment by koke** [comment] 2017-12-22 08:02
> this is inconsistent (sometimes taking me to the WordPress.org plugin page and other times taking me to the plugin homepage)

Hello Dolly is working as expected, it's homepage [is set](http://plugins.svn.wordpress.org/hello-dolly/trunk/hello.php) to https://wordpress.org/plugins/hello-dolly/, so we don't show the WordPress.org link because it would be the same.

Jetpack should be showing both though, I'm investigating that

**Comment by koke** [comment] 2017-12-22 08:06
Ah, I [disabled directory links](https://github.com/wordpress-mobile/WordPress-iOS/blob/ff920904dc8d6aafddac3ace060c8613cbdaa1a1/WordPressKit/WordPressKit/PluginState.swift#L66) until we implement checking if a plugin is in the WordPress.org directory (we don't want to show a link to a plugin that doesn't exist).

@jklausa will likely take care of this as part of plugin browsing.

**Comment by elibud** [comment] 2017-12-22 12:13
So we are showing whatever link the author listed as the plugin homepage for now, is that correct?

**Comment by koke** [comment] 2017-12-22 12:14
Yes, that's the only thing we're displaying for now

**Comment by designsimply** [comment] 2017-12-22 22:36
Tested and confirmed with iPhone 6S, iOS 11.2.1, WPiOS 9.1.

**Comment by designsimply** [comment] 2019-03-12 23:22
Re-opening because I re-tested the steps provided using WP Internal 12.0.0.20190311 on iPhone 6S iOS 12.1.4 and found that clicking on "Plugin Homepage" for Jetpack led to https://jetpack.com/ and not https://wordpress.org/plugins/jetpack/ as expected.

@jklausa would this be a quick fix?

**Comment by jklausa** [comment] 2019-03-13 16:07
I think this should be _relatively_ quick fix, but I'm not sure — I remember there being something weird about how we extract links from the WP.Org plugin catalogue, since there's barely any API for that and I think we had to do some weird HTML scrapping thing — so it's probably a couple hour of spelunking. 

I'm currently swamped with wrapping up Stats work, but I'd be happy to take a peek after I'm done.

**Comment by jklausa** [comment] 2019-04-02 03:40
I took another look at this today and I _think_ I might have misunderstood this ticket earlier.

Right now there are two separate links visible — one labeled "WordPress.org Plugin Page" that leads to `https://wordpress.org/plugins/jetpack/` and another one called "Plugin Homepage" that links to `jetpack.com`.

I *think* that's the correct behavior here? At least it feels like that????

@designsimply I'm unclear if I there's actually anything to be done here — I think the current behavior makes sense, but I'm open to changes!

![Simulator Screen Shot - iPhone Xs Max - 2019-04-02 at 05 37 28](https://user-images.githubusercontent.com/1594081/55374621-6b03f980-5509-11e9-95af-facf7d8df142.png)

**Comment by designsimply** [comment] 2019-04-09 20:36
No no, I think you are right I am the one who made a mistake when I tested! I mislead you! 🤦‍♀️

I re-tested and I see just one option showing for Hello Dolly (and as explained above this is the expected behavior) and I see both the plugin page and plugin homepage options working properly for the Jetpack plugin now:

<img src="https://user-images.githubusercontent.com/1119271/55833387-a20f7780-5ad4-11e9-9d72-d9599542f091.PNG" width="270" alt="IMG_2459"> &nbsp; <img src="https://user-images.githubusercontent.com/1119271/55833414-b18ec080-5ad4-11e9-9477-87d24611dc94.PNG" width="270" alt="IMG_2460">
<p style="clear:both;"><sub>Tested with WP Internal 12.1.0.20190408 on iPhone 6S iOS 12.2</sub></p>

**Comment by jklausa** [comment] 2019-04-10 13:00
Alrighty then, I think I'm gonna close this one then :)

**Closed by jklausa** 2019-04-10 13:00 UTC
Labels: Jetpack Plugins, [Type] Bug

**Comment by designsimply** [comment] 2019-04-11 18:32
Thank you for catching my mistake!
