### ISSUE TITLE
Stats: Percent sign should be localized in stats screen

### ISSUE THREAD

**Issue by irfano** [wordpress-mobile/WordPress-iOS#18536] opened 2022-05-07 11:35 UTC
### Expected behavior
Shortly, the percent sign should be localized according to the current language's rules.

The percentage symbol `%` should be at the start of the number (%100) in some languages (Turkish, Arabic), and the end of the number (100%) in some languages (English, French...). There are also rules for spacing between the sign and the number that can be checked over: https://en.wikipedia.org/wiki/Percent_sign#Form_and_spacing

WordPress.com stats screen in Turkish:
![Screen Shot 2022-05-07 at 13 28 05](https://user-images.githubusercontent.com/2471769/167250487-d5fd243c-d352-4136-b08b-c5dceda0d444.png)

### Actual behavior
The percent sign is the end of the number in Turkish. I could find it only in days-weeks-months-years tabs of stats screens, but please check other screens where the sign could be used.
<img src="https://user-images.githubusercontent.com/2471769/167252172-28488646-e8b4-4fa9-b6d4-64fc931172c0.PNG" height=640>

### Steps to reproduce the behavior
1. Change your device language to Turkish from OS settings > General > Language & Region > iPad Language > Türkçe(Turkish)
2. Open WordPress app.
3. Go to stats either using quick links or menu.
4. Switch to DAYS ("GÜNLER" in Turkish) tab.
5. Check the percent sign and notice it's the end of the number instead of the start.

##### Tested on iPad mini, iOS 15.4, WPiOS 19.6 (19.6.0.6)

**Comment by guarani** [comment] 2022-05-27 23:31
Thanks for reporting this, @irfano! 

> The percent sign is the end of the number in Turkish. I could find it only in days-weeks-months-years tabs of stats screens, but please check other screens where the sign could be used.

It looks like we would need to do an audit here. On iOS, `NumberFormatter` should be able to handle the locale-specific differences between countries (e.g. the % symbol before the value in Turkish). I had a quick look at the code and it seems like it might not be used consistently. 

I'm going to assign this low priority due to a low severity and low impact. This is based on my assumption that in most user locales, the current 0% (no space between value and symbol, and symbol following value) looks acceptable.

**Comment by guarani** [comment] 2024-03-18 10:00
~~Noting that this is still reproducible, even though the specific case highlighted in the screenshots no longer exists because the new Traffic tab doesn't show comparison labels.~~ Update: The Traffic tab was disabled, so this issue is reproducible again.

The scope of this issue is still to audit stats screens to see if % is handled in a locale-specific way and to fix any instances where it's not.

**Closed as completed** 2024-04-03 07:53 UTC
Labels: [Pri] Low, Stats, i18n
