### ISSUE TITLE
Reader: Some YouTube videos can't play (only in app)

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#10693] opened 2018-12-19 12:47 UTC
### Expected behavior

I expect that if I can play an embedded YouTube video in the browser, I should be able to play it in the app Reader.

### Actual behavior

Some YouTube videos can be played in the app Reader. However, others behave as described:

> This post's embedded Youtube video works on the site in a browser, on both desktop and mobile, it works in the Reader when accessed from a browser, but not in the Reader within the iOS app.

This is a video that won't play in the app Reader: https://www.youtube.com/watch?v=wF6e0or4Xmc

### Steps to reproduce the behavior

1. Embed the problem video in a post.
2. Open that post in the browser Reader and play the video.
3. Open the same post in the app Reader and try to play the video.

Result: It shows the message "Video unavailable."

##### Tested on iPhone XS, iOS 12.1, WPiOS 11.4 internal

Internal ref: p4a5px-2jL-p2

**Comment by donalirl** [comment] 2019-11-10 04:35
Another case of this, seen at #2481671-zen. I thought it might be related to the block editor, but I re-saved the post in the classic editor and the video was still unavailable.

Seen also in my WordPress Android app.

**Comment by designsimply** [comment] 2020-04-29 00:17
Tested and confirmed using WPiOS 14.7.0.2 TestFlight beta that the embedded YouTube video https://www.youtube.com/watch?v=wF6e0or4Xmc cannot be played in the Reader. Note: tested with the `core-embed/youtube` block, post created with Calypso Gutenberg. The video plays fine in a web browser on the same device though.

WPiOS Reader | Safari
---|---
<img src="https://user-images.githubusercontent.com/1119271/80550135-5e580c00-897c-11ea-9510-be43405405f4.PNG" width="200" alt="IMG_3944">|<img src="https://user-images.githubusercontent.com/1119271/80550117-41233d80-897c-11ea-8025-94379244b9b2.PNG" width="200" alt="IMG_3946">

<p style="clear:both;"><sup>Tested with WPiOS 14.7.0.2 TestFlight beta on iPhone 11 iOS 13.4.1.</sup></p>

Note: I noticed the dimensions of that video on YouTube.com aren't the same compared to most other videos—this one looks… more square, less rectangular.

**Comment by designsimply** [comment] 2020-04-29 00:26
Aside: the video embed has a poster image and looks nice when you first open the full post in the Reader, but the card in the main Reader stream doesn't have a video preview images while Android does:

Android app | iOS app
---|---
 <img src="https://user-images.githubusercontent.com/1119271/80550481-7b410f00-897d-11ea-9aa3-41557ec68857.png" width="200" alt="Screenshot_20200428-142302">|<img src="https://user-images.githubusercontent.com/1119271/80550485-7e3bff80-897d-11ea-93b4-d6de666d1c0b.PNG" width="200" alt="IMG_3947">

<p style="clear:both;"><sup>Tested with WPAndroid 14.7-rc-2 on Pixel 3 Android 10 and WPiOS 14.7.0.2 TestFlight beta on iPhone 11 iOS 13.4.1.</sup></p>

@yaelirub should the issue with the card be filed as a separate issue?

**Comment by yaelirub** [comment] 2020-04-29 17:54
> should the issue with the card be filed as a separate issue?

Yes, @designsimply and thanks for checking 🙏

**Comment by leandroalonso** [comment] 2020-07-02 19:37
@malinajirka and I have tested this in both Android and iOS.

Some specific videos don't play in the apps — we're not sure if this is some different permission or any other thing. But there isn't much we can do about that (since a Youtube video is just an `iframe`)

Anyway, most of the videos play without any issues.

I'll close this one for now, if we start seeing that as a recurrent thing we can investigate it further.

**Closed by leandroalonso** 2020-07-02 19:37 UTC
Labels: Mobile Request, Reader, [Type] Bug
