### ISSUE TITLE
Reader: Rapidly unfollow multiple blogs glitches the UI.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#4019] opened 2015-07-14 20:34 UTC
In the Topics > Followed Sites list, if you edit and start unfollowing blogs quickly you can see a previously unfollowed site reappear momentarily then disappear.  
Props @designsimply

**Comment by rachelmcr** [comment] 2015-12-07 16:24
I also encountered this issue last week while unfollowing blogs in the latest 5.8 beta.

**Comment by hoverduck** [comment] 2017-01-24 16:39
Unable to reproduce with the current UI.  Closing.

**Closed by hoverduck** 2017-01-24 16:39 UTC
Labels: Reader, [Type] Bug
