### ISSUE TITLE
Editor: em tags are only applied to some language text

### ISSUE THREAD

**Issue by naokomc** [wordpress-mobile/WordPress-iOS#10367] opened 2018-10-30 06:40 UTC
Italics only work for some languages on the visual editor. [This Stackoverflow answer](https://href.li/?https://stackoverflow.com/a/21034160) suggests using “[affine transformation](https://href.li/?https://en.wikipedia.org/wiki/Affine_transformation)”.

### Steps to reproduce
1. Copy & paste the text below into the visual editor (English, Japanese, Taiwanese Chinese, Korean, Thai, Vietnamese, and Khmer).

```
Website
サイト
網站
웹사이트
เวบไซต์
Trang web
វេបសាយ
```

2. Select all the text.
3. Tap the italicize icon.
4. Switch to HTML editor to view the code.

### Expected behavior

`<em>` and `</em>` are added to the beginning and end of the text.

The result is the same is you enter the `<em>` tags using the HTML mode and save the post, then re-open it. `<em>` tags added using desktop browser are also lost if you open the post using the app.

Other languages with the same issue (that I know of): Arabic, Farsi, Hindi, Marathi, Uighur, and Urdu. 

### Actual behavior

`<em>` tags are only applied to the English and Vietnamese text, and spaces in between other language text.

![em-test](https://user-images.githubusercontent.com/34067/47700539-2b836980-dc5a-11e8-9f00-0ba38ff6a85a.jpeg)

##### Tested on iPhone 8 (OS language set to Japanese), iOS 12.0.1, WPiOS 11.0

**Comment by guarani** [comment] 2021-03-31 02:10
Thanks for the report, I can reproduce this in the classic editor. 

The block editor is the default editor now in the apps and this issue does not appear to be present there (i.e. `<em>` and `</em>` tags are added to the beginning and end of the text – as expected).

The classic editor [is deprecated](https://github.com/wordpress-mobile/gutenberg-mobile/issues/3209) and I don't think it will be receiving updates for regular bug-fixes or improvements.

I'm closing this now since I don't think it will be worked on, but if you think this should remain open please leave a comment below.
cc @mchowning

**Closed** 2021-03-31 02:10 UTC
Labels: Posting/Editing, [Type] Bug, i18n
