### ISSUE TITLE
Status Bar while searching Themes

### ISSUE THREAD

**Issue by startuptester** [wordpress-mobile/WordPress-iOS#15714] opened 2021-01-26 19:41 UTC
### Expected behavior
The status bar should not turn white with a white search bar

### Actual behavior
https://cloudup.com/c5IWwVEE5Ah

### Steps to reproduce the behavior
1. Tap Themes on the My Site screen
2. Enter the search bar

**Comment by yaelirub** [comment] 2021-02-16 23:32
Hey @Gio2018 , will this be fixed as part of the white headers project? can you please make sure this is fixed?

**Comment by Gio2018** [comment] 2021-02-17 21:37
> Hey @Gio2018 , will this be fixed as part of the white headers project? can you please make sure this is fixed?

Sure!!

**Comment by Gio2018** [comment] 2021-02-17 22:03
Hey @mattmiklic ,pinging you since I understood this came up in the focused site creation, and just to make sure I understand correctly: what would be the exact expected behavior here? 

When we will activate the white headers, if we don't change anything else, the behavior will reflect what is already happening in dark mode, which is: 

the nav bar would still shift up, but be the same color of the background. Is this acceptable or do we want a different behavior for that nav bar?

Thank you!!

**Comment by mattmiklic** [comment] 2021-02-17 22:50
> the nav bar would still shift up, but be the same color of the background. Is this acceptable or do we want a different behavior for that nav bar?

@Gio2018 I think that's just right. It already looks fine in Dark Mode (other than the issue where the search box is no longer vertically centered on its background when it's active). The issue in light mode is that the header background is switching from blue to white but the status bar text is white on white.

**Comment by Gio2018** [comment] 2021-02-17 22:53
Thanks for clarifying @mattmiklic !

**Comment by frosty** [comment] 2021-03-12 19:38
This issue will be fixed by #15714, once large titles / white headers is shipped.

**Closed as completed** 2021-08-20 00:33 UTC
Labels: Themes
