### ISSUE TITLE
Reader: Jetpack Slideshow Block has no fallback in iOS Reader

### ISSUE THREAD

**Issue by rezzap** [wordpress-mobile/WordPress-iOS#14545] opened 2020-07-30 11:52 UTC
### Expected behavior

If the block isn't supported in the Reader, it should display some fallback content instead of showing blank.

### Actual behavior

When the Jetpack Slideshow Block is used, only the bullet points display and the images don't load at all.

On Android, the images show in a list, which is what I would have expected to see on iOS also. Instead it shows nothing at all. 

<img src="https://p-xBFZpQ2k.t2.n0.cdn.getcloudapp.com/items/v1u2Kxo5/Image%20from%20iOS%20(3).png?v=152b4e0538fb15ef21bfd95ae118baba" width="300" alt="">

On Android:

<img src="https://p-xBFZpQ2k.t2.n0.cdn.getcloudapp.com/items/Blu5L1jK/Screenshot_20200730-111630_WordPress.jpg?v=3221914fb30f12b10989c413576cd9fe" width="300" alt="">

### Steps to reproduce the behavior

1. Create a new post on a WordPress.com or Jetpack site that includes the Jetpack Slideshow Block 
2. View the post in the reader on the iOS app. 
3. Compare this to what is seen on the web Reader and the Android Reader.
4. See the issue.

For internal reference, the post that this was noticed on is p7DVsv-92t-p2.

**Comment by leandroalonso** [comment] 2020-07-30 20:15
@rezzap I just tested here and I'm able to see the images just like in Android:

<img src="https://user-images.githubusercontent.com/7040243/88970087-2c5e8a80-d288-11ea-816d-7eb48d230739.png" width="300">

You're able to see other images in this article?

**Comment by rezzap** [comment] 2020-07-31 19:25
@leandroalonso I just realized that actually I have not been seeing any images in posts under the 'Automattic' filter in the Reader for a while. I can click on images normally to see the full-size image and it shows as an overlay, which is why I haven't really been bothered by this. But with the slideshow, I'm unable to click through.

I have tried switching from data to WiFi, connection through proxy or without and all images from the 'Automattic' section of the Reader are not showing images in post content on my iOS app. 

I have even tried re-installing the app and clearing media data, no change. 

Images do seem to load correctly in the Following and Discover section. I also just tried with a test with the Jetpack slideshow and it's working. Most likely something under the filter that is blocking this. The same happens on my iPad with version 15.2. Maybe it's my network if it's not being replicated.

**Comment by rossanafmenezes** [comment] 2020-07-31 19:36
Just to add to @rezzap 's comment, I am having the same issue on my iPad. Can't see images on posts from Automattic in the reader. I see the images on the list of posts, but once I click on one specific post (that shows an image on the list) I can't see it and I tested on my Android, the images work well.

**Comment by leandroalonso** [comment] 2020-08-03 12:46
@rezzap @rossanafmenezes that's what I thought.

If you log out and then log in the images appear?

We've been experiencing this issue for some time in iOS: https://github.com/wordpress-mobile/WordPress-iOS/pull/14360

It affects both the Preview and the Reader (for private sites). I guess we'll have to look at those again.

@diegoreymendez sorry to ping you here, but I know you've worked on the private Atomic feature. Do you have any idea what Android might be doing that is different than iOS? They don't seem to have this issue. And AFAIK the problem relies on the service we've been using to retrieve the cookie (also pinging @etoledom who worked on a fix for this quite recently).

**Comment by diegoreymendez** [comment] 2020-08-03 14:45
@leandroalonso - I was just testing this in my device and weirdly enough, it seems to work just fine for me.  I'm going into the "Automattic" team filter in the reader and then going into a post with an image from the list, and both in the list and details view I can see the image just fine.

But if it's not working in some scenarios for some users, we need to figure out what's causing the different experience.

My best bet is I'm doing something different when testing.  In order to address this, can I ask you @rezzap and @rossanafmenezes to:

1. Record your screen all the way into this issue, and send me a link to the recording.
2. Let me know of a post that triggers this, so that I can go specifically into it.

Please keep in mind that since we're using the Automattic filter, you may prefer to send me the above info via private DM.

Thanks!

**Comment by leandroalonso** [comment] 2020-08-03 17:50
@rezzap @diegoreymendez I managed to reproduce the issue and found the problem.

I'll close this issue and open a new one with the correct steps to reproduce. Thank you all for the inputs!

**Comment by leandroalonso** [comment] 2020-08-03 19:21
Closing in favor of https://github.com/wordpress-mobile/WordPress-iOS/issues/14564

**Closed by leandroalonso** 2020-08-03 19:21 UTC
Labels: Reader, [Pri] Medium, [Type] Bug
