### ISSUE TITLE
Killing the app while creating a post does weird things

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/WordPress-iOS#3737] opened 2015-05-28 10:32 UTC
Video at: https://cloudup.com/iOZ-BQXHqyx

When you relaunch the app, there's an _empty_ post

![emptypost](https://cloud.githubusercontent.com/assets/8739/7857941/c9fb7e46-0534-11e5-8088-0854bb7a5a2c.png)

If you try to trash it, it will fail, because it was never published

![notfound](https://cloud.githubusercontent.com/assets/8739/7857998/23bb87e6-0535-11e5-9662-9ac431ef2f4f.png)

If you open it, it says there are unsaved changes

![unsavedchanges](https://cloud.githubusercontent.com/assets/8739/7858010/3dd11718-0535-11e5-9036-ee2ea74b96e7.png)

If you discard them, you still have an empty post with unsaved changes

![stillunsaved](https://cloud.githubusercontent.com/assets/8739/7858023/57ee1862-0535-11e5-8f8f-fc2771667794.png)

The only way to delete that post is to actually publish it (or save as a draft), and then delete it.

Also found this

![publishdate](https://cloud.githubusercontent.com/assets/8739/7858044/84c4340c-0535-11e5-9879-e24f45bc1c9a.png)

Not sure if this is the new post list changes, the new editor, or a little bit of both, so cc @aerych @bummytime @diegoreymendez

**Comment by koke** [comment] 2015-05-28 10:44
@aerych A couple UI details for you (in super slow-mo :stuck_out_tongue:), which aren't a big deal and might not be worth fixing, but I noticed them

In the post list, the bottom banner animates but new cells don't

![postlist](https://cloud.githubusercontent.com/assets/8739/7858250/1355f98e-0537-11e5-8e25-eb6abc72d9d2.gif)

When you create a post, the empty post is briefly visible on the list, and it's after the oldest one

![editoropens](https://cloud.githubusercontent.com/assets/8739/7858268/30dcbb3c-0537-11e5-830d-a766caf122f4.gif)

**Comment by aerych** [comment] 2015-05-28 16:16
> Not sure if this is the new post list changes, the new editor, or a little bit of both,

I don't think that would be due to changes in either feature. 

> A couple UI details for you [...]

I'll add these to #3673

**Comment by diegoreymendez** [comment] 2015-05-28 17:02
The problem of properly restoring the GUI-state for posts is very closely related to how we handle the post's publication-state locally.

This is a good starting point to try and find the issue: https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/WordPress/Classes/ViewRelated/Post/WPPostViewController.m#L203

**Comment by aerych** [comment] 2015-06-02 23:51
We'll handle the empty post, and publish issues in #3786.  Leaving just the wonky date picker layout.

**Comment by diegoreymendez** [comment] 2015-06-03 01:35
@aerych - This bug is caused by state restoration being currently broken.  With state restoration the app would open up in the post being edited.

I think this may have broken with the WPTabBarController changes.  See my  comments in [this PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/3742).

**Comment by diegoreymendez** [comment] 2015-06-03 01:37
By the way... state restoration is also broken for the posts list (which is not restored anymore, even though the code is there).  The problem with state restoration is that if a parent VC doesn't restore anymore, the child VCs won't either.

**Comment by diegoreymendez** [comment] 2015-06-03 14:47
Removed my last 2 comments since they weren't accurate.

**Comment by diegoreymendez** [comment] 2015-06-03 16:16
From [Apple's documentation](https://developer.apple.com/library/ios/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/StrategiesforImplementingYourApp/StrategiesforImplementingYourApp.html#//apple_ref/doc/uid/TP40007072-CH5-SW2):

```
If you want to test your app’s ability to restore its state, you should not use the multitasking bar to kill the app during debugging. Instead, use Xcode to kill the app or kill the app programmatically by installing a temporary command or gesture to call exit on demand.
```

When following these guidelines for testing [this is the behavior I'm getting in the App](https://cloudup.com/cF770FqHhY9).

We should still fix this though, in the case that state information is reset for any reason.

**Comment by kwonye** [comment] 2016-09-29 15:44
Also related: long video uploads. This is a hard problem to solve. From what I last know, Apple's watchdog (guard prevent apps from using too much battery in the background) only gives a 10 minute window max to allow for background processes to finish. 24 minutes of video, depending on the quality, can easily exceed that. Google Photos solves this by showing a pop up saying "Please stay on this app for optimal uploading of photos".

Same possible situation since we'll get killed mid-way during a post if the user backgrounds.

**Comment by rachelmcr** [comment] 2019-01-18 14:45
We've resolved the main issue reported here (killing the app while creating a post now saves a local draft) and long media uploads are improved with async uploads. Closing as resolved.

**Closed by rachelmcr** 2019-01-18 14:45 UTC
Labels: Posts List, [Pri] Medium, [Type] Bug, [Type] Content Loss
