### ISSUE TITLE
App freezes when trying to add tags

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-iOS#13522] opened 2020-02-20 19:28 UTC
From a 3-star review "tags bagg" — Version 14.0 — Feb 4, 2020

> The tagging option is bagging.  The application freezes.

Noting this App Review so we can investigate it. 🧐

**Comment by designsimply** [comment] 2020-05-16 01:31
3-star review by  – Feb 9, 2020

> Se traba cuando pongo etiquetas.
> No puedo ponerle etiquetas, cuando abro esa parte se traba y tengo que cerrar la aplicación para que vuelva a funcionar.

> It locks up when I put labels.
> I can't put labels on it, when I open that part it gets stuck and I have to close the application to make it work again.

<sup>Version 14.0. Mexico. Translated with http://translate.google.com/.</sup>

Note: this could be related to a more general crash.

**Comment by dcalhoun** [comment] 2021-03-30 18:16
I was unable to reproduce this issue on iPhone SE, iOS 14.4.2, WPiOS 16.9 (16.9.0.13). I tested tags with various diacritics and non-alphanumeric characters. I also tested adding a large quantity of tags (~1,000) all at once.

**Comment by dcalhoun** [comment] 2021-04-01 14:27
Closing this as non reproducible but, please feel free to reopen if it still occurs, thanks!

**Closed by dcalhoun** 2021-04-01 14:27 UTC
Labels: App Review Request, Posting/Editing, [Type] Bug
