### ISSUE TITLE
My Sites: Add Site button missing when there is one or zero blogs in the list. 

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#4667] opened 2016-01-12 17:59 UTC
Title has it.  
Looks like we're setting the right navbar button to nil under these circumstances.  This was fine when the right bar button was just used for search but we have the add button there now as well. 

Blocker for 5.9

**Comment by kwonye** [comment] 2016-01-12 18:49
Closing as duplicate of #4647

**Closed by kwonye** 2016-01-12 18:49 UTC
Labels: General, [Type] Bug

**Comment by aerych** [comment] 2016-01-12 19:37
@koke is just too fast :D
