### ISSUE TITLE
Close commenting shows "on" from the menu but "off" from the detailed view.

### ISSUE THREAD

**Issue by southp** [wordpress-mobile/WordPress-iOS#9812] opened 2018-07-20 03:45 UTC
### Expected behavior
The detailed view and the outer menu should be consistent.

### Actual behavior
On my device, this is what I'm seeing from the outer menu:

<img src="https://user-images.githubusercontent.com/1842898/42982035-ecc8da88-8c11-11e8-9e78-19158fb6c6c8.png" width="200" />

When clicking through it, it shows:

<img src="https://user-images.githubusercontent.com/1842898/42982057-154fb06c-8c12-11e8-8dc9-a597f9c620bd.png" width="200" />

### Steps to reproduce the behavior
Click through settings -> discussion -> under "Comments session, find "Close commenting"

**Comment by rachelmcr** [comment] 2020-01-16 15:54
I just ran across this issue again and confirmed that the original string used when the Close Commenting setting is disabled is "Off" but it is translated as "開" in [ZH-TW](https://translate.wordpress.org/projects/apps/ios/dev/zh-tw/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=55227&filters%5Btranslation_id%5D=2416042 ) and [ZH-HK](https://translate.wordpress.org/projects/apps/ios/dev/zh-hk/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=55227&filters%5Btranslation_id%5D=49947739) locales.

I'm going to close this issue as the problem is related to the translated string rather than a bug in the app. Could you contribute a more accurate translation for this string? We will then pull in the updated translation in a later release.

**Closed by rachelmcr** 2020-01-16 15:54 UTC
Labels: Localization, Project Glot, [Type] Bug, i18n
