### ISSUE TITLE
Cannot reply when open comment from notification

### ISSUE THREAD

**Issue by phamdacloc** [wordpress-mobile/WordPress-iOS#4533] opened 2015-12-01 03:59 UTC
When someone reply to a post or to a comment and push notification is received on the phone, the user can view the comment to like, approve, spam it, or trash it.  The user can also click on the notification header block to view all post's comments, but comment reply is disabled. I doubt disabling reply on this view is by design. 

The culprit here is that `refreshReplyTextView:` in `ReaderCommentsViewController.m` is checking on stale data `self.canComment`

**Comment by jleandroperez** [comment] 2015-12-01 12:16
Closing as dupe of #4312 (Fixed in 5.7.1)

Thanks for reporting this @phamdacloc!!

**Closed by jleandroperez** 2015-12-01 12:16 UTC
