### ISSUE TITLE
Search Button for Themes Should Be on Top Right Portion of Navigation Bar

### ISSUE THREAD

**Issue by sendhil** [wordpress-mobile/WordPress-iOS#5539] opened 2016-06-09 00:20 UTC
Right now on Themes the search button is embedded in the web content. We should probably change this to a button on the right side of the navigation bar to more closely match native patterns(we see an example of this on the My Sites page). The motivation behind this is that when we tap on search on the web portion of themes and it jumps to the native search box at the top it feels like there's a little bit of a disconnect as compared to other parts of the app.

Here's some videos of what I'm talking about. This is what the theme search looks like now:
https://cloudup.com/cm4XfaZKAuH

Here's what it looks like on my sites:
https://cloudup.com/cgvoW-s6GjY

Here's what I think would be ideal on Themes Search:
<img width="655" alt="screen shot 2016-06-08 at 5 16 39 pm" src="https://cloud.githubusercontent.com/assets/437043/15915272/cd9403e8-2d9c-11e6-9812-35c8706ba9b5.png">

**Comment by sendhil** [comment] 2016-06-09 00:20
Since this is quasi design related, @mattmiklic thoughts on this change?

**Comment by mattmiklic** [comment] 2016-06-15 23:26
> Since this is quasi design related, @mattmiklic thoughts on this change?

Agreed 💯 -- in iOS, I'd look for the search either at the top of the content view (like in Mail) or an icon in the toolbar. A toolbar icon seems like the best solution here.

**Comment by kurzee** [comment] 2016-06-20 22:06
Oops, looks like I created a duplicate in https://github.com/wordpress-mobile/WordPress-iOS/issues/5583

**Comment by kurzee** [comment] 2016-06-20 22:11
I just pushed a branch with the fix for this as the theme icon in the navigation bar top-right.

https://github.com/wordpress-mobile/WordPress-iOS/tree/issue/5583-replace-themes-searchbar

@mattmiklic can you take that branch for a spin to make sure the icon/design is as expected?

**Comment by kwonye** [comment] 2016-06-20 22:14
This initial design was due to there being a dropdown next to it that searched free/premium/all themes. I do want to make sure @folletto knows about this as this was his design.

Also, if this is what we want to do, we should do the same for Android.

**Comment by kurzee** [comment] 2016-06-20 22:19
The fix I pushed above removes the bottom bar completely to look as so:

![simulator screen shot jun 20 2016 5 15 09 pm](https://cloud.githubusercontent.com/assets/1873422/16212038/d0b6016c-370a-11e6-8a37-962feca3d0a6.png)

If we re-enable the ability to make purchases (which is currently hardcoded to disabled) the drop-down is shown as:

![simulator screen shot jun 20 2016 5 15 52 pm](https://cloud.githubusercontent.com/assets/1873422/16212059/f5e5c1ac-370a-11e6-99e8-dc8f7a354758.png)

If we do end up enabling this drop down, it would probably better be served a native segmented control.

**Comment by folletto** [comment] 2016-06-20 22:24
Thanks for the ping. I'm not against these design changes, but please be aware that the choices that were done here were to be consistent across Web / iOS / Android, finding a balance between the different patterns and cases.

So, if we want to change it, my quick answer is that we should do first some design work across all the three to make sure we're not causing any dissociation or regression. My guess is that it's probably doable without too much trouble, but I feel uncomfortable in pushing asymmetrically such a change without checking. Check specifically the design done for M4-M7 milestones on Hyperion's P2.

**Comment by kurzee** [comment] 2016-06-20 22:32
@kwonye can you shed insight on the availability of showing free/premium/all themes? Currently this is hardcoded to disabled on iOS, so the dropdown is never shown, in which case there is no need for a space for the dropdown as currently seen.

**Comment by apeatling** [comment] 2016-06-20 22:38
@folletto I think in terms of how this work, it's going to be exactly the same, just having the initial search icon in a more native position. Using in the apps right now feels very strange and disconnected from tapping the search box to seeing a native one appear in the header.

**Comment by folletto** [comment] 2016-06-20 22:45
@apeatling I agree. As said above, I'm not denying that in any way. iOS has both the "top search in the corner" pattern, as well as the "search at the top of the list" (usually hidden below an initial scroll), and when we did this design we decided to opt for the decision above, which also includes filters and matches perfectly Calypso patterns. 

I'm just saying that it needs to be cross checked (it's 23:43 here now, otherwise I would have done it myself to help).
 
It's likely to be ok, but **we really must avoid to do these changes unilaterally.**

**Comment by folletto** [comment] 2016-06-20 22:56
For reference, the pattern that component followed when it was designed is this native iOS one:

![screen shot 2016-06-20 at 23 52 14](https://cloud.githubusercontent.com/assets/4389/16212790/175ee598-3742-11e6-9b88-5b03e9c46518.png)

Which matches Calypso design patterns more closely than the lens in the top-right corner, thus that's why it was preferred. If there's a design disconnection between different screens on iOS specifically, I'd probably err to remove the icon in the top-right corner elsewhere too, not the other way around — even if, the problem here is really consistency, so either way, the important bit is that it's consistent both inside the iOS standards as well as in the Calypso ones. I'd be ok with either.

**Comment by kurzee** [comment] 2016-06-20 23:00
@folletto that's probably the best direction in general. I found the same thing on a separate issue today in https://github.com/wordpress-mobile/WordPress-iOS/issues/4343#issuecomment-227255572.

Ultimately, the app should probably move towards search bars within the header of table views, rather than within the navigation bar itself. This would be a much larger change across the Post/Pages list, Blog list ,Themes and maybe the Reader if we're keeping absolute consistency.

**Comment by mattmiklic** [comment] 2016-06-20 23:13
> Ultimately, the app should probably move towards search bars within the header of table views, rather than within the navigation bar itself. This would be a much larger change across the Post/Pages list, Blog list ,Themes and maybe the Reader if we're keeping absolute consistency.

Agreed on both points; this is the more native iOS UI to search and it would be a much bigger change. I was OK with switching to a search icon in the navigation bar as a more-native-than-the-status-quo change, but don't have any beef with doing this instead. It'll just require taking a look at each section to make sure it looks and works as intended, and makes sense with anything else that might appear at the top of the view like a segmented control.

**Comment by kurzee** [comment] 2016-06-20 23:16
Awesome, I think a larger to-do can be opened for the header search bars. However, in the mean time, we still have a blank space for the currently unused/unseen dropdown.

The above fix could be a nice holdover for the blank space and inconsistent search icon placement, until the larger change (which would still have the blank dropdown space) is ready and shipped.

**Comment by kurzee** [comment] 2016-06-20 23:18
CC @aerych for the reader search https://github.com/wordpress-mobile/WordPress-iOS/issues/5539#issuecomment-227295235

**Comment by aerych** [comment] 2016-06-21 00:03
Thanks for the ping @kurzee. I we might be dodging the issue for the reader. Once the new menu is in the lens icon in the upper right of the reader list will go away and the search controller will be presented from the menu instead.

**Closed** 2016-06-22 20:44 UTC
Labels: Themes, [Type] Enhancement

**Comment by kurzee** [comment] 2016-06-22 23:22
Merged in the fix for moving the search icon to the top-right and removing the empty space: https://github.com/wordpress-mobile/WordPress-iOS/pull/5587, this will land in 6.4.

Moving forward, we'll be working on those search bars to be inline header views as part of the iPad refresh: https://github.com/wordpress-mobile/WordPress-iOS/issues/5576
