### ISSUE TITLE
Themes: Hide WordPress.com masterbar on theme details

### ISSUE THREAD

**Issue by charliescheer** [wordpress-mobile/WordPress-iOS#7716] opened 2017-08-22 19:06 UTC
### Expected behavior
When you go to the Themes page and click on the details for your current theme, the information for the theme should appear in the framework of the app

### Actual behavior
However when you click on the theme details it is loading the complete webpage for the theme details as if you were seeing it in a browser instead of the app.  This leads to replicating the menus twice, once for the app, and a second time because the admin bar appears at the top of the details section
![img_0045](https://user-images.githubusercontent.com/22015538/29582617-9f7348d6-873a-11e7-8ce6-b02f9bdace97.PNG)

### Steps to reproduce the behavior
1. go to Themes in your mobile app
2. Click on Details to see the details for the current theme
What you see is actually a web browser version of the theme details page including the logged in WordPress admin bar at the top, so if you…
3. click on the my sites in the top left to open the WordPress.com menu you can have menus inside of menus

##### Tested on [device], iOS [version], WPiOS [version]
Tested on iPad mini and iPhone 6s both on iOS 10.3.3 WPiOS 8.3

**Comment by designsimply** [comment] 2019-12-03 20:03
Tested and confirmed this issue is still valid in that you can open a Webview from the Themes section and see the Masterbar and browse Calypso via a Webview (which can be problematic), however, Webviews now show up in a modal window and so you won't see the problem mentioned where the left-side menu shows as duplicate.

1. Go to My Sites > Themes.
1. Tap Details.
1. Tap My Sites.
1. Tap any top-level navigation.
1. Browse around within the Webview and try to complete tasks there.

**Result:** you are now in a Webview with access to manage the site via Calypso within a Webview—which is not guaranteed to work due to Webviews not being a full browser experience similar to browsers such as Safari and some functions may not work there.

<img src="https://user-images.githubusercontent.com/1119271/70085049-be64a500-15cc-11ea-81f5-86412c09c70d.PNG" width="200" alt="IMG_3154"> <img src="https://user-images.githubusercontent.com/1119271/70085050-be64a500-15cc-11ea-8983-bfb727c3bd70.PNG" width="400" alt="IMG_0197">
<sup>Tested with WP Internal 13.8.0.20191202 MS App Center beta on iPhone 6S and on iPad Mini 4 (WiFi) (iPad5,1) iOS 13.2.3.</sup>

Notice the theme name at the top of the Webview in the screenshots.

**Comment by chipsnyder** [comment] 2021-01-25 21:23
This came up in a recent site-creation exercise `pbArwn-1AT` so I removed the stale flag and moved it to that board.

**Comment by chipsnyder** [comment] 2021-01-26 00:04
We're exploring a Calypso fix for this https://github.com/Automattic/wp-calypso/pull/49281

**Comment by enejb** [comment] 2021-02-03 20:33
The masterbar is now gone in calypso for mobile app requests. 
We might want to hide some of the buttons though as well. The arrow and the activate theme buttons for example.

**Comment by enejb** [comment] 2021-02-04 18:36
This seems to be fixed now. With Automattic/wp-calypso#49686

**Closed by enejb** 2021-02-04 18:36 UTC
Labels: Themes, Webviews, [Type] Bug
