### ISSUE TITLE
Spotlight: suggestion to a specific site doesn't change the currently selected site

### ISSUE THREAD

**Issue by leandroalonso** [wordpress-mobile/WordPress-iOS#18001] opened 2022-02-21 20:07 UTC
### Expected behavior

When I tap a "Spotlight suggestion" to go to a specific site I expect to go to this site.

### Actual behavior

The currently selected site doesn't change:

https://user-images.githubusercontent.com/7040243/155019852-cc84cf93-31f1-4254-aaca-f8c4c2dec52c.MP4

### Steps to reproduce the behavior

1. Install the app
2. Log in into an account with multiple sites
3. Switch between those site
4. Close the app
5. Swipe down on the main screen on your phone
6. Check the Spotlight suggestion for any site
7. Tap on it
8. Check that the currently selected site doesn't change

**Comment by onefrfry** [comment] 2022-11-10 18:58
I would like to try my hands at this sometime in the near future! Wish me luck!

**Comment by momo-ozawa** [comment] 2023-02-01 10:56
I can't seem to reproduce this issue - is this still happening for you @leandroalonso?

**Comment by tiagomar** [comment] 2023-06-05 12:18
I also can't reproduce it on 22.5. Closing this ticket for now and we can reopen if needed.

**Closed as completed by tiagomar** 2023-06-05 12:18 UTC
Labels: Good First Issue
