### ISSUE TITLE
Core Data: Multithreading violation when setting blogging reminders

### ISSUE THREAD

**Issue by staskus** [wordpress-mobile/WordPress-iOS#20841] opened 2023-06-13 07:36 UTC
Core Data: Multithreading violation when setting blogging reminders.

Could be the cause of crashes in the production: https://github.com/wordpress-mobile/WordPress-iOS/issues/20840

### Steps to reproduce the behavior

1. Pass `-com.apple.CoreData.ConcurrencyDebug 1` arguments on launch
2. Open Jetpack app and log in
3. Site Settings
4. Reminders
5. Set Reminders
6. Observe `Multithreading Violation`

```
Thread 41 Queue : com.apple.usernotifications.UNUserNotificationServiceConnection.call-out (serial)
#0	0x00000001845323a0 in +[NSManagedObjectContext __Multithreading_Violation_AllThatIsLeftToUsIsHonor__] ()
#1	0x0000000184531f7c in _PFAssertSafeMultiThreadedAccess_impl ()
#2	0x0000000184520074 in -[NSManagedObject willAccessValueForKey:] ()
#3	0x0000000104df6f74 in -[Blog dotComID] at /Users/povilasstaskus/Projects/WordPress-iOS/WordPress/Classes/Models/Blog.m:749
#4	0x0000000106195b04 in PromptRemindersScheduler.unschedule(for:) at /Users/povilasstaskus/Projects/WordPress-iOS/WordPress/Classes/Utility/Blogging Prompts/PromptRemindersScheduler.swift:70
#5	0x000000010619504c in PromptRemindersScheduler.processSchedule(_:blog:time:completion:) at /Users/povilasstaskus/Projects/WordPress-iOS/WordPress/Classes/Utility/Blogging Prompts/PromptRemindersScheduler.swift:139
#6	0x00000001061958f0 in closure #1 in PromptRemindersScheduler.schedule(_:for:time:completion:) at /Users/povilasstaskus/Projects/WordPress-iOS/WordPress/Classes/Utility/Blogging Prompts/PromptRemindersScheduler.swift:62
#7	0x0000000105def2f8 in closure #1 in InteractiveNotificationsManager.requestAuthorization(completion:) at /Users/povilasstaskus/Projects/WordPress-iOS/WordPress/Classes/Utility/InteractiveNotificationsManager.swift:72
#8	0x00000001054facc4 in thunk for @escaping @callee_guaranteed (@unowned Bool, @guaranteed Error?) -> () ()
```

https://github.com/wordpress-mobile/WordPress-iOS/assets/4062343/ca55927d-c954-4b5a-b3e0-6bfd20e8a9b9

**Comment by dvdchr** [comment] 2023-06-13 16:26
This should be related to #20848.

**Comment by staskus** [comment] 2023-06-14 12:23
> This should be related to https://github.com/wordpress-mobile/WordPress-iOS/issues/20848.

They are related but could also require fixes in 2 places. This ticket crashes when accessing `[Blog dotComID]` in `PromptRemindersScheduler.unschedule`, while https://github.com/wordpress-mobile/WordPress-iOS/issues/20848 crashes when accessing `WPAccount.lookup` in `BloggingPromptsService.init`.

**Comment by crazytonyli** [comment] 2023-06-19 21:44
This crash is caused by the `processSchedule` function accessing a `blog` instance in an incorrect thread. [This PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/20854/files#diff-bafdc8a1d5c0333535441694657aa42ce552a259e4e317ad43457c6ecf490bfa) has changed all the call sites of `processSchedule` function, to ensure it's called from the `blog`'s context queue, which should resolve this issue.

I'll close this issue as resolved, please let me know if you have any questions.

**Closed as completed by crazytonyli** 2023-06-19 21:44 UTC
Labels: Core Data, Blogging Reminders
