### ISSUE TITLE
iPad: The transition when changing device orientation is not very smooth.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#5902] opened 2016-08-26 19:29 UTC
To reproduce: 
Launch release/6.5 on an iPad.
Rotate the device and observe the transition animation.
Not that rather than a smooth size change, the animation shows large black bars that suddenly fill once the transition is complete. 

### Example 1
<img width="478" alt="screen shot 2016-08-26 at 2 27 01 pm" src="https://cloud.githubusercontent.com/assets/1435271/18017886/6a200510-6b99-11e6-95c6-1f995710958b.png">

### Example 2
<img width="458" alt="screen shot 2016-08-26 at 2 27 15 pm" src="https://cloud.githubusercontent.com/assets/1435271/18017906/7c7e014e-6b99-11e6-800d-80cb49a5be58.png">

### Video demo
https://cloudup.com/cacQfj2jpfa

cc @frosty, @kurzee

**Comment by kurzee** [comment] 2016-08-26 19:31
Whoah! Thanks @aerych, I'll take a look.

**Comment by frosty** [comment] 2016-08-26 20:33
Is this new behaviour in 6.5?

**Comment by aerych** [comment] 2016-08-26 20:36
> Is this new behaviour in 6.5?

Indeed it is.

**Comment by kurzee** [comment] 2016-08-27 05:27
Some more steps for reproducing this one:

1. Launch app in landscape.
2. Rotate, see black bars.
3. Doesn't happen starting from portrait.

**Comment by kurzee** [comment] 2016-08-27 06:23
Looks like this one is caused by Lookback, confirmed by enabling Lookback for a debug build via compiler flags, the pod configuration, building to an iPad device and running the steps above.

The latest Lookback SDK`1.4.1` produces the same result, we currently run `1.3.0`.

**Comment by aerych** [comment] 2016-08-29 14:42
If its just for the beta builds then maybe we don't need to worry too much about it. 
Close?

**Comment by kurzee** [comment] 2016-08-29 15:01
>If its just for the beta builds then maybe we don't need to worry too much about it. 
Close?

Yeah, I'd say we could close this for now.

**Closed** 2016-08-29 15:06 UTC
Labels: [Type] Bug
