### ISSUE TITLE
Site Title doesn't update in the app

### ISSUE THREAD

**Issue by rachelsquirrel** [wordpress-mobile/WordPress-iOS#3319] opened 2015-02-24 08:00 UTC
Changing the Site Title of a site doesn't change it in the app.

Steps.
1. Edit the Site Title of a site that is accessible via the app.
2. Open the app: the Site Title is still the old one. This then affects the Today Widget which still displays the old Site Title.

It only updates when the user signs out of the app and signs back in again.

**Comment by rachelsquirrel** [comment] 2015-02-24 08:07
User report: https://automattic.helpshift.com/admin/issue/13994/

**Comment by jstart** [comment] 2015-02-24 22:27
This issue occurs because we only sync with BlogService in viewDidLoad of BlogListViewController.  If the app is quit, or the user logs out, viewDidLoad is called again and we syncBlogsForAccount.  Since we don't get notified when a blog has been renamed, how often should sync?  Every viewWillAppear?  Maybe add a notification observer for UIApplicationWillEnterForegroundNotification? Would be happy to provide a PR triggering the sync on one of these app lifecycle events. What do you think is the best approach? @aerych @astralbodies

**Comment by aerych** [comment] 2015-02-24 23:00
I'd say once per launch would be good enough. Thoughts @astralbodies?

**Comment by sendhil** [comment] 2015-02-26 01:40
I think once per launch is enough...

**Comment by jstart** [comment] 2015-02-26 01:52
@aerych @sendhil what exactly are we defining as launch?  The issue is that we are doing it once per viewDidLoad.  Are you saying we should perform the sync in appDelegate didFinishLaunching?

**Comment by sendhil** [comment] 2015-02-26 02:08
I'd define launch as whenever the application engages in a full restart of the cycle, i.e. when it kicks off `application:didFinishLaunchingWithOptions`. IMO I think the sync is fine the way it is as this particular scenario seems like a bit of an edge case to me and I think syncing every single time you open that view might be overkill. Perhaps @aerych or @astralbodies have other thoughts.

**Comment by jstart** [comment] 2015-02-26 02:26
I agree, I think this is a pretty unusual edge case and the current sync interval seems sufficient.

**Comment by koke** [comment] 2015-06-28 09:59
I think this is fixed by #3874

**Closed by koke** 2015-06-28 09:59 UTC
Labels: General
