### ISSUE TITLE
Editor: images inserted from Media Library do not include captions previously saved in the Media Library

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-iOS#13063] opened 2019-12-09 23:40 UTC
### Expected behavior

I expected that if I add a caption to an image in Media and save it and then insert an image into the editor that the caption will be included by default. This is how captions work in Calypso and WP Admin.

### Actual behavior

Images added to posts from the Media Library do not include captions saved for the image in the Media section.

### Steps to reproduce the behavior

1. Go to Media, upload an image, and save a caption for that image.
1. Start a new post in either editor in the app.
1. Add the image with a caption saved in the media library from step 1.
1. Check to see if a caption is created in the editor.

**Result:** captions are not included when adding images with saved captions from the media library. ([1m48s](https://cloudup.com/c_4pR13tODl))

<img src="https://user-images.githubusercontent.com/1119271/70482332-73ea9900-1aa2-11ea-85b8-605911f13988.png" width="270" alt="caption-saved"> <img src="https://user-images.githubusercontent.com/1119271/70482331-73520280-1aa2-11ea-854a-cf0b2003952c.png" width="270" alt="caption-missing-when-inserted">
<sup>Tested with WPiOS 13.8.0.0 TestFlight beta on iPhone 6S iOS 13.2.3.</sup>

<sup>(internal references: 2262379-zen p4a5px-2qu-p2 cc @ChrissiePollock)</sup>

**Comment by iamthomasbishop** [comment] 2019-12-13 01:46
@designsimply Good catch! Would you mind adding this issue in the Mobile Gutenberg repo as well if you haven’t already?

**Comment by designsimply** [comment] 2020-02-04 01:31
Certainly! I've moved this to https://github.com/wordpress-mobile/gutenberg-mobile/issues/1851.

**Comment by SergioEstevao** [comment] 2020-04-15 10:10
I'm reopening this because this needs to be fixed in the Aztec editor too.

**Comment by illusaen** [comment] 2021-03-31 15:04
No longer reproducible.

**Comment by illusaen** [comment] 2021-04-01 15:27
Closing this as non reproducible but, please feel free to reopen if it still occurs, thanks!

**Closed by illusaen** 2021-04-01 15:27 UTC
Labels: Aztec, Media, Posting/Editing, [Status] Duplicate, [Type] Bug
