### ISSUE TITLE
[Auto-upload Published] Author filter returns empty list

### ISSUE THREAD

**Issue by shiki** [wordpress-mobile/WordPress-iOS#12329] opened 2019-08-15 17:17 UTC
Found by @diegoreymendez in https://github.com/wordpress-mobile/WordPress-iOS/pull/12317#pullrequestreview-275481285. 

Steps:
1. Launch the app
2. Go offline
3. Create a new post
4. Add title, content and an image
5. Hit Publish
6. Go ahead and publish
7. Once the post fails to upload make sure the failed post is on screen (or change tab so that it is).
8. Quit the app.
9. Go back online
10. Reopen the app… you should see the failed post autosave.
11. Once the autosave completes, you’ll see the no results view.

Filtering by _Me_ returns an empty list. 

<img src="https://user-images.githubusercontent.com/1836005/63108639-bde0c980-bf5d-11e9-9648-9c41a19c220d.gif" width="320">

I could not reproduce this in `develop` and on the #12317 branch. This may be caused by the filtering changes in #12252.  

@diegoreymendez Feel free to pick it up if you have some time. If not, someone else can take it. 🙂

**Comment by yaelirub** [comment] 2019-08-16 22:13
I can't reproduce this either.

**Comment by diegoreymendez** [comment] 2019-08-20 17:23
I'll test this once more and close it if I can no longer reproduce.

**Comment by diegoreymendez** [comment] 2019-08-22 17:18
I managed to reproduce this today by chance.  It happened after tapping "Retry" on a post that had failed to upload before.

**Comment by yaelirub** [comment] 2019-08-22 20:48
Followed the steps and was not able to reproduce.

**Comment by diegoreymendez** [comment] 2019-08-23 14:59
I was able to reproduce this originally, and even yesterday.  That said I can't reproduce anymore right now.  I'll close this issue for the time being, but we can reopen if there's any other occurrence of this issue.

**Closed by diegoreymendez** 2019-08-23 14:59 UTC
Labels: Offline Support, [Type] Bug
