### ISSUE TITLE
Lists are being rendered in iOS comments but with an added bullet after an indented list. 

### ISSUE THREAD

**Issue by startuptester** [wordpress-mobile/WordPress-iOS#17057] opened 2021-08-19 21:58 UTC
### Expected behavior
Like Android, I did not expect iOS to render lists in comments 
**Android, it just looks like a paragraph.**
![Screenshot_20210819-152716_WordPress](https://user-images.githubusercontent.com/66104034/130149441-139289fc-a4bc-44f1-b014-faad1da30dbf.jpg)

### Actual behavior
It works, but it adds an extra bullet after any indented list. 
![IMG_BB9357242FE4-1](https://user-images.githubusercontent.com/66104034/130149546-c0546aa8-76a0-43fb-a76c-81db6d64c1b3.jpeg)

From @aerych: 
> My guess would be the parser either thinks there is a new line after the indented list, or that it’s “splitting” the bullet that contains the indented list.  It could be something in our parser code that could be improved, or it could be a glitch with the way text kit handles nested HTML lists. 

### Steps to reproduce the behavior
Create a list in a comment, add indented lists and view in mobile reader.

**Comment by ScoutHarris** [comment] 2021-10-27 23:36
Hey @startuptester .

We are in the process of refactoring the comments lists (pbArwn-2ks). This particular problem will be resolved with that refactor. I confirmed a list comment renders correctly in the view we've already refactored, My Site > Comments. The same refactored view will be applied to the threaded comments in maybe a month or so. What do you think about closing this? If you'd prefer not to, we should at least remove it from GK and I can close it later.

**Comment by ScoutHarris** [comment] 2021-10-29 18:07
Hey @startuptester .

I'm closing this since it will be fixed soon-ish with Unified Comments. Let me know if you object!

(cc @dvdchr )

**Closed as completed by ScoutHarris** 2021-10-29 18:07 UTC
Labels: Comments
