### ISSUE TITLE
Post-post "freezes" app when posting offline

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/WordPress-iOS#6446] opened 2017-01-23 09:54 UTC
There's a weird bug where post-post isn't dismissed properly

### Steps to reproduce the behavior

- Launch the app, go to a site's blog posts
- Create a new post and write a title
- Put the phone in airplane mode
- Tap post
- Post-post appears, along with a short popup "Error occurred during publishing"
- Tap on share, Mail. Cancel and delete draft since it doesn't really have the post link.
- You are back to what appears to be the posts list, but you can't tap anywhere.
- Force quit the app

For some reason, when the mail controller is dismissed, post-post becomes "transparent" but is still on top of the posts list:

![screen shot 2017-01-23 at 10 43 41](https://cloud.githubusercontent.com/assets/8739/22199177/18eeb9e8-e15a-11e6-8281-37236f76a810.png)

So the app is not really "frozen", as in something blocking the UI thread, it's just not responding to touches.

**Comment by nheagy** [comment] 2017-02-02 17:42
Duplicate of #6544, which seems to be the root problem.

**Closed by nheagy** 2017-02-02 17:42 UTC
Labels: Posting/Editing, [Pri] Medium, [Type] Bug
