### ISSUE TITLE
Image upload failure "Failed to get size for image"

### ISSUE THREAD

**Issue by donkristo** [wordpress-mobile/WordPress-iOS#12103] opened 2019-07-11 05:43 UTC
### Expected behavior
In editor (block or classic) when the upload of the picture completes the picture should be shown.

### Actual behavior
When the upload completes the picture is not shown. Instead a picture placeholder is shown. 
The log has entries about a failed image download.
It only happens on my self hosted sites not on wordpress.com hosted site. I've tried two different wordpress virtual machine images (bitnami and turnkey). Both have the same problem.

### Steps to reproduce the behavior

1. Setup a self hosted wordpress site based on bitnami or turnkey virtual machine image.
2. Use the app to create a new blog post and upload an image.
3. When the image upload is complete instead of the image an image placeholder graphic is shown.

##### Tested on [device], iOS [version], WPiOS [version]
iphone XS Max with iOS 12.3.1
WPiOS: 12.7.1

##### Log output
2019-07-10 20:46:18:917 Unable to download image for attachment with url = http://192.168.1.250/wp-content/uploads/2019/07/routereinstellung-1024x576.png. Details: Optional("Der Vorgang konnte nicht abgeschlossen werden. (WordPress.ImageDownloaderError-Fehler 0.)")
2019-07-10 20:46:18:918 Failed to get size for image: http://192.168.1.250/wp-content/uploads/2019/07/routereinstellung-1024x576.png

**Comment by donkristo** [comment] 2020-07-16 06:25
Bug is still valid. Tested 2 or 3 weeks ago.

**Comment by illusaen** [comment] 2021-03-31 15:12
Unable to reproduce with `jurassic-ninja`: https://tense-parrotfish.jurassic.ninja/2021/03/31/6/

**Comment by illusaen** [comment] 2021-04-01 15:27
Closing this as non reproducible but, please feel free to reopen if it still occurs, thanks!

**Closed by illusaen** 2021-04-01 15:27 UTC
Labels: Posting/Editing, [Type] Bug
