### ISSUE TITLE
[GlobalStep] iOS - “Play on SoundCloud” button requires a double tap. 

### ISSUE THREAD

**Issue by wptester9845** [wordpress-mobile/WordPress-iOS#14293] opened 2020-01-31 14:24 UTC
**Describe the bug**
When creating a post containing a SoundCloud shortcode a soundcloud box is present with 2 buttons “Play on SoundCloud” and “Listen in browser”. Tapping the “Play on SoundCloud” button appears to have no function. The button will only function if the user performs a double tap. 

It should be noted that this only occurs when viewing the post directly in the app, not when in browser within the app (such as the reader). 

**To Reproduce**
1. Launch WordPress 14.1 (14.1.0.0) 
2. Log into an account
3. Create a post with a valid soundcloud shortcode  (e.g. [soundcloud url =”https://soundcloud.com/chvrches/death-stranding”]
4. Tap My Site > Blog Posts and View the post. 
5. Tap “Play on SoundCloud”. 

**Expected behavior**
The soundcloud app should open and play the song on a single tap.

**Actual behavior**
The link only functions if the user performs a double tap. 

**Tested on **
iPhone 11 (13.0)

Please see attached video
[PlayOnSoundCloud iOS.zip](https://github.com/wordpress-mobile/gutenberg-mobile/files/4139813/PlayOnSoundCloud.iOS.zip)

[Update from Sheri: edited to add screenshots inline.]

<img width="200" alt="Screen Shot 2020-06-24 at Jun 24 12 26 02 PM" src="https://user-images.githubusercontent.com/1119271/85612219-e6bdfa80-b615-11ea-9691-7787fc482527.png">

**Submitted by**
Alex Wood

**Comment by designsimply** [comment] 2020-06-24 19:14
Closing because I was unable to replicate the bug as described. I tested and confirmed that tapping "Play on SoundCloud" in a webview opened the correct SoundCloud link in Safari on a single tap when using WPiOS 15.1.0.2 TestFlight beta on iPhone 6S iOS 13.3.1.

Note: I also found that the webview crashed several times in my case and added details to the crash report at https://github.com/wordpress-mobile/WordPress-iOS/issues/14030#issuecomment-649012489.

**Closed by designsimply** 2020-06-24 19:14 UTC
Labels: Webviews, [Type] Bug
