### ISSUE TITLE
Login: Unable to login after restoring from iCloud backup.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#8262] opened 2017-12-04 19:04 UTC
Originally reported by @biskobe at p4a5px-25H-p2

> Today I finally managed to get my hands on an iPhone X and set up my phone the lazy way with restoring everything from iCloud.
>
> After the WordPress app finished downloading I started it up to see if I needed to log-in.
>
> Then the following happened:
> [video content: https://cloudup.com/cNxpeVqqLQt ]
>
> As you can see the username was gone from the username field and there was no way to write it.
> 
> And because of that it didn’t accept only a password.
>
> Canceling to clear out data didn’t work because the popup appeared for a second and then disappeared automatically. I tried tapping the Delete button, but the whole popup was inactive while visible 😦
> 
> I finally managed to sign in because I noticed the 1Password button and went that way, which worked like magic.

The attached video shows the LoginWPComViewController presented modally (cancel button in the upper left navbar).  The email address label is empty and immediately an error alert is shown.
<img width="204" alt="screen shot 2017-12-04 at 12 58 34 pm" src="https://user-images.githubusercontent.com/1435271/33570697-4dcd7546-d8f3-11e7-8325-6b8311d64b12.png">

Typing into the password text field does not enable the Next button on the screen. 
<img width="204" alt="screen shot 2017-12-04 at 12 59 05 pm" src="https://user-images.githubusercontent.com/1435271/33570713-57f39dca-d8f3-11e7-8cec-597d998fee41.png">

Attempting to cancel momentarily shows a propmt that all data will be removed but the prompt immediately is dismissed. 

<img width="340" alt="screen shot 2017-12-04 at 12 59 35 pm" src="https://user-images.githubusercontent.com/1435271/33570774-82219e1c-d8f3-11e7-8120-ea64fbe6e57b.png">

 He's pretty much stuck.

**Comment by nheagy** [comment] 2017-12-05 17:38
Closing as a duplicate of #8098 tho this has good info. 

I plan to address this one ASAP.

**Closed by nheagy** 2017-12-05 17:38 UTC
Labels: Login, [Status] Duplicate, [Type] Bug
