### ISSUE TITLE
NSInternalInconsistencyException: Attempted to perform update with invalid index path: <NSIndexPath: 0x283ff4900> {length = 2, path...

### ISSUE THREAD

**Issue by jkmassel** [wordpress-mobile/WordPress-iOS#15371] opened 2020-11-23 18:34 UTC
**Sentry Url**: https://sentry.io/share/issue/d36aac251b5f4881984c02a949ff6f9e/
**User Count**: 441
**Count**: 611
**First Release**: 15.5.0.3
**First Seen**: 2020-09-01T18:18:55Z
**Last Seen**: 2020-11-23T17:52:11Z
**24 Hours**: 128
**30 Days**: 508
**LogID:** 759889CB-4418-49F1-BEF2-6A9570846A72

```
NSInternalInconsistencyException: Attempted to perform update with invalid index path: <NSIndexPath: 0x2808a90e0> {length = 2, path...
  File "Classes/Utility/WPTableViewHandler.m", line 702, in -[WPTableViewHandler controller:didChangeObject:atIndexPath:forChangeType:newIndexPath:]
  File "main.swift", line 7, in main
...
(34 additional frame(s) were not displayed)
```

**Comment by leandroalonso** [comment] 2020-11-24 12:36
Duplicate of https://github.com/wordpress-mobile/WordPress-iOS/issues/15366

**Closed as completed by leandroalonso** 2020-11-24 12:36 UTC
Labels: [Type] Crash
