### ISSUE TITLE
Stories post: Keyboard overlaps the publish sheet and makes it hard to use

### ISSUE THREAD

**Issue by fluiddot** [wordpress-mobile/WordPress-iOS#16625] opened 2021-06-03 11:21 UTC
### Expected behavior
Publish sheet should be fully visible.

### Actual behavior
The keyboard overlaps the publish sheet and makes it almost unusable.

### Steps to reproduce the behavior
1. Go to "My Site".
2. Create a new Story post.
3. Take a picture.
4. Tap on the ➡️ button to publish it.
5. Observe that the keyboard overlaps the publish sheet.

**NOTE:** I managed to fix it by putting the app in to background and open it again.

https://user-images.githubusercontent.com/14905380/120636829-6aab7400-c46e-11eb-87fe-ebae10176134.mp4

**Comment by startuptester** [comment] 2021-06-10 06:51
This is a regression in 17.5. Thanks for catching it @fluiddot !

cc: @jkmassel

**Comment by mokagio** [comment] 2021-06-14 01:57
@startuptester I'm not sure what the process is but since I just shipped 17.5, I'm guessing to keep this visible it should go into the milestone for the release, right?

I'm bumping this to 17.6.

Feel free to amend if that wasn't appropriate.

Thanks!

**Comment by startuptester** [comment] 2021-06-14 03:41
I think this was actually fixed and I cannot repro it in 17.5. @bjtitus or @fluiddot, can you confirm? Thanks!

**Comment by fluiddot** [comment] 2021-06-15 14:20
> I think this was actually fixed and I cannot repro it in 17.5. @bjtitus or @fluiddot, can you confirm? Thanks!

I've just checked the issue in the last version from the AppStore (`17.5.0.4`) and looks fixed 🎊 .

**Comment by bjtitus** [comment] 2021-06-15 14:27
Fixed in https://github.com/wordpress-mobile/WordPress-iOS/issues/16625

**Closed as completed by bjtitus** 2021-06-15 14:27 UTC
Labels: [Pri] High

**Comment by mokagio** [comment] 2021-06-15 19:58
@bjtitus 

> Fixed in https://github.com/wordpress-mobile/WordPress-iOS/issues/16625

I assume you meant #16666, the PR linked above, right? #16625 is this issue 😄 ♻️

**Comment by mokagio** [comment] 2021-06-15 19:59
Moved to 17.5 milestone because the fix shipped with it.
