### ISSUE TITLE
Viewing posts launches Safari app with widgets.wp.com

### ISSUE THREAD

**Issue by davipontesblog** [wordpress-mobile/WordPress-iOS#8615] opened 2018-02-13 13:57 UTC
### Expected behavior
When browsing posts with iOS app, and clicking on "View" on the bottom bar, the post is loaded full screen.

### Actual behavior
When browsing posts with iOS app, and clicking on "View" on the bottom bar, the post is loaded full screen, but then immediately opens up the browser app (Safari) with a redirect to `https://widgets.wp.com/likes/#`.

### Steps to reproduce the behavior
We cleared the history and it still does the same thing.
Open WordPress.com app, check a post in Reader or own site, click on "View" (bottom nav bar).

##### Tested on [device], iOS [version], WPiOS [version]
WP version 9.3 phone iOS 11.2.5
Did not happen on computer
Device: Iphone 6 plus

Issue - 953241-zen

**Comment by elibud** [comment] 2018-02-13 16:15
I was not able to replicate this, does it happen for a particular post? Can you let me know which reader feed/tag are you looking at? Thanks

**Comment by rachelmcr** [comment] 2018-02-13 17:42
I had the same happen to me in the past day or so on my iPhone 6, iOS 11.2.5, with the 9.3 internal beta. I only tried to view one post (because it was very slow to load/scroll in the Reader view) from my Followed Sites feed: https://kpresner.com/2018/02/10/myanmar-markets-and-meals/

I just tried selecting "View" on that post again, and it opened as expected in the webview without opening `https://widgets.wp.com/likes/#` in Safari. I'm not sure if that's because I updated to version 9.4.0.20180212 in the meantime, or if there was another factor involved.

**Comment by elibud** [comment] 2018-02-13 17:47
@rachelmcr can you try the same thing on the current production version `9.3`? Thanks

**Comment by rachelmcr** [comment] 2018-02-13 18:03
Good idea :) I just tested on the production version 9.3 and couldn't reproduce there, either.

I see that the original user report came in on Sunday, so perhaps this was a more general issue with the Like button at that time that has since been resolved?

**Comment by rachelmcr** [comment] 2018-02-13 18:07
Actually, I take it back. I saw the issue in the Reader, but I just looked at the user report and it happened to them under My Sites > Blog Posts > View. I can reproduce the issue there in both production and beta versions:

1. Go to the My Sites tab.
2. Select Blog Posts.
3. Under a blog post, select "View."

The post begins to load, and then `https://widgets.wp.com/likes/#` opens in Safari. Going back to the app shows the post view, but if you go back to the post list and select "View" again the behavior is repeated.

**Comment by davipontesblog** [comment] 2018-02-13 18:23
Just tested now with my app and could reproduce the issue. Same as @rachelmcr mentioned:

1 Go to the My Sites tab.
2 Select Blog Posts.
3 Under a blog post, select "View."

I did this with two of my sites, and it happens on both.

Here is what I am using:
iOS 11.2.5
iPhone 7
WordPress.com app, version 9.2.1

I have tried testing with the new version, 9.3. Updated my app to 9.3, and it still happened with one site, and not with the other site. Seems to be sporadic now.

**Comment by etoledom** [comment] 2018-02-13 19:26
I was able to reproduce it too!
I took a quick look and I noticed this quite interesting bit:

<img width="485" alt="screen shot 2018-02-13 at 4 15 41 pm" src="https://user-images.githubusercontent.com/9772967/36168905-6c9e66ba-10d9-11e8-9490-66d756758f03.png">

This is a breakpoint at [this callback](https://github.com/wordpress-mobile/WordPress-iOS/blob/f470847db4d74d74530d665b48c4a39e109f79d8/WordPress/Classes/ViewRelated/Post/PostPreviewViewController.m#L146):

It basically means that the app is reacting to a "tap" on that link in the web view, and then it opens Safari.
Where does that tap come from? That's a good question.

Could it be something in the page itself?
But then, It doesn't redirect when opening the same page in the web browser.

**Comment by elibud** [comment] 2018-02-13 19:29
Thanks @etoledom for troubleshooting, I can replicate too and I'm clueless, the code seems to be this:

```<iframe src='https://widgets.wp.com/likes/master.html?ver=20180212#ver=20180212' scrolling='no' id='likes-master' name='likes-master' style='display:none;'></iframe>```

I wonder if how we handle likes changed recently, I'll try to find out.

**Comment by elibud** [comment] 2018-02-13 20:48
As @etoledom pointed out the culprit seems to be a request to `https://widgets.wp.com/likes/#` that to the OS considers to be originated by a user action (tap on a link) but isn't.

This seems to be related to changes made to the way we load likes, either back in December (I think we would've heard about it before, right @rachelmcr @davipontesblog) or some minor updates done at the end of last week by @gravityrail He will look more into this and will get back to us.

**Comment by SiobhyB** [comment] 2018-02-15 09:35
This came up again in 261101-h. The user noticed that they're being redirected to `https://widgets.wp.com/likes/#` when navigating to My Site > Blog Posts > Views ever since updating to 9.3.

**Comment by elibud** [comment] 2018-02-15 12:18
@gravityrail fixed this one!

@SiobhyB Can you ask the user to try again now?
@rachelmcr and @davipontesblog can you confirm this is no longer an issue for you two?

Thanks and Cclaps all around

**Comment by rachelmcr** [comment] 2018-02-15 12:30
I tested and can confirm that the issue is resolved in both production and beta versions of the app, on WordPress.com Simple and Jetpack sites.

**Closed** 2018-02-15 12:37 UTC
Labels: Posts List, [Type] Bug
