### ISSUE TITLE
NSInternalInconsistencyException: Modifications to the layout engine must not be performed from a background thread after it has be...

### ISSUE THREAD

**Issue by loremattei** [wordpress-mobile/WordPress-iOS#14030] opened 2020-04-30 08:35 UTC
**Sentry Url**: https://sentry.io/share/issue/5b844000e9a945f591975d0feab90622/
**User Count**: 51
**Count**: 265
**First Release**: 14.4.0.1
**First Seen**: 2020-04-19T08:40:03Z
**Last Seen**: 2020-04-30T07:57:07Z
**24 Hours**: 43
**30 Days**: 263

```
NSInternalInconsistencyException: Modifications to the layout engine must not be performed from a background thread after it has be...

```

**Comment by bummytime** [comment] 2020-04-30 20:30
This one looks very similar to #12628 and #14032 but involves `UIAlertController`. Only 64 users are impacted so leaving it open, but marking it low.

**Comment by designsimply** [comment] 2020-06-13 01:32
If you look at the [90-day graph for issue.id:1619624696](https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=release&field=os&field=device&field=culprit&name=All+Events&project=1438083&query=issue.id%3A1619624696&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1) in Discover in Sentry for this case, you can see that the crash popped up at the end of Apr and started averaging ~50 crashes per day pretty quickly. 50 crashes per day is not the highest we are tracking but also not low priority either. Because of that, I would have marked this as medium priority to start.

<img width="1021" alt="Screen Shot 2020-06-12 at Jun 12 3 47 10 PM" src="https://user-images.githubusercontent.com/1119271/84548921-0115e100-acc4-11ea-856a-a27501b1297e.png">

**Events in the last 90d:** 2,500
**Users affected in the last 90d:** 522
<sub>https://sentry.io/share/issue/5b844000e9a945f591975d0feab90622/</sub>

The very best thing we can do for new crashes is to try to pinpoint a commit where the crash was introduced—or any tips at about where it might be coming from in the code. If we can find where the problem was introduced soon after the crash began, it may be a lot easier for the developer who worked on the related code to fix it quickly. If we can't pinpoint the cause of the problem in the code, then we should watch the rate of change for the number of crashes. Ones that escalate quickly should be addressed sooner. Any that have relatively high rates (i.e. 100 or more crashes per day), should either be addressed as high priority or sent to the top of the list for the next Groundskeeping rotation.

**Comment by designsimply** [comment] 2020-06-24 19:11
I triggered this crash several times today while beta testing with WPiOS 15.1.0.2 TestFlight iPhone 6S iOS 13.3.1.

Steps to reproduce:

1. Create a new post.
1. Paste in a SoundCloud url such as `https://soundcloud.com/claude-debussy/clair-de-lune`.
1. Publish the post.
1. Go to My Site > Blog Posts and tap View for the post.

**Result:** the app crashed in _most_ cases (but not every time) after opening a webview for a post with a Soundcloud embed added to a post by pasting the URL into a block. ([1m29s](https://cloudup.com/cJYUVt5G43d))

**Note:** the post I tested was originally made using Calypso Gutenberg on a WordPress.com Premium site, not sure whether that's relevant. Sometimes closing and re-opening the post or opening it in the editor then leaving quickly and opening it in a webview right afterward helps to trigger the crash.

<p style="clear:both;"><sup>Tested with WPiOS 15.1.0.2 TestFlight beta on iPhone 6S iOS 13.3.1 on WordPress.com Premium made4testing0318.blog logged in as testuser0313.</sup></p>

**Comment by designsimply** [comment] 2020-08-07 00:09
Looks like we quashed this one in 15.0. There were zero reports in the same graph for the latest two releases, 15.2 & 15.3. 🎉 Closing.

[![image](https://user-images.githubusercontent.com/1119271/89594691-c6d24700-d80f-11ea-8c4e-cac489d3c49f.png)](https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=release&field=os&field=device&field=culprit&name=All+Events&project=1438083&query=issue.id%3A1619624696+release%3A15.0%2A&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1)

**Closed by designsimply** 2020-08-07 00:09 UTC
Labels: General, [Pri] Medium, [Type] Crash, iOS 13
