### ISSUE TITLE
Reader site viewer is missing post title in navigation bar

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-iOS#15326] opened 2020-11-18 19:29 UTC
**Note: This issue is not yet present on the 16.0, 16.1, or 16.2 WPiOS versions, it's only present on the current `develop` branch.**

### Expected behavior

When I visit a post in Reader, the modal screen that is shown should display the post title in the navigation bar.

### Actual behavior

When I visit a post in Reader, the post title in the navigation bar is not visible.

The screen recording below shows the invisible post title using the iOS simulator's "Show Blended Layers" option.

| <img src="https://user-images.githubusercontent.com/1898325/99578137-1c93bf00-29bb-11eb-9fa8-3274213c55c0.gif" alt="Screenshot showing missing nav bar title" width="350">  |
| - |

### Steps to reproduce the behavior

1. Open the Reader
2. Select a post
3. Tap the ellipsis menu (three dots on the right hand side of the post)
4. Select "Visit" from the bottom sheet that appears
5. Notice that the white text of the post title is hidden against the white nav bar background

**Comment by designsimply** [comment] 2020-11-19 04:01
Tested and confirmed that I couldn't see this problem in 16.2.20201116 alpha or 16.2.0.0 TestFlight beta.

@emilylaguna is this something we should be concerned about for `develop` or that we should watch out for in 16.3?

**Comment by emilylaguna** [comment] 2020-11-19 21:09
Hey @designsimply, I took a look at this and it looks like it's related to the new navigation bar (all white) that's under a feature flag and is only enabled on develop currently. If you disable that feature flag on develop the issue is not present. 

I'll ping @frosty since I believe he worked on that project recently.

**Comment by guarani** [comment] 2020-11-19 22:31
> Hey @designsimply, I took a look at this and it looks like it's related to the new navigation bar (all white) that's under a feature flag and is only enabled on develop currently. If you disable that feature flag on develop the issue is not present.

Good find @emilylaguna, I was wondering why I saw this issue on a local checkout of 15.9, but it makes total sense now since it's enabled on development builds.

**Comment by frosty** [comment] 2020-11-20 11:20
Thanks folks, yes this only affects development so far. We'll work on a fix!

**Comment by leandroalonso** [comment] 2021-03-25 17:36
Fixed in the recent "big titles" changes.

**Closed as completed by leandroalonso** 2021-03-25 17:36 UTC
Labels: [Pri] Low, Reader
