### ISSUE TITLE
NSInternalInconsistencyException: Attempted to perform update with invalid index path: <NSIndexPath: 0x282df6120> {length = 2, path...

### ISSUE THREAD

**Issue by jkmassel** [wordpress-mobile/WordPress-iOS#15372] opened 2020-11-23 18:35 UTC
**Sentry Url**: https://sentry.io/share/issue/ac285c965807430f9a6c6ce0413161fa/
**User Count**: 393
**Count**: 448
**First Release**: 15.5.0.3
**First Seen**: 2020-08-31T19:29:25Z
**Last Seen**: 2020-11-23T18:12:38Z
**24 Hours**: 103
**30 Days**: 396
**LogID:** 5EC78FA6-4C28-4451-B5FA-6963E896B756

```
NSInternalInconsistencyException: Attempted to perform update with invalid index path: <NSIndexPath: 0x282df6120> {length = 2, path...
  File "Classes/Utility/WPTableViewHandler.m", line 702, in -[WPTableViewHandler controller:didChangeObject:atIndexPath:forChangeType:newIndexPath:]
  File "main.swift", line 7, in main
...
(34 additional frame(s) were not displayed)
```

**Comment by leandroalonso** [comment] 2020-11-24 12:36
Duplicate of https://github.com/wordpress-mobile/WordPress-iOS/issues/15366

**Closed as completed by leandroalonso** 2020-11-24 12:36 UTC
Labels: [Type] Crash
