### ISSUE TITLE
[GlobalStep] Image’s Captions are not displayed while viewing a Gallery’s Image in Fullscreen

### ISSUE THREAD

**Issue by wptester9845** [wordpress-mobile/WordPress-iOS#13435] opened 2020-02-12 14:20 UTC
### Description
Tapping an Image in a Gallery block causes it to be open in Fullscreen but if this image has captions they are not displayed while in this view.

### Reproduction Rate
4/4 100%

### Expected behavior
The Image’s captions should be displayed while viewing the Image in Fullscreen.

### Actual behavior
The Image’s captions are not displayed when viewing the Image in Fullscreen.

### Steps to reproduce the behavior
1. Install WordPress 14.2
2. Log in to an account.
3. Open the Post Editor.
4. Add a Gallery block.
5. Press “Add Media”.
6. Press “WordPress Media Library”.
7. Add some pictures.
8. Tap a picture and add a caption to it.
9. Publish the Post.
10. Open the post in the reader.
11. Tap the captioned picture.
##### Tested on the following
iPhone XR (12.0.1)

#### Screenshot of the Reader displaying the Images with Captions
<img width="270" src="https://user-images.githubusercontent.com/60415523/74343091-656e7580-4da2-11ea-9919-dfa77da6c659.jpg" />

#### Screenshot of the first Image being displayed in Fullscreen without its Captions
<img width="270" src="https://user-images.githubusercontent.com/60415523/74343087-643d4880-4da2-11ea-8edf-cecc677a708e.jpg" />

### Submitted by:
Luis Pimenta

**Comment by designsimply** [comment] 2020-08-13 00:34
Tested and confirmed using WPiOS 15.5.0.0 that tapping on an image in a gallery from a Reader post view results in the image showing fullscreen without a caption. In comparison, the mobile web Reader does nothing when an image is tapped (no fullscreen view) and on the front-end a carousel view is shown which includes the caption. 

WPiOS Reader|Mobile Web Reader (image detail not avail)|Front-end
---|---|---
![image](https://user-images.githubusercontent.com/1119271/90080342-984ce400-dcc7-11ea-9aa4-6242519ad8cf.png)|![image](https://user-images.githubusercontent.com/1119271/90080447-dcd87f80-dcc7-11ea-9b76-531d56a72602.png)|![image](https://user-images.githubusercontent.com/1119271/90080458-e4982400-dcc7-11ea-9744-030e8206eaff.png)

<p style="clear:both;"><sup>Tested with WPiOS 15.5.0.0 TestFlight beta on iPhone 6S iOS 13.6.</sup></p>

I believe this the current intended behavior in the app and that we may want to close this issue and create a new issue requesting the carousel view option for galleries in the app as an enhancement request. 

@frosty may I have your opinion on this one? If a carousel update was already discussed and decided against, then I think we can close this issue as wontfix for now. If adding a carousel view sounds like something we want to do in the not-too-distant future, let me know and I'll make a separate issue for that.

**Comment by leandroalonso** [comment] 2021-03-25 16:43
Given the lack of response here I'm assuming we won't change that in the near future, thus closing this issue.

**Closed by leandroalonso** 2021-03-25 16:43 UTC
Labels: Previews, Reader, [Pri] Low, [Status] Wontfix, [Type] Bug
