### ISSUE TITLE
[GlobalStep] [iOS] User is not able to set profile image using "Camera" as "Use" option is not available.

### ISSUE THREAD

**Issue by gglobalstep** [wordpress-mobile/WordPress-iOS#14065] opened 2020-05-06 16:56 UTC
**Environment:**
iPad Air 2(v13.3.1), iPhone 11 Pro (v13.3.1).

**Steps To Reproduce:**
 1. Install and launch the application.
 2. log in with valid credentials.
 3. Tap on "Me" tab.
 4. Tap on "Add a Profile Photo".
 5. Select Camera option and click a picture. 
 6. Try to set that image as Profile photo.
  7. Observe that "Use" option is not there to set photo and user is not able to set profile photo.
  
 **Actual Result:**
User is not able to set profile image using "Camera" as "Use" option is not available.
 
 **Expected Result:**
 User should able to set profile image using "Camera".

![#14065_1](https://user-images.githubusercontent.com/41110392/81205864-e4adc700-8fe8-11ea-9db9-c38599a9d861.PNG)
[#14065_2.zip](https://github.com/wordpress-mobile/WordPress-iOS/files/4588221/14065_2.zip)

**Comment by designsimply** [comment] 2020-05-12 20:52
Closing as a duplicate of #9685.

**Closed by designsimply** 2020-05-12 20:52 UTC
Labels: /Me, [Type] Bug
