### ISSUE TITLE
Plugins: Items aren't tappable or open the wrong screen

### ISSUE THREAD

**Issue by mattmiklic** [wordpress-mobile/WordPress-iOS#16246] opened 2021-04-07 00:21 UTC
### Expected behavior
- On a Jetpack-enabled site, open the Plugins menu
- Tap on a plugin in any of the categories on that screen
- The detail page for that Plugin should be displayed.

### Actual behavior
- Tapping any of plugins in the Installed, Popular, or Newest rows opens the list of plugins in that category (what "See All" should link to), instead of going directly to that plugin's listing.
- Tapping anywhere on the Featured row does nothing; taps have no effect.

**Comment by frosty** [comment] 2021-05-19 16:27
Closing as a duplicate of #16087

**Closed as completed by frosty** 2021-05-19 16:27 UTC
Labels: Jetpack Plugins
