### ISSUE TITLE
Editor: Unable to add category from post options

### ISSUE THREAD

**Issue by brbrr** [wordpress-mobile/WordPress-iOS#8227] opened 2017-11-24 03:32 UTC
### Expected behavior

The category is successfully created and assigned.

### Actual behavior

"Title missing" validation shows up

![img_2115](https://user-images.githubusercontent.com/5654161/33194365-2866f4ec-d102-11e7-857e-02f0daedbd28.PNG)

### Steps to reproduce the behavior

In post editor:
- Open post options > Categories > Add ("+")
- Set any category title
- [Optional] set any parent category
- Try to save new category

**Comment by ChrissiePollock** [comment] 2017-12-09 19:19
Brought up again in #244854-h.

**Comment by pmciano** [comment] 2017-12-13 14:42
Reported 245545-h

**Comment by charliescheer** [comment] 2017-12-13 18:36
reported in 245811-h as well

**Comment by elibud** [comment] 2017-12-13 18:39
@koke can you take a quick look at this one?

**Comment by koke** [comment] 2017-12-13 20:26
It’s a duplicate of #8294, that has a fix ready to merge

**Closed by koke** 2017-12-13 20:26 UTC
Labels: Aztec, [Pri] High, [Type] Bug

**Comment by brbrr** [comment] 2017-12-14 06:40
Forgot to add bug label, sorry :(
