### ISSUE TITLE
Editing posts sometimes appearing with unsaved changes and sometimes not

### ISSUE THREAD

**Issue by charliescheer** [wordpress-mobile/WordPress-iOS#9614] opened 2018-06-19 17:16 UTC
Hey y'all, I stumbled onto this while testing 10.3.  This problem seems to be intermittent, and I have not been able to identify a common thread between the posts that do or do not do this...  

What I noticed was that sometimes (maybe 60% of the time) when I would go to Blog Posts and then select a post to edit, when the edit view loaded the post was automatically marked as having changes.  So the app acted accordingly, highlighting the update button and when I tried to exit the post I was getting the unsaved changes alert, and being asked to discard the changes. Here is a video that shows this behavior, starting with a post that does not display this and then moving to a post that does.

<a href="http://cld.wthms.co/brn5YY">video</a>

As I mentioned I have not been able to identify what makes some of these posts have this problem and some not, but it does seem to be consistent that it is certain posts with this problem.
To reproduce (keeping in mind that it is intermittent)
1. Go to My Site > Blog Posts
2. Check a few different already published posts
3. When you open the edit for one of the posts check to see if update is highlighted even before you make a change.

WordPress 10.3
iOS 11.4
iPhone 6s

**Comment by rachelmcr** [comment] 2019-02-18 10:46
This happens to me frequently these days. I also am not seeing it for every post, and there isn't an exact pattern, but it seems to happen mainly (if not always) with posts created on the web and then opened in the app.

I just saw it happen with a post that had nothing but a photo in it. I saved the post and checked the revisions history, and the change was related to the order of the attributes in the img tag. This was the post content HTML before:

```
<img class="alignnone size-full wp-image-1386" src="https://doalittletest.files.wordpress.com/2018/12/file000163792294516219938169938417995.jpg" width="1600" height="1200" />
```

And after opening it and updating it in the app:

```
<img src="https://doalittletest.files.wordpress.com/2018/12/file000163792294516219938169938417995.jpg" class="alignnone size-full wp-image-1386" width="1600" height="1200" />
```

**Comment by ceyhun** [comment] 2021-03-31 18:05
I was only able to reproduce with the **Classic editor** and **not** with Gutenberg editor.

<p style="clear:both;"><sup>Tested with iPhone 11 Pro, iOS 14.4, WPiOS 17.0.0.20210329</sup></p>

**Comment by ceyhun** [comment] 2021-04-01 09:58
Closing this Classic editor issue since the Classic editor is being deprecated on mobile at the time of writing. That said, if you find the issue occurring in the block editor as well, please feel free to open and repurpose, thanks!

**Closed by ceyhun** 2021-04-01 09:58 UTC
Labels: Posting/Editing, [Type] Bug
