### ISSUE TITLE
Attached image not in a gallery is used as a featured image

### ISSUE THREAD

**Issue by naokomc** [wordpress-mobile/WordPress-iOS#3612] opened 2015-05-04 01:40 UTC
When you have an attached image which is not inserted a post, it shows up as a featured image on the iOS app. This seems to happen only when other images are added to the post as a gallery.

Steps to reproduce:
1. Upload 3 images.
2. Create a gallery with 2 of the images, leaving the last uploaded image.
3. Publish the post.
4. View the post on your Reader feed. The last image which in not included in the post will show up as a featured image.

**Comment by aerych** [comment] 2015-05-27 20:02
Nice catch Naoko.

**Comment by rachelmcr** [comment] 2015-11-30 14:49
I tested this issue in beta v. 5.8.0.20151124 and confirmed that it is still an issue there.

**Comment by hoverduck** [comment] 2017-01-24 15:03
Unable to reproduce with v6.8.0.20170112; Closing

**Comment by aerych** [comment] 2017-01-24 16:46
Heya @hoverduck. :) I can still reproduce this one so let's keep it open.  
The steps I use to reproduce: 
1. Start a new post, add a title and some text.
2. In the editor, choose the option to add media.
3. Choose the option to upload a new image and insert it into the post.  This step attaches the image to the post.
4. Now that the image has been inserted into the post, delete the image. 
5. Publish.

Even though the image was removed from the content it still is attached to the post and is included in the post's attachments dictionary when the post is fetched from the REST API. 

Nick and I chatted about this one recently.  We want to continue checking the attachments dictionary because size information is included there, but we're planning to add an additional check to confirm an attachment is present in the post content.

**Closed** 2017-01-25 22:06 UTC
Labels: Reader, [Pri] Low, [Type] Bug
