### ISSUE TITLE
When viewing a post in a UIWebView comments can not be submitted.

### ISSUE THREAD

**Issue by charliescheer** [wordpress-mobile/WordPress-iOS#10262] opened 2018-10-16 17:46 UTC
I noticed recently if you try to view a post from the My Sites > Blog post page, in the UIwebview you can not actually submit a comment.  Everything acts the way it would in a web browser but when you click on the submit button nothing happens.  I have tried this with anonymous and not anonymous comments, and the result was the same, when you click on the submit comment button nothing happens.

Here is a quick video of the problem:
http://cld.wthms.co/w6d8Zo+

To test this:
1. Go to My Site > Blog Posts > and click on View for an already published post on the test site. (make sure to choose a site that does not allow for anonymous posting)
2. When viewing the page, scroll down to the comments section, write up a comment
3. Click on submit a comment and the button will react but nothing will happen.

**Comment by rachelmcr** [comment] 2018-10-17 08:56
I'd like design input on this, as the post view/preview is meant to show you how the post looks but wasn't meant for further user interactions (such as leaving comments). It's expected that comment replies/management will happen in native views in the app.

If you tap on a link in the post view/preview it opens in the device browser. Could we do something similar for handling when someone tries to submit a comment there?

**Comment by charliescheer** [comment] 2018-10-17 15:50
One thing that I found to be odd when I was testing this is if you go to the Reader and then view a post, it looks/feels similar to viewing the post from Blog posts (as in a web view appears) and from the reader you can comment, it was only from Blog Post > view that I was coming across this problem

**Comment by megsfulton** [comment] 2019-04-29 19:13
This appears to be related to Android issue #9649

Following up here too. Recommending that we change the behavior for viewing published posts to show the published post view and not the ?preview=true view.

**Comment by diegoreymendez** [comment] 2019-09-03 18:27
I'm adding this to the "Migrate to WKWebView" project in case we can manage to sort this out with the migration.

If that's not the case we may eventually move this out again, but I think it's worth reviewing this anyway.

**Comment by designsimply** [comment] 2019-11-13 23:11
I accidentally created a duplicate of this issue at https://github.com/wordpress-mobile/WordPress-iOS/issues/11926 and am copying that report here:

Steps to reproduce:

1. Open the WPiOS app and log in to a WP.com account.
1. Go to My Sites > Blog Posts > View on a site with comments allowed.
1. Check the comment form to see if you are recognized as a logged in user (ref: https://github.com/wordpress-mobile/WordPress-iOS/issues/11414).
1. Try to leave a comment and then verify whether or not it was saved.

<strong>Result:</strong> the comment form recognizes that I am logged in but posting a comment does not go through. ([1m5s](https://cloudup.com/c7C2sAiY_Jq))

<img src="https://user-images.githubusercontent.com/1119271/59473104-25fc1d80-8dfe-11e9-9fe7-4495cbf92d4b.png" width="270" alt="comment-test-via-webview-wpios-12 5 1">
<sup>Tested with WPiOS 12.5.1 (currently latest app store version) on iPhone 6S iOS 12.3.1</sup>

**Comment by designsimply** [comment] 2019-11-13 23:15
From a support chat dated 11:18 am, April 3rd 2019:

> I’m the Admin of my site and even though I’ve logged in, I’m now being asked to provide my name/email when I comment on a post. Also, when I click the “like” button the screen flashes but no ‘like’ shows up. This is a new development since the forced logout-update of the app this week. This appears to be some bug in the app.

<sup>(internal reference: 10763120-hc, 1935298-zen, 2107412-zen)</sup>

**Comment by diegoreymendez** [comment] 2020-02-07 00:09
I'm moving this out of the WKWebView migration project, as the project doesn't include the migration of the post preview VC.

**Comment by ScoutHarris** [comment] 2021-03-26 22:02
This appears to have been resolve at some point. Tested in 17.0. I am able to successfully comment from Blog Posts > View.

**Closed by ScoutHarris** 2021-03-26 22:02 UTC
Labels: Comments, Webviews, [Type] Enhancement
