### ISSUE TITLE
Style: Authenticator is missing styles when launched to fix an broken auth token.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#12547] opened 2019-09-24 16:26 UTC
There is a scenario where the Authenticator can appear but be missing some styling.  The navbar and lower right button are the main offenders. Check it out: 
![Simulator Screen Shot - iPhone 8 - 2019-09-24 at 10 45 16](https://user-images.githubusercontent.com/1435271/65530510-b77b3100-debd-11e9-9b44-f84dd6ee6108.png)

To reproduce try the following:

- Start logged into the app
- You want to clear your existing auth token. One way to do this is set a break point in the [BlogListViewController setEditing:], go to the My Sites tab and view the blog list. Tap the Edit button. Then run po [WordPressAuthenticationManager showSigninForWPComFixingAuthToken];.
- Close and relaunch the app.
- Note that the navbar style is wrong.  When you enter your password to login you'll see the button style is also wrong.

**Comment by bjtitus** [comment] 2020-01-02 19:12
I believe this was fixed by https://github.com/wordpress-mobile/WordPress-iOS/pull/13153. I am unable to reproduce locally.

**Comment by aerych** [comment] 2020-01-02 19:24
Awesome! Feel free to close!

**Closed** 2020-01-02 19:47 UTC
Labels: General, Low Hanging Fruit, [Type] Bug
