### ISSUE TITLE
WPContentCell not laying out properly when data updated

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#1633] opened 2014-04-28 20:53 UTC
When the data behind a WPContentCell is updated (and the cell is currently visible) the cell's interior components are not resized.  This includes the age (related #1185) and the title of the post.  To reproduce:

1. View the posts for a Blog.
1. Create a new draft (either on device or via web).  Draft should appear at the top of the list.
1. Log in via web and update the title.  Example: Pickles Uno to Pickles UnoDos (text must be visually longer).  Save the draft.
1. Pull to refresh on the device.
1. Notice the title is missing UnoDos (if my example is used) and only Pickles is showing.  The UILabel is truncating the last word due to it not being resized.
1. Scroll down a screen if possible and scroll back up.  Notice the label is showing the proper title.

**Comment by rachelmcr** [comment] 2015-12-15 17:36
It looks like WPContentCell was nuked in #4152, and I confirmed that the original steps no longer reproduce the issue.

Closing as resolved.

**Closed by rachelmcr** 2015-12-15 17:36 UTC
Labels: General, [Type] Bug
