### ISSUE TITLE
Activity Log shows strings in account language

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/WordPress-iOS#9937] opened 2018-08-08 14:52 UTC
### Expected behavior

All the strings in the activity log should show in the device language

### Actual behavior

Some strings are translated to the account language.

### Steps to reproduce the behavior

1. Set your account language to Spanish
2. Visit the activity log
3. See some translated strings (e.g. "Actualizaciones de tema disponibles")

**Comment by jklausa** [comment] 2018-08-21 21:15
x-reported to automattic/wp-calypso as https://github.com/Automattic/wp-calypso/issues/26814

**Comment by jklausa** [comment] 2018-08-21 21:15
(We're already sending the locale argument as part of the request payload)

**Comment by jklausa** [comment] 2019-04-16 23:15
This is (sorta) a duplicate of #9818, which will be closed by #11479

**Closed by jklausa** 2019-04-16 23:15 UTC
Labels: Activity Log, [Type] Bug, i18n
