### ISSUE TITLE
Reader: Horizontal rule (separator) rendered with inconsistent weight

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#13410] opened 2020-02-10 17:52 UTC
### Expected behavior

I expect the horizontal rule (separator block in the block editor) to be rendered in the Reader with a consistent weight.

### Actual behavior

The left end is thicker than expected, and the right end is thinner than expected:

<img src="https://user-images.githubusercontent.com/8658164/74175515-e7895d80-4c2d-11ea-817c-1c4365396e38.PNG" width="50%">

### Steps to reproduce the behavior

1. Create a new post with a separator block.
2. Publish the post and view it in the Reader.

##### Original report in p4a5px-2v3-p2

**Comment by leandroalonso** [comment] 2021-03-25 16:41
After Reader Detail refactor, the issue is now fixed.

**Closed by leandroalonso** 2021-03-25 16:41 UTC
Labels: Mobile Request, Reader, [Type] Bug
