### ISSUE TITLE
Image Upload Problems

### ISSUE THREAD

**Issue by azollafox** [wordpress-mobile/WordPress-iOS#14561] opened 2020-08-03 15:31 UTC
### Expected behavior
When a feature image is added it should upload successfully to the post when published

### Actual behavior
>when we try to post featured image .. it shows the the upload done successfully however when we publish the post it doesn’t appear so when again we go back to edit we could not see the featured image so we have to upload it again ..

### Steps to reproduce the behavior
Not reproduced yet

#####Tested on iPad 7, iOS 13.5.1, WPiOS 15.3
User reported on 15.2 on multiple devices

#3189303-zen
#3175647-zen

**Comment by designsimply** [comment] 2020-08-04 02:22
Noting the site types and editors in use (at least according to the logs sent at the time the tickets were created) for reference:

* 3189303 - Atomic, Gutenberg
* 3175647 - Jetpack Personal, Aztec (note: they said they are having similar upload problems in Media as well)

And here are some of the snippets from the app logs mentioning media errors in case they're helpful:

```
2020-07-31 22:24:43:209 🔵 Tracked: editor_session_start <blog_type: jetpack, content_type: gutenberg, editor: gutenberg, has_unsupported_blocks: 0, post_type: post, session_id: 9381F1FE-72CF-4135-83F5-EBB265D694E6, startup_time_ms: 928, unsupported_blocks: (
)>
2020-07-31 22:24:48:471 <PostSettingsViewController: 0x10349e800> viewDidLoad
2020-07-31 22:24:48:472 🔵 Tracked: post_settings_shown <>
2020-07-31 22:24:53:749 🔵 Tracked: editor_post_featured_image_changed <action: removed, via: settings>
2020-07-31 22:24:54:613 <WordPress.WordPressAppDelegate: 0x281003400> applicationWillResignActive(_:)
2020-07-31 22:24:55:083 Stats Period: finished persisting Period Stats to disk.
2020-07-31 22:24:55:708 <WordPress.WordPressAppDelegate: 0x281003400> applicationDidEnterBackground(_:)
2020-07-31 22:24:55:717 🔵 Tracked: application_closed <last_visible_screen: Post Editor, time_in_app: 17>
2020-07-31 22:24:55:721 PingHub disconnecting
2020-07-31 22:24:56:218 PingHub disconnected: WSError(type: Starscream.ErrorType.protocolError, message: "", code: 1000)
2020-07-31 22:24:56:223 🔵 Tracked: media_service_upload_started <blog_id: 178491266>
2020-07-31 22:25:12:057 <WordPress.WordPressAppDelegate: 0x281003400> applicationWillEnterForeground(_:)
2020-07-31 22:25:12:057 PingHub connecting
2020-07-31 22:25:12:352 <WordPress.WordPressAppDelegate: 0x281003400> applicationDidBecomeActive(_:)
2020-07-31 22:25:12:355 checkAppleIDCredentialState: No Apple ID found.
2020-07-31 22:25:12:360 🔵 Tracked: application_opened <>
2020-07-31 22:25:12:708 PingHub connected
2020-07-31 22:25:18:116 🔵 Tracked: editor_post_featured_image_changed <action: added, via: settings>
2020-07-31 22:25:30:640 🔵 Tracked: editor_post_update <blog_id: 178491266, editor_source: gutenberg, has_gutenberg_blocks: 1, post_id: 12837, post_type: post, word_count: 25>
2020-07-31 22:25:32:956 Error in updateMediaForPost while uploading post. description: An error occurred when attempting to attach uploaded media to the post.
2020-07-31 22:25:35:984 🔵 Tracked: post_epilogue_displayed <>
2020-07-31 22:25:37:183 🔵 Tracked: post_epilogue_view <>
2020-07-31 22:25:37:200 🔵 Tracked: web_preview_opened <blog_type: jetpack, post_type: post>
2020-07-31 22:25:45:504 🔵 Tracked: post_epilogue_edit <>
2020-07-31 22:25:45:512 Returning existing revision
```

```
2020-08-03 10:04:26:538 🔵 Tracked: editor_post_created <blog_id: 1075085, post_type: post, tap_source: create_button>
2020-08-03 10:04:26:872 🔵 Tracked: editor_session_start <blog_type: jetpack, content_type: new, editor: classic, has_unsupported_blocks: 0, post_type: post, session_id: A8FE8612-C9FB-4FA8-9EFC-039764D4804F, startup_time_ms: 38, unsupported_blocks: (
)>
2020-08-03 10:04:29:015 🔵 Tracked: media_service_upload_started <blog_id: 1075085>
2020-08-03 10:04:32:595 <PostSettingsViewController: 0x10849da00> viewDidLoad
2020-08-03 10:04:32:598 🔵 Tracked: post_settings_shown <>
2020-08-03 10:04:52:233 🔵 Tracked: editor_session_end <blog_type: jetpack, content_type: new, editor: classic, has_unsupported_blocks: 0, outcome: discard, post_type: post, session_id: A8FE8612-C9FB-4FA8-9EFC-039764D4804F>
2020-08-03 10:04:52:242 🔵 Tracked: editor_discarded_changes <blog_id: 1075085, editor_source: aztec, has_gutenberg_blocks: 0>
2020-08-03 10:04:52:274 🔵 Tracked: editor_closed <blog_id: 1075085, editor_source: aztec, has_gutenberg_blocks: 0>
```

**Comment by rossanafmenezes** [comment] 2020-08-05 13:38
User on ticket 3189303-zen has replied with the logs after the issue occurs. 

This seems to be the a similar issue https://github.com/wordpress-mobile/WordPress-iOS/issues/12729

**Comment by JavonDavis** [comment] 2020-08-05 18:22
User on ticket 3189303-zen has replied with additional logs after the issue happens

**Comment by designsimply** [comment] 2020-08-08 00:48
Thanks for the eagle eye on #12729 @rossanafmenezes. One difference between the two issues is that 12729 mentions featured images fail to upload at all and the post cannot be published while this issue mentions the featured image does appear to upload and they are able to publish the post but then the featured image doesn't show up in the app afterward. Very strange indeed. This case needs more investigation.

**Comment by rossanafmenezes** [comment] 2020-09-04 12:00
The user came back with some more info on ticket 3283407-zen

They say they can upload image from the media library but takes forever, but when they upload it from the post it does not work. Other employees using iPhone have the same issue. They have also added some screenshots to the ticket. 

cc @guarani

**Comment by erricgunawan** [comment] 2020-09-13 01:58
User on 3283407-zen is back with more info:

> Just want to add this below image shows that the image from (a) block is also not working ! So now i can confirm both featured image and add from block image both get stuck

> And even when it shows completely posted when i publish the post it shows empty

**Comment by mchowning** [comment] 2020-09-21 22:17
A similar issue reported at https://github.com/wordpress-mobile/WordPress-iOS/issues/13208#issuecomment-695069425.

**Comment by mchowning** [comment] 2020-09-21 22:40
> now i can confirm both featured image and add from block image both get stuck

Updated the issue title to reflect that this is not limited to the feature image.

**Comment by cameronvoell** [comment] 2020-09-22 21:56
I tried to recreate this issue and was unsuccessful. Documenting what I tried here so others are aware:

Featured Image (also tried stesp from Steps from: https://github.com/wordpress-mobile/WordPress-iOS/pull/9570):
1. Add new article with title and content
2. Settings => Featured Image
3. Upload new Image
4. Publish

Image Block:
1. Add Image Block to new article
2. Upload new image from device
3. Publish

Tested on Wordpress.com hosted and a self hosted jetpack connected site
Tested on iPhone XR iOS 14, and iPad Pro iOS 13.5.1
Tested on WordPress iOS 15.6
Tested with images from 1MB to 8MB in size

* One thing I noticed was that a self-hosted site I was testing with had a 2MB limit for uploading photos, and the messaging around that wasn't always super clear.

**Comment by bummytime** [comment] 2020-10-07 17:08
I am removing the high-pri status from this issue. We will potentially add this issue to a "Media improvements" project starting in the near term.

**Comment by ccwalburn** [comment] 2020-10-21 22:14
User from 3283407-zen has contacted us again on 3426699-zen with a request for a fix

**Comment by guarani** [comment] 2020-10-22 15:27
> User from 3283407-zen has contacted us again on 3426699-zen with a request for a fix

Thanks for the update! I had a read of the new Zendesk ticket now and can understand the user is waiting for a fix. 

Although we couldn't reproduce this [earlier](https://github.com/wordpress-mobile/WordPress-iOS/issues/14561#issuecomment-697003805), I tried again just now by testing featured images on:
- WordPress.com Simple sites
- WordPress.com Atomic sites
- Jetpack connected self-hosted site
- Plain self-hosted sites (accessed via their credentials, not Jetpack)

And I still couldn't reproduce this bug. Every time I set a featured image on a post and published the post, I could see the featured image when previewing the post, and if I opened the editor again, I could see the feature image was still set in Post Settings. These Zendesk tickets also mention the Image block, but I haven't seen any issues with it lately (and neither were issues found when testing [earlier](https://github.com/wordpress-mobile/WordPress-iOS/issues/14561#issuecomment-697003805)). 

---

Without us being able to reproduce this, it's difficult to identify what the problem is. I think this issue will need more investigation, but I wanted to share this status as-is to communicate where we are on the developer side of things with regard to this issue.

A possible lead is that the user is backgrounding the app during upload (as evidenced by `application_closed` in the logs [above](https://github.com/wordpress-mobile/WordPress-iOS/issues/14561#issuecomment-668341682)) and is on a poor network connection, which would make this somewhat similar to the [Unable to upload large video issue](https://github.com/wordpress-mobile/WordPress-iOS/issues/15032#issuecomment-714553350). However the error here is "An error occurred when attempting to attach uploaded media to the post." while the error in that issue is "The network connection was lost.". Also, it appears that featured images in this issue appear to load correctly but upon revisiting the post they are no longer present, while on https://github.com/wordpress-mobile/WordPress-iOS/issues/15032 the media upload fails outright.

**Comment by guarani** [comment] 2021-05-31 22:13
Un-assigning myself since I haven't been working on this and have no immediate plans to.
cc @SiobhyB, I just thought I'd ping you here in case you have experienced this bug while working on Featured Image Support inside the block editor and had any insights.

**Comment by SiobhyB** [comment] 2021-06-04 14:47
@guarani, I haven't come across similar in my testing and wasn't able to find any recent reports that were similar to this for iOS in Zendesk (after searching for `"featured image" tags:ios order_by:created_at sort:desc`). From reading through this thread and the main referenced ticket, I'd agree that there currently isn't enough to go on to reproduce this and there's probably a good case for closing this ticket.

**Comment by guarani** [comment] 2024-01-31 23:26
This issue is mentioned in this app review: https://appfigures.com/reviews/334311506925L5kaPGzna25Oxj85PxXKqeg?lang=en

**Comment by twstokes** [comment] 2024-02-15 20:07
This issue feels too broad to appropriately address. I propose we close it and open future issues that are specific and preferably reproducible. Recent work has been done to connect site types to media upload failures, so that will be helpful.

**Closed by twstokes** 2024-02-15 20:07 UTC
Labels: [Type] Bug, [Pri] Medium, Media, Post Settings, [Status] Needs Testing, Linked to App Review
