### ISSUE TITLE
Posting/Editing: Audit & improve error messages

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#10663] opened 2018-12-14 18:37 UTC
We should audit the errors we show while posting/editing in the app to look for:

* Improvements to the wording (less scary, more actionable)
* Unclear errors, especially where server errors could be handled better (replaced with human readable messaging, perhaps with the server error included in the app log)
* How error notifications are handled (e.g. when you resolve the error)

Examples that @m shared:

1. Upload failed notification
- Message "1 post, 1 file not uploaded" is unclear
- Notification persists even after a successful upload

![image from ios 5](https://user-images.githubusercontent.com/8658164/50020710-c2b83c80-ffce-11e8-8877-0b90d29b5511.jpg)

2. Media upload failure in editor
- "Media Options" header doesn't make sense
- API error is unclear and not actionable

![image from ios 6](https://user-images.githubusercontent.com/8658164/50020800-09a63200-ffcf-11e8-9285-06e85f323be6.jpg)

**Comment by elibud** [comment] 2018-12-17 17:17
@kwonye can you take care of this one during Hackweek please?

**Comment by kwonye** [comment] 2019-03-25 18:32
Sorry I dropped this. I'll be picking it up this week before I head out and handing it to the appropriate person.

**Comment by diegoreymendez** [comment] 2019-06-05 19:17
We're going to start by fixing the specific examples that were reported in this issue, and then spawn new issues for anything else that we find in terms of messaging.

**Comment by thehenrybyrd** [comment] 2019-07-21 10:10
Ran into this in #2195107-zen, particularly the unclear "Message "1 post, 1 file not uploaded" message.

> I noticed an error saying that my post isn't uploaded but it doesn't tell me which post it is.

![uploaderror](https://user-images.githubusercontent.com/15107387/61589833-7eba9500-abb8-11e9-8f60-aff839fed474.png)

It would be great if we could include the post's title and/or specify the type of file we're having trouble. For instance, we could say "We couldn't upload Post Title because a Video File ..." (was too big, took too long, etc.) 
It might also be helpful to tell them what to try, such as "Try again on a stronger connection" or similar.

**Comment by nheagy** [comment] 2019-07-24 21:49
I added the tag `Needs Design` because I feel we need a reference point to know _what_ to implement here.

**Comment by yaelirub** [comment] 2019-08-15 02:11
@osullivanchris , can we get your input / ideas on this?

This issue should be split so I'm marking it as 13. 

Let's start with the "1 post, x files not uploaded" message and refer to the suggestion from this comment: https://github.com/wordpress-mobile/WordPress-iOS/issues/10663#issuecomment-513540908

**Comment by diegoreymendez** [comment] 2019-08-29 11:38
I agree with @yaelirub that this issue should be split AND that we should start with the "1 post, x files not uploaded" since it feels so broken.

The different scenarios I think we need to consider for this message's review are:

1. App is online, upload fails.
2. App is offline, upload fails but we'll retry.
3. App is offline, upload fails and it won't be retried.
4. No upload was attempted but the upload was cancelled since 48hs passed and the device is still offline.  I believe this case could be really tricky to implement and fairly rare... so it may make sense to ignore thiis one for now.

@osullivanchris - Any updates on this?

**Comment by osullivanchris** [comment] 2019-08-30 08:50
Thanks for the ping @diegoreymendez . Bit of a verbose relpy to follow but this touches on a few topics.

**Existing Improvements**

I spent some time reviewing offline error messages with @malinajirka yesterday. We have made significant improvements to error messages making them more meaningful and actionable.

E.G. when the user tries to publish offline; rather than a blocking error, the user is now told that the post _will be published_ when connection returns. And they can cancel it if they wish. That gives them

- information on the current status 
- the promise of a positive outcome
- sets clear expectations about what's going to happen
- the option to opt-out and resolve it manually as they wish

That's the type of error handling we can all be happier with. And that's the direction we're hopefully heading in (which didn't exist when this issue was opened)

**Generally - auditing and improving error messages**
- I wonder how many of these we already improved as part of offline project. That should ship on Android soon. We're not quite ready to ship on iOS yet.
- If a developer could pair with me to do the audit (quite hard to have visibility without digging into the code) we could categorise and improve 1 by 1. Agree with @diegoreymendez and @yaelirub that it could be an epic with individual messages as issues. As a designer I would actually like to address it at that epic level to understand differences and get consistency. Then we could pick them off 1 by 1. 
- We did not address **multiple** errors in the offline project. I am not familiar with the grouping logic that we have. But as a general point, while giving the user 1 message bout 3 things rather than 3 separate messages is tidier, it does mean that the 1 message needs to be generalised a little to apply to all 3 cases.
- **NB** We have an issue with media errors right now on Android, I'm guessing it might be the same on iOS. The issue is that we can't differentiate between connection errors and other errors. That makes it hard to provide specific information. E.g. we could say 'we'll upload this file when your device is online' but thats gonna be weird if you're actually online and the issue was a corrupt media file. So to really make improvements with media errors we would need to break out those issues, and understand why media failed. I don't know how big a task that is, but it was one that we felt we couldn't address in offline so it must be complex.

**Specifics on the '1 post, x files not uploaded' case**
- I have tried to reproduce this on iOS. From the screenshot I imagined this involved a user uploading both a post and X number of files/images. 
- However I just tried to upload 4 images while online, turned on airplane mode, and got this error
- So in my opinion this specific case might not even be a copy improvement, its just a bug
- I need someone to dig into the code and find out where this error is. But if it is only used for media uploads we could change it to say 'N images not uploaded', 'N videos not uploaded' or 'N images and N videos not uploaded'

**Specifics on the 'Media upload failure in editor'**
- I am no longer seeing the subheading about the API issue
- it has also changed to have an 'edit' option rather than 'retry'. That's quite nice because you can set the alt text and layout for an image while waiting for it to upload
- Following that line of thought, it would be nice to make the error a bit softer. Per the offline project we want to make things feel like they work while offline. So ideally I would change it to not look broken, but rather have a smaller label or something saying "Image will be uploaded when connection returns". Then it would be a quite nice experience where you can organise photos for your blog post while offline, organise and edit them. And its made clear that ok its not uploaded yet, but we'll do it automatically when you do come online. 
- That's the kind of experience I'd like to provide here - but its limited by the point I wrote about in **NB** above

**Comment by yaelirub** [comment] 2019-09-05 22:39
@osullivanchris , I'd be happy to pair with you on this. 
A few comments:

* I honestly think that most of the issues in this ticket have been improved with the work we've done on offline support. 

* I realize that figuring out the source of media upload failure is  an obstacle in away but maybe we can work around it while still remaining true to our principals. 

* I'd like to come back to this issue once we're unblocked by the current media issues.

**Comment by jinnypark** [comment] 2021-03-03 21:29
I was beta testing WordPress iOS app and went down the rabbit hole from ambiguous error messages. This was for a self-hosted, jetpack-connected wp.org sites.
p4a5px-2HO-p2

- [failed to insert media](https://mobilerequests.files.wordpress.com/2021/01/img_8364.png) error message: this error message was caused by a broken jetpack connection, which is hard to figure out.
- [Frozen loading page](https://user-images.githubusercontent.com/15963276/109873737-2bd20c00-7c3c-11eb-84e0-079244f1e5be.png) for post editing. I was not able to figure out what was causing this (jetpack connection was solid), but updating to Jetpack 9.5, and disconnecting/reconnecting Jetpack solved the issue. I was not able to recreate this issue, unfortunately.

**Comment by kean** [comment] 2024-05-01 17:04
Improving the error handling was one of the major goals of pcdRpT-6vS-p2:
- Publishing now happens synchronously and the errors are timely; the notification was removed
- Auto-upload for publishing was removed, so you can't never be in a scenario where there are multiple errors at once
- For media, there is an entire new "Media Uploads" screen with detailed information about the upload status, errors, and with options how to resolve them
And more...

**Closed by kean** 2024-05-01 17:04 UTC
Labels: [Type] Enhancement, [Pri] Medium, Posting/Editing, Design Needed, 13, User-Facing
