### ISSUE TITLE
My Site Dashboard: Check UI tests

### ISSUE THREAD

**Issue by momo-ozawa** [wordpress-mobile/WordPress-iOS#18187] opened 2022-03-23 00:06 UTC
### Description

Check if My Site Dashboard breaks UI tests when the dashboard is displayed. Fix UI tests if necessary.

**Comment by momo-ozawa** [comment] 2022-03-24 06:49
I set the MSD feature flag to always return true and tested the full UI test suite on both iPhone and iPad.

All the tests besides the ReaderTests are passing. The default section is always “site menu” when running the UITests -- this is probably because the mock auth token defined in WordPressMocks gets assigned to the control group. This explains why most of the tests are passing even with the MSD feature flag enabled.

iPhone 13 | iPad Air (4th gen)
-- | --
<img width="1071" alt="Screen Shot 2022-03-24 at 14 36 17" src="https://user-images.githubusercontent.com/6711616/159853027-15012fec-3843-47ef-bec9-8f254e9c2650.png"> | <img width="1072" alt="Screen Shot 2022-03-24 at 14 37 08" src="https://user-images.githubusercontent.com/6711616/159853033-29a676c2-3f4b-4a4f-b307-ab1600bd5a90.png">

The Reader tests (i.e. `testViewPost()` and `testViewPostInSafari()`) are failing because they're timing out on `LoginFlow.logoutIfNeeded`. 

<img width="882" alt="Screen Shot 2022-03-24 at 15 10 20" src="https://user-images.githubusercontent.com/6711616/159853463-bdbf1ec2-8bd7-4ace-9977-83a5b48b6f59.png">

Here's something I'm confused about the Reader tests:
- These tests are passing on Buildkite on the latest trunk (see: artifacts on the UITests for[ this job](https://buildkite.com/automattic/wordpress-ios/builds/6200#5e84b3e4-b166-436e-b92f-11fec541adb5)) 
- These tests are failing for me locally on the latest trunk (I'm on ef28092 which is the same commit as above... I also tested with the MSD feature flag disabled but still failing)

@tiagomar Tagging you since you added these tests and maybe you know something -- any ideas why this might be happening? 🤔

**Comment by tiagomar** [comment] 2022-03-24 22:17
Hey @momo-ozawa 👋 , I have no idea especially because `logoutIfNeeded()` is part of the `tearDownWithError()` for all the other tests that are passing for you. I'll try to run it locally and will let you know how it goes.

**Comment by momo-ozawa** [comment] 2022-03-24 23:39
Thanks @tiagomar! 

> I have no idea especially because logoutIfNeeded() is part of the setUp() for all the other tests that are passing for you

These were my exact thoughts as well. Plus, to add to the confusion... when you run the test you can clearly see the app logging out (~01:05 on the video).  But somehow the test times out and is retried twice more (for a total of 3 times) until it fails.


https://user-images.githubusercontent.com/6711616/160026595-78ffea8f-4d5c-4838-8075-a6180f86c8d7.mov

**Comment by momo-ozawa** [comment] 2022-03-25 01:43
@tiagomar 👋 

An update: I made a [test draft PR with MSD enabled](https://github.com/wordpress-mobile/WordPress-iOS/pull/18210) to trigger UI tests on Buildkite. The ReaderTests are [passing](https://buildkite.com/automattic/wordpress-ios/builds/6236#06a23f69-88bb-4d16-aca2-f173b5eea7d9)... 🙃 
I'm still confused about why the ReaderTests are failing locally 🤯

**Comment by tiagomar** [comment] 2022-03-25 14:40
@momo-ozawa 👋 

Thanks for the updates. I couldn't reproduce it locally but from your video we can see that the timeout happens before the prologue screen is displayed as seen in the picture below. There is not a big delay, it was actually hard to find the proper frame. 

![image](https://user-images.githubusercontent.com/42008628/160135494-c1fd467b-d12f-4c0d-95f0-66b7f576a61d.png)

My guess is that the time it takes from tapping the `Log out` button until we display the prologue screen has been around the limit of making the tests fail for a while. We may have not seen it happening that often in Buildkite either because, for some reason, it runs a bit faster there or it does happen but not consistently enough to fail all the three automatic retries in a row.

**Comment by leandroalonso** [comment] 2022-03-25 19:46
Given the Reader issue is not related and UI tests are green even with MSD I'm closing this issue. :)

**Closed as completed by leandroalonso** 2022-03-25 19:46 UTC
Labels: Testing, [Type] Task
