### ISSUE TITLE
The operation couldn’t be completed. (WordPressKit.WordPressComRestApiError error 7.)

### ISSUE THREAD

**Issue by loremattei** [wordpress-mobile/WordPress-iOS#13953] opened 2020-04-21 14:22 UTC
**Sentry Url**: https://sentry.io/share/issue/9ff043231d4c4b978ff53ddb3c367c3b/

**User Count**: 27
**Count**: 122
**First Release**: 14.6.0.0
**First Seen**: 2020-04-08T16:22:24Z
**Last Release**: 14.6.0.3
**Last Seen**: 2020-04-21T14:10:23Z
**24 Hours**: 97
**30 Days**: 122

```
The operation couldn’t be completed. (WordPressKit.WordPressComRestApiError error 7.)

```

**Comment by yaelirub** [comment] 2020-04-22 01:06
Triage: Priority high by version.
Seems to be an issue in PreviewWebKitViewController or WebKitViewController
@bjtitus , would you  mind taking a look at this?

**Comment by bjtitus** [comment] 2020-04-24 16:51
It seems like the `unknown` `WordPressComRestApiError` comes from the Atomic authentication service (added in https://github.com/wordpress-mobile/WordPress-iOS/pull/13712) when it fails to fetch a cookie from the API. I tried on my own ephemeral atomic site and was unable to reproduce the issue.

@yaelirub Is there anyone familiar with the atomic stuff who might be able to take a look or provide some tips?

**Comment by yaelirub** [comment] 2020-04-24 16:56
Thanks so much for looking into this. I hope @aerych might be able to provide some help on this crash 🙏

**Comment by bjtitus** [comment] 2020-04-27 15:56
Here are a few updates on this from my investigation over the last few days:

- I was able to reproduce this error 100% of the time on a wordpress.com atomic site.
- To be clear, this is **NOT** a crash but is an error logged whenever the atomic proxy cookie fetch fails.
- I was unable to reproduce user facing bugs related to the cookie failure. The `frame-nonce` query parameter allows private page and post previews to be shown without the cookies. I'm not sure if there are cases where that parameter does not work.
- My best guess is that the required Jetpack xmlrpc method (`getReadAccessCookies`) isn't available on all instances yet.

### Details

Can reproduce by:
* Setting up an Atomic Site on WordPress.com
* Attempting to view any page or post preview on the blog.

Kibana/logstash shows the following logged from the cookie request:
```json
"url": "/wpcom/v2/sites/170037822/atomic-auth-proxy/read-access-cookies?_locale=en",
"@version": "1",
"message": "Auth failed: server error. requested method jetpack.getReadAccessCookies does not exist.",
```

Notice the `requested method jetpack.getReadAccessCookies does not exist`

**Comment by aerych** [comment] 2020-04-28 15:05
Thanks for wrangling this @bjtitus :) 
> My best guess is that the required Jetpack xmlrpc method (getReadAccessCookies) isn't available on all instances yet

Atomic privacy was rolled out to only a % of users so I think you're probably right here.  I'd expect this error to go away once its rolled out to everyone.

**Comment by frosty** [comment] 2020-04-29 13:00
Thanks @aerych! @bjtitus, let's make a note to re-review this after full support has been rolled out.

**Comment by designsimply** [comment] 2020-06-13 04:04
**Events in the last 90d:** 41,000
**Events in the last 11d for 14.9:** [48](https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=release&field=os&field=device&field=culprit&name=All+Events&project=1438083&query=issue.id%3A1538584086+release%3A14.9.0.4&sort=-timestamp&statsPeriod=30d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1) in 14.9 since it was released on 2020-06-01
**Users affected in the last 90d:** 3,800
<sub>https://sentry.io/share/issue/9ff043231d4c4b978ff53ddb3c367c3b/</sub>

Closing as resolved because these seemed to have stopped as of Jun 8 according to the [90-day graph for issue.id:1603264909](https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=release&field=os&field=device&field=culprit&name=All+Events&project=1438083&query=issue.id%3A1603264909&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1). 🎉

<img width="1029" alt="Screen Shot 2020-06-12 at Jun 12 10 01 34 PM" src="https://user-images.githubusercontent.com/1119271/84559502-697eb580-acf8-11ea-8fac-a4b2deb842c3.png">

**Closed by designsimply** 2020-06-13 04:04 UTC
Labels: Atomic, [Pri] High, [Type] Bug

**Comment by designsimply** [comment] 2020-06-17 18:12
Heads up, we're still seeing this error happen ~300 times per day in Japanese (looks like it's logged as a separate issue in Sentry). @frosty should I open a separate GitHub issue for this one? I'm not 100% sure how to prioritize since it's logging errors and not fatals/crashes.

> 操作を完了できませんでした。（WordPressKit.WordPressComRestApiErrorエラー7）

Errors in the last 90d: 58,000
Users affected in the last 90d: 5,600
<sup>https://sentry.io/share/issue/3da4662c65224346bb3a731c131df13d/</sup>

<img width="1030" alt="Screen Shot 2020-06-17 at Jun 17 12 09 24 PM" src="https://user-images.githubusercontent.com/1119271/84933627-6b979a00-b093-11ea-911a-34d9ac250f9f.png">

**Comment by aerych** [comment] 2020-06-19 16:16
I've dug into this a bit.  The issue looks like a server side matter. There is some expected jetpack functionality that is missing for some reason and this results in an error being returned for the user. I'll post findings and update this comment with a reference.
