### ISSUE TITLE
Posting: Publish immediately doesn't work when post is created/edited in app but published on web

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#10188] opened 2018-09-21 11:19 UTC
### Expected behavior

If I have a draft set to publish immediately, it should always be published with the current date/time, regardless of when I created or edited it.

### Actual behavior

Posts created or edited in the app, and then published on the web, have the publish date set to the creation date instead of immediately.

More discussion here: https://github.com/Automattic/wp-calypso/issues/9014#issuecomment-417249276

Publish date gets tricky, though, and we should keep in mind past issues related to setting the publish date, e.g. https://github.com/wordpress-mobile/WordPress-iOS/issues/6113, https://github.com/wordpress-mobile/WordPress-iOS/issues/5350, https://github.com/wordpress-mobile/WordPress-iOS/issues/3516.

### Steps to reproduce the behavior

Created in the app:
1. Create a post draft in the app and confirm it is set to publish immediately.
2. Open the draft on the web to edit it, and note the publish date setting.
3. Publish the post.
Result: The post is published with the creation date instead of the current date.

Edited in the app:
1. Create a post draft on the web.
2. Open the draft in the app.
3. Make a change and update the draft in the app.
4. Open the draft again on the web, and note the publish date setting.
5. Publish the post.
Result: The post is published with the creation date.

Related Android issue: https://github.com/wordpress-mobile/WordPress-Android/issues/7729

**Comment by nerdysandy** [comment] 2021-02-10 21:13
Closing it as duplicate of https://github.com/Automattic/wp-calypso/issues/9014

**Comment by ceyhun** [comment] 2021-03-31 18:24
I was not able reproduce this with a very old draft I created in the app. I published it on the web and date was correct. It was the current date. Also tried editing a post created on web in the app and then publishing and still couldn't reproduce.

<p style="clear:both;"><sup>Tested with iPhone 11 Pro, iOS 14.4, WPiOS 17.0.0.20210329</sup></p>

**Comment by ceyhun** [comment] 2021-04-01 09:59
Closing this as non reproducible but, please feel free to reopen if it still occurs, thanks!

**Closed by ceyhun** 2021-04-01 09:59 UTC
Labels: Posting/Editing, [Type] Bug
