### ISSUE TITLE
[GlobalStep] [iPad] Label for "Change Visibility" button appears truncated.

### ISSUE THREAD

**Issue by gglobalstep** [wordpress-mobile/WordPress-iOS#14081] opened 2020-05-07 17:52 UTC
Environment:
iOS:  iPad (6th Gen)-v12.4, iPad Air 2(v13.3.1)

Steps To Reproduce:
 
 1. Install and launch the application.
 2. Tap on "Log In".
 3. Log in to the app using valid credentials.
 4. Open "My site" tab.
 5. Tap on "Switch Site" in top right hand corner.
 6. Tap on Edit option.
 7. Observe that "You have 1 hidden Wordpress site" appears with "Change Visibility" button appears truncated.

 Actual Result:
Label for "Change Visibility" button appears truncated

 Expected Result:
Upon tapping My Site>Switch Site>Edit>"Change Visibility" button label should appear properly.

[#14081.zip](https://github.com/wordpress-mobile/WordPress-iOS/files/4594824/14081.zip)

**Comment by designsimply** [comment] 2020-05-13 05:30
Tested and confirmed that the "Change Visibility" button text is truncated in the splitscreen view in portrait orientation for the My Site > Switch Site > Edit panel if all sites for the account are hidden. Landscape orientation looks good in comparison.

Portrait orientation | Landscape orientation
---|---
<img src="https://user-images.githubusercontent.com/1119271/81774519-f9d29c00-94a7-11ea-87d4-c3571b6ea2f5.PNG" height="250" alt="IMG_0362">|<img src="https://user-images.githubusercontent.com/1119271/81774514-f63f1500-94a7-11ea-9aaa-ab9f7c573811.PNG" height="250" alt="IMG_0361">

<sup>Tested with WPiOS 14.8.0.1 TestFlight beta on iPad Mini 4 (WiFi) (iPad5,1) iPadOS 13.3.1.</sup>

**Comment by designsimply** [comment] 2020-05-13 05:33
Labeling as low priority because it's probably not very common to have all sites hidden for most active user accounts and because it doesn't block the function of the button.

**Comment by kean** [comment] 2024-09-12 17:37
Fixed in 25.4.

**Comment by dangermattic** [comment] 2024-09-12 17:38
Thanks for reporting! 👍

**Closed by kean** 2024-09-12 17:37 UTC
Labels: [Type] Bug, [Pri] Low, Site Management
