### ISSUE TITLE
Content of notifications is not localised

### ISSUE THREAD

**Issue by ctarda** [wordpress-mobile/WordPress-iOS#9813] opened 2018-07-20 03:48 UTC
![img_2907](https://user-images.githubusercontent.com/2722505/42982111-4b288448-8c12-11e8-9e56-2f18c14b70bf.PNG)

### Expected behavior
Some of the content of the notifications should be localised. For example, if the system is in Spanish, a notification should not read as "J Johnson and 674 others liked your post....", but "Tu post le ha gustado a J Johnson y a otros 674 bloggers" (or similar)

### Actual behavior
The full content of the notifications is displayed in English

### Steps to reproduce the behavior
- Make sure your device's locale is not English
- Navigate to the Notifications tab
- Notice how the content of all notifications is in English

##### Tested on [device], iOS [version], WPiOS [version]
Tested on iPhone 7s Plus, iOS 11.4.1, WPiOS 10.4

**Comment by elibud** [comment] 2018-07-20 14:55
@dmsnell you are working on server side fix for this one right?

**Comment by dmsnell** [comment] 2018-07-20 15:47
> @dmsnell you are working on server side fix for this one right?

@elibud yesterday I removed the `note_hash` caching - we have one tiny little step left before the `locale` parameter will work

is mobile already sending it? if not, let's do that so it's automatically updated once the server starts accepting it

**Comment by elibud** [comment] 2018-07-20 17:17
I believe we are already sending it, @jleandroperez and @mzorz can you double check please?

**Comment by jleandroperez** [comment] 2018-07-23 13:46
I'm afraid iOS is still [not sending the locale](https://github.com/wordpress-mobile/WordPressKit-iOS/blob/develop/WordPressKit/NotificationSyncServiceRemote.swift#L138) (issue still stands). 

I'll make sure to squeeze the patch this week.

Closing this issue as duplicate of #9686, thanks everyone!

**Closed by jleandroperez** 2018-07-23 13:46 UTC
Labels: Localization, Project Glot, i18n

**Comment by mzorz** [comment] 2018-07-23 14:38
Android PR ready here https://github.com/wordpress-mobile/WordPress-Android/pull/8096
