### ISSUE TITLE
Editor - Make Preview More Robust

### ISSUE THREAD

**Issue by sendhil** [wordpress-mobile/WordPress-iOS#5579] opened 2016-06-17 06:49 UTC
Right now Preview doesn't render properly in some circumstances (e.g. shortcodes won't render, plugins won't get a stab at the content, etc.). Let's update it so it's more robust and users can better get a sense of what their content will look like without having to leave the app.

Here's an example of the issue in action:
https://cloudup.com/iJ_-a6Jn4xs

**Comment by rachelmcr** [comment] 2016-06-22 13:55
Just spitballing here, but what if we removed this Preview and when a user previews from within the editor two things happen:

- The draft is saved/updated on the server (not just locally)
- The preview displays the "real" preview on the site (as it does when you select View/Preview on the post's card in the post list)

That would give the most realistic preview and encourage saving to the server instead of just locally.

(Potential downside: It would make it harder to draft/preview posts offline.)

**Comment by rachelmcr** [comment] 2016-08-25 09:10
Another issue that came up recently with a user (125894-h): Preview doesn't align images when they have an image alignment set.

**Comment by koke** [comment] 2016-10-03 14:03
We had an attempt at this 3+ years ago, and there are some challenges about real previews.

What if:
- I create a new post, preview it, and decide I don’t really want it. Tapping “Discard draft” should remove it from the server.
- I edit an existing post, preview uploads my new changes, but eventually I decide I want to discard those edits. The app needs to revert to a previous version
- I have edited the post on the web but the app hasn’t picked up the changes yet. Previewing the post would overwrite my changes
- I updated a draft while offline so it’s “Failed”. I also updated it on the web. What happens when the app syncs?
- I started editing a draft while the app was syncing and the original post had changed. Same case but post was already published on the server

Part of the problem is #404 Conflict Resolution, plus we'd need to integrate post revisions to preview existing posts. Some extra issues with revisions:

- some hosts completely disable revisions
- some users don’t even know about revisions
- revisions might be hidden by default on the edit screen
- only the last 25 revisions are kept (so careful about autosaving too often)

I think this was attempted before we even used the REST API in the app, so some of those problems might have changed, but I thought I'd dump the previous knowledge in this issue.

I personally had high hopes for Simperium to sync drafts.

**Comment by koke** [comment] 2018-05-07 14:04
There were a bunch of similar issues related to previews, I did some cleanup and created a master issue with specific steps. Closing this in favor of #9282.

**Closed** 2018-05-07 14:04 UTC
Labels: Posting/Editing, [Pri] Medium, [Type] Enhancement
