### ISSUE TITLE
Scheduled draft can be inadvertently published

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-iOS#3973] opened 2015-07-03 17:30 UTC
As reported from a user:

> 1. Create a new post in the iOS app
> 2. Save it as a draft
> 3. Open the draft in the editor, go back to the settings, and schedule it for a future date/time (note that the Status changes to Scheduled)
> 4. Tap the Schedule link to schedule the post. Result: The app says “Scheduled!” but the post is saved in draft status with a future date/time (not actually scheduled).
> 5. Open the draft in the editor, go back to the settings (note that “Published on” shows the scheduled date and Status now shows Draft), and change Status to Published (there’s no option to choose Scheduled).
> 6. Tap the Post link in the top right in hopes that it schedules the post. Result: It’s published immediately.

I think this is a problem rooted in poor UX which we can fix. Looking at wp-admin:

![napkin 13 07-03-15 12 23 40 pm](https://cloud.githubusercontent.com/assets/154014/8503035/630f2e56-217e-11e5-9c10-7b012a6a6749.png)

There is no explicit way to set a "published" status (except when a post already is published and setting it then does nothing). Publishing, updating, and scheduling are actions from the users' perspective.  Perhaps we should guard the user from explicitly setting a published status via UI like wp-admin?

![napkin 14 07-03-15 12 29 49 pm](https://cloud.githubusercontent.com/assets/154014/8503089/3901be98-217f-11e5-93bf-a7474ecc3d0a.png)

**Comment by bummytime** [comment] 2015-07-03 17:31
Ping @aerych because we chatted about this and he may have addition thoughts or opinions.

**Comment by aerych** [comment] 2015-07-03 18:11
> The app says “Scheduled!” but the post is saved in draft status with a future date/time (not actually scheduled).

I haven't tried this myself yet, but wnated to comment while my thoughts were fresh. I'm interpreting "Scheduled!" to be a toast confirmation and that the post was appearing under the draft filtered list instead of the scheduled filtered list.  This sounds like a bug but its not immediately clear why it happens. 

Observation:  The XML-RPC and REST api's have some weird behavior when it comes to posts with a future status. When the api returns a post with a future date, and a publish status, we have code to change the status to "future" within the app for internal consistency, and back to publish (if necessary) when updating.  

Theory: We're missing a step somewhere and the future status for a draft post is not correctly set somewhere.

**Comment by rachelmcr** [comment] 2015-07-03 18:30
> I'm interpreting "Scheduled!" to be a toast confirmation and that the post was appearing under the draft filtered list instead of the scheduled filtered list. This sounds like a bug but its not immediately clear why it happens.

As yes, to clarify, when I got to that point I logged in to the dashboard (in a browser) and confirmed that the post was saved with draft status and not actually scheduled. It was also appearing in the draft filtered list in the app.

**Comment by bummytime** [comment] 2015-07-06 13:44
Bump. Another user report:

> I did what I was told, I deleted and reloaded Wordpress app. The scheduled feature does not work. You pick a future date to publish and instead it publishes immediately.

**Comment by bummytime** [comment] 2015-07-14 01:39
More user feedback around scheduling woes:

> when showing when a post is scheduled to be posted it is confusing.
Currently it seems to round down to the nearest number of days away. For example if there is a post scheduled for July 12 at 9:00 am and it is currently July 9th at 11:00 am it shows 2d as the time frame when it would really be closer to 3d.
>
> Would it be possible to actually show the date when it will be published instead?

**Comment by aerych** [comment] 2015-07-14 15:15
More and more I'm thinking we should show a proper timestamp in the post cards.  I think the "short hand" style we're using in the reader makes sense when you're consuming another's content, and knowing the exact minute something was published maybe isn't very important. On your own posts, particularly ones that are scheduled it can be useful to view the exact publish date.
@mnt, @adambbecker thoughts?

**Comment by adambbecker** [comment] 2015-07-14 18:29
> I'm thinking we should show a proper timestamp in the post cards.

For the short term, yes I think that being a bit more explicit for the time stamp in post cards is probably a good idea. Less confusion the better.

---

For the longer term, this is actually something I've been curious about for a while, but I would love to display the date in the format set in the site's settings:

![screen shot 2015-07-14 at 2 25 38 pm](https://cloud.githubusercontent.com/assets/1427136/8681221/3b73c1e0-2a34-11e5-9a21-4f17d3636665.png)

Obviously, that potentially is a bit out of scope for this particular issue, but bringing it up just in case it's easier to implement than I think.

**Comment by aerych** [comment] 2015-08-14 12:57
Another report:
https://ios.forums.wordpress.org/topic/scheduling-posts-by-others?replies=1


>    Recently, I've run into an issue on the iOS Wordpress app where I can't schedule a post to go live at a later time. I'll set the time for something on a later date and hit the schedule button as I always have. But the post goes live immediately. This has happened twice in the past 2 days. Both posts were written by other writers and submitted as "pending review", which is a new procedure for our site.

 >   Since I had this issue previously, while working on a post tonight, I was very careful with my workflow this time around. I first set the publication time (9:10am tomorrow morning), and then set the post to 'drafts'. After completing my edits, I went to change it from 'drafts' to 'scheduled'. However, only drafts, pending review, and published were available. Reopening the 'schedule post' dialog seemed to make 'scheduled' reappear, however once I pressed 'schedule' in the upper right corner of my screen, the post went live immediately. Oddly, I was then able to go in and change the publication time (it had reverted to the current day and time) and the post was pulled down and scheduled for the appropriate time tomorrow.

>    Running the latest version of the iOS app, and Wordpress version 3.6.1 on the website. Thanks for any help.

**Comment by rachelmcr** [comment] 2016-01-29 19:00
I tested and confirmed that this is still an issue (using the steps in the original report) but only for self-hosted sites. When I use the same steps on a WordPress.com site, the post is scheduled as expected.

Tested in app beta v. 5.9.0.20160126; issue reproduced with a self-hosted site running WordPress 4.4.1 (no Jetpack).

**Comment by supernovia** [comment] 2016-03-18 17:56
We have another user on WordPress.com who is very careful about using the same workflow every time. Sometimes the posts schedule, and sometimes they publish immediately.

**Comment by aerych** [comment] 2016-03-30 17:50
The situation should (hopefully) be greatly improved in #4976 but I want to leave this open a bit longer til we see if there are other use cases we need to consider.

**Comment by ChrissiePollock** [comment] 2016-09-07 15:58
We have a new case in #128346-h

**Comment by rachelmcr** [comment] 2016-09-07 16:09
I can reproduce the case in #128346-h with these steps:

1. Start a new post in the app
2. In the post settings, set a future date
3. Tap **Schedule** to schedule the post
4. In the list of scheduled posts, find the post and open it again in the editor
5. Open the post settings and confirm that the Publish section shows the future date is still selected and the Status is Scheduled
6. Edit the post and tap Update

Result: The post is published immediately.

Tested on iPhone 6, iOS 9.3.5, WPiOS 6.5.0.20160906

**Comment by ChrissiePollock** [comment] 2016-10-22 18:36
Another case #137961-t

**Comment by rachelmcr** [comment] 2016-10-31 09:42
The user who reported the case in 128346-h (steps to repro above) also left an app review (1 star):

> This app used to be good, until a bug appeared that publishes scheduled posts immediately when they are updated. Makes it unusable as you can't plan blog posts ahead of time. Such a shame. Reported the bug but no action.

Publishing a post unexpectedly is really bad behavior; we need to fix this if possible.

**Comment by aerych** [comment] 2016-10-31 15:53
I agree with @kurzee that this is likely the same issue as #6113 and fixing one likely will fix the other.

**Comment by kurzee** [comment] 2016-11-21 19:16
Closing this as the primary issue was recently resolved from UX changes. The secondary issues of accidentally publishing have been resolved in https://github.com/wordpress-mobile/WordPress-iOS/pull/6212

The near future, a nice re-think of our entire UX for editing post statuses/dates, etc, would be super beneficial to both cleaning up the UX and code logic.

**Closed by kurzee** 2016-11-21 19:16 UTC
Labels: Posting/Editing, [Type] Bug
