### ISSUE TITLE
Editor: Errors editing a failed post

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#3070] opened 2015-01-22 19:59 UTC
When tapping to edit a post in a failed state, the following was logged to the console: 

> 2015-01-22 13:56:33.772 WordPress[9874:95142] **\* Assertion failure in -[UITableView _endCellAnimationsWithContext:], /SourceCache/UIKit_Sim/UIKit-3318.16.14/UITableView.m:1582
> 2015-01-22 13:56:43.021 WordPress[9874:95142] CoreData: error: Serious application error.  An exception was caught from the delegate of NSFetchedResultsController during a call to -controllerDidChangeContent:.  Invalid update: invalid number of rows in section 0.  The number of rows contained in an existing section after the update (1) must be equal to the number of rows contained in that section before the update (1), plus or minus the number of rows inserted or deleted from that section (0 inserted, 1 deleted) and plus or minus the number of rows moved into or out of that section (0 moved in, 0 moved out). with userInfo (null)
> 2015-01-22 13:56:44:259 WordPress[9874:607] !!! Attempted to create a revision of a revision

I think the last line, `Attempted to create a revision of a revision` maybe is the root issue?

cc @bummytime 

UPDATE 06/2020: `Attempted to create a revision of a revision` HAS BEEN UPDATED TO `Post is already a revision, no need to create a new one` and still appears when updating a post failed to upload

**Comment by aerych** [comment] 2015-01-22 21:12
Following up: there was something weird with the state of the post list when this happened. There was a section for a failed post, then another section containing two different failed posts, and finally the section for published posts. 

I'm also seeing the `Attempted to create a revision of a revision` when creating new posts.

**Comment by rachelmcr** [comment] 2016-01-29 17:21
I haven't been able to reproduce this exact issue (with the weird state of the post list and the first couple lines in the logs above).

I do see the line `Attempted to create a revision of a revision` when editing a failed post, or when starting a new post on a site that isn't syncing properly, so that's an issue but may not be directly related to the other errors described here.

**Comment by diegoreymendez** [comment] 2016-01-29 17:53
The `Attempted to create a revision of a revision` message is happening because we have some faulty logic somewhere.  It's not dangerous per-se, as the code is smart enough not to create the second revision, but it is an alert due to faulty logic.

The reason is that revisions shouldn't be allowed to live outside of the editor.  When it closes, the revision should die with it.

**Comment by diegoreymendez** [comment] 2016-05-30 15:35
@rachelmcr - Any recent reports resembling this issue?  I haven't seen a crash like this in a while now and was wondering if we can close this one for the time being.

**Comment by rachelmcr** [comment] 2016-05-31 08:40
The message `Attempted to create a revision of a revision` is still coming up in app logs in some support issues, but mainly I have seen that around issues where there is a syncing problem (e.g. the oAuth token is expired and the posts aren't syncing). I haven't seen any recent reports where it was related to a failed post, or where it included the assertion failure from the original report here.

**Comment by nheagy** [comment] 2018-01-17 20:36
18 months later… has anything changed here? Perhaps Aztec has improved things?

**Comment by diegoreymendez** [comment] 2018-01-18 03:42
@nheagy - This isn't really Aztec related.  This seems to be an issue with the post list / post synchronization code.

It is still important, though.

**Comment by jkmassel** [comment] 2020-10-26 16:49
A user has reported experiencing this issue (and I've confirmed it via the app logs) as of October 2020.

**Comment by kean** [comment] 2024-05-01 15:51
You can now open failed posts and posts in the middle of the sync process. Implemented in the scope of  pcdRpT-6vS-p2.

**Closed by kean** 2024-05-01 15:51 UTC
Labels: [Type] Bug, [Pri] Low, Posting/Editing
