### ISSUE TITLE
Draft Pages Automatically Close When Navigating Away to a Different App on iPads

### ISSUE THREAD

**Issue by kelasante** [wordpress-mobile/WordPress-iOS#23699] opened 2024-10-24 22:56 UTC
### Expected behavior
For the draft page to remain open until it is saved and closed, like the behavior on iPhones. 

### Actual behavior
When editing a draft page on the Jetpack app, if you navigate to a different app and then come back, the draft page is automatically closed. 

This does not happen on iPhones. 

### Steps to reproduce the behavior
- Open a Page or Post to edit on an iPad
- Navigate to a different app like Chrome 
- Reopen the Jetpack app and the draft page will be closed

### Other Notes 

The user reported the issue in 8927258-zen. The user and I are not able to replicate it on iPhone, but the user says this happens on iPad. Unfortunately, I do not have an iPad to test this. 

The user shared a video in the ticket, but I have not added their video here due to privacy.

**Comment by dangermattic** [comment] 2024-10-24 22:57
Thanks for reporting! 👍

**Comment by kean** [comment] 2024-10-24 23:27
Hey, thanks for reporting it. It's a regression in 25.4, and it's fixed in 25.4.1, which will be available in the App Store soon.
Dupe: https://github.com/wordpress-mobile/WordPress-iOS/issues/23686.

**Closed as completed by kean** 2024-10-24 23:27 UTC

**Comment by Siphompeks** [comment] 2024-10-25 00:35
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
