### ISSUE TITLE
Crash: presenting action sheet without source

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/WordPress-iOS#8807] opened 2018-03-05 17:18 UTC
>Fatal Exception: NSGenericException
Your application has presented a UIAlertController (<UIAlertController: 0x12ea8b200>) of style UIAlertControllerStyleActionSheet. The modalPresentationStyle of a UIAlertController with this style is UIModalPresentationPopover. You must provide location information for this popover through the alert controller's popoverPresentationController. You must provide either a sourceView and sourceRect or a barButtonItem. If this information is not known when you present the alert controller, you may provide it in the UIPopoverPresentationControllerDelegate method -prepareForPopoverPresentation.

http://crashes.to/s/81b0d8934a3

**Comment by koke** [comment] 2018-03-05 17:22
This seems to be a recurring issue that happens when you present a `UIAlertController` on an iPad and forget to set the source view in the `popoverViewController`. Going through all the instances that use an action sheet I found one in `MediaLibraryViewController.presentRetryOptions(for:)`. To reproduce:

1. Go to the media library
2. Start uploading a picture, then go offline (I turned off wifi while using the simulator)
3. Tap on the thumbnail for the uploading image.
4. Crash
5. After you relaunch, every time you tap retry the app crashes.

**Comment by koke** [comment] 2018-04-03 07:46
This is still happening on 9.6

**Comment by SiobhyB** [comment] 2018-06-26 10:54
This came up in 1241725-z. (Found by searching crash reports by username.)

@koke: The user noted that the app only crashes when they tap the "write" option. I'm going to check whether they recently had any failed media uploads but wanted to note in case this was caused by something else.

**Comment by koke** [comment] 2018-06-27 07:20
Do you know what they mean exactly by "write option"? Is that the new post button in the tab bar or something else?

**Comment by nheagy** [comment] 2018-07-02 21:17
Can recreate this reliably on iPad by logging in with a wpcom account with no blogs. Tap write, and the app locks up with exact error shown above.

**Comment by nheagy** [comment] 2018-07-05 23:00
I've fixed the crash from the Write button.

The instance caused by `MediaLibraryViewController.presentRetryOptions(for:)` remains. I'll do that next.

**Comment by nheagy** [comment] 2018-07-08 06:04
@koke I can't recreate the `MediaLibraryViewController.presentRetryOptions(for:)` scenario. Can you try it again to see if you can?

**Comment by koke** [comment] 2018-07-09 07:10
The media one seems to work fine on 10.4

**Comment by nheagy** [comment] 2018-07-09 15:45
Fantastic.

Closing this with the assumption that #9688 fixed the last remaining occurance. Feel free to re-open if that's incorrect.

**Closed by nheagy** 2018-07-09 15:45 UTC
Labels: Groundskeeping, Media, [Type] Crash
