### ISSUE TITLE
NSInternalInconsistencyException in UIPredictionViewController

### ISSUE THREAD

**Issue by loremattei** [wordpress-mobile/WordPress-iOS#13885] opened 2020-04-14 09:56 UTC
**Sentry Url**: https://sentry.io/share/issue/60a850970b2f45a9afb81597b1a72619/
**User Count**: 41
**Count**: 65
**First Release**: 14.3.0.3
**First Seen**: 2020-03-29T13:46:18Z
**Last Release**: 14.5.0.2
**Last Seen**: 2020-04-14T03:57:30Z
**24 Hours**: 20
**30 Days**: 65

**Stacktrace**:
```
NSInternalInconsistencyException: <RCTVideo: 0x123e91cf0; frame = (0 0; 339 193); layer = <CALayer: 0x283336ea0>>: An -observeValueForKeyPath:ofObject:change:context: message was received but not handled.
Key path: status
Observed object: <AVPlayerItem: 0x28300b280, asset = <AVURLAsset: 0x28331f740, URL = file:///private/var/mobile/Containers/Data/Application/66A19682-3EFE-4977-8017-D41AC5E5F356/tmp/-1038243254.jpg>>
Change: {
    kind = 1;
}
Context: 0x0
    at null.__exceptionPreprocess(null:null)
    at null.objc_exception_throw(null:null)
    at null.-[NSObject(NSKeyValueObserving) observeValueForKeyPath:ofObject:change:context:](null:null)
    at null.-[RCTVideo observeValueForKeyPath:ofObject:change:context:](react-native-video/ios/Video/RCTVideo.m:null)
    at null.NSKeyValueNotifyObserver(null:null)
    at null.NSKeyValueDidChange(null:null)
    at null.NSKeyValueDidChangeWithPerThreadPendingNotifications(null:null)
    at null.-[AVPlayerItem _changeStatusToFailedWithError:](null:null)
    at null.__avplayeritem_fpItemNotificationCallback_block_invoke(null:null)
    at null._dispatch_call_block_and_release(null:null)
...
(9 additional frame(s) were not displayed)
```

**Comment by yaelirub** [comment] 2020-04-20 23:46
This issue is low by impact but since it's new and I think the use of video in blocks is going to increase and since RCTVideo hasn't been modified in a while, I wonder what's going on here. 

Seems like one of the observers hasn't been removed properly but Im not sure. 

@hypest , I wonder if you have any insight into what's going and the priority 🙏

**Comment by hypest** [comment] 2020-04-22 08:01
👋 @SergioEstevao , can you have a look at this one to see if you can gain insight? Thanks!

**Comment by SergioEstevao** [comment] 2020-04-27 10:45
Some things come to mind looking at the stack trace:
 - The AVPlayerItem is set to play an image file instead of a video: ```tmp/-1038243254.jpg```
 - Another thing strange is that the video component is pointing to a local path, so this can be something to the upload process or the async upload doing a bad job replacing the local urls for remote urls.
 - While the React component is not being updated we have been updating the `react-native-video` library every time we update RN version maybe something was introduced there and started the issue.

**Comment by hypest** [comment] 2020-04-27 12:38
Since this is a crash and seems to happen a bit often, please have a go on this @SergioEstevao to try to fix. Thanks!

**Comment by SergioEstevao** [comment] 2020-04-29 15:28
Ok I had a look on this, and the error is caused by an unhandled observation that pops up to the NSObject level.

After checking our current version of RCTVideo I noticed that our fork is based on version 5.0.1 and this was fixed in version 5.0.2 here: https://github.com/react-native-community/react-native-video/pull/1720.

I will go ahead and update our fork and try to get this for the new version of GB-mobile.

**Comment by SergioEstevao** [comment] 2020-04-29 15:46
Update for react-native-video fork: https://github.com/wordpress-mobile/react-native-video/pull/7

**Comment by designsimply** [comment] 2020-06-13 01:14
**Events in the last 90d:** 1,200
**Events in the last 11d for 14.9:** [zero](https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=release&field=os&field=device&field=culprit&name=All+Events&project=1438083&query=issue.id%3A1586943465+release%3A14.9.0.4&sort=-timestamp&statsPeriod=30d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1) in 14.9 since it was released on 2020-06-01
**Users affected in the last 90d:** 638
<sub>https://sentry.io/share/issue/60a850970b2f45a9afb81597b1a72619/</sub>

Appears fixed by https://github.com/wordpress-mobile/gutenberg-mobile/pull/2205 (props @SergioEstevao 🎉) and the [90-day graph for issue.id:1586943465](https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=release&field=os&field=device&field=culprit&name=All+Events&project=1438083&query=issue.id%3A1586943465&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1) seems to agree:

<img width="1025" alt="Screen Shot 2020-06-12 at Jun 12 7 13 31 PM" src="https://user-images.githubusercontent.com/1119271/84556561-d38b6080-ace0-11ea-933e-10098672bdcb.png">

**Closed by designsimply** 2020-06-13 01:14 UTC
Labels: Gutenberg integration, [Pri] Low, [Type] Crash
