### ISSUE TITLE
Reader: Margins sometimes expand after navigating back to feed

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#14017] opened 2020-04-29 16:42 UTC
### Expected behavior

I expect the Reader margins to always stay the same.

### Actual behavior

Sometimes, when I navigate back to a Reader feed (e.g. from the post or comment detail) the margins expand. They stay that way (including when I navigate around the Reader) until something else changes the layout, for example when I rotate the device.

### Steps to reproduce the behavior

I don't have reliable steps to reproduce this issue. I have only noticed it twice, when navigating back to a Reader feed after viewing a post or comment detail.

Possibly relevant: I grabbed screenshots the second time this happened, and my screenshots were saved in landscape even though the device orientation was portrait.

![IMG_2416](https://user-images.githubusercontent.com/8658164/80622496-c96b1680-8a40-11ea-959b-223f09dfd964.PNG)

**Comment by leandroalonso** [comment] 2021-03-25 17:07
I couldn't reproduce this issue. Probably it was fixed by the changes in the Reader + Tab bar.

**Closed by leandroalonso** 2021-03-25 17:07 UTC
Labels: Reader, [Type] Bug
