### ISSUE TITLE
Unable to update plugin

### ISSUE THREAD

**Issue by reginabally** [wordpress-mobile/WordPress-iOS#16667] opened 2021-06-11 04:04 UTC
Originally reported in 4038137-zd-woothemes.

### Expected behavior

I would expect to be able to update the plugins through the app.

### Actual behavior

When I tapped the "Update" button, I saw a spin wheel and the "Update" button still appears on the screen.

### Steps to reproduce the behavior

1. Go to My Site > Plugins > Manage
2. Select a plugin that needs to be updated
3. Tap the "Update" button
4. The "Update" button shows up again after the spin wheel appeared for a few seconds
5. Check WP Admin > Plugins > Installed Plugins and notice the plugin still needs to be updated

**Video recording**

https://user-images.githubusercontent.com/40906847/121628850-a10b7380-caac-11eb-8f35-7717f81084cd.MP4

##### Tested on iPhone SE, iOS 14.6, WPiOS WPInternal 17.5.0.20210531

**Comment by thehenrybyrd** [comment] 2021-06-15 16:24
Also occurring on [Android](https://github.com/wordpress-mobile/WordPress-Android/issues/14822). Further discussion for reference: p9dueE-340

**Comment by reginabally** [comment] 2021-06-18 06:28
Another report in 4073806-zd-woothemes

**Comment by momo-ozawa** [comment] 2021-08-16 14:28
@reginabally @thehenrybyrd 

Looks like this was being [caused by a server side bug](https://github.com/wordpress-mobile/WordPress-Android/issues/14822#issuecomment-872318794) and has been fixed.

I just tested on 17.9, and I'm able to update the plugin successfully. I was also able to confirm that the plugin get updated properly via Calypso.


https://user-images.githubusercontent.com/6711616/129579417-dad03714-4d70-4b30-9a7a-ae67e8ed4ad4.mp4


Calypso before | Calypso after
-- | --
<img width="1542" alt="Screen Shot 2021-08-16 at 15 19 14" src="https://user-images.githubusercontent.com/6711616/129579739-ef913a26-4c95-4c25-8dc8-a2133b0358b0.png"> | <img width="1037" alt="Screen Shot 2021-08-16 at 15 21 14" src="https://user-images.githubusercontent.com/6711616/129579778-6b13eb59-673d-44f2-a3cc-d1bcc35bab39.png">

**Comment by ScoutHarris** [comment] 2021-10-27 23:13
Closing per Momo's comment above.

**Closed as completed by ScoutHarris** 2021-10-27 23:13 UTC
Labels: [Pri] High, Jetpack Plugins
