### ISSUE TITLE
Fetch and show avatars for XML-RPC Posts

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-iOS#2076] opened 2014-07-21 19:39 UTC
On the Me tab, when you browse the posts of a site, a default gravatar is shown for XML-RPC posts. It should fetch the gravatar email if possible and fetch the image for it instead. This is discussed in [#2022](https://github.com/wordpress-mobile/WordPress-iOS/issues/2022) and possibly related to [#904](https://github.com/wordpress-mobile/WordPress-iOS/issues/904)

**Comment by rachelmcr** [comment] 2015-11-26 15:01
Posts have moved around since this issue was opened, but from what I see this is still an issue.

I checked My Sites > Select a site > Blog Posts in the latest beta (5.8.0.20151124) and confirmed that a default avatar is still being shown for posts there. (This was the case for all blogs I checked; I confirmed that the sites had a blavatar/site icon and the authors had a Gravatar.)

![2015-11-26 14 57 26](https://cloud.githubusercontent.com/assets/8658164/11425645/3d4c3040-944e-11e5-91d9-cc84a0cf159e.png)

**Comment by oguzkocer** [comment] 2015-12-04 20:46
@rachelmcr Unfortunately we didn't end up merging the mentioned PR, but @aerych has worked on the new posts list and it might be the same issue I am not sure. @aerych did you noticed anything like that?

**Comment by aerych** [comment] 2015-12-04 21:30
The new post list currently tries to show site blavatars, not author gravatars.  IIRC this is what wpcom was doing at the time the list was redesigned but things have shifted since then.  Funny enough, the code to display the blavatar is also broken. :(  

I can kick this into shape. Thanks for the ping @oguzkocer and @rachelmcr :)

**Comment by aerych** [comment] 2015-12-04 22:56
Following up.  Double checked with @mattmiklic and the site blavatar is the correct image to show, not an author's gravatar (those square icons yo).  I think I was a bit confused about the gravatar vs blavatar thing.  There were use cases where a gravatar was displayed on the web's post list in lieu of the normal blavatar but we never supported the difference in the app.  #4554 addresses the issue with broken blavatar.   

Since we've on design-wise from the old post style we can probably close this issue.

**Closed by aerych** 2015-12-04 22:56 UTC
Labels: General, [Type] Enhancement
