### ISSUE TITLE
Connection Sharing option to Facebook brings up a blank screen

### ISSUE THREAD

**Issue by rezzap** [wordpress-mobile/WordPress-iOS#13306] opened 2020-01-29 11:18 UTC
### Expected behavior

I would expect that after adding my login information for the Facebook sharing connection, a new page would show to allow me to connect my Page to the site.

### Actual behavior

After adding in your login information, a blank page shows and there is no further action to be taken. The site is not connected to the Facebook Page.

### Steps to reproduce the behavior

1. Use a site with sharing enabled (WordPress.com Premium plan was used in the test)
2. Navigate to Sharing and select Facebook.
3. Follow steps to Connect. Add your login information and login to connect. 
4. The blank screen shows with no further options than to 'X' out. 

<img src="https://user-images.githubusercontent.com/10325627/73352204-8c985380-4288-11ea-981f-437c9bf53c8a.jpeg" width="270" alt="IMG_F849DA640AC6-1">

##### Tested on iPhone X, iOS 13.3, WPiOS 14.0

A number of users have been reaching out about having trouble connecting Facebook, but this was last reported in 2667175-zen with a screenshot of the blank page. 

Connecting from the browser at WordPress.com worked and updated the connection listed in the app after doing so. Other services seem to work fine.

**Comment by diegoreymendez** [comment] 2020-01-29 12:31
@designsimply - I can confirm that this happens.

For context:

During my work [here](https://github.com/wordpress-mobile/WordPress-iOS/pull/13249#event-2986140545) both @leandroalonso and I verified that the Facebook integration was broken in `develop` (before my work was merged).

**Comment by rezzap** [comment] 2020-01-29 15:45
Reported again in 2668480-zen

**Comment by SiobhyB** [comment] 2020-01-31 21:42
Another report in 2677428-zen

**Comment by diegoreymendez** [comment] 2020-01-31 23:42
@elibud - Since this isn't great I was wondering if this issue is on the radar, or if we should give it extra priority.

**Comment by elibud** [comment] 2020-02-02 21:36
This is not great at all, let's please take a look this week @diegoreymendez, can you coordinate with @yaelirub on who should tackle it? If it's a simple enough fix let's target the frozen branch.

**Comment by yaelirub** [comment] 2020-02-02 23:52
Testing this, I see the issue in 14.1 but not in develop. @diegoreymendez , @leandroalonso, can you confirm?

**Comment by erricgunawan** [comment] 2020-02-03 02:26
Still got a report here: 2685558-zen

Since this has been worked on, please let me know if y'all still need to have them reported here or not.

**Comment by yaelirub** [comment] 2020-02-03 02:29
Thank you, @erricgunawan! No need to report more cases here 🙏

**Comment by diegoreymendez** [comment] 2020-02-03 12:55
@yaelirub - In 14.1 it seems like the blank page is indeed not shown so I'm closing this specific issue.

That said, I am still unable to successfully connect to Facebook for other reasons so I opened a new issue here: https://github.com/wordpress-mobile/WordPress-iOS/issues/13356

**Closed by diegoreymendez** 2020-02-03 12:55 UTC
Labels: [Type] Bug

**Comment by leandroalonso** [comment] 2020-02-03 13:25
@yaelirub @diegoreymendez It's working on `develop` as Yael mentioned, but I still see the blank page in `14.1` — I think this is the issue, isn't?

**Comment by diegoreymendez** [comment] 2020-02-03 14:08
I added the 14.2 milestone to document what version fixes this issue.  Do we want to backport this to 14.1 @yaelirub ?
