### ISSUE TITLE
Reader: Following Sites list is incomplete

### ISSUE THREAD

**Issue by eduardozulian** [wordpress-mobile/WordPress-iOS#15651] opened 2021-01-15 15:38 UTC
Not all the sites you follow in the WordPress.com Reader appear in the app. In fact, the number is way lower and I have the impression that the only sites I see on the Reader are WordPress sites with a connected Jetpack account.

### Expected behavior
To see all my followed sites on the Reader, no matter the platform.

### Actual behavior
* I see a smaller number on the app (76) in Reader > Filter > Following if compared to the WordPress.com Reader via browser (200+) [First image]
* I see a different list of sites on Reader > Manage > Followed Sites. The list has more than 76 sites but it's still incomplete.  [Second image]
* While the sites are not visible in the Following section, their posts are still being listed in the Reader

First Image | Second Image
------------ | -------------
<img width="480" alt="Captura de Tela 2021-01-15 às 12 26 19" src="https://user-images.githubusercontent.com/1136160/104746214-bcf13000-572d-11eb-80c4-a1db56d37eeb.png"> | <img width="523" alt="Captura de Tela 2021-01-15 às 12 30 07" src="https://user-images.githubusercontent.com/1136160/104746226-c11d4d80-572d-11eb-8529-7bddfe8b4c00.png">
https://www.atlasobscura.com/ is not on the Following List as well as many other sites | Reader > Manage > Followed Sites. The site http://diariodorio.com/ is not present on Reader > Filter > Following

### Steps to reproduce the behavior
1. Log in to WordPress.com 
2. Go to the Reader
3. Make sure you follow a few non-JP, non-WP sites
4. Take note of the number of sites you follow
5. Go to the WP app and click on Reader
6. Tap the Filter and see the number of sites you're following
7. From the same page, click on Manage > Followed Sites
8. Count the number of sites you see

### Tasks

- [x] Get the same list of followed sites in Reader > Following > Filter as in web [#17173](https://github.com/wordpress-mobile/WordPress-iOS/pull/17173)
- [ ] Get the same list of followed sites in Reader > Settings > Followed Sites

**Comment by ScoutHarris** [comment] 2021-01-15 18:07
Hey @eduardozulian  . The Reader tab filters have been updated to behave as Calypso now does (https://github.com/wordpress-mobile/WordPress-iOS/pull/15585). That is, the filters only show the sites for the tab you are on. Thus the total sites shown in the manage view should be split between all the filterable tabs you have. 

I'm going to close this. If you still think there's an issue feel free to reopen.

**Comment by ScoutHarris** [comment] 2021-01-15 18:09
Ugh. 🤦 . I just realized what you were saying. 

> https://www.atlasobscura.com/ is not on the Following List as well as many other sites

Got it. I'll take a look.

**Comment by ScoutHarris** [comment] 2021-01-21 19:40
Hey @eduardozulian . Would you mind trying again with WPiOS 16.5? That version is more in sync with Calypso (i.e. the data the API provides).

**Comment by eduardozulian** [comment] 2021-01-22 12:20
No luck, @ScoutHarris

* My Reader > Filter section now has 55 (when I logged in, the number was 56) sites. It's lower than the initial test with 16.4
* I still can't see a full list on Manage > Followed Sites

Thanks!

**Comment by aerych** [comment] 2021-02-05 22:16
I looked into this a little bit. The following list is populated by calling the `/read/following/mine` endpoint via [ReaderTopicServiceRemote.fetchFollowedSitesWithSuccess:failure](https://github.com/wordpress-mobile/WordPressKit-iOS/blob/b2f3542ec479c717df1317094d91d8dc17bcec3d/WordPressKit/ReaderTopicServiceRemote.m#L72).  Note that no parameters are passed other than `meta`.   Then endpoint returns a maximum of 100 results at a time, ordered from newest.  These results are divided between the following, automattic, and followed p2s filters as appropriate.  Since the app does not paginate the results from the API, anyone who is follows more than 100 sites will find the excess missing.  
We should consider either fetching multiple pages of results until all followed sites are cached or implementing some pagination mechanism. We might need to make a change to the API in order to support alpha numeric ordering.

**Comment by reginabally** [comment] 2021-02-26 04:55
Another report in 3762505-zen.

> The sites I follow appear and disappear from my Managed Reader at their own will. If there is a restriction on number of sites which can be displayed on the app it should be my choice and not WPs. Ideally it should be all sites. I follow more than 1700 sites but can only see 100-150 on the app and mostly newly followed sites. 

I can confirm they're following 1763 sites now.

**Comment by ScoutHarris** [comment] 2021-03-11 18:44
I've added this to the Hummingbird backlog. It'll take a bit of work to figure out and implement a solution, so it's best to treat it as a project.

**Comment by reginabally** [comment] 2021-06-04 02:33
Another report in 4042047-zd-woothemes.

> while my computer says I follow 163 blogs, my iPad says I follow 95.

**Comment by staskus** [comment] 2022-08-09 07:45
This bug happens because pagination is not implemented for [read/following/mine](https://developer.wordpress.com/docs/api/1.1/get/read/following/mine/) endpoint .

This is an example response:

```
"page": 1,
"number": 91,
"total_subscriptions": 680
```
5461497-zd-wootheme

However, `fetchFollowedSitesWithSuccess` in `ReaderTopicService` doesn't take into account pagination and "total_subscriptions" value. 

The same issue also reproducible on WordPress-Android.

**Comment by daniloercoli** [comment] 2024-02-26 11:05
Android ticket here: https://github.com/wordpress-mobile/WordPress-Android/issues/20218

**Closed as completed** 2024-03-29 18:41 UTC
Labels: [Pri] Medium, Reader
