### ISSUE TITLE
Redirect editing of Gutenberg posts

### ISSUE THREAD

**Issue by pento** [wordpress-mobile/WordPress-iOS#9191] opened 2018-04-25 05:03 UTC
With Gutenberg support being focussed on [gutenberg-mobile](https://github.com/wordpress-mobile/gutenberg-mobile), there are understandably a bunch of bugs when someone attempts to edit a Gutenberg post in the iOS app. There are several issues described in [this post](https://wptavern.com/wordpress-for-ios-and-gutenberg-dont-get-along), and I would imagine there are similar incompatibilities with a bunch of blocks.

With that in mind, it'd be useful to add a temporary check to prevent people from editing Gutenberg posts in the mobile apps, so that they can't accidentally cause major formatting changes to their post. It's a reasonable assumption that the Gutenberg plugin would be installed on the site that has a Gutenberg post on it, so you could redirect to Gutenberg on the site for editing those posts, at least until gutenberg-mobile is ready for testing.

Related Android issue: https://github.com/wordpress-mobile/WordPress-Android/issues/7669

**Comment by mcsf** [comment] 2018-04-25 10:44
> so you could redirect to Gutenberg on the site for editing those posts, at least until gutenberg-mobile is ready for testing

And/or offer to edit as HTML? As long as we're sure that nothing has been silently altered in the process (currently, merely opening a post strips out tags (`<p>`) essential to block validity).

**Comment by rachelmcr** [comment] 2018-10-16 12:06
I tested a similar scenario as reported in the post linked above, and I couldn't reproduce any of the issues. The draft in the app looked as I expected it to, and the updated draft when edited on the web was intact (without any issues for the Gutenberg blocks).

@pento @koke @diegoreymendez Are there any other known issues between Gutenberg web and the iOS app right now? Is further testing needed to confirm that Aztec can handle the launch of Gutenberg web (until Mobile Gutenberg is launched), or is it ok to close this issue now?

**Comment by diegoreymendez** [comment] 2018-10-16 12:43
Closing for now, as I'm not aware of any pending issues.  If there's anything it can be reported separately.

**Closed by diegoreymendez** 2018-10-16 12:43 UTC
Labels: Posting/Editing, [Type] Broken Window
