### ISSUE TITLE
Focus is not right when post has no text, only image.

### ISSUE THREAD

**Issue by JiangYuf** [wordpress-mobile/WordPress-iOS#6667] opened 2017-02-14 06:41 UTC
### Expected behavior
insert the second image is at bottom of the first image

### Actual behavior

insert the second image is at top of the first image 

### Steps to reproduce the behavior
1. no text only image
2.focus at image bottom
3.insert image 
4 the second image at the top of first image
![1](https://cloud.githubusercontent.com/assets/11827242/22918110/9aa6f8ae-f2c3-11e6-995f-51b9de86e3fa.png)
![img_3863](https://cloud.githubusercontent.com/assets/11827242/22918116/a426f0b4-f2c3-11e6-9a98-3954306af79f.png)
![3](https://cloud.githubusercontent.com/assets/11827242/22918117/a6dd71c0-f2c3-11e6-90fb-34091b796622.png)
![4](https://cloud.githubusercontent.com/assets/11827242/22918124/a8c7758a-f2c3-11e6-83e3-8c409bb98adf.png)

##### Tested on [device], iOS [version], WPiOS [version]
iOS 6s (all version)  WPiOS newest version

**Comment by hoverduck** [comment] 2017-02-14 14:52
Confirmed bug on iPad Air 2 with v6.9.0.20170210

**Comment by jleandroperez** [comment] 2018-01-04 13:58
Closing this one since the visual editor has been replaced by Aztec, and this issue is no longer valid.

Thanks everyone!

**Closed by jleandroperez** 2018-01-04 13:58 UTC
Labels: Media, Posting/Editing, [Pri] Low, [Type] Broken Window, [Type] Bug
