### ISSUE TITLE
Login: 2FA accept SMS code without last digit

### ISSUE THREAD

**Issue by brbrr** [wordpress-mobile/WordPress-iOS#8106] opened 2017-11-07 14:59 UTC
### Expected behavior

2FA fails if SMS code is not matching 

### Actual behavior

Possible to login without last digit from SMS code

### Steps to reproduce the behavior

0. Logout from your account
1. Start login process with 2FA account
2. Type SMS code and remove the last digit
3. Login will be successful

**Comment by aerych** [comment] 2017-11-16 20:05
I can reproduce this, and also reproduce it on the web.  Right now it looks like an issue at the API layer.  I'll follow up with the respective team and see what we need to do.

**Comment by aerych** [comment] 2017-11-21 20:02
Caught up with a @tug and @pento regarding this behavior.  It is by design, so closing.
Thanks noticing and for making the report @brbrr :)

**Closed by aerych** 2017-11-21 20:02 UTC
Labels: Login, [Type] Bug
