### ISSUE TITLE
[GlobalStep] [iPad] Profile image fails to update on My Profile tab upon changing it from ME tab.

### ISSUE THREAD

**Issue by gglobalstep** [wordpress-mobile/WordPress-iOS#14083] opened 2020-05-07 17:58 UTC
Environment:
iOS: iPad Air 2(v13.3.1), iPad (6th Gen) - v12.4
Steps To Reproduce:

1. Install and launch the application.
2. Tap on "Log In".
3. Log in to the app using valid credentials.
4. Open "Me" tab.
5. Tap on profile icon to change the profile.
6. Select select image and upload.
7. Observe that it fails to update in "My profile"

Actual Result:
Profile image fails to update on My Profile tab upon changing it from ME tab.

Note: If you change a photo for My Profile it gets updated for Me section as well but vice-versa fails to work.

Expected Result:
Upon changing the profile photo from "Me" tab it should get update in My profile.

[#14083.zip](https://github.com/wordpress-mobile/WordPress-iOS/files/4594856/14083.zip)

**Comment by designsimply** [comment] 2020-05-13 06:09
Tested and confirmed that updating the account profile image from a splitscreen view with the "Me" menu on the left and "My Profile" on the right doesn't update the first time it is updated but it does appear to work normally for subsequent profile image updates. ([2m23s](https://cloudup.com/chB6LjAkXyD))

<img width="400" alt="Screen Shot 2020-05-13 at May 13 12 03 36 AM" src="https://user-images.githubusercontent.com/1119271/81777054-4a98c380-94ad-11ea-8faa-2a96fb87ab41.png">
<p style="clear:both;"><sup>Tested with WPiOS 14.8.0.1 TestFlight beta on iPhone 11 iOS 13.4.1 landscape orientation.</sup></p>

**Comment by designsimply** [comment] 2020-05-13 06:11
Labeling as low priority because it only happens the first time the account profile image is updated and the problem only appears when viewing the My Profile screen in splitscreen view.

**Comment by kean** [comment] 2024-09-12 17:38
Fixed in 25.4.

**Comment by dangermattic** [comment] 2024-09-12 17:38
Thanks for reporting! 👍

**Closed by kean** 2024-09-12 17:38 UTC
Labels: [Type] Bug, [Pri] Low, /Me
