### ISSUE TITLE
Reader: Missing space between 'By' and 'author' for some languages.

### ISSUE THREAD

**Issue by tiagomar** [wordpress-mobile/WordPress-iOS#19086] opened 2022-07-20 15:26 UTC
For some languages there is no space between `By` and `author` when viewing a post, like pt-br, it, de, he, etc. This is not a comprehensive list, there might be other languages with the same problem.

### Expected behavior
| EN | FR |
| - | - |
| <img width="300" alt="image" src="https://user-images.githubusercontent.com/42008628/180017196-29175496-078d-4d93-9df9-8092a2e39f36.png"> | <img width="300" alt="image" src="https://user-images.githubusercontent.com/42008628/180017527-956b375d-bca6-4492-8cb0-636b486dbf0e.png"> |

### Actual behavior
| PT-BR | IT | DE | HE |
| - | - | - | - |
| <img width="300" alt="image" src="https://user-images.githubusercontent.com/42008628/180018181-63a9435c-bb73-4a45-bedf-dfd2bd175182.png"> | <img width="300" alt="image" src="https://user-images.githubusercontent.com/42008628/180018362-952a4e7e-d6d1-4748-80eb-e72d5d2a2e0e.png"> | <img width="300" alt="image" src="https://user-images.githubusercontent.com/42008628/180018907-c678f5f1-6093-4cf2-9a16-6e202cb4b484.png"> | <img width="300" alt="image" src="https://user-images.githubusercontent.com/42008628/180019082-10b575d4-7ba2-4c16-9ba7-e820f1c7c0fa.png"> |

### Steps to reproduce the behavior
1. Open a post.
2. Change the device language to any of the affected languages.

**Comment by dlind1** [comment] 2023-11-02 14:28
👋 This is indeed caused by the lack of a space for the translations of `By ` in [GlotPress](https://translate.wordpress.org/projects/apps/ios/dev/pt-br/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=10729573&filters%5Btranslation_id%5D=78714011).

I have went ahead and reviewed the translations for Mag-16 languages and added the missing space for German, Hebrew, Indonesian and Italian, as well as suggested a translation for Brazilian Portuguese and Swedish which would have to be approved. There are also some Korean/Chinese translations which don't have a space, but would need a review from a native speaker, plus the Japanese is using the English text, which should be fixed as well.

A possible solution would be to remove the whitespace from the original/translations and always add it in the code, provided that it'd work ok with Chinese/Korean/Japanese scripts.

**Comment by kean** [comment] 2024-12-20 10:28
Obsolete.

**Closed as completed by kean** 2024-12-20 10:28 UTC
Labels: [Pri] Low, Reader, i18n, Good First Issue
