### ISSUE TITLE
User reports being unable to approve comments from notifications (Self hosted)

### ISSUE THREAD

**Issue by sendhil** [wordpress-mobile/WordPress-iOS#1232] opened 2014-02-18 00:18 UTC
User reports that when they approve a comment from the comments screen there isn't a problem but when they try and approve a comment from the notifications screen nothing happens.

**Comment by hoverduck** [comment] 2015-10-29 16:58
29Oct15 Bug Scrub

Closing - unable to reproduce

**Closed by hoverduck** 2015-10-29 16:58 UTC
Labels: bug, Jetpack, priority-high

**Comment by koke** [comment] 2015-10-29 17:02
For reference, I believe this might have been fixed by https://github.com/Automattic/jetpack/issues/2792
