### ISSUE TITLE
Reader: 'Can't add self as subview' crash when closing the Reader

### ISSUE THREAD

**Issue by staskus** [wordpress-mobile/WordPress-iOS#20843] opened 2023-06-13 07:48 UTC
'Can't add self as subview' crash when closing the reader. Crash happens only sometimes and inconsistently. 

![image](https://github.com/wordpress-mobile/WordPress-iOS/assets/4062343/44b57eb2-1105-4d47-9978-07557637a5df)

### Investigation

The inconsistent crash happens due to calling `super.viewDidAppear` in `viewDidDisappear` method

```
    override func viewDidDisappear(_ animated: Bool) {
        super.viewDidAppear(animated)

        ReaderTracker.shared.stop(.readerPost)
    }
```

```
2023-06-12 14:34:45.191085+0300 Jetpack[93899:2704431] [ViewController] Calling -viewDidAppear: directly on a view controller is not supported, and may result in out-of-order callbacks and other inconsistent behavior. 0x15c942c00>

2023-06-12 14:34:46.149397+0300 Jetpack[93899:2704431] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Can't add self as subview'
```

**Related Stats issue:** https://github.com/wordpress-mobile/WordPress-iOS/issues/20849

**Comment by guarani** [comment] 2023-06-14 14:58
👋 @momo-ozawa, I manually added https://github.com/wordpress-mobile/WordPress-iOS/pull/20844 under Development in the side panel here so that the GitHub board shows the linked PR. It looks like it didn't happen automatically because this PR is targeting the release branch and not `trunk`. Hope that helps!

Thanks for fixing this 🙇

**Comment by guarani** [comment] 2023-06-14 22:25
I experienced this crash today, so thank you for fixing it, @momo-ozawa! 

I'm sure this crash corresponds to [JETPACK-IOS-31](https://a8c.sentry.io/share/issue/370718624b35441d8214418ab819dcd8/), so I've gone ahead and linked to this issue from Sentry. 

~~I also marked it as "resolved in the next release" in Sentry, although I'm not sure exactly how Sentry interprets what our next release is yet.~~ **(update: see below)**

For the record, this was how I ran into this (I couldn't reproduce consistently):

1. Tested Stats on a high-traffic WP.com blog
2. Opened Stats then Insights and added all cards
3. Opened Year tab
4. Backgrounded app and added This Week widget
5. Opened app and switched to Insights screen
6. App shows blank grey screen with navigation bar visible
7. Tap Back button and app crashes

**Comment by guarani** [comment] 2023-06-15 00:01
I un-resolved Sentry issue JETPACK-IOS-31 after realizing that it contains events with two distinct error messages:
- `NSInvalidArgumentException: Can't add self as subview` (this issue)
- `NSInvalidArgumentException: -[__NSCFSet addObject:]: attempt to insert nil` (https://github.com/wordpress-mobile/WordPress-iOS/issues/20840)

**Comment by staskus** [comment] 2023-06-15 06:53
> I un-resolved Sentry issue JETPACK-IOS-31 after realizing that it contains events with two distinct error messages:
> 
> * `NSInvalidArgumentException: Can't add self as subview` (this issue)
> * `NSInvalidArgumentException: -[__NSCFSet addObject:]: attempt to insert nil` ([NSInvalidArgumentException: -[__NSCFSet addObject:]: attempt to insert nil #20840](https://github.com/wordpress-mobile/WordPress-iOS/issues/20840))

@guarani, yes, there's even more. Sentry report has at least one more distinct error message:

```
 <UINavigationController: 0x1540f7a00> is pushing the same view controller instance (<WPMediaPickerViewController: 0x1560c1c00>)
```

**Comment by guarani** [comment] 2023-06-16 00:56
I made a separate issue now for the above @staskus. So now [JETPACK-IOS-31](https://a8c.sentry.io/issues/3140539221/?referrer=github_integration) is split into three issues:

- `NSInvalidArgumentException: Can't add self as subview` (this issue)
- https://github.com/wordpress-mobile/WordPress-iOS/issues/20840)
- https://github.com/wordpress-mobile/WordPress-iOS/issues/20890

**Comment by guarani** [comment] 2023-06-16 22:12
👋 Hey @momo-ozawa, I've closed this since https://github.com/wordpress-mobile/WordPress-iOS/pull/20844 is merged. The other issues mentioned above track the other crashes within the [JETPACK-IOS-31](https://a8c.sentry.io/issues/3140539221/?referrer=github_integration) Sentry issue.

Please feel free to re-open if you think so.

**Comment by guarani** [comment] 2023-07-14 18:53
@salimbraksa [reported this issue is still occurring](p1689333961574339-slack-C05CANZ2B6F) and I just ran into this. 

Here are the steps to reproduce:

1. Log in to a WP.com account
2. On the dashboard, tap the blogging prompts "View all responses" **multiple times in quick succession**
3. Notice that the Reader screens are pushed multiple times onto the navigation stack (and there's a white square on the screen)
4. Tap back
5. Tap back again
6. App crashes

**Comment by staskus** [comment] 2023-07-17 12:32
@guarani Thanks, I'll try to reproduce and fix.

Since it looks like this crash happens in Reader as well as Stats, I suppose both can have similar ways to reproduce it as you reported. Tapping CTA multiple times in quick succession pushing the same VC multiple times and then coming back.

**Closed as completed** 2023-07-20 07:07 UTC
Labels: [Type] Crash, [Pri] Medium, Reader
