### ISSUE TITLE
Bug: Reader - Search Site generates duplicate results

### ISSUE THREAD

**Issue by pinarol** [wordpress-mobile/WordPress-iOS#10227] opened 2018-10-10 08:09 UTC
### Expected behavior

Expected to see only 1 result for a specific site in Reader site search

### Actual behavior

Displays multiple results pointing to same site, also infinite scroll continues to generate same results

![simulator screen shot - iphone xr - 2018-10-10 at 11 01 58](https://user-images.githubusercontent.com/5032900/46721631-27c47e80-cc7c-11e8-8308-5826608a60d3.png)

### Steps to reproduce the behavior

Open Reader > Search > Sites
Type lymeliferevealed and search

##### Tested on [device], iOS [version], WPiOS [version]
iOS 11.4 iPhone 6
iOS 12.0 iPhone XR
WPiOS 10.9

**Comment by designsimply** [comment] 2019-08-21 16:06
I was unable to reproduce the problem where you can see duplicate posts in a search at Reader > Search  > Sites.

<img src="https://user-images.githubusercontent.com/1119271/63448315-e4d64a00-c3fa-11e9-8e2d-7bb119fcc8c4.PNG" width="400" alt="IMG_0158">
<sup>Tested with WP Internal 13.1.0.20190819 on iPad Mini 4 (WiFi) (iPad5,1) iOS 12.4.</sup>

Closing for now but with a note to say I would like to re-open if we find additional cases.

**Closed** 2019-08-21 16:06 UTC
Labels: Reader, [Type] Bug
