### ISSUE TITLE
NSInternalInconsistencyException: Attempted to perform update with invalid index path: <NSIndexPath: 0x280ea5ac0> {length = 2, path...

### ISSUE THREAD

**Issue by jkmassel** [wordpress-mobile/WordPress-iOS#15373] opened 2020-11-23 18:35 UTC
**Sentry Url**: https://sentry.io/share/issue/0372f2e941c74943b76637facdee49ac/
**User Count**: 288
**Count**: 336
**First Release**: 15.3.0.3
**First Seen**: 2020-09-01T16:42:47Z
**Last Seen**: 2020-11-23T17:51:55Z
**24 Hours**: 80
**30 Days**: 322
**LogID:** C1AEB997-CDB0-4032-8962-AD66E8D34E65

```
NSInternalInconsistencyException: Attempted to perform update with invalid index path: <NSIndexPath: 0x280ea5ac0> {length = 2, path...
  File "Classes/Utility/WPTableViewHandler.m", line 702, in -[WPTableViewHandler controller:didChangeObject:atIndexPath:forChangeType:newIndexPath:]
  File "main.swift", line 7, in main
...
(34 additional frame(s) were not displayed)
```

**Comment by leandroalonso** [comment] 2020-11-24 12:37
Duplicate of https://github.com/wordpress-mobile/WordPress-iOS/issues/15366

**Closed as completed by leandroalonso** 2020-11-24 12:37 UTC
Labels: [Type] Crash
