### ISSUE TITLE
Cant see invalid links in when editing menus

### ISSUE THREAD

**Issue by charliescheer** [wordpress-mobile/WordPress-iOS#12965] opened 2019-11-15 23:40 UTC
### Expected behavior
If you go to My Sites > Menus you should be able to see and edit all of the menu links that appear in the menu on your site

### Actual behavior
If a link is marked as invalid, the link does not appear.  So what appears in the Menus edit view does not reflect what appears in wp-admin or in the customizer.  That way if a link has become invalid you can see it and remove it
In the menus menu:
<img src="https://cdn-std.droplr.net/files/acc_593859/XXy9RG" />

In customizer:
<img src="https://cdn-std.droplr.net/files/acc_593859/zRNAIs" />

### Steps to reproduce the behavior
First you will need to create an invalid link.  This can happen by directly pointing to something on your site and then removing it.  
1.  Create a new test page
2. Go to the customizer and add the test page to your menu
3. Delete the page
4. return to the customizer and it should appear as an invalid link

Now go to the app, if you go to My Site > Menus you will not see the invalid link but it will still appear in the customizer

wpiOS 13.5.1
iOS 13.1.3

**Comment by rachelmcr** [comment] 2019-11-21 12:08
Closing as a duplicate of https://github.com/wordpress-mobile/WordPress-iOS/issues/12914.

**Closed by rachelmcr** 2019-11-21 12:08 UTC
