### ISSUE TITLE
Race condition when undoing destructive actions in the notifications tab

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-iOS#4208] opened 2015-08-26 19:31 UTC
Here's [a video](https://cloudup.com/clVwoA934qb) of the issue.

Ping @jleandroperez.

**Comment by rachelmcr** [comment] 2016-01-25 16:30
I have been testing this issue, and I haven't been able to reproduce it yet. So far, I either undo the action early enough to avoid the problem (so the comment is restored and doesn't disappear from the notifications list) or I'm too slow and the comment disappears before I can undo the action.

Tested in beta v. 5.9.0.20160113.

**Comment by diegoreymendez** [comment] 2016-01-25 16:46
@rachelmcr - I believe I've seen a PR fixing this issue a while ago.  I'll look it up to confirm.

**Comment by diegoreymendez** [comment] 2016-01-25 17:01
@rachelmcr - Can't find the fix, but I confirm that I can no longer reproduce this issue.

/cc @jleandroperez for extra confirmation.

**Comment by rachelmcr** [comment] 2016-01-26 12:34
Thanks for checking! I'm going to go ahead and close this issue since we can't reproduce it anymore, but if it turns out it wasn't really fixed we can reopen it.

**Closed by rachelmcr** 2016-01-26 12:34 UTC
Labels: [Type] Bug

**Comment by jleandroperez** [comment] 2016-02-04 19:41
@diegoreymendez + @rachelmcr just confirming that this issue wasn't directly addressed, *yet*, i cannot repro anymore.

If needed, let's reopen. Thanks for checking!!
