### ISSUE TITLE
[GlobalStep] [iOS] "Problem Following/UnFollowing site" error popup is displayed when user tries to follow/unfollow a post multiple times from Readers tab

### ISSUE THREAD

**Issue by gglobalstep** [wordpress-mobile/WordPress-iOS#14172] opened 2020-05-21 15:13 UTC
**Environment:**
Android: Samsung Galaxy s9 (v10).
Build WPAndroid [version]: v14.9

**Steps To Reproduce:** 
 1. Install and launch the application.
 2. Tap on "Log In".
 3. Log in to the app using valid credentials.
 4. Tap on "My site".
 5. Tap on "Create Blog" symbol.
 6. Add any text at title.
 7. From footer tap on "+" to add Video block.
 8. Upload video in video block.
 9. Tap on "Publish" button.
 10. Go to My Site-> View Site and play the video.
 Note that video has proper resolution
 11. Now go to Reader tab, (Assuming your site is in "followed sites" or else Followed Sites> Manage> Enter URL)
 12. Observe that video is displayed in very less resolution screen as compared to View Site.

 **Actual Result:**
 Video is displayed in improper resolution for blog post under readers tab.

 **Expected Result:**
 Video should be displayed appropriately for blog post under readers tab.

**Attachment:**
[#2297.zip](https://github.com/wordpress-mobile/gutenberg-mobile/files/4663189/2297.zip)

**Comment by designsimply** [comment] 2020-05-22 21:03
Noting that the original steps to reproduce and results listed for this bug report don't match with the title or the attachment.

Duplicate of https://github.com/wordpress-mobile/WordPress-iOS/issues/14078.

**Closed** 2020-05-22 21:56 UTC
Labels: Beta Request, Reader, [Status] Duplicate, [Type] Bug
