### ISSUE TITLE
Incorrect dimming view layout at the Sites lists screen when rotating

### ISSUE THREAD

**Issue by ngoctr** [wordpress-mobile/WordPress-iOS#13901] opened 2020-04-15 01:22 UTC
### Actual behavior
**on iPad**
1. Within Site screen, tap **Switch Site** at the top left corner
![image](https://user-images.githubusercontent.com/17534738/79288552-63dc3d80-7f0a-11ea-835c-5dab1a38960b.png)
2. At the _Sites list_ screen, rotate the device, you will notice the gap between the side bar and the dimming view on the right.
![image](https://user-images.githubusercontent.com/17534738/79288633-9c7c1700-7f0a-11ea-8084-b3a55d3df100.png)

**on iPhone Plus/X/XS/11** (which support splitview in landscape mode)

1. Put the phone on Portrait mode, go to Site screen, then tap **Switch Site**
![image](https://user-images.githubusercontent.com/17534738/79288801-0a284300-7f0b-11ea-8a45-fc7b465fc288.png)
2. At the _Sites list_ screen, rotate the device to landscape, you will notice the dimming view overlapping the side bar
![image](https://user-images.githubusercontent.com/17534738/79288903-51aecf00-7f0b-11ea-9417-6055b829799c.png)

**Comment by ScoutHarris** [comment] 2020-04-15 01:30
Closing as dupe of https://github.com/wordpress-mobile/WordPress-iOS/issues/13550 (which I've updated to reference "dimmed view").

**Closed by ScoutHarris** 2020-04-15 01:30 UTC
