### ISSUE TITLE
Jetpack App Crashed When Clicking on Today's Stats

### ISSUE THREAD

**Issue by thabotswana** [wordpress-mobile/WordPress-iOS#20285] opened 2023-03-08 10:05 UTC
A user reported that when they click on **Today's Stats** on the _HOME_ tab, their app shuts down immediately. 

I found the [Sentry reports](https://a8c.sentry.io/discover/jetpack-ios:c05506bc298c44dfa0548d3b27c348b6/?field=title&field=event.type&field=project&field=user.display&field=timestamp&homepage=true&name=All+Events&project=5716771&query=user.email%3Akleung2733%40gmail.com&sort=-timestamp&statsPeriod=7d&yAxis=count%28%29) with the following error:

```
EXC_BREAKPOINT: Swift/StringIndexValidation.swift:390: Fatal error: String index is out of bounds
```

https://user-images.githubusercontent.com/35628116/223682395-99ff3d98-1370-44c2-aa1e-ae6e5ffbe924.mp4

##### User/device details
Ticket link: 6014421-zen
App version: 21.7.2
Device model: iPhone XR (iPhone11,8)
OS version: iOS 16.3.1
Type of site: Atomic

**Comment by guarani** [comment] 2023-12-26 19:10
I couldn't reproduce this. The Sentry link isn't working, so I searched for the user's email, and the error message, and neither returned a result in Sentry. I also tested with the device language set to Traditional Chinese, and there was no crash.

I appreciate you reporting this and including the Sentry link, @thabotswana. If you have any thoughts on how to reproduce now, I'd be glad to hear them!

We could lower close this as "unable to reproduce." Since you added this to the maintenance board and set its priority @tiagomar, could I get your thoughts on this?

**Comment by guarani** [comment] 2023-12-26 19:10
I couldn't reproduce this. The Sentry link isn't working, so I searched for the user's email, and the error message, and neither returned a result in Sentry. I also tested with the device language set to Traditional Chinese, and there was no crash.

I appreciate you reporting this and including the Sentry link, @thabotswana. If you have any thoughts on how to reproduce now, I'd be glad to hear them!

We could lower close this as "unable to reproduce." Since you added this to the maintenance board and set its priority @tiagomar, could I get your thoughts on this?

**Comment by tiagomar** [comment] 2023-12-27 10:22
> We could lower close this as "unable to reproduce." Since you added this to the maintenance board and set its priority @tiagomar, could I get your thoughts on this?

Yeah, it makes sense since the user's email and the error message don't return results in sentry.

**Comment by tiagomar** [comment] 2023-12-27 10:23
Unable to reproduce.

**Closed as not planned by tiagomar** 2023-12-27 10:23 UTC
Labels: [Type] Crash, [Pri] High, Stats

**Comment by guarani** [comment] 2023-12-27 14:54
Thanks for checking, @tiagomar!
I updated this to "closed as not planned / unable to reproduce", in case that helps differentiate this from issues that were actually resolved

<img width="286" alt="Screenshot 2023-12-27 at 11 53 19" src="https://github.com/wordpress-mobile/WordPress-iOS/assets/1898325/f1243ee6-4ac0-4b08-aa00-c2199b3b0ed3">
