### ISSUE TITLE
Stats page showing error when user doesn't have permissions to view stats on jetpack sites

### ISSUE THREAD

**Issue by charliescheer** [wordpress-mobile/WordPress-iOS#11823] opened 2019-05-30 21:05 UTC
With a Jetpack site, the administrators have the choice to decide what permissions level has access to view the stats for the site.  If you are in calypso from an account that does not have permission to view stats for a site there is no link to see the stats page at all.  I would expect in the WordPress app that if the user didn't have the permissions to view stats that the page to click on and view stats would not appear for that user.

What is currently happening in iOS is that the stats page does exist for jetpack users even if they do not have sufficient permissions to view the stats.  When you click on the stats page you get an error saying that the stats can't be accessed, but it does not indicate why.
<img src="https://cdn-std.dprcdn.net/files/acc_593859/9giwV1" />
 (note this image is in 12.5 post stats refresh.  In earlier versions the page appears, but it displays no content or error)

To replicate:
1.  Invite a new user on a jetpack site that does not have sufficient permissions to view stats on site (note: to change who can access stats in a jetpack site, go to Wp-admin > Jetpack > Settings > Traffic and scroll down to Site Stats)
2. In the WordPress app log into the WordPress.com account without access to stats
3.  Go to  My Site > Stats to see the error.

If possible, I think it would be better if the stats link wasn't available at all if the user didn't have access to stats.

Tested on:
WordPress 12.5.0.20190530
iOS 12.3.1
iPhone 8

**Comment by ScoutHarris** [comment] 2019-05-30 21:18
Thanks @charliescheer . I've added it to The List.

**Comment by ScoutHarris** [comment] 2019-05-31 00:12
Hey @charliescheer . Would it be possible for you to do this on the current App Store version (i.e. on old stats) and let me know what happens? I'm not entirely sure this is a new problem. Sadly, I'm having issues with our test JP sites. Thank you!!

**Comment by charliescheer** [comment] 2019-05-31 17:25
Sure thing.  Current app store version has the same problem, it just doesn't display an error.  It loads the stats page and you get no data.
<img src="https://cdn-std.dprcdn.net/files/acc_593859/Bbb13m" >

**Comment by ScoutHarris** [comment] 2019-05-31 18:18
Thanks @charliescheer !

**Comment by dangermattic** [comment] 2024-04-04 10:07
Thanks for reporting! 👍

**Comment by staskus** [comment] 2024-04-04 10:53
The issue is still reproducible.

We determine whether or not show Dashboard option with this check:

```
    @objc public func isViewingStatsAllowed() -> Bool {
        return isAdmin || isUserCapableOf(.ViewStats)
    }
```

I exhibited this behavior:

- `isUserCapableOf(.ViewStats)` wrongly returns `true` for the WP.com user who shouldn't have access to Stats on the Jetpack site.
- `isUserCapableOf(.ViewStats)` correctly returns `false` for the WP.com user who shouldn't have access to Stats on the WordPress site.
- In both cases, it works as expected on the web.

I checked the code on Calypso (fbhepr%2Skers%2Spnylcfb%2Spyvrag%2Szl%2Qfvgrf%2Sfgngf%2Sfgngf%2Qerqverpg%2Sybnq%2Qfgngf%2Qcntr.gfk%3Se%3Qsp1r566p%2393-og). It has a comment that acknowledges a broken capability check, and uses some workaround:

> TODO: Fix incorrect view_stats permission on Calypso.
> If the user's role is missing from the site's stats dashboard access allowlist, then it should be reflected in the user's view_stats capability.

Check this PR for more context: https://github.com/Automattic/wp-calypso/pull/78210 with conclusion:

> Note that the view_stats capability is currently bugged in the backend for Atomic sites and ignores the configured allowlist for accessing the stats dashboard. Once this is fixed in the backend, everything should work as expected on Calypso.

Given a low priority, this issue being 5 years old, and the fact that this is an issue on the backend, we shouldn't be fixing this on the app's side. Therefore, I think it's the most reasonable to close this issue. 

@guarani do you agree, or do you think it makes sense to keep such issues open?

**Closed** 2024-04-04 13:18 UTC
Labels: [Type] Bug, Jetpack, Stats

**Comment by guarani** [comment] 2024-04-15 22:31
Sorry for the late reply. I forgot to leave an update here after our Slack convo (p1712248314605799/1712242744.351269-slack-C441E3YTS). 

I think it's fair to close due to more pressing work. I'd still like to dig more into this if I find the time since the Jetpack app should handle Jetpack permissions well, just like WP.com does.

**Comment by guarani** [comment] 2024-04-15 22:31
Sorry for the late reply. I forgot to leave an update here after our Slack convo (p1712248314605799/1712242744.351269-slack-C441E3YTS). 

I think it's fair to close due to more pressing work. I'd still like to dig more into this if I find the time since the Jetpack app should handle Jetpack permissions well, just like WP.com does.
