### ISSUE TITLE
Missing nav and status bars

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#6032] opened 2016-10-03 21:17 UTC
We received a report (thanks @melchoyce) of the app missing the status and navigation bars. 
The steps to reproduce are currently unknown.  Potentially an issue with state restoration when the editor was the last thing visible.  Opening this issue to track.
Mel's device was an iPhone SE running iOS 9.3.5.  WPiOS was v6.5

**Comment by hoverduck** [comment] 2017-01-27 15:59
I've labelled this `[Pri] Low` since we don't have any repro steps, but if this issue pops up from more users it would be a big deal.

@melchoyce - have you seen this again since the initial report?

**Comment by melchoyce** [comment] 2017-01-27 21:21
Yes, I have. I feel like @aerych pinged me at some point telling me he figured out why it was happening — something to do with how much processing power my phone was using.

**Comment by aerych** [comment] 2017-01-27 22:44
I think I might have explained things poorly 😬 
This one is still a mystery.  Best guess is its something related to state restoration.

**Comment by melchoyce** [comment] 2017-01-27 22:53
If this helps, it only happens when I've been using my phone for a while. I recently saw it happen in another app, too (can't remember which off the top of my head, but I was like, "oh, my WordPress app bug!")

**Comment by melchoyce** [comment] 2017-01-27 22:53
PS, there should be a video recording of me reproducing this.

**Comment by jleandroperez** [comment] 2017-10-13 17:22
We've not seen this issue in a while (100% an SDK issue).

Closing this one for now.

**Closed by jleandroperez** 2017-10-13 17:22 UTC
Labels: General, [Pri] Low, [Type] Bug
