### ISSUE TITLE
Add in Sharing Extension

### ISSUE THREAD

**Issue by sendhil** [wordpress-mobile/WordPress-iOS#4316] opened 2015-09-28 22:20 UTC
Lets add in a sharing extension in so it's easy for our users to add content to their blogs. This should be a lot easier today than it was a year ago as we are about to deprecate iOS 7 and will be able to better re-use code in the extension rather than having to duplicate it like we would have last year.

**Comment by grimmwerks** [comment] 2015-11-10 20:33
Wondering where this might be as I'm thinking of creating a Share Extension for my blog on my own.

**Comment by rachelmcr** [comment] 2015-11-30 17:25
This looks like a duplicate of https://github.com/wordpress-mobile/WordPress-iOS/issues/2231. Since that issue has some recent activity, I'm closing this issue in favor of that one.

**Closed by rachelmcr** 2015-11-30 17:25 UTC
Labels: Sharing, [Type] Enhancement
