### ISSUE TITLE
Can't initialize Core Data stack

### ISSUE THREAD

**Issue by jkmassel** [wordpress-mobile/WordPress-iOS#14785] opened 2020-08-28 16:18 UTC
**Sentry Url**: https://sentry.io/share/issue/edaf60f265d649208e6efc3f600b1003/
**User Count**: 360
**Count**: 1097
**First Release**: 15.0.0.6
**First Seen**: 2020-06-15T20:45:11Z
**Last Seen**: 2020-08-28T08:03:53Z
**24 Hours**: 5
**30 Days**: 557
**LogID:** 0DA6E3BA-B508-4863-8505-C0FED00AECB0

```
Can't initialize Core Data stack:  >
  File "Classes/Utility/ContextManager.m", line 235, in __37-[ContextManager persistentContainer]_block_invoke_2
  File "Classes/Utility/ContextManager.m", line 231, in __37-[ContextManager persistentContainer]_block_invoke
  File "Classes/Utility/ContextManager.m", line 217, in -[ContextManager persistentContainer]
  File "Classes/Utility/ContextManager.m", line 270, in -[ContextManager persistentStoreCoordinator]
  File "Classes/Utility/ContextManager.m", line 69, in __31-[ContextManager writerContext]_block_invoke
  File "once.h", line 84, in _dispatch_once
  File "Classes/Utility/ContextManager.m", line 67, in -[ContextManager writerContext]
  File "Classes/Utility/ContextManager.m", line 81, in __29-[ContextManager mainContext]_block_invoke
  File "once.h", line 84, in _dispatch_once
  File "Classes/Utility/ContextManager.m", line 79, in -[ContextManager mainContext]
  File "Classes/Utility/ContextManager.m", line 279, in -[ContextManager startListeningToMainContextNotifications]
  File "Classes/Utility/ContextManager.m", line 36, in -[ContextManager init]
  File "Classes/Utility/ContextManager.m", line 46, in __40+[ContextManager internalSharedInstance]_block_invoke
  File "once.h", line 84, in _dispatch_once
  File "Classes/Utility/ContextManager.m", line 45, in +[ContextManager internalSharedInstance]
  File "CoreDataHelper.swift", line 187, in ContextManager.sharedInstance
  File "<compiler-generated>", line null, in ContextManager.sharedInstance
  File "<compiler-generated>", line 180, in ContextManager.sharedInstance
  File "WPCrashLoggingProvider.swift", line 29, in WPCrashLoggingProvider.currentUser.getter
  File "<compiler-generated>", line null, in WPCrashLoggingProvider.currentUser.getter
  File "<compiler-generated>", line 27, in WPCrashLoggingProvider
  File "CrashLogging.swift", line 189, in CrashLogging.currentUser.getter
  File "CrashLogging.swift", line 202, in CrashLogging.setNeedsDataRefresh
  File "CrashLogging.swift", line 64, in CrashLogging.start
  File "WordPressAppDelegate.swift", line 78, in WordPressAppDelegate.application
  File "<compiler-generated>", line null, in WordPressAppDelegate.application
  File "<compiler-generated>", line 67, in WordPressAppDelegate.application
  File "main.swift", line 7, in main
...
(53 additional frame(s) were not displayed)
```

From the logs:

```
2020-08-28 18:03:47:881 Migration required for persistent store.
2020-08-28 18:03:48:001 Unable to migrate store: Error Domain=IterativeMigrator Code=100 "Failed to find source model for metadata: ["NSStoreType": SQLite, "NSPersistenceFrameworkVersion": 977, "_NSAutoVacuumLevel": 2, "NSStoreUUID": 54FCFBEA-8281-40F8-8354-17C40145A529]" UserInfo={NSLocalizedDescription=Failed to find source model for metadata: ["NSStoreType": SQLite, "NSPersistenceFrameworkVersion": 977, "_NSAutoVacuumLevel": 2, "NSStoreUUID": 54FCFBEA-8281-40F8-8354-17C40145A529]}
2020-08-28 18:03:48:251 Error opening the database. Error Domain=NSCocoaErrorDomain Code=134020 "The model configuration used to open the store is incompatible with the one that was used to create the store." UserInfo={message=Can't find table for entity 'Account' in database at URL 'file:///var/mobile/Containers/Data/Application/2BA819B1-852E-450B-898B-3912B9F8C623/Documents/WordPress.sqlite', NSFilePath=/var/mobile/Containers/Data/Application/2BA819B1-852E-450B-898B-3912B9F8C623/Documents/WordPress.sqlite}
Deleting the file and trying again
```

**Comment by designsimply** [comment] 2020-09-02 19:56
**Events in the last 90d:** 1,100
**Users affected in the last 90d:** 381
<sub>WORDPRESS-IOS-3865: https://sentry.io/share/issue/edaf60f265d649208e6efc3f600b1003/</sub>

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=release&field=os&field=device&field=culprit&name=All+Events&project=1438083&query=issue.id%3A1727985708&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1">![image](https://user-images.githubusercontent.com/1119271/92030323-ba141680-ed1b-11ea-91ec-a1916fd63676.png)</a>

**Comment by designsimply** [comment] 2020-09-30 23:36
Hi @Gio2018 👋  were you able to make any progress on this crash?

**Events in the last 90d:** 1,200
**Users affected in the last 90d:** 430
<sub>WORDPRESS-IOS-3865: https://sentry.io/share/issue/edaf60f265d649208e6efc3f600b1003/</sub>

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=release&field=os&field=device&field=culprit&name=All+Events&project=1438083&query=issue.id%3A1727985708&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1">![image](https://user-images.githubusercontent.com/1119271/94750519-7674f280-0343-11eb-8e20-b22bf377e8a5.png)</a>

**Comment by Gio2018** [comment] 2020-10-01 13:54
> Hi @Gio2018 👋 were you able to make any progress on this crash?

Hi @designsimply  👋, not yet. Tried a few things but was not able to reproduce or point out the cause. Will do more investigation today and in the upcoming days, thank you!!

**Comment by Gio2018** [comment] 2020-10-12 16:02
Deassigned myself from the issue as was not able to reproduce/make any progress on this one.
For more context, since the issue seems originated from a variety of sources (notices, auth, stats) what I did was just try a variety of situations that would potentially cause the crash. Since this happens at the beginning, I tried to recreate these scenarios at startup, using state restoration.
To add some more info, it seems that, as of release 15.7, the crash has not occurred yet.

**Comment by designsimply** [comment] 2020-12-10 01:26
Good note about 15.7! I checked the numbers again and confirmed that there have been no new cases recorded for v15.7 or above in the last 90 days. Closing because of that and because the overall number of users affected is relatively low compared to other crashes we're tracking.

**Events in the last 90d:** 1,400
**Users affected in the last 90d:** 103
<sub>WORDPRESS-IOS-3865: https://sentry.io/share/issue/edaf60f265d649208e6efc3f600b1003/</sub>

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=release&field=os&field=device&field=culprit&name=All+Events&project=1438083&query=issue.id%3A1727985708&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1">![image](https://user-images.githubusercontent.com/1119271/101708963-b515e000-3a4b-11eb-9dca-45de17651078.png)</a>

**Closed as completed by designsimply** 2020-12-10 01:26 UTC
Labels: [Type] Crash, [Pri] Medium, Core Data
