### ISSUE TITLE
Keyboard renders incorrectly in iPadOS with Stage Manager

### ISSUE THREAD

**Issue by paulforgione** [wordpress-mobile/WordPress-iOS#21956] opened 2023-11-02 16:38 UTC
### Expected behavior

When opening a post on an iPad with Stage Manager and selecting a text input field, the Block insertion / text editing bar should stay at the bottom of the display due to the attached physical keyboard
![IMG_94D34DDDE9E5-1](https://github.com/wordpress-mobile/WordPress-iOS/assets/4359124/17ba5103-ed75-40dc-a935-6fd96dbb9d34)

### Actual behavior
The app renders the Block insertion / text editing bar as if it is displaying the onscreen keyboard, even though the keyboard does not and should not render.
![image](https://github.com/wordpress-mobile/WordPress-iOS/assets/4359124/bb2390a7-8f50-43cc-8baa-6efac70e494e)

### Steps to reproduce the behavior

1. Plug iPad with [Stage Manager capabilities](https://support.apple.com/en-us/HT213405) into an external display
2. Launch Jetpack, move to external display
3. Create a new post
4. Focus on a text field
5. The block insertion / text editing bar appears at the bottom of the screen, with a large amount of whitespace beneath (room for the on-screen keyboard, despite Stage Manager requiring a physical trackpad / keyboard to be attached to the iPad for input).

**Comment by kean** [comment] 2024-09-12 18:24
Closing as duplicate of https://github.com/wordpress-mobile/WordPress-iOS/issues/19543

**Closed as completed by kean** 2024-09-12 18:24 UTC
Labels: [Pri] Medium, iPad, Gutenberg
