### ISSUE TITLE
Japanese text gets garbled when switching to HTML mode in Aztec 

### ISSUE THREAD

**Issue by jklausa** [wordpress-mobile/WordPress-iOS#8147] opened 2017-11-14 15:18 UTC
![img_3237](https://user-images.githubusercontent.com/1594081/32787663-6104630a-c957-11e7-8ed0-d1c690209a1e.PNG)

I was able to replicate on my iPhone X.

### The easiest way to replicate:

Start composing a new post.
Type in some Japanese text.
Add image.
Switch to HTML mode in Aztec.
Try typing additonal text.

### Expected result:
The text continues to display fine.

### Actual result:
The text becomes garbled.

#### WordPress 8.7, iOS 11.1.1, iPhone X (CDMA)

**Comment by jklausa** [comment] 2017-11-14 15:19
oh, should I have filed this against wordpress-mobile/AztecEditor-iOS?

**Comment by jklausa** [comment] 2017-11-14 15:35
(x-posting my comment from the P2:


>I tried looking if polish characters would get similarily corrupted and it worked fine — but typing Korean broke it again (altough I had to type more than one character there).

**Comment by bummytime** [comment] 2017-11-14 15:40
ref: https://github.com/wordpress-mobile/AztecEditor-iOS/issues/709

**Comment by rachelmcr** [comment] 2018-10-16 16:07
It looks like this was fixed in https://github.com/wordpress-mobile/AztecEditor-iOS/pull/825. I can no longer reproduce; closing as resolved.

**Closed by rachelmcr** 2018-10-16 16:07 UTC
Labels: Aztec, [Type] Bug
