### ISSUE TITLE
NSInternalInconsistencyException: Attempted to perform update with invalid index path: <NSIndexPath: 0x28356d220> {length = 2, path...

### ISSUE THREAD

**Issue by jkmassel** [wordpress-mobile/WordPress-iOS#15369] opened 2020-11-23 18:33 UTC
**Sentry Url**: https://sentry.io/share/issue/2668f88c560f4dae9b5fbf2c1ba85132/
**User Count**: 489
**Count**: 831
**First Release**: 15.5.0.3
**First Seen**: 2020-09-03T03:33:47Z
**Last Seen**: 2020-11-23T18:12:20Z
**24 Hours**: 107
**30 Days**: 814
**LogID:** 297028AD-3552-4B81-87DD-3640147A968A

```
NSInternalInconsistencyException: Invalid indexPath
  File "NotificationsViewController.swift", line 925, in NotificationsViewController.selectRow
  File "NotificationsViewController.swift", line 225, in NotificationsViewController.traitCollectionDidChange
  File "<compiler-generated>", line null, in NotificationsViewController.traitCollectionDidChange
  File "main.swift", line 7, in main
...
(27 additional frame(s) were not displayed)
```

**Comment by leandroalonso** [comment] 2020-11-24 12:49
Duplicate of https://github.com/wordpress-mobile/WordPress-iOS/issues/15368

**Closed as completed by leandroalonso** 2020-11-24 12:49 UTC
Labels: [Type] Crash
