### ISSUE TITLE
Reader: blog post with lots of images is crashing the app

### ISSUE THREAD

**Issue by alisterscott** [wordpress-mobile/WordPress-iOS#7529] opened 2017-07-11 06:28 UTC
### Expected behavior

App not to crash

### Actual behavior

App becomes non-responsive - have to close app and re-open which resets app

### Steps to reproduce the behavior

Follow site twofatamericans.com (WordPress.com site)
Open article "Italy Part 2: Adding More To Our Waistlines" - https://twofatamericans.com/2017/07/09/italy-part-2-adding-more-to-our-waistlines/ 
https://wordpress.com/read/feeds/59589465/posts/1521466326 

##### Tested on iPhone 7 plus, 8.0.0.20170704 and 7.9 (app store), iOS 10.3.2

Video: https://cloudup.com/cv8FZMzo65z

**Comment by koke** [comment] 2017-07-11 06:37
I'd say it's a duplicate of #6040 as we've had several problems with posts with lots of images, but I'll let @aerych decide.

**Comment by aerych** [comment] 2017-07-11 20:15
Yeah, I agree with @koke, this looks like the same issue as #6040 after taking a quick peek at the specified post.  Closing in favor of the other issue.  Thanks for the report @alisterscott !!

**Closed by aerych** 2017-07-11 20:15 UTC
Labels: Reader
