### ISSUE TITLE
General: Shake to Undo does not match core iOS experience

### ISSUE THREAD

**Issue by alisterscott** [wordpress-mobile/WordPress-iOS#5844] opened 2016-08-07 23:35 UTC
### Expected behaviour

In the iOS editor, doing something to text, selecting and cutting for example, then shaking phone to undo should match core iOS experience which undoes that action
### Actual behaviour

Shaking the phone to undo text being 'cut' shows an 'undo' dialog but this doesn't appear to do anything - the text can't be restored
### Steps to reproduce the behaviour
1. Open iOS editor
2. Select some text and 'cut'
3. Shake iDevice
4. Select 'Undo'

Compare this to Notes app, or Simplenote where shake to undo is supported
#### Video:

https://cloudup.com/cGNOQ-BEn8c

Found by #dogfooding

**Comment by aerych** [comment] 2016-09-20 19:33
Seems that just typing, then shaking to undo, does not undo the recent typing.

**Comment by rachelmcr** [comment] 2017-01-18 23:51
It looks like this is a duplicate of this editor issue: https://github.com/wordpress-mobile/WordPress-Editor-iOS/issues/496

**Closed by rachelmcr** 2017-01-18 23:51 UTC
Labels: General, Posting/Editing, [Type] Bug
