### ISSUE TITLE
Posts: Duplicate post appears in post list after saving/publishing

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#5364] opened 2016-05-12 12:09 UTC
### Expected behavior

After I save or publish a post, that post appears in the posts list.

### Actual behavior

After I save or publish a post, two copies of the post appear in the post list. The duplicate remains in the list until the list is synced/refreshed.

### Steps to reproduce the behavior

1. Open the editor to start a new post
2. Add a title and content to the post
3. Publish the post OR Tap the "X" to exit the editor and save the draft

Result:

- In the post list, two copies of the post appear
- One copy has the "Local" label until the post is uploaded
- After the post is uploaded, the post that was marked "Local" only displays the title

##### Immediately after the editor closes (after saving/publishing in the editor)

![2016-05-12 13 00 12](https://cloud.githubusercontent.com/assets/8658164/15214027/90e3de74-1842-11e6-9332-dfe14ecc3f6c.png)

##### After the local post finishes uploading

![2016-05-12 13 00 17](https://cloud.githubusercontent.com/assets/8658164/15214029/94dfa260-1842-11e6-9c37-09f1bc8c8046.png)

##### After the list is refreshed (manually pulling down to refresh or after its syncs with the site)

![2016-05-12 13 00 23](https://cloud.githubusercontent.com/assets/8658164/15214031/96a0090a-1842-11e6-8337-4256b17a8239.png)

**Comment by rachelmcr** [comment] 2016-06-13 15:07
Another beta tester reported this for the WPiOS 6.3 beta, and it's still happening to me as well.

This is now also coming up in support, with users deleting posts thinking that there is a duplicate on the site. I'm setting high priority on this issue due to issues it can cause for users.

**Comment by kriskarkoski** [comment] 2016-08-30 19:44
I confirmed this still happens in the iOS 6.5 beta:

![img_3915](https://cloud.githubusercontent.com/assets/1900444/18104319/a058cacc-6ec8-11e6-9e72-ca2ddbcfc616.PNG)

**Comment by kurzee** [comment] 2016-10-24 18:35
Tested, this does not replicate from `develop` and is resolved, probably from https://github.com/wordpress-mobile/WordPress-iOS/pull/6102.

@astralbodies should https://github.com/wordpress-mobile/WordPress-iOS/pull/6102 be merged into `release/6.6` as well?

**Comment by astralbodies** [comment] 2016-10-24 19:08
@kurzee I was thinking about that but since this was more than just a bug fix (new string to translate also) I thought we could hold off until the next release (6.7)

@sendhil @kwonye I could be convinced otherwise.

**Closed** 2016-10-24 20:13 UTC
Labels: Posts List, [Pri] High, [Type] Bug
