### ISSUE TITLE
Alert when/before deleting a post

### ISSUE THREAD

**Issue by kwonye** [wordpress-mobile/WordPress-iOS#6374] opened 2017-01-04 18:42 UTC
Currently when you delete a post, the only indicator is the post list item changing as shown here:

![img_6166](https://cloud.githubusercontent.com/assets/1158819/21654444/624e91de-d26a-11e6-95a1-bc97919cec7e.png)

Let's either show an alert before (confirming the action) or after (how Android does it).

**Comment by ablyx** [comment] 2017-01-11 16:13
How about creating a UIAlertAction after the user taps on the bin button to alert the user that the post is going to be deleted and she can choose between ok and cancel?

**Comment by kwonye** [comment] 2017-01-11 17:25
@ablyx thanks for the suggestion! Do you think this action warrants such a "blocking" UI element?

**Comment by aerych** [comment] 2017-01-11 19:42
> Let's either show an alert before (confirming the action) or after (how Android does it).

I'm not sure about adding a confirmation prompt (either before or after) since we want to stay consistent with the experience on calypso. Would it be better to maintain the full sized card with an "undo" overlay (which is what Calypso does) rather than transitioning to the small cell?

**Comment by kwonye** [comment] 2017-01-12 07:05
@aerych I agree that's the best initial option as the fix should be super quick 👌

**Comment by ablyx** [comment] 2017-01-12 07:38
What about binned posts, should there be an alert for that?

**Comment by aerych** [comment] 2017-01-12 15:06
@ablyx good point, and calypso *does* show a prompt in that particular case.

**Comment by ablyx** [comment] 2017-01-13 09:17
@aerych is it ok if I submit a pr for an alert for deleting trashed posts?

**Comment by ablyx** [comment] 2017-01-13 09:47
@aerych I created issue #6415 for that case. Will submit a pr for that soon.

**Comment by rachelmcr** [comment] 2017-01-18 23:49
>Would it be better to maintain the full sized card with an "undo" overlay (which is what Calypso does) rather than transitioning to the small cell?

This sounds like the change proposed in https://github.com/wordpress-mobile/WordPress-iOS/issues/4185. I'm closing this issue as it looks like the suggested change is a duplicate of that issue; please reopen if I'm missing anything.

**Closed by rachelmcr** 2017-01-18 23:49 UTC
Labels: Posting/Editing, Posts List, [Pri] Medium, [Type] Enhancement
