### ISSUE TITLE
Users without a site are incorrectly asked to login by the widget

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-iOS#15857] opened 2021-02-10 19:50 UTC
### Expected behavior

Users without a site shouldn't be able to add any of the current widgets (Today stats or All Time stats).

### Actual behavior

Users who don't have a site yet (e.g. chose "Not now" option after sign up) are shown the "Log in to WordPress..." message in the widget.

### Steps to reproduce the behavior

1. Sign up for a new account
2. Skip the site creation process
3. Background the app and notice you can add the stats widgets
4. Notice that the widgets ask you to log in even though you're already logged in

##### Tested on iPhone 11, iOS 14.4, WPiOS 16.6

<sub>First reported [here](https://github.com/wordpress-mobile/WordPress-iOS/pull/15838#pullrequestreview-586657850)</sub>

**Comment by staskus** [comment] 2022-06-09 11:58
I would add a minor related UX issue:

 In case user has multiple sites but hasn't selected any we show _"Unable to load site stats"._ 
A more UX friendly message would be _"Please select a site..."_

![Simulator Screen Recording - iPhone 13 - 2022-06-09 at 14 57 09](https://user-images.githubusercontent.com/4062343/172841407-ccbb7c41-9519-442d-9070-0693ee02f79b.gif)

**Comment by staskus** [comment] 2022-06-09 12:00
@guarani 

Should we allow adding widgets when user is **not logged in**, if we **wouldn't allow users without a site** add any of the current widgets? I think we could make behaviour more consistent

I have 2 proposals for the sake of consistency:
1. If we wouldn't allow widgets without the site, then we shouldn't allow widgets if user is not logged in
2. If we continue allowing widgets when user is not logged in, we should allow widgets without the site with "Select a site..." message. 

I would choose an option number 2:
1. Widgets are always discoverable as an option
2. Users will know what is missing to make them work

**Comment by guarani** [comment] 2022-06-17 13:43
Good point that ensuring discoverability of widgets should be a top priority, @staskus. I agree with your suggestion that allowing the widget to be added, but providing an actionable message, is a great approach.

Apologies for the delay responding to you here, @staskus.

**Comment by staskus** [comment] 2022-06-21 08:45
Note: Added a new issue related to account having no site and widgets https://github.com/wordpress-mobile/WordPress-iOS/issues/18914

**Comment by staskus** [comment] 2023-01-19 13:18
The task has already time invested [and the issue is almost fixed in the PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/18916) so setting the priority to finish higher.

**Comment by guarani** [comment] 2023-01-19 20:44
I remember that PR from months back 👍 I think Medium priority is accurate here because users will sometimes not create a site and as it stands the widgets aren't showing actionable info in this scenario.

**Closed as completed** 2023-01-24 12:31 UTC
Labels: [Pri] Medium
