### ISSUE TITLE
Reader: Avatar is black for reblogged posts. 

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#4021] opened 2015-07-14 20:52 UTC
Follow one of your own sites in the reader.  Find a post you like on a different blog, and reblog that post to your own site.  For at least some of these posts, the avatar is showing up black. 

Props @designsimply

**Comment by rachelmcr** [comment] 2015-12-01 14:07
I wasn't able to reproduce this issue in the latest 5.8 beta with a post reblogged in a web browser. Since reblogging is no longer part of the Reader, and the issue isn't (at least consistently) reproducible, I'm going to close this issue for now. We can reopen it if this becomes more of an issue in the future.

**Closed by rachelmcr** 2015-12-01 14:07 UTC
Labels: Reader
