### ISSUE TITLE
Switching between dark and light mode while the app is open confuses the appearance

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-iOS#12441] opened 2019-08-30 21:54 UTC
Steps to reproduce:

1. Open any area of the app.
1. Put the app in the background (do not force close).
1. On the device, go to Settings > Display & Brightness > Appearance.
1. Change the mode from Light to Dark or vice versa.
1. Go back to the app and observe that some parts of the app change and others do not.
1. Force refresh the app.
1. Repeat steps 1-5.

**Result:** if the appearance is switched from Dark to Light or from Light to Dark after the app is opened, the colors become confused. ([40s](https://cloudup.com/cFIps2zwew2))

<img src="https://user-images.githubusercontent.com/1119271/64053057-07c0d680-cb3e-11e9-8d4d-dba1db417006.png" width="270" alt="after-dark-to-light-mode-switch"> <img src="https://user-images.githubusercontent.com/1119271/64053056-07284000-cb3e-11e9-9e73-83e13168d903.png" width="270" alt="after-light-to-dark-mode-switch">
<sup>Tested with WPiOS 13.2-beta1 (TestFlight) on iPhone 6S iOS 13.1 Beta 1 in Dark & Light Modes.</sup>

> The view controller needs to listen for the notification that the mode has changed and refresh the UI.

<sup>h/t @rachelmcr for the original report at p5T066-Zv-p2#comment-3427 and @jkmassel for the tip.</sup>

**Comment by danielebogo** [comment] 2019-10-02 15:29
[ ] Reader Detail
[ ] Fancy button
[ ] SearchBar strokes
[ ] Icons In WP Authenticator screens

**Comment by designsimply** [comment] 2019-10-16 23:34
I tested this again as part of 13.4 beta testing and found that if you toggle dark mode while the screen is visible the text color still doesn't update for the login/signup, log in, and logged in as screens.

Steps to reproduce:

1. Log out.
1. Tap "Log In".
1. Go to iOS Settings > Display & Brightness > Appearance.
1. Switch from Light to Dark (or vice versa).
1. Go back to the WP app and check to see if the buttons on the log in screen look correct.
1. Close and re-open the app.
1. Repeat steps 3-6 for the "Log In/ Sign up" screen.
1. Repeat steps 3-6 for the "Logged in as" screen.

**Result:** the buttons become unreadable with dark text on a dark background or light text on a light background if you toggle dark mode for the login/signup, log in, and logged in as screens screens while the app is open.

<img src="https://user-images.githubusercontent.com/1119271/66966561-e9099700-f03a-11e9-98ab-788fe4708f04.PNG" width="200" alt="IMG_3209"> <img src="https://user-images.githubusercontent.com/1119271/66966571-f030a500-f03a-11e9-97f5-ae6fbac3172c.PNG" width="200" alt="IMG_3215"> <img src="https://user-images.githubusercontent.com/1119271/66966580-f4f55900-f03a-11e9-8696-7d95b00cc48e.PNG" width="200" alt="IMG_3217">
<sup>Tested with WPiOS 13.4.0.1 (TestFlight) on iPhone 6S iOS 13.2.</sup>

**Comment by designsimply** [comment] 2019-10-21 21:51
1. Start in Dark Mode.
1. Open Reader and like some posts.
1. Switch to Light Mode.
1. Open Reader again and like some posts.

**Result:** the icons at the bottom of the post become very light gray on white and are hard to see.

<img src="https://user-images.githubusercontent.com/1119271/67245790-162ebe80-f41a-11e9-80ee-6563a02a4377.PNG" width="270" alt="IMG_3240"> <img src="https://user-images.githubusercontent.com/1119271/67245791-162ebe80-f41a-11e9-8058-e3f05807668e.PNG" width="270" alt="IMG_3241">
<sup>(Left) After switching from dark to light while the app is open and (right) after closing and reopening the app while in light mode, tested with WP Internal 13.5.20191021 (HockeyApp) on iPhone 6S iOS 13.2.</sup>

**Comment by designsimply** [comment] 2019-11-07 22:31
I tested with WP Internal 13.6.20111104 and I can still see the problem happening where switching from dark to light mode, or vice versa, causes some buttons to become unreadable. ([13s](https://cloudup.com/cuDK9SyjXKv))

<img src="https://user-images.githubusercontent.com/1119271/68433140-1695bc00-0173-11ea-9b50-105dfa17ef6a.png" width="270" alt="login-screen-after-light-to-dark-switch"> <img src="https://user-images.githubusercontent.com/1119271/68433139-1695bc00-0173-11ea-9981-3ff3d96294b1.png" width="270" alt="login-screen-after-dark-to-light-switch">
<sup>Tested with WP Internal 13.6.20111104 (HockeyApp version) on iPhone 6S iOS 13.2.</sup>

@danielebogo do you think you could fix this for the 13.6 or 13.7 release?

**Comment by danielebogo** [comment] 2019-11-08 09:24
@designsimply this is basically the main task for [Dark Mode V2](https://github.com/orgs/wordpress-mobile/projects/45#card-27241751). There's a list of elements you can see in the project card that have the same problem. Probably some can be addressed in `13.7`? @frosty

**Comment by designsimply** [comment] 2020-02-04 01:20
Possibly related: https://github.com/wordpress-mobile/WordPress-iOS/issues/13364.

**Comment by rachelmcr** [comment] 2020-02-04 16:42
Reader comment text color doesn't update when you switch between dark and light mode, rendering the text invisible against the background. This is visible both in the Reader tab and when accessing all comments on a post through the Notifications tab.

1. Set your device to dark mode.
2. Open the comments section on a post in the Reader.
3. Switch to light mode. Notice that any comment text is not visible, although other elements (comment author, timestamp, emoji, links) are visible.
4. Exit the comments section and reopen it, and notice that the text color is now fixed.

<img src="https://user-images.githubusercontent.com/8658164/73765777-f030ee00-476c-11ea-81e2-29074e2729b8.PNG" width="40%"> <img src="https://user-images.githubusercontent.com/8658164/73765776-f030ee00-476c-11ea-9374-d824546c9b59.PNG" width="40%">

Tested with WPiOS 14.1.0.20200131 on iPhone XS, iOS 13.3.

**Comment by SiobhyB** [comment] 2020-02-27 19:01
There was another report of this issue in 2744797-zen, the user notes that the input fields in the post editor were black on black after switching between modes.

They weren't able to grab a screenshot (and I can't replicate as I have an older iOS device that doesn't support dark mode).

**Comment by ScoutHarris** [comment] 2020-03-12 17:25
I'm closing this as these issues have either been fixed or are tracked on other issues. Since Dark Mode is no longer a project, I think it'd be best to create separate issues going forward so they can be addressed individually.

Recap:

- Login/Signup buttons - mostly fixed with https://github.com/wordpress-mobile/WordPress-iOS/pull/13636. At noted on that PR:
  - Sign in with Apple will be updated on https://github.com/wordpress-mobile/WordPress-iOS/issues/13620.
  - 'Connect another site' button on the login epilogue will be removed with the new epilogue https://github.com/wordpress-mobile/WordPress-iOS/issues/13413, and thus won't be an issue soon.
- Reader icons - https://github.com/wordpress-mobile/WordPress-iOS/issues/13630
- Reader comments - https://github.com/wordpress-mobile/WordPress-iOS/issues/13638
- Post editor input fields - couldn't reproduce. Tested on `develop` (i.e. release 14.5)

**Closed by ScoutHarris** 2020-03-12 17:25 UTC
Labels: Beta Request, Dark mode, [Type] Beta OS, [Type] Bug
