### ISSUE TITLE
Menus: Changing default menu title doesn't work correctly without refresh

### ISSUE THREAD

**Issue by jeremeylduvall** [wordpress-mobile/WordPress-iOS#5684] opened 2016-07-08 22:23 UTC
### Expected behavior

I didn't have any menus on my site so I was presented with the default menu option. I wanted to change the menu title though from "Default Menu" to something else. In Calypso, when you change the title of the default menu, it automatically "copies" the default menu into a new menu with the title you give it. You then have two menus (Default and the new one you just named).
### Actual behavior

When I first renamed the default menu, it showed that I only had one menu. Upon save, I actually had two, which was a bit weird but that's what I expected since I knew how Calypso handled it. When I expanded the menu list though, it displayed my new menu two times instead of the new menu and "Default menu." It only fixed itself when I exited the menu screen and reentered.
### Steps to reproduce the behavior
1. Open up the menus section for your WordPress.com site. This is easiest to see on a site with no menus. You would then only have a default menu.
2. Click the pencil icon next to "Default Menu" to change the menu title. Title it anything else.
3. Click "Done." You'll see "1 menu available" in the dropdown with your newly-named menu.
4. Click "Save." Now, you'll see two menus available. When you expand the list, it looks like the same menu.
5. Exit the Menu mode and re-enter. Now, you'll see the default option back in the choices alongside your newly-named menu.

Video: https://cloudup.com/cKgZBShWMGN (30sec)

**Comment by designsimply** [comment] 2019-03-13 18:43
Tested with WP Internal 12.0.0.20190311 on iPhone 6S iOS 12.1.4 and confirmed that renaming the default menu then saving results in a duplicate menu item with the same name listed until the screen is refreshed. ([28s](https://cloudup.com/c4viSyR4j38))

Before and after saving:

<img src="https://user-images.githubusercontent.com/1119271/54305652-5fb65180-458d-11e9-8730-0b39f76a5a8d.png" width="270" alt="before save">   <img src="https://user-images.githubusercontent.com/1119271/54305651-5fb65180-458d-11e9-91f7-cbc5d2139132.png" width="270" alt="after save">

**Comment by designsimply** [comment] 2020-08-08 02:18
I re-tested this issue using WPiOS 15.4.0.3 TestFlight beta on iPhone 11 iOS 13.6 and found that I could no longer see the problem where changing the name of a menu caused it to be duplicated in the menu list. ([49s](https://cloudup.com/cT6kkKQMpxc))

Closing, but please re-open if you find the problem is still happening and thank you for the report @jeremeylduvall!

**Closed by designsimply** 2020-08-08 02:18 UTC
Labels: Menus, [Pri] Low, [Type] Broken Window, [Type] Bug, good first issue
