### ISSUE TITLE
Crash when trying to visit the WordPress Help Center

### ISSUE THREAD

**Issue by megsfulton** [wordpress-mobile/WordPress-iOS#11781] opened 2019-05-24 23:55 UTC
The app crashed when tapping on the WordPress Help Center link in support

### Steps to reproduce the behavior

1. Open Me Tab
2. Tap Help and Support
3. Tap WordPress Help Center
4. Crash

**Comment by yaelirub** [comment] 2019-05-30 02:02
I spent hours on this and unfortunately I cannot reproduce it or track the cause for it.
i know @megsfulton is still experiencing this crash on WP 12.3.
All the users in Sentry who experience this crash are on WP 12.3, iOS 12.2.

The only change that has been done for this version in the SupportTableViewController and it's related files is in this commit: https://github.com/wordpress-mobile/WordPress-iOS/commit/11c9d4d1d6e74c40e45cd78315957567034f69f5
And has no affect on this issue. 

@ScoutHarris , do you have any suggestions?

**Comment by ScoutHarris** [comment] 2019-05-30 17:55
Hey @yaelirub . I'll take a look.

**Comment by ScoutHarris** [comment] 2019-05-30 19:07
Well, I tried every scenario I could think of accessing the Help Center, on `develop` and `release/12.3`, and I couldn't repro it either.

I did see this Sentry issue [WORDPRESS-IOS-G](https://sentry.io/organizations/a8c/issues/1014091239/) that is suspiciously similar. @jkmassel marked it as resolved in version 12.4, although there is no linked GH issue so I'm not sure why.

I suspect this has been resolved post-12.3 as well. 

@megsfulton - can you repro this on any version after 12.3?

**Comment by jkmassel** [comment] 2019-05-30 19:38
Hi y'all – this was resolved in 12.4 by the Sentry refactoring to stop the ZenDesk SDK warnings. I suspect it was an incompatibility between the SDK and the app after the Xcode 10.2 update (to update to Xcode 10.2, we needed their new SDK, which had had deprecation warnings in it for some time. I suspect our use of the deprecated method caused the crash)

**Comment by ScoutHarris** [comment] 2019-05-30 19:45
Aaahhh. Thanks @jkmassel ! So when the deprecated methods were removed in https://github.com/wordpress-mobile/WordPress-iOS/pull/11511 (which was in 12.4) that probably had the side effect of resolving the crashes? Interesting. I vote to close. 😄

**Comment by yaelirub** [comment] 2019-05-30 21:00
Thank you so much @ScoutHarris and @jkmassel. @designsimply closing this issue as it was resolved in 12.4

**Comment by yaelirub** [comment] 2019-05-30 21:00
Thank you so much @ScoutHarris and @jkmassel. @designsimply closing this issue as it was resolved in 12.4

**Closed by yaelirub** 2019-05-30 21:00 UTC
Labels: [Pri] High, [Type] Crash
