### ISSUE TITLE
Followers button stays selected after being pressed

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-iOS#16569] opened 2021-05-24 21:48 UTC
### Expected behavior

Tapped cells should not stay selected.

### Actual behavior

When tapping a cell on the Notifications follower screen, the cell unexpectedly stays selected.

### Steps to reproduce the behavior

1. Locate a new follower notification (e.g. "**Juan** followed your site **Site Title**")
2. Tap the notification to reveal the "n Followers" screen
3. Tap any of the followers and a modal screen is shown
4. Close the modal screen (tap X button)
4. Notice that the follower you tapped in Step 3 is still selected (cell is in grey state)

##### Tested on iPhone 11, iOS 14.5, WPiOS 17.4

Similar to https://github.com/wordpress-mobile/WordPress-iOS/issues/13307

**Comment by justtwago** [comment] 2024-03-06 18:58
Closing the issue since I cannot reproduce it.

**Closed as completed by justtwago** 2024-03-06 18:58 UTC
Labels: Notifications
