### ISSUE TITLE
WPContentView should update when provider changes

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/WordPress-iOS#1824] opened 2014-06-10 16:13 UTC
As I'm refactoring comments for REST, I noticed the comment view doesn't update after editing a comment. Unless you go back to the comments list, select the comment again, and the comment view is regenerated.

The `WPContentViewProvider` protocol doesn't include a way to communicate changes, and `WPContentView` is only configured on `setContentProvider:`, which would be fine if the provider was immutable. You can't even re-set the provider to force an update:

```obj-c
    if (_contentProvider == contentProvider)
        return;
```

**Comment by rachelmcr** [comment] 2015-11-27 13:25
I tested this in the latest 5.8 beta and can't reproduce the issue. When I edit a comment, as soon as I save the changes I see the updated comment on the comment detail view. When I go back to the comments list, I also see the updated comment there.

Closing this as it looks like it's no longer an issue. (Please reopen if I missed something.)

**Closed by rachelmcr** 2015-11-27 13:25 UTC
Labels: General
