### ISSUE TITLE
Reader: Improve failed loading post error message on detail

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#4566] opened 2015-12-15 15:30 UTC
The post detail shows a generic "Error Loading Post" message when a post fails to load.  We could make a few changes to the failure block in `WordPressComAPI HTTPRequestOperationWithRequest:success:failure:` and include some additional information in the `NSError userInfo` dictionary to improve error message displayed.  For example, including the http status code would let us specify a post failed to load because it was private in the case of a 403 error.

**Comment by yaelirub** [comment] 2020-06-10 23:08
Closing as duplicate of #13525

**Closed by yaelirub** 2020-06-10 23:08 UTC
Labels: General, Reader, [Pri] Low, [Type] Broken Window, [Type] Enhancement
