### ISSUE TITLE
Site Creation > New Site Doesn't Open after Creation

### ISSUE THREAD

**Issue by startuptester** [wordpress-mobile/WordPress-iOS#17928] opened 2022-02-10 03:40 UTC
### Expected behavior
I expect a newly created site to open after I dismiss Quick Start and I'll see the My Site screen

### Actual behavior
It goes back to the site "Choose a site to open." screen

### Steps to reproduce the behavior
1. Log in
2. Select Create New Site 
3. Create a site and choose a domain
4. Tap Create Site
4. A preview will appear, tap Done
5. Quick Start will ask if you want help with this site. Tap no. 
6. You are back where you started instead of My SIte

https://user-images.githubusercontent.com/66104034/153332807-0e5f4437-e03f-4ded-a0b0-ca7587ae1c39.MP4

##### Tested 
on iPhone 13 Pro, iOS 15.3, WPiOS 19.1

**Comment by antonis** [comment] 2022-02-10 12:38
I tested the appstore version `19.1` on an iPhone SE 2020 (14.7.1) and a latest `trunk` version on an iPhone 13 Pro (15.2) simulator and wasn't able to reproduce this. I wonder if this has to do with the iOS version 🤔 

https://user-images.githubusercontent.com/304044/153409907-162dc3a1-b3c2-46e2-b4ff-d764a3746397.mov

**Comment by twstokes** [comment] 2022-02-11 15:38
I was unable to reproduce this as well, but did see what may be a clue:

| Domain selected | Domain shown on preview |
| ----------------- | -------------------------- |
<img width="295" alt="Screen Shot 2022-02-11 at 10 32 55" src="https://user-images.githubusercontent.com/2092798/153620709-c640f44f-f7c4-4930-b78d-5ad4fdc9b826.png"> | <img width="295" alt="Screen Shot 2022-02-11 at 10 32 40" src="https://user-images.githubusercontent.com/2092798/153620881-490e5491-ef66-4160-976d-dda9fb4b74e9.png">

@startuptester selected [mynewsite.business.blog](https://mynewsitebusiness.wordpress.com), but the preview shows [mynewsitebusiness.wordpress.com](https://mynewsitebusiness.wordpress.com) (which redirects to [mynewsite.business.blog](https://mynewsitebusiness.wordpress.com)). 🤔

**Comment by startuptester** [comment] 2022-02-11 19:12
Wow, good find @twstokes!

**Comment by antonis** [comment] 2022-02-14 08:12
> I was unable to reproduce this as well, but did see what may be a clue

That's an interesting find indeed @twstokes! I wonder if we check the site name to see if a new site was created and that leads to the issue in corner cases like this 🤔

**Comment by twstokes** [comment] 2022-02-14 19:32
>I wonder if we check the site name to see if a new site was created and that leads to the issue in corner cases like this 🤔

That sounds quite plausible @antonis! I'll dig and see what I can find.

**Comment by twstokes** [comment] 2022-02-19 04:02
Although these are probably two separate issues, I wanted to make note of https://github.com/wordpress-mobile/WordPress-iOS/issues/17993 and https://github.com/wordpress-mobile/WordPress-iOS/issues/17982.

**Comment by twstokes** [comment] 2022-02-21 18:59
@startuptester and @antonis I dug into this issue fairly deeply but was never able to reproduce it. My conclusion was that at the end of the new site creation (which appeared to be successful), the site picker view was never dismissed. Since there has been [recent work and refactoring related to this flow](https://github.com/wordpress-mobile/WordPress-iOS/pull/17814), I wonder if we should pause this deep dive until it can be reproduced.

If this can be reproduced, please reassign me and I'll be happy to continue troubleshooting. 🙇

**Comment by antonis** [comment] 2022-02-24 08:05
Thank you for investigating this @twstokes 🙇 

> If this can be reproduced, please reassign me and I'll be happy to continue troubleshooting. 🙇

I agree to put this issue a side till we have a way to reproduce 👍

**Comment by kean** [comment] 2024-08-14 17:22
The ad-hoc site picker after login is no longer in the picture. I think it's safe to assume this is no longer an issue, closing.

**Closed as completed by kean** 2024-08-14 17:22 UTC
Labels: Site Creation
