### ISSUE TITLE
Media: Unable to upload audio file from Voice Memos app

### ISSUE THREAD

**Issue by mdrockwell** [wordpress-mobile/WordPress-iOS#16068] opened 2021-03-11 16:56 UTC
### Expected behavior
Audio files recorded in the Voice Memos app and saved to Files should upload to media library.

### Actual behavior
Error occurs instead:

```
The operation couldn't be completed.
(WordPress.MediaURLExporter.URLExportError
error 2.)
```

### Steps to reproduce the behavior
1. Record an audio clip in the Voice Memos app.
2. Tap on the … icon and select "Save to Files".
3. Save the file in any location.
4. In the WordPress app, navigate to the Media Library
5. Tap on the + button.
6. Select "Other Apps"
7. Select your audio recording from Voice Memos
8. An error appears.

![Markup on 2021-03-11 at 11:54:18](https://user-images.githubusercontent.com/42454301/110824067-b3350600-8260-11eb-98dd-feed27bba2fd.png)

##### Tested on iPhone 11 Pro, iOS 14.4, WPiOS 16.9.0.0

**Comment by jd-alexander** [comment] 2021-03-12 02:29
@ceyhun could this in any way impact Audio block flow? meaning someone may try to do an upload this way to be able to access it from the Audio block?

**Comment by ceyhun** [comment] 2021-03-12 12:35
Yes indeed this seems to not work on Audio block as well. I was able to reproduce this on WPiOS 16.8 and 16.9 both from media library and Audio block on a wpcom site with premium plan.

**Comment by eduardozulian** [comment] 2021-03-30 18:52
Reported by a user in 3866804-zen with WPiOS 16.9

**Comment by mdrockwell** [comment] 2021-04-17 19:04
Another report here: 3901679-zen

**Comment by ceyhun** [comment] 2021-04-21 16:45
I came across a similar issue in 3926774-zen and I think this is in general about .m4a files rather than specifically Voice Memos (which also happen to use .m4a format). 

When I try uploading an .m4a from Safari and Firefox using an Audio block, I get this error:

<img width="600" src="https://user-images.githubusercontent.com/1845482/115589134-c90e0000-a2cf-11eb-97de-731f14ac08c1.png">

But when I tried uploading an .m4a from Safari using web's media library from https://wordpress.com/media/ **and it was successful**! I then used that media in an Audio block and it worked! Although I had some playback issue when I previewed the page:

<img width="600" src="https://user-images.githubusercontent.com/1845482/115590039-cfe94280-a2d0-11eb-94f9-5362eb03983d.png">

There also seems to be a warning about .m4a files at [this link](https://wordpress.com/support/accepted-filetypes/#audio.). It says `.m4a (might not work in all browsers)` and suggests `re-encoding it again to .m4a`. I tried re-encoding the .m4a and uploading again using an Audio block both from web browser and mobile, but still got the same errors (security one on web and `URLExportError error 2` on WPiOS). 

I didn't get to test it on WPAndroid yet, @jd-alexander maybe you can give me a hand to see if uploading an .m4a on WPAndroid works via Audio block or from media library?

I'm also curious about the security reasons that are valid inside the block editor but not in the media upload page on web, and if those security reasons are also an issue on mobile, how do you think we can investigate this @jd-alexander?

**Comment by thabotswana** [comment] 2021-05-19 08:23
A similar report here: 3996219-zen

**Comment by sla8c** [comment] 2022-01-26 15:33
Hi, this looks like its fixed by the PR https://github.com/wordpress-mobile/WordPress-iOS/pull/16450

I've tested a .m4a file as well as a VoiceMemo file using the VoiceMemo app

Tested on WPiOS v19.0

Test steps that I actioned:
1. I downloaded this .m4a on my device https://filesamples.com/samples/audio/m4a/Symphony%20No.6%20(1st%20movement).m4a
2. Opened WPiOS and navigated to the MediaLibrary
3. Tapped on the + button
4. Select "Other Apps"
5. Selected this file and it uploaded successfully with successful message
![image](https://user-images.githubusercontent.com/88816724/151166831-32e6cca6-9109-4de2-80ae-8c8a1fa0b4c4.png)


6.  On desktop browser (Safari) wordpress.com I navigated to Media Library and can play the .m4a in browser
<img width="785" alt="image" src="https://user-images.githubusercontent.com/88816724/151166965-4845422e-4907-4a1b-b943-1c4fdb2afedf.png">

7. I repeated same steps with a .m4a created from Voice Memos app and it worked as well.

VoiceMemo m4a upload from WPiOS
<img width="473" alt="image" src="https://user-images.githubusercontent.com/88816724/151167476-58a2266a-ed5a-4352-bee9-a50d0004f6db.png">

VoiceMemo m4a played successfully via desktop safari on Wordpress.com
<img width="854" alt="image" src="https://user-images.githubusercontent.com/88816724/151167661-6be488a1-9eb0-4b67-aa78-ea76fe32f19b.png">

**Closed as completed by sla8c** 2022-01-26 15:33 UTC
Labels: Media
