### ISSUE TITLE
Error message is not shown if something went wrong during the deletion of a comment

### ISSUE THREAD

**Issue by sendhil** [wordpress-mobile/WordPress-iOS#525] opened 2013-11-14 08:19 UTC
Reported by @daniloercoli 
- Go to the comments list
- Tap on a comment
- Disable the XML-RPC services on your blog, or shutdown the server (, or reply with an invalid response)
- Delete the comment

Error message is not shown to the user, and the comment you tried to delete is not in the list. You need to refresh the comments list to see it again.

Original trac thread [here](http://ios.trac.wordpress.org/ticket/1049)

**Comment by kurzee** [comment] 2016-10-25 22:11
Note: this still reproduces, leaving open.

**Comment by yaelirub** [comment] 2020-06-08 22:39
Unable to reproduce this anymore. Following the steps, I disabled XML-RPC on my blog and deleted a comment. The comment was deleted successfully. I'd like to close this issue. @rachelmcr, can you please confirm just to make sure Im not way off here? 😬

**Comment by rachelmcr** [comment] 2020-06-09 10:50
@yaelirub I can still reproduce the issue using the original steps. Here are the exact steps I took:

1. Add a comment on a test site.
2. Open My Site > Comments in the app and confirm I see the comment there.
3. Disable XML-RPC with the [Disable XML-RPC](https://wordpress.org/plugins/disable-xml-rpc/) plugin.
4. Check the [XML-RPC Validator](https://xmlrpc.eritreo.it/) to confirm that XML-RPC is disabled. (The validator shows a 405 response with the error message `XML-RPC services are disabled on this site.`.)
5. In the app, select the trash icon to delete the comment.
6. Go to wp-admin > Comments on the web and refresh the page. Notice the comment still appears there.
7. In the app, refresh the comment list. Notice the comment does not appear there, and there was no error message shown in the app.

**Comment by yaelirub** [comment] 2020-06-09 17:54
Thanks @rachelmcr ! I'll leave this one open then

**Comment by aerych** [comment] 2021-08-05 20:46
This one was partially resolved by recent improvements to comments messaging (h/t @ScoutHarris).  An error message was being shown, however the comment was being deleted from core data prior to the API request completing. Due to the failure the deleted comment faulted and the app appeared to be in a broken state. 
<img width="239" alt="Screen Shot 2021-08-05 at 3 36 14 PM" src="https://user-images.githubusercontent.com/1435271/128417733-c5e8f0a9-b914-443e-b429-51089d7077d9.png">

**Closed** 2021-08-17 20:26 UTC
Labels: [Type] Bug, [Pri] Low, Trac, General
