### ISSUE TITLE
Unresolved Core Data save error (Derived Context) in SourcePostAttribution.post

### ISSUE THREAD

**Issue by loremattei** [wordpress-mobile/WordPress-iOS#13892] opened 2020-04-14 10:13 UTC
**Sentry Url**: https://sentry.io/share/issue/1c7329b09b694798b6a0df9eea315e1f/
**User Count**: 541
**Count**: 6356
**First Release**: 13.4.1.1
**First Seen**: 2019-11-05T22:56:33Z
**Last Release**: 14.5.0.2
**Last Seen**: 2020-04-14T03:16:03Z
**24 Hours**: 10
**30 Days**: 380

**Stacktrace**:
```
Unresolved Core Data save error (Derived Context): Non-optional property with a nil value on SourcePostAttribution.post
    at null.__exceptionPreprocess(null:null)
    at null.objc_exception_throw(null:null)
    at null.-[NSException raise](null:null)
    at null.ContextManager.handleSaveError(ContextManager+ErrorHandling.swift:69)
    at null.ContextManager.handleSaveError(<compiler-generated>:null)
    at null.-[ContextManager internalSaveContext:](Classes/Utility/ContextManager.m:328)
    at null.__65-[ContextManager saveDerivedContext:andWait:withCompletionBlock:]_block_invoke.65(Classes/Utility/ContextManager.m:153)
    at null.developerSubmittedBlockToNSManagedObjectContextPerform(null:null)
    at null._dispatch_client_callout(null:null)
    at null._dispatch_lane_serial_drain$VARIANT$mp(null:null)
...
(4 additional frame(s) were not displayed)
```

**Comment by yaelirub** [comment] 2020-04-17 01:09
SourcePostAttribution is being used in the reader so I'd like to bump this one's priority. 
We've been dealing with context saving issues on the derived and main for some time (for example: https://github.com/wordpress-mobile/WordPress-iOS/issues/13429). I'd love a fresh set of eyes on this. @emilylaguna , would you mind digging in seeing if you can find something?

**Comment by jleandroperez** [comment] 2020-05-06 18:29
### Few notes on this one:
- **ReaderPost** has a N to 1 relationship with **SourcePostAttribution**
- Deletion rule is set to cascade (from ReaderPost > SourcePostAttribution)
- Inverse deletion rule is nullify

Deleting a ReaderPost should, effectively, get rid of the SourcePostAttribution.
My theory on this one would be a race condition in the **ReaderPost / SourcePostAttribution** sync'ing code.

I'm not sure **exactly** what happens if two (parallel) derived contexts interact with the same entity, one of them gains access, while the other one deletes it. Suggestion is to start by checking what shape that scenario has (does the entity in the former context get deleted / nullified?)

#### Suspect sequence:
1. Follow a new site from the reader
2. [refreshPostsForFollowedTopic](https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/WordPress/Classes/Services/ReaderPostService.m#L198)
2. [fetchPostsForTopic](https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/WordPress/Classes/Services/ReaderPostService.m#L107)
3. [ReaderPostService::mergePosts](https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/WordPress/Classes/Services/ReaderPostService.m#L729).


#### Proposed Fix
We **had similar issues** in the past, in Notifications, involving multiple Sync OP(s) happening concurrently, in parallel Derived Contexts.

This rendered an inconsistent CoreData state (a worker inserting entities, while another worker deleted entities). Specifically, we had duplication, but Notifications doesn't really have nested entities, so it's highly likely this is another manifestation of the same issue.

My fix, back then, was to implement [NotificationSyncMediator](https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/WordPress/Classes/Services/NotificationSyncMediator.swift).

Similar concept as a Service, but with a shared Derived context, with thread safety access. We could attempt to replicate the same mechanism (or perhaps in a simplified way, single Service, all of the OPs running in the same CoreData queue).

**Comment by emilylaguna** [comment] 2020-05-06 20:46
I looked into this last week and a bit today but unfortunately wasn't able to reproduce this issue following the conventional flows in the app, or following some of the  Sentry. 

I was however able to reproduce this by manually editing the databases `ZPOST` field on the `ZSOURCEPOSTATTRIBUTION` table to `NULL` which resulted in the following when scrolling around the reader:

<img width="50%" alt="screenshot" src="https://user-images.githubusercontent.com/793774/81220063-90c5c280-8f95-11ea-9e22-36282f337fbd.png">

I then took a bit more of an unconventional approach which involved mapping the WordPress API to a local sandbox and manually returning the JSON for the posts then removing/editing/adding rows in between refreshes. Unfortunately this did not yield in any reproduction of the error. 

One of the things I did locally that sort-of fixed this was to set the `post` attribute on the `SourcePostAttribution` model to optional. While this did fix the issue, I'm not able to recommend that as a fix right now since I am not familiar enough with how our CoreData database is structured yet and what other potential issues that could cause.

**Comment by designsimply** [comment] 2020-06-13 00:23
Closing as fixed because the [90-day graph for issue.id:1316724417](https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=release&field=os&field=device&field=culprit&name=All+Events&project=1438083&query=issue.id%3A1316724417&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1) is showing a significant drop in events and [no new events have been recorded for the 14.9.0.4 release](https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=release&field=os&field=device&field=culprit&name=All+Events&project=1438083&query=issue.id%3A1316724417+release%3A14.9.0.4&sort=-timestamp&statsPeriod=30d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1) since it went out on 2020-06-01. 👍

<img width="1026" alt="Screen Shot 2020-06-12 at Jun 12 6 22 01 PM" src="https://user-images.githubusercontent.com/1119271/84555378-cd45b600-acd9-11ea-961e-38c57efa61f9.png">

**Closed by designsimply** 2020-06-13 00:23 UTC
Labels: Core Data, Reader, [Pri] High, [Type] Crash
