### ISSUE TITLE
Add support for multiple WordPress.com accounts

### ISSUE THREAD

**Issue by Sh4rky** [wordpress-mobile/WordPress-iOS#6204] opened 2016-11-16 17:29 UTC
### Expected behavior
The user should be able to login with multiple wp accounts, and then being able to switch between them

### Steps to reproduce the behavior

When the user is logged in with a WP.com account should see 'Add Account' option in 'Me' section. And on the navigation bar tap in on the title should show a list of current users. 
Disconnect Account, will remove current account and set as default the next logged in account available

**Comment by rachelmcr** [comment] 2017-03-16 09:03
A user noted in an app review that they want this feature:

> Vad hände med att ha flera konton och kunna växla mellan? Lägger jag nu till mitt andra konto (+, På egen server) så försvinner den första :( :(

Translation:

> What happened to have multiple accounts and switch between? Do I now to my other account (, on your own server) will disappear the first :( :(

Note: Some users expect this to be an existing feature (as in this review) due to the issue resolved in https://github.com/wordpress-mobile/WordPress-iOS/issues/3401.

**Comment by rachelmcr** [comment] 2017-03-16 10:59
Looks like this is a dupe of this issue: https://github.com/wordpress-mobile/WordPress-iOS/issues/6015

**Closed by rachelmcr** 2017-03-16 10:59 UTC
Labels: General, [Pri] Low, [Type] Enhancement
