### ISSUE TITLE
Cannot post to Atomic Site as an author

### ISSUE THREAD

**Issue by adamjohndaly** [wordpress-mobile/WordPress-iOS#16858] opened 2021-07-13 17:44 UTC
### Expected behavior

Creating or editing posts I own as an author will not fail to upload. 
### Actual behavior
Error message saying Post Failed to Upload

### Steps to reproduce the behavior
1. Be an author on an Atomic site
2. Create blog post on WP iOS client
3. Publish
4. Error message stating Post Failed to upload.

##### Slack ID 
p1626191963467800-slack-C03URUK5C

##### Zendesk
4136410-zen

![IMG_BF1B46CF018F-1](https://user-images.githubusercontent.com/18173779/125500690-b0736d08-bbcf-41bb-84c7-689e9eb68826.jpeg)

**Comment by SiobhyB** [comment] 2021-07-13 19:40
Noting that I was also able to replicate this issue on an iPhone XR, iOS 14.6, WPiOS 17.8. 

The user mentioned that they first noticed the issue around three months ago and I found that there was also an issue with authors on Atomic sites losing access on the web around that timeframe: https://github.com/Automattic/wp-calypso/issues/51794. I'm not certain if it's relevant, but thought I'd make a note of it just in case!

**Comment by SiobhyB** [comment] 2021-07-14 08:58
I did a bit more testing and confirmed this _isn't_ reproducible on Android for me, only on iOS. 

I also went digging through Zendesk to see if there are other user reports and only found one other so far, in 4019961-zd-woothemes. I followed up with that user in 4138243-zd-woothemes to let them know we're currently looking into this issue.

The common errors in the logs are as follows:

```
2021-07-12 11:27:14:718 Failed syncing settings for blog https://[redacted].com: Error Domain=WordPressKit.WordPressComRestApiError Code=7 "You do not have the capability to manage settings for this site." UserInfo={WordPressComRestApiErrorMessageKey=You do not have the capability to manage settings for this site., WordPressComRestApiErrorCodeKey=Forbidden, NSLocalizedDescription=You do not have the capability to manage settings for this site.}

2021-07-12 11:27:14:750 Failed checking muti-author status for blog https://[redacted].com: Error Domain=WordPressKit.WordPressComRestApiError Code=2 "User cannot view authors for specified post type" UserInfo={NSLocalizedDescription=User cannot view authors for specified post type, WordPressComRestApiErrorCodeKey=unauthorized, WordPressComRestApiErrorMessageKey=User cannot view authors for specified post type}
```

**Comment by hypest** [comment] 2021-07-14 14:58
Thanks for raising @adamjohndaly and triaging @SiobhyB !

@diegoreymendez gave it a look and there's indeed an issue with the API calls for posting to Atomic sites, on WPiOS. Along with @twstokes and Diego we have identified the [recent work](https://github.com/wordpress-mobile/WordPress-iOS/pull/16269) that has contributed to the issue. Tanner will collab with @guarani to land a fix.

**Comment by twstokes** [comment] 2021-07-15 00:07
We've determined that for limited users on Atomic sites (authors, contributors), the app was sending the wrong author ID on the API calls to create a new page or post. This is because there's a difference between their wp.com ID and what the Atomic site uses.

The proposed fix will be in https://github.com/wordpress-mobile/WordPress-iOS/pull/16870 and will be aimed at the current beta, 17.8. Thanks for surfacing this!

**Comment by hypest** [comment] 2021-07-16 09:58
Closing as https://github.com/wordpress-mobile/WordPress-iOS/pull/16870 got merged.

**Closed as completed by hypest** 2021-07-16 09:58 UTC
Labels: [Pri] High, Posting/Editing
