### ISSUE TITLE
Clicking on featured image crashes in WordPress app on iOS 

### ISSUE THREAD

**Issue by scwbrian** [wordpress-mobile/WordPress-iOS#19211] opened 2022-08-19 01:40 UTC
##### Tested on iPhone 13 Pro MAX, IOS 15.6, WPiOS version 20.

https://user-images.githubusercontent.com/111547899/185524149-ab318c40-7c7c-4838-96f2-b9e3cd6b2a2c.mp4

**Comment by twstokes** [comment] 2022-08-19 01:45
👋 @scwbrian we're aware of this crash and [merged the fix today](https://github.com/wordpress-mobile/WordPress-iOS/pull/19198) for it to be included in the `20.5` [release](https://github.com/wordpress-mobile/WordPress-iOS/milestone/226) which should go to the App Store on August 22nd. Thank you!

**Closed as completed by twstokes** 2022-08-19 01:45 UTC

**Comment by scwbrian** [comment] 2022-08-19 01:49
Thank you, tried everything.
Should I delete the app and re-download it then or just go to updates?

**Comment by twstokes** [comment] 2022-08-19 01:51
Updating from the App Store should work fine once `20.5` appears. If the problem isn't fixed after you do, please feel free to reopen this issue and we'll take a look.

**Comment by scwbrian** [comment] 2022-08-19 01:52
Okay great, do you have an ETA that day? My colleague - more or a less a website client is pretty antsy with this stuff

**Comment by twstokes** [comment] 2022-08-19 02:03
Unfortunately we won't have an ETA for that and we're also not guaranteed it'll appear that day for multiple reasons. However, looking back at our last two versions it's appeared in the App Store a day before our [milestone date](https://github.com/wordpress-mobile/WordPress-iOS/milestones?state=closed) so possibly it'll be available on the 21st.
