### ISSUE TITLE
Reader: Slow loading Followed Sites > Manage screen

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#6080] opened 2016-10-17 14:55 UTC
### Expected behavior

I expect to see a "loading" message while sites load on the Followed Sites > Manage screen in the Reader, or to have all sites appear quickly there.
### Actual behavior

A small number of sites appear at first when you open the Manage screen, and after waiting the rest of the list loads.

As [reported by Ryan](https://test.wordpress.com/2016/10/06/session-notes-editor-customizer-undo-ays-vscroll-macnchrome-iphone-7/):

> This showed only four entries for about 10 seconds then filled.

![image](https://cloud.githubusercontent.com/assets/8658164/19442571/9f5dbf72-9481-11e6-9c0d-e584e1735d53.png)
### Steps to reproduce the behavior

I have seen this on my iPhone 6, iOS 10.0.1, but I can't reproduce the issue consistently. I will watch for consistent steps to repro the behavior.

**Comment by hoverduck** [comment] 2017-01-27 16:57
As best I can tell (but not 100% sure) this is a problem where you have a few sites in the Reader, then add more sites via the web, then go back to re-load the Manage Sites list.  With a fast network it loads the remaining sites quickly, but a spotty connection takes a while.

Conversely, if you don't have any sites in the list already it does show a Loading screen as it pulls the list down

**Comment by leandroalonso** [comment] 2021-03-24 20:37
I can't reproduce this issue. Since it's quite dated I'm closing it.

**Closed by leandroalonso** 2021-03-24 20:37 UTC
Labels: Performance, Reader, [Type] Bug
