### ISSUE TITLE
Reported: some posts are stuck as drafts in the app even though they are published.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#9449] opened 2018-05-23 22:12 UTC
See p4a5px-2cs-p2 for details.

A wpcom user (WPiOS 9.9) has reported that several of their posts continue to show up as drafts in the app even though they have been published and show up as published on her blog.

A screen shot provided shows an example of a post in the draft filter, with the local changes label.  A link to the post shows its published. 

The user has deleted/reinstalled previously to clear up the drafts but new instances of the bug reappear. 

So far I've been unable to reproduce the glitch or determine a likely code path that would yield the reported behavior.  

Let's track future reports here (if any) and look for new details to determine the cause.

**Comment by rachelmcr** [comment] 2019-08-27 11:24
I came across three user reports like this last week. In each case, the user had local changes to a draft in the app, and they had since published that draft on the web and didn't know how to sync those remote changes with the app.

I instructed the users on how to open the posts in the app and discard the local changes (after confirming that they didn't want to save those local changes), which allowed them to sync with the remote version of the post. In each case, those instructions worked for the users.

I think the issue may be that the `Local` label isn't meaningful to these users and isn't instructive (they aren't sure how to resolve it). Have we considered using the same label/flow that was implemented for Android in https://github.com/wordpress-mobile/WordPress-Android/pull/8989?

**Comment by zdenys** [comment] 2019-12-04 16:08
(As pointed by @rachelmcr I'm reposting it here as it's the correct place).

Another report in 2536903-zen. Posts (not Pages) that have been published already on the site are still appearing in the app in Draft and Scheduled tabs respectively with annotation Local changes below them.

I asked the user to follow the above suggestions.

**Comment by rezzap** [comment] 2019-12-18 08:06
I have another report of a confused user who didn't understand how to remove local changes to a draft since publishing in the browser. 

2565337-zen

**Comment by zdenys** [comment] 2019-12-27 16:30
Another case 2587245-zen of a user reports that posts published from their laptop appear as drafts on iPad Air 3rd generation with iOS 13.1.3 on WordPress App 13.6.

**Comment by pmciano** [comment] 2020-02-18 20:27
Another case in 2695726-zen.

Additional info:

- WordPress iOS app version `14.1`
- Device is iPhone SE
- iOS version `13.3`

Their full app log is provided in their ticket.

**Comment by leandroalonso** [comment] 2020-03-16 13:01
I was checking 2778345-zen and one thing caught my attention: based on the logs, the user is closing the editor and no option to discard changes is appearing.

That makes me wonder if this is what's causing the issue. I wasn't able to reproduce it, but it's a case that [might possibly happen](https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/WordPress/Classes/ViewRelated/Post/PostEditor+Publish.swift#L192) if the post is local and has the `shouldAttemptAutoUpload` property as `true`.

However, I'm still not 100% sure that this is the issue with all the cases, I do also believe in what @rachelmcr mentioned, that the `Local Changes` label is not very informative and is causing confusion.

The main thing is: if there's a local version and the user doesn't discard it, the most up-to-date version of the post won't be displayed. It's there, but it won't be visible.

For comparison, we're not receiving those requests in Android and there are two main different issues:

1. Android has different handling for discarding changes;
2. When the case above happens (the user has a local version but the post was published in the web or other device), they show the message "Version conflict" to the user and when trying to edit it a prompt appears:

| Post list        | Prompt           |
| ------------- |:-------------:|
| <img src="https://user-images.githubusercontent.com/7040243/76760446-711bd600-676c-11ea-8ea3-34e50ec721c4.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/7040243/76760543-99a3d000-676c-11ea-804d-d514f9a8c7d4.png" width="300px" /> |

I wonder if the proper fix to this is to match the iOS feature with Android. Or maybe at least change the warning to a meaningful message.

**Comment by rezzap** [comment] 2020-03-17 13:01
I have another report of something similar here. The user's post got stuck with 'local changes' after it was scheduled and published. 

Full set of logs in the ticket for more details.
WordPress.com Personal plan site
iOS 14.3

2766017-zen

**Comment by rezzap** [comment] 2020-03-19 12:58
Another report in 2799770-zen 

"My version of a post worked on my mobile app, when I update it, the previous edits I made on my desktop version the night before get completely undone. How do I maintain both edited versions on desktop and edits done via mobile app both current?"

Pulling down to refresh the post list can help to sync posts that have made changes in the app but any posts with changes made in desktop remain unsynced. 

I'm asking the user to try to discard local changes and will update with the results.

**Comment by rezzap** [comment] 2020-04-10 13:56
Another report in 2851663-zen

This time the posts show as drafts and published at the same time. I'm asking them to get rid of the local draft.

**Comment by designsimply** [comment] 2020-06-08 23:49
This came up in an app review:

> I wrote a blog post on desktop and scheduled it for this Thursday. It said all changes were saved. I open the app and the post is not under the scheduled tab, but the Drafts tab. It is also missing edits that I made on the desktop site. Now either the desktop site, or the app is not refreshing/saving properly. I do not like publishing something with glaring errors. I proofread for hours. According to the app, my last revisions on desktop weren’t saved or they’re just not showing up on the app!
> 
> <sup>1-star review "Am frustrated " – Jan 13, 2020 – Version 13.9</sup>

**Comment by designsimply** [comment] 2020-06-13 02:41
This came up in an app review:

> For self-hosted sites not using JetPack this app can be frustrating. Published posts never move from drafts to posts in the app.
> 
> <sup>2-star review by Newer Reviewer Tour - Mar 16, 2020 - Version 14.3</sup>

**Comment by ericamQA** [comment] 2020-12-03 21:00
Another instance at zd-3539737 

Asked them to update to the latest app version as well as Jetpack.

**Comment by mchowning** [comment] 2021-03-30 17:25
Spent a bit of time trying to reproduce these issues, but I didn't have any luck either.

**Comment by kean** [comment] 2024-05-01 16:58
The sync engine was re-engineering in the scope of pcdRpT-6vS-p2:
- The "local changes" scenario was eliminated
- The queries that display the post of lists are dramatically simplified
- The damage done by the "offline posting" project was reverted
- There is a new conflict detection mechanism to ensure the app never overwrites the changes made elswhere

**Closed by kean** 2024-05-01 16:58 UTC
Labels: [Type] Bug, Posting/Editing, User Expectations, App Review Request
