### ISSUE TITLE
Editor: Publish button is active immediately after creating new (empty) post

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#14115] opened 2020-05-13 15:30 UTC
### Expected behavior

I expect the Publish button to only be active when a post has some content, so it can be saved.

### Actual behavior

The Publish button is active immediately after creating a new post, even though the post is empty.

Publishing the empty post causes a "Post failed to upload" message to appear, and the app retries the upload (and shows the message again) every time I open the app after that. It continues until I open the empty draft in the editor and then exit the editor again, at which point the post disappears.

Note that this has come up in the past (see https://github.com/wordpress-mobile/WordPress-iOS/pull/4830 where it was previously fixed); we should ensure there are tests in place to prevent this regression.

### Steps to reproduce the behavior

1. Create a new post.
2. Tap the Publish button.
3. Tap Publish Now in the pre-publishing nudge.
4. Notice that a draft with "(no title)" appears in the Blog Posts > Drafts list, and a "Post failed to upload" message appears.

<img src="https://user-images.githubusercontent.com/8658164/81832396-5b414c00-9536-11ea-81f6-2028f292eb20.jpeg" width="300px">

**Comment by dcalhoun** [comment] 2021-03-30 18:39
I was unable to reproduce this on iPhone SE, iOS 14.4.2, WPiOS 16.9 (16.9.0.13). The Publish button remains disabled while the draft post has no content. I think we can likely close this. @rachelmcr what do you think?

https://user-images.githubusercontent.com/438664/113039340-2a253680-915d-11eb-9a11-893c9ba56b33.MP4

**Comment by dcalhoun** [comment] 2021-04-01 14:27
Closing this as non reproducible but, please feel free to reopen if it still occurs, thanks!

**Closed by dcalhoun** 2021-04-01 14:27 UTC
Labels: Posting/Editing, [Pri] Low, [Type] Bug
