### ISSUE TITLE
Disable WhatsNew for New Editor

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#4573] opened 2015-12-16 12:49 UTC
I think the editor has been around enough where we don't need to pop up what's new for it. I know we're seeing it a lot because we uninstall and reinstall a bunch more than regular users would. But I think the editor is good enough to not have to point out that our old editor sucked to new users, right?

@sendhil @diegoreymendez

**Comment by diegoreymendez** [comment] 2015-12-16 13:43
Sounds reasonable to me.

**Comment by diegoreymendez** [comment] 2015-12-16 21:16
Closing since this is a duplicate of [this issue](https://github.com/wordpress-mobile/WordPress-iOS/issues/4414).

**Closed by diegoreymendez** 2015-12-16 21:16 UTC
Labels: Editor, General, review
