### ISSUE TITLE
مشروع١

### ISSUE THREAD

**Issue by AbdullahZahaiyan** [wordpress-mobile/WordPress-iOS#17295] opened 2021-10-11 15:51 UTC
مشروع١

**Comment by designsimply** [comment] 2021-11-01 23:34
Closing because there is not enough information to go on and it looks like this may have been posted by mistake. If you would like to submit a bug about the WordPress iOS app, please [create a new issue](https://github.com/wordpress-mobile/WordPress-iOS/issues/new) and please make sure to include the following details: 

* Expected behavior
* Actual behavior
* Steps to reproduce the problem
* List your device, iOS, and app versions.

**Closed as completed by designsimply** 2021-11-01 23:34 UTC
