### ISSUE TITLE
Bug: App does not preserve scroll location in blog when going into the background when the cursor does not mark a location in the blog

### ISSUE THREAD

**Issue by susered** [wordpress-mobile/WordPress-iOS#14416] opened 2020-07-05 21:44 UTC
### Expected behavior

If a blog post is in edit-mode and the blinking cursor (keyboard hidden) has not marked a place for editing yet, then the user scrolls down anywhere beyond the start of blog post. If the user puts the WordPress iOS app in the in the background, then the expected behavior would be when the user goes back to the WordPress iOS app, the user's place would be preserved. 

### Actual behavior

The user's previously scrolled location is not preserved but rather at the start of the blog post again.

The unexpected behavior can be mitigated by scrolling to the location where the user might make an edit. Then place the blinking cursor anywhere. Then the user can put the app in the background, and then come back to the WordPress iOS app to the location where the user placed the cursor. The WordPress iOS app does not scroll to the start of the blog.

Also, the floating keyboard feature in iPadOS creates interesting iOS app behaviors such as what is described above as well.

### Steps to reproduce the behavior

1. Open a long blog post

2. Do not touch the screen such that a blinking cursor exists.

3. Scroll down to anywhere in the blog post.

4. Put the WordPress iOS app in the background.

5. Go back (foreground) to the WordPress iOS App.

6. The screen should be back at the start of the blog posting.

##### Tested on [device], iOS [version], WPiOS [version]
iPad Pro, 13.5.1, 15.0.1

**Comment by rachelmcr** [comment] 2020-07-08 10:46
I tested this with an iPad Mini (iPadOS 13.5.1) using WPiOS 15.0.1 and the latest internal beta (15.2.0.20200707) and can't reproduce this issue.

When I background the app, it always reopens at the same place in the post where I left it. Here's a screencast showing an example of that behavior: https://cloudup.com/cYW3jU59-5L

I'm going to close this issue since it doesn't seem to be reproducible, but you're welcome to share more details and we can revisit it!

**Closed by rachelmcr** 2020-07-08 10:46 UTC
Labels: Posting/Editing, [Type] Bug

**Comment by susered** [comment] 2020-07-09 02:28
Please attached. Your recreation was not exactly as I specified in my description. I have attached a screen video of my actions within an existing post in WordPress for iOS.

[recreation-2020-07-08-222258.mp4.zip](https://github.com/wordpress-mobile/WordPress-iOS/files/4894111/recreation-2020-07-08-222258.mp4.zip)

**Comment by rachelmcr** [comment] 2020-07-09 10:37
Thank you for that video! From there I can see that you're using the app's classic editor. Currently, we're focused on developing the app's newer block editor, which does preserve the scroll location (using the same steps shown in your recording). Since the focus on the block editor, we don't plan to address behavior like this in the classic editor at this point, although patches are welcome if someone would like to contribute a fix.

To use the block editor in the app, you can go to My Site > Settings and enable "Use block editor." If you are editing posts in the app that were created on the web, be sure to use the WordPress block editor on the web as well.

**Comment by susered** [comment] 2020-07-09 12:02
Yep, that is a difference. I admit I do not gravitate towards the Block Editor. I intentionally disabled its functionality.

The quirk started about a month ago with a recent upgrade. I know it is not a high priority issue but it is a bug.

I guess I have a choice of using the Block Editor or live with the quirkiness of the Classic Editor.

Thanks
