### ISSUE TITLE
Unable to add a self-hosted site to the mobile app if 2FA is enabled 

### ISSUE THREAD

**Issue by alinclamba** [wordpress-mobile/WordPress-iOS#23475] opened 2024-08-05 12:13 UTC
## Issue Description

On a self-hosted site, if you use a plugin to set 2FA, you are not able to add that site to the Jetpack mobile app. 

We received the following review from a user about that:

> No 2FA support
In a self-hosted WordPress with two-factor authentication (2024!), you cannot log in with the app. This has been known for years and will not change.

I was able to replicate this issue by following these steps:

1. Installed a random 2FA plugin on one of my self-hosted sites: [WP 2FA Plugin](https://wordpress.org/plugins/wp-2fa/).
2. Configured 2FA on that site via the web interface.
3. Opened the Jetpack mobile app on iOS and attempted to add the new self-hosted site.
4. After entering the username and password, I received an error stating that the username or password are incorrect.
5. Disabling the 2FA plugin via the web interface allowed me to add the site to the app successfully.

## Expected Behavior
The Jetpack mobile app should allow users to add self-hosted WordPress sites that have 2FA enabled, successfully authenticating and providing access to the site's management features.

## Actual Behavior
When attempting to add a self-hosted site with 2FA enabled to the Jetpack mobile app, the app fails to authenticate the user, displaying an incorrect username or password error despite correct credentials being used.

## Environment
Tested on iPhone 13, iOS 17.6
Jetpack iOS 25.1

_____

Issue reported here: 8570969-zd-a8c

**Comment by dangermattic** [comment] 2024-08-05 12:13
Thanks for reporting! 👍

**Comment by kean** [comment] 2024-08-13 17:31
Closing as duplicate of https://github.com/wordpress-mobile/WordPress-iOS/issues/23475

**Closed as completed by kean** 2024-08-13 17:31 UTC
