### ISSUE TITLE
Pages List: App crash after screen loading

### ISSUE THREAD

**Issue by brbrr** [wordpress-mobile/WordPress-iOS#9295] opened 2018-05-08 11:13 UTC
### Expected behavior

No crash when loading Pages list

### Actual behavior

For some of my sites app is crashing when I loading Pages list

### Steps to reproduce the behavior

1. Launch app with logged in user
1. Select a site
1. Open Site Pages

I was able to reproduce it with Woo store and Simple WP.com sites: `testbrbrratsite.blog`, `brbrrtestbloggggg.wordpress.com`

##### Tested on iPhone SE, iOS 11.3, WPiOS 10.0.20180507

![screenrecording_05-08-2018 14-14-28](https://user-images.githubusercontent.com/5654161/39754272-4fb5e5ea-52ca-11e8-9a67-4282e22d96c7.gif)

(not sure why, but recording stops right after crash, so the crash is not actually visible)

**Comment by frosty** [comment] 2018-05-08 14:10
Previously reported in #9182, should've been fixed in #9209 (but clearly still present).

**Comment by aerych** [comment] 2018-05-08 14:37
Confirming I can reproduce on my test blog.

**Comment by aerych** [comment] 2018-05-08 15:45
Seeing this in develop.  Guessing it reverted due to a bad merge somewhere:
<img width="821" alt="screen shot 2018-05-08 at 10 44 24 am" src="https://user-images.githubusercontent.com/1435271/39767660-e424690e-52ac-11e8-8731-a0d81579ca22.png">

**Comment by aerych** [comment] 2018-05-08 16:15
I think here's our culprit: https://github.com/wordpress-mobile/WordPress-iOS/commit/b5480e82780f7130daf98d5c74d8463b0c01bbda

Looks like version 75 was created but didn't include changes made to version 74.

**Closed as completed** 2018-06-13 09:26 UTC
Labels: [Type] Crash
