### ISSUE TITLE
Reader: Placeholder content appears if you switch tabs while Reader screens are loading

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#15437] opened 2020-12-04 13:35 UTC
### Expected behavior

I expect that any time I open a Reader screen I'll either see a ghost view (while content is loading) or the expected Reader content.

### Actual behavior

If I open a Reader screen, see a ghost view (because content is being loaded), and switch to another tab in the app, then when I open the Reader again I see placeholder content that doesn't scroll.

This happened to me repeatedly while dogfooding the Reader, after I first logged in to the app, since it was taking a long time for my Reader feeds to finish loading.

### Steps to reproduce the behavior

1. Start logged out of the app (since the ghost view in the Reader is most visible after the initial login).
2. Log in to a WordPress.com account.
3. Open the Reader tab.
4. While the content is still loading in the Reader, switch to another tab (My Site or Notifications).
5. Open the Reader tab and notice the placeholder content is now visible, and you can't scroll on the screen.

### Screenshots

Placeholder content|GIF
-|-
<img src="https://user-images.githubusercontent.com/8658164/101169421-c9657180-3634-11eb-9df8-ad1988fa9b4b.PNG" width="300px">|<img src="https://user-images.githubusercontent.com/8658164/101169646-29f4ae80-3635-11eb-83f0-3e8dbd977aeb.gif" width="300px">

**Comment by designsimply** [comment] 2020-12-10 23:33
Oof, this was hard for me to spot (you have eagle eyes!) and I agree it's easier to see it if you both have a slow internet connection and you are using an account that is following a lot of sites in the Reader. ([49s](https://cloudup.com/ctPt4lel4EW)) Also, in my testing, the placeholder content isn't shown very long and after it loads I can scroll normally—which I assume is why it's labeled low priority. Here are some screenshots from a test using dark mode.

Ghost view from step 3|Content still loading view from step 5
---|---
![Screen Shot 2020-12-10 at Dec 10 4 24 53 PM](https://user-images.githubusercontent.com/1119271/101842106-958ebe00-3b04-11eb-82f7-f3b11363172e.png)|![Screen Shot 2020-12-10 at Dec 10 4 25 01 PM](https://user-images.githubusercontent.com/1119271/101842118-99224500-3b04-11eb-8326-477936121679.png)

<sup>Tested with WPiOS 16.3.0.5 TestFlight beta on iPhone 11 iOS 14.2 using account design5279 which is currently following 67 sites and 1 tag.</sup>

**Comment by rachelmcr** [comment] 2020-12-11 16:01
You need a trip to my part of the world, to experience the joys of always testing on slower internet connections. ;) The real content takes much longer to load for me, but indeed everything works fine once the real content finishes loading so I'd say it's low priority (more of a visual issue than a significant functional issue).

**Comment by ovitrif** [comment] 2022-11-16 12:16
I've noticed a similar issue while beta-testing WP-iOS `21.2.0.0` .

It's now more likely to occur since there's another issue on Reader which prevents posts filtered by topic to appear ([link](https://github.com/wordpress-mobile/WordPress-iOS/issues/19607)).
It's also more critical now imho, since the placeholder content never gets replaced.

**Repro Steps:**
1. Go to `Reader` → `Discover` → tap any topics
2. **Expect** content to never load
3. Put app in background
4. Open it again
5. **Notice** the placeholder content remains forever


https://user-images.githubusercontent.com/4588074/202178319-a9f4d557-69da-40f7-9334-f32366d20bcb.mp4

**Comment by ovitrif** [comment] 2022-11-18 10:33
> I've noticed a similar issue while beta-testing WP-iOS 21.2.0.0 .

>It's now more likely to occur since there's another issue on Reader which prevents posts filtered by topic to appear (https://github.com/wordpress-mobile/WordPress-iOS/issues/19607).
>It's also more critical now imho, since the placeholder content never gets replaced.

I reverted the priority to `Low`, since with the fix from https://github.com/wordpress-mobile/WordPress-iOS/pull/19621 this bigger problem described in the [comment above](https://github.com/wordpress-mobile/WordPress-iOS/issues/15437#issuecomment-1316918677) is gone, and the only remaining issue is visual, which still reproduces with the [initial repro steps](https://github.com/wordpress-mobile/WordPress-iOS/issues/15437#issue-757107448).

**Comment by daniloercoli** [comment] 2024-02-26 11:00
Closing this issue since I cannot replicate it on the latest Jetpack version (24.2).

**Closed as completed by daniloercoli** 2024-02-26 11:00 UTC
Labels: [Pri] Low, Reader
