### ISSUE TITLE
Reader Feed does not refresh

### ISSUE THREAD

**Issue by rezzap** [wordpress-mobile/WordPress-iOS#10392] opened 2018-11-03 12:52 UTC
### Expected behavior

I would expect that navigating to the reader and pulling down to refresh would update the feed. I've been having this issue for about a week now using the Automattic feed and it was just reported by a user in 1538008-zen.

### Actual behavior

The loading icon is frozen at the top of the page and doesn't refresh until I go back to the main reader page or close the app completely. I then go back to the reader feed in question to refresh and it loads new posts. 

![reader bug](https://user-images.githubusercontent.com/10325627/47952443-42ca9b80-df67-11e8-8335-01bfb81144bd.png)

### Steps to reproduce the behavior

1. Open the app and go to Reader
2. Open one of the streams either 'followed sites' or 'teams' list and pull down. 
3. If no new posts are available, the wheel should keep spinning.
4. Go visit a different app and then return to the reader. 
5. At the top, the wheel will be frozen and pulling down to refresh does not change anything. 
6. Click on Reader to go back to the main page and then go back to the reader feed. 
7. The icon is removed and you can pull down to refresh again.

**Comment by stevebaranski** [comment] 2018-11-06 22:06
Thank you for reporting this issue @rezzap. Upon investigation, we believe this issue is a duplicate of #10356, which has been resolved in the v11.1 release.

**Closed by stevebaranski** 2018-11-06 22:06 UTC
Labels: Reader, [Type] Bug
