### ISSUE TITLE
On tapping 'Edit' from the posts list, the search bar is briefly visible

### ISSUE THREAD

**Issue by roop** [wordpress-mobile/WordPress-iOS#4036] opened 2015-07-19 07:59 UTC
When transitioning from the posts list to the post editor directly using the 'Edit' button of a post in the posts list, the search bar becomes briefly visible during the push transition.

![210ac114-2944-11e5-88d2-b06727eb7b47](https://cloud.githubusercontent.com/assets/554/8762098/a4b049fc-2d8c-11e5-8864-7f78692e49d9.png)

The status bar is shown when in the posts list and hidden when editing a post. When the status bar disappears while the app transitions to the post editor, it reveals a bit of the search wrapper view (that was hidden underneath the navigation bar).

This issue was previously discussed in #3992.

**Comment by sendhil** [comment] 2015-07-22 01:47
cc @kwonye

**Comment by hoverduck** [comment] 2017-01-24 16:43
Closing; I'm unable to reproduce

**Closed by hoverduck** 2017-01-24 16:43 UTC
Labels: Pages List, Posts List, [Type] Enhancement
