### ISSUE TITLE
[GlobalStep] “Continue with WordPress.com” Log In option is unnecessarily cropped

### ISSUE THREAD

**Issue by wptester9845** [wordpress-mobile/WordPress-iOS#13466] opened 2020-02-14 10:36 UTC
### Description
After the user presses Log In, the option “Continue with WordPress.com” is cropped to “Continue with...ordPress.com” this crop is unnecessary and the ```...``` takes about as much space as the replaced text ``` W``` would.
This issue only happens on small devices but there is enough space for the whole message to fit its button.

### Reproduction Rate
4/4 100%

### Expected behavior
The message “Continue with WordPress.com” should be fully displayed.

### Actual behavior
The message is cropped to “Continue with...ordPress.com”.

### Steps to reproduce the behavior
1. Install WordPress 14.2
2. Press the Log In button.
##### Tested on the following
iPhone SE (12.0.1)
iPhone 5S (11.4)

#### Please see the attached screenshot for more information
<img width="270" src="https://user-images.githubusercontent.com/60415523/74523851-d7b39700-4f15-11ea-8c31-745e9748932a.jpg" />

### Submitted by:
Luis Pimenta

**Comment by rachelmcr** [comment] 2020-02-14 11:13
It looks like there isn't quite enough room for the text with the button padding, but the string is shortened in a very unfortunate way (especially as a first impression). This could also be relevant for i18n, i.e. if other languages make this string too long even on larger devices.

**Comment by ScoutHarris** [comment] 2020-02-14 19:37
@rachelmcr we could probably address this in the Unified Auth project. Since @mattmiklic is still working on the designs, maybe a solution can be worked out. 

(cc @mindgraffiti )

**Comment by mindgraffiti** [comment] 2020-02-14 21:24
Hey @ScoutHarris thanks for the ping! @rachelmcr it's added to our Unified Auth project.

**Comment by ScoutHarris** [comment] 2020-03-20 21:56
Fixed with https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/213.

**Closed by ScoutHarris** 2020-03-20 21:56 UTC
Labels: Login, [Type] Bug

**Comment by ScoutHarris** [comment] 2020-03-23 18:54
I'm going to leave this closed as a dupe of https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/issues/155. But noting here that this is no longer fixed. https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/issues/155 has been reopened and will track the issue.
