### ISSUE TITLE
App stops responding if post-post sharing to Messages is cancelled

### ISSUE THREAD

**Issue by nheagy** [wordpress-mobile/WordPress-iOS#6544] opened 2017-02-01 18:57 UTC
App locking up, likely due to post-post's hidden presenter not being dismissed.

Reported in 6.9 beta.

### To reproduce:
1. Create a new post
2. Tap Share from the post-post screen
3. Tap Message in the share sheet
4. Without sending a message, tap Cancel

### Result:

The app no longer responds.

**Comment by koke** [comment] 2017-02-02 06:45
Dupe of #6446?

**Comment by nheagy** [comment] 2017-02-02 17:44
@koke absolutely is. Wasn't sure the best thing to do, so I closed that one…

**Closed** 2017-02-02 21:46 UTC
Labels: Posting/Editing, [Pri] High, [Type] Bug
