### ISSUE TITLE
No results view should use more of available horizontal layout on wider screens

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#4348] opened 2015-10-06 13:56 UTC
The default width can result in some unfortunate wrapping where a wider screen would allow for all the text on a single line.   For example:

![simulator screen shot oct 6 2015 8 46 40 am](https://cloud.githubusercontent.com/assets/1435271/10310553/18183cce-6c08-11e5-949c-a61cc3e41365.png)

Let's have it adjust its size smartly.

**Comment by jleandroperez** [comment] 2015-10-07 20:28
Thanks for filing this one @aerych!

**Comment by hoverduck** [comment] 2017-01-24 20:33
The "No unread notifications" notice is no longer line-wrapped as shown in the initial issue here, but Comments and Followers still are.  I'm not sure if that's by design or if it's still desired that they be on the same line.  There's plenty of room, but they are long strings and I could see the argument that it looks better wrapped.

Seen here on iPad:
![803110377_8999014124306657274](https://cloud.githubusercontent.com/assets/7233112/22265498/4d37df7c-e24a-11e6-82ea-200e86f061b2.jpg)
![803721228_12993839429698851790](https://cloud.githubusercontent.com/assets/7233112/22265499/4fcf496e-e24a-11e6-86c9-160ab0a2c87f.jpg)

**Comment by ScoutHarris** [comment] 2018-06-05 18:00
This should be resolved with https://github.com/wordpress-mobile/WordPress-iOS/issues/9504, but leaving open for now to verify.

**Comment by ScoutHarris** [comment] 2018-08-17 19:15
Replacing all instances of NoResults is still ongoing (https://github.com/wordpress-mobile/WordPress-iOS/issues/9504) but Notifications have been fixed with https://github.com/wordpress-mobile/WordPress-iOS/pull/9969.

![iphone_landscape](https://user-images.githubusercontent.com/1816888/44284602-842c9400-a21f-11e8-8732-1ae7dc0809af.png)

**Closed by ScoutHarris** 2018-08-17 19:15 UTC
Labels: General, [Pri] Low, [Type] Enhancement
