### ISSUE TITLE
Video Thumbnails do not load in Mobile Web / Jetpack iOS Mobile App

### ISSUE THREAD

**Issue by cuemarie** [wordpress-mobile/WordPress-iOS#22020] opened 2023-11-09 19:45 UTC
### Expected behavior

When viewing a post containing videos in the mobile app, that the videos' thumbnails load.

### Actual behavior

Video thumbnails are not loading; so the videos just appear as blank space with the play button.

### Steps to reproduce the behavior

1. Upload a video to a blog post via the Jetpack App
2. Publish the post
3. View the post in the app, or via Reader
4. Observe that the video thumbnail does not load, even though you can press play and play the content of the video.

| Uploading in the Editor | Viewing the Post |
| ------------- | ------------- |
| ![IMG_2006](https://github.com/wordpress-mobile/WordPress-iOS/assets/27249804/7d1032d9-0973-4a85-a099-c1def53ebeca) | ![IMG_2007](https://github.com/wordpress-mobile/WordPress-iOS/assets/27249804/6cdd0494-7f2e-41c1-87f0-bec115f8bed1) |

https://github.com/wordpress-mobile/WordPress-iOS/assets/27249804/246bd992-ca85-45ee-93ae-86ed38fbfef3

##### Tested on [device], iOS [version], Jetpack iOS / WordPress iOS [version]

- Tested on iPhone XR, iOS 16.6.1, Jetpack iOS 23.5.2.0
- Tested with a simple (advanced features not activated) site on a WordPress.com Business plan
- Reported by a WordPress.com customer here: 7261816-zen

**Comment by twstokes** [comment] 2023-11-10 00:38
Thanks for the report! I was able to reproduce this on a .com Simple site.

#### Adding a video via the Video block in the app
- ✅ The video thumbnail in the app editor worked
- ❌ The thumbnail was not shown in the app's web views or Reader
- ❌ The thumbnail was not shown in Mobile Safari

#### Adding the same video via the Video block on web
- ❌ The video block was not populated in the app editor
- ✅ The thumbnail was shown in the app's web views and Reader
- ✅ The thumbnail was shown in Mobile Safari

**Comment by SiobhyB** [comment] 2023-11-10 18:29
Thank you for the report! Adding my notes:

**Adding a video via the Video block in the app**

I was only able to reproduce this on the iOS app, on both a public and a private simple site. I couldn't reproduce on Android, which makes me wonder whether this could be a Safari-related issue, similar to what we've previously seen with images not displaying for private sites (see: https://github.com/wordpress-mobile/WordPress-iOS/issues/15596).

**Adding the same video via the Video block on web**

I was able to reproduce this in both iOS and Android, and tracked the issue down to a change in the way we render the media placeholder in Gutenberg. I've got a proposed fix in the works at https://github.com/Automattic/jetpack/pull/34073.

**Comment by SiobhyB** [comment] 2024-02-23 19:13
Noting that the issue with the video's placeholder not working upon upload was fixed in https://github.com/WordPress/gutenberg/pull/58015. In addition, upcoming changes to the video block in the 24.4 release will fix a number of other issues with the block, including those related to the block being unplayable in certain cases. I'll close this issue for now, but please feel welcome to reopen or create a new one if extra issues are spotted. 🙇‍♀️

**Closed as completed by SiobhyB** 2024-02-23 19:13 UTC
Labels: [Pri] Medium, Media, Gutenberg
