### ISSUE TITLE
Delay before interactivity after bringing app to foreground

### ISSUE THREAD

**Issue by twstokes** [wordpress-mobile/WordPress-iOS#20654] opened 2023-05-10 01:51 UTC
### Expected behavior
App to be immediately interactive and respond to user input.

### Actual behavior
- Sometimes there's a delay before the app is interactive
- This doesn't happen when Airplane Mode is enabled

| Airplane Mode off | Airplane Mode on |
| - | - |
| <video src="https://github.com/wordpress-mobile/WordPress-iOS/assets/2092798/3d6cb28b-9a95-45e6-b07c-919b19fdfb95" /> | <video src="https://github.com/wordpress-mobile/WordPress-iOS/assets/2092798/3488d4b7-a92e-4831-a5fb-5c0c9d2408a7" /> |

### Steps to reproduce the behavior
1. Send the app to the background
2. Bring the app to the foreground
3. Immediately try to scroll or switch views using the tab bar

**Comment by twstokes** [comment] 2023-05-10 01:53
Interestingly this only happened on my personal device in the evenings of GMT -4.

Ideas:
- Low battery
- ~Dark mode~ ruled this out
- Server-side latency

**Comment by tiagomar** [comment] 2023-06-04 03:49
I've reproduced it a couple times with full battery around 1 am GMT-3. 
Assigning Low priority since it's not 100% reproducible and the delay is quite short.

**Comment by tiagomar** [comment] 2023-07-07 20:54
Similar report: p1688752153311229-slack-C0180B5PRJ4
It mentions the app freezing for "a few seconds" and "being super frequent".

**Comment by twstokes** [comment] 2023-07-08 01:33
It appears that clearing the local device logs may be a workaround:

1. Open the app -> My Site
2. Tap your profile photo at the top right
3. Help & Support
4. Logs
5. Clear Old Activity Logs

**Comment by twstokes** [comment] 2023-07-08 15:17
I wanted to follow up and note that delays came back quickly in some cases.

Ref: p1688819425049569/1688752153.311229-slack-C0180B5PRJ4

**Comment by twstokes** [comment] 2023-07-10 18:49
To add another data point:

1. I cleared logs on my device and (it seemed to) remove the delay
2. A couple days went by and the delay started again
3. I put the device in Airplane Mode and the delay disappeared
4. I took the device out of Airplane Mode, the Internet connection came back, but the delay was also still gone

**Comment by dcalhoun** [comment] 2023-07-10 20:33
Clearing the activity logs appeared to help the several seconds delay I experienced, but I needed to quit and relaunch the app to see the improvement.

**Comment by aerych** [comment] 2023-07-10 20:39
I'm currently experiencing this in version 22.6.1 (iOS 16.5.1) iPhone 11 Pro.  For me, the app consistently is unresponsive for several seconds whenever I background and reopen the app, the tab I'm on doesn't seem to matter.  I've cleared activity logs but this doesn't seem to have made a difference. 
My first guess was there might be something blocking the main thread when the app is opened but I haven't dug any farther yet.

**Comment by aerych** [comment] 2023-07-11 03:30
I might have stumbled on steps to reproduce this consistently. Try this: 

- Start fresh by force closing the app.  Open and then background the app. Then open it again and confirm that the app is immediately responsive. 
- Switch to the reader tab. 
- Tap on a post with many comments and view the detail.
- Tap on the option to view the comments. 
- Background and reopen the app.  Confirm the app is **not** immediately responsive. 
- Back out of the comments to the post stream. (The stream shouldn't matter.)
- Background and reopen the app.  Confirm the app is **still** unresponsive.
- Switch tabs to either sites or notifications. Background and reopen the app.  Confirm the app is **still** unresponsive.

Can anyone repro with these steps?

**Comment by dcalhoun** [comment] 2023-07-11 13:19
> Can anyone repro with these steps?

Yes, I reproduced unresponsiveness (1-3 seconds) when following the [outlined steps](https://github.com/wordpress-mobile/WordPress-iOS/issues/20654#issuecomment-1630051541). Jetpack 22.7.0.0 on an iPhone 13 mini running iOS 16.5.1. Quitting and relaunching the app appeared to resolve the unresponsiveness.

**Comment by twstokes** [comment] 2023-07-11 18:43
I don't think the call to [`GutenbergSettings().performGutenbergPhase2MigrationIfNeeded()`](https://github.com/wordpress-mobile/WordPress-iOS/blob/48b8a391394f2b4aee9b886abe21f62a521c0a81/WordPress/Classes/System/WordPressAppDelegate.swift#L211) is doing any favors. It's also dependent on [Internet reachability](https://github.com/wordpress-mobile/WordPress-iOS/blob/48b8a391394f2b4aee9b886abe21f62a521c0a81/WordPress/Classes/Utility/Editor/GutenbergSettings.swift#L70) which corroborates (in my case) that Airplane mode has an effect. 

It looks like it iterates through [all the user's blogs](https://github.com/wordpress-mobile/WordPress-iOS/blob/48b8a391394f2b4aee9b886abe21f62a521c0a81/WordPress/Classes/Utility/Editor/GutenbergRollout.swift#L33) on every firing of `applicationDidBecomeActive`.

**Comment by aerych** [comment] 2023-07-11 22:46
Dug into this a bit. 
> It looks like it iterates through [all the user's blogs](https://github.com/wordpress-mobile/WordPress-iOS/blob/48b8a391394f2b4aee9b886abe21f62a521c0a81/WordPress/Classes/Utility/Editor/GutenbergRollout.swift#L33) on every firing of applicationDidBecomeActive.

I'm seeing this too. The check `return allBlogs.contains { $0.editor == .aztec }` references [this bit in Blog+Editor.swift](https://github.com/wordpress-mobile/WordPress-iOS/blob/48b8a391394f2b4aee9b886abe21f62a521c0a81/WordPress/Classes/Models/Blog%2BEditor.swift#L42):  `return mobileEditor ?? GutenbergSettings().getDefaultEditor(for: self)`.  A new instance of `Gutenbergsettings` is created, and this is where things get interesting. The convenience initializer is used which [creates a new instance of UserDefaults](https://github.com/wordpress-mobile/WordPress-iOS/blob/48b8a391394f2b4aee9b886abe21f62a521c0a81/WordPress/Classes/Utility/Editor/GutenbergSettings.swift#L46) as its database. 
```
    convenience init() {
        self.init(database: UserDefaults() as KeyValueDatabase)
    }
```
According to [the docs](https://developer.apple.com/documentation/foundation/userdefaults/1414356-init), initializing UserDefaults "Creates a user defaults object initialized with the defaults for the app and current user."   If we look at Instruments we can see the main thread has a severe hang where all those calls to check the blogs create new instances of UserDefaults that each are populated with the current defaults. 
<img width="1658" alt="Screenshot 2023-07-11 at 3 31 33 PM" src="https://github.com/wordpress-mobile/WordPress-iOS/assets/1435271/9db11e76-766a-4141-8f4c-de8526e52c0f">

Some quick testing suggests the hang could be resolved by passing `UserDefaults.standard` when instantiating GutenbergSettings, altering Blog+Editor.swift like so: 
```
    var editor: MobileEditor {
        return mobileEditor ?? GutenbergSettings(database: UserDefaults.standard).getDefaultEditor(for: self)
    }
```
I'm not 100% sure I understand if there was a reason GutenbergSettings needed a copy of user defaults rather than using the singleton instance.  There doesn't seem to be but I'm pretty unfamiliar with the related code. 

Thoughts?

**Comment by aerych** [comment] 2023-07-11 23:08
[Draft PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/21065) in case we like the change.

**Comment by twstokes** [comment] 2023-07-11 23:27
I totally agree @aerych - it seems to me that it was an oversight that the singleton wasn't called. Thanks for the all the great help with this!

**Closed as completed** 2023-07-12 02:37 UTC
Labels: [Pri] High, Performance

**Comment by shaunandrews** [comment] 2023-07-12 16:06
Very nice work, @aerych!
