### ISSUE TITLE
Stats events send wrong value for "period" property

### ISSUE THREAD

**Issue by irfano** [wordpress-mobile/WordPress-iOS#22752] opened 2024-03-03 14:44 UTC
### Expected behavior

Events should send "days", "weeks", "months", "years" instead of "day", "week", "month", "year".
https://github.com/wordpress-mobile/jetpack-issue-repo/issues/4

| Action | Event | Properties |
|-|-|-|
| Tap Date Backward | `stats_date_tapped_backward`  |  `period`:"days", "weeks", "months", "years" |
| Tap Date Forward | `stats_date_tapped_forward`  | `period`:"days", "weeks", "months", "years" |
| Tap Views | `stats_overview_type_tapped_views`  |  `period`:"weeks", "months", "years" |
| Tap Visitors | `stats_overview_type_tapped_visitors`  | `period`:"weeks", "months", "years" |
| Tap Comments | `stats_overview_type_tapped_comments`  |  `period`:"weeks", "months", "years" |
| Tap Likes | `stats_overview_type_tapped_likes`  | `period`: "weeks", "months", "years" |

### Actual behavior

| Action | Event | Properties |
|-|-|-|
| Tap Date Backward | `stats_date_tapped_backward`  |  `period`:"day", "week", "month", "year" |
| Tap Date Forward | `stats_date_tapped_forward`  |  `period`:"day", "week", "month", "year" |
| Tap Views | `stats_overview_type_tapped_views`  |  `period`:"week", "month", "year" |
| Tap Visitors | `stats_overview_type_tapped_visitors`  |  `period`:"week", "month", "year" |
| Tap Comments | `stats_overview_type_tapped_comments`  |  `period`:"week", "month", "year" |
| Tap Likes | `stats_overview_type_tapped_likes`  |  `period`:"week", "month", "year" |

### Steps to reproduce the behavior

1. Log in.
2. Open "My Site → Stats".
3. Take the actions listed above.

**Comment by dangermattic** [comment] 2024-03-03 14:45
Thanks for reporting! 👍

**Comment by guarani** [comment] 2024-03-04 14:43
Thanks for catching, @irfano!

I confirmed that these events are sending the period in **singular** when they should be sending it in **plural**:
- `stats_date_tapped_backward`
- `stats_date_tapped_forward`
- `stats_overview_type_tapped_views`
- `stats_overview_type_tapped_visitors`
- `stats_overview_type_tapped_likes`
- `stats_overview_type_tapped_comments`

> Events should send "day", "week", "month", "year" instead of "days", "weeks", "months", "years".
> https://github.com/wordpress-mobile/jetpack-issue-repo/issues/4

This should be reversed, right?

**Comment by irfano** [comment] 2024-03-04 15:05
> This should be reversed, right?

Yes! The table in the description is accurate, but my comment was incorrect. I have corrected it.

**Comment by guarani** [comment] 2024-03-04 17:12
Closing this after we decided to keep this as-is because the above property names have been around since before the Traffic tab project (see p1709564601197609/1709262268.077389-slack-C06BR07TJHK for decision).

**Closed as not planned by guarani** 2024-03-04 17:12 UTC
Labels: Stats, Observability
