### ISSUE TITLE
Latest Post Summary doesn't work if "API calls" are disabled on a Jetpack blog

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#7169] opened 2017-05-17 16:52 UTC
Original issue: https://github.com/wordpress-mobile/WordPressCom-Stats-iOS/issues/318

References: https://github.com/wordpress-mobile/WordPress-Android/issues/3187

**Comment by designsimply** [comment] 2019-10-30 19:54
I cannot see the original issue at https://github.com/wordpress-mobile/WordPressCom-Stats-iOS/issues/318.

I tested with the following steps and found that Stats don't work at all if the JSON API is disabled for a Jetpack site even if that site has an active Jetpack plugin with a connected WordPress.com user.

1. Go to `/wp-admin/admin.php?page=jetpack_modules`  for your Jetpack site. ([ref](https://jetpack.com/support/control-jetpack-features-on-one-page/))
1. Click the "Deactivate" link for `JSON API`.
1. Go to WPiOS > your Jetpack site > Stats.

<img src="https://user-images.githubusercontent.com/1119271/67893583-73162d00-fb1c-11e9-9a50-2d3010da42ce.PNG" width="270" alt="IMG_3021 1">
<sup>Tested with WPiOS 13.5.0.2 beta (TestFlight) on iPhone 6S iOS 13.1.3 using site `honest-spiders.jurassic.ninja` running WP 5.2.5 and Jetpack 7.8 logged in to the app as wpcom user `design5279`.</sup>

I believe this is the intended behavior. @ScoutHarris can you confirm whether the "JSON API" module is required for Stats to work for a Jetpack site in WPiOS and close this issue if so?

**Comment by ScoutHarris** [comment] 2019-10-30 20:12
Hey @designsimply .

That is correct - Stats will not work if the API is disabled.

However, looking at the old Android issue in the description, it looks like they displayed a different error message for that case. We could probably do the same. Would it be too much trouble to ask you to check Android and see what they display now?

**Comment by designsimply** [comment] 2019-10-31 21:52
I tested using WPAndroid 13.5-rc-1 and found that no error is displayed if you try to access Stats for a Jetpack site with the JSON API module disabled. ([37s](https://cloudup.com/cY-WdsUyORs))

<img src="https://user-images.githubusercontent.com/1119271/67988688-5d753600-fbf6-11e9-8b02-12d281979c2a.png" width="270" alt="stats-screen-with-json-api-disabled-wpandroid-13 5-rc-1">
<sup>Tested with WPAndroid 13.5-rc-1 on Pixel 3 Android 10 using site `dominant-right.jurassic.ninja` running WP 5.2.4, Jetpack 7.8 connected as WP.com user `design5279`.</sup>

**Comment by designsimply** [comment] 2019-11-15 18:58
Moved to https://github.com/wordpress-mobile/WordPress-iOS/issues/12957.

**Closed by designsimply** 2019-11-15 18:58 UTC
Labels: Stats, [Type] Enhancement
