### ISSUE TITLE
Login epilogue can't be dismissed when adding a site

### ISSUE THREAD

**Issue by frosty** [wordpress-mobile/WordPress-iOS#7267] opened 2017-05-31 16:21 UTC
When already logged into the app, add a new self-hosted site. A login epilogue screen will appears after successful login, but it can't be dismissed (tapping the 'done' button has no effect).

cc @nheagy

**Comment by nheagy** [comment] 2017-06-22 19:46
Dupe of #7270, tho with some detail as to what's happening. Thanks @frosty!

**Closed by nheagy** 2017-06-22 19:46 UTC
Labels: Login, [Type] Bug
