### ISSUE TITLE
Signup Flow Password Field

### ISSUE THREAD

**Issue by startuptester** [wordpress-mobile/WordPress-iOS#17927] opened 2022-02-10 02:07 UTC
### Expected behavior
If I tap to enter an optional password in the magic link flow and then change my mind, I want to dismiss the keyboard and move on. 

### Actual behavior
I am unable to dismiss the keyboard and I have to either tap the name field to edit my username and then go back, or create a password. 

### Steps to reproduce the behavior
1. Start the email address signup flow
2. Open the email and tap the magic link 
3. When the app opens, you should see the screen with your username and an **optional** password creation field 
4. If you tap in that field (and tell keychain you want to create your own), there is no way to dismiss the keyboard so you can't change your mind. You either have to create a password or tap on the username field and then go back to this screen.

**Comment by guarani** [comment] 2022-02-10 18:31
I can reproduce this issue, thanks for reporting @startuptester! 

The issue is that the keyboard covers the "Done" button. iPadOS provides a handy "keyboard dismiss" button so this is not an issue there, but on iPhones there is no such button.

The options I see are:
1. Put a custom "close keyboard" button above the keyboard
2. Make the blue "Done" button always sits above (floats above) the keyboard (of course, when the keyboard is not shown, it should go back to its normal current position at the bottom of the screen)
3. Make the keyboard dismiss by "swiping down" or "dragging down" from just above the keyboard
4. Make the keyboard dismiss by tapping anywhere on the screen (anywhere where there is not a text input or button)

My first preference is Option 2 because it's more intuitive for the user since they don't need to guess that the "Done" button might be behind the keyboard. The challenge might be to make this work on smaller devices such as the iPhone 13 mini where there is less space for a "Done" button between the existing content and the keyboard. 

My second preference would be option 3. Dragging down to hide the keyboard is a familiar gesture to users who use iOS' system Messages app, but is not super intuitive to all users (they have to guess there is a Done button behind the keyboard).

**Comment by guarani** [comment] 2022-02-10 20:24
I found that smaller devices (e.g. iPhone 13 mini) don't have space to float the "Done" button between existing screen content and the keyboard, so I went with Option 3 (drag down to dismiss keyboard):

https://user-images.githubusercontent.com/1898325/153490062-e19427c9-39c1-4456-a966-4627928c9932.MP4

I've made [a draft PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/17938) while I continue testing this.

**Comment by guarani** [comment] 2022-02-11 12:23
I only just realized the above screen-recording doesn't show the keyboard 🤦 😄

**Comment by startuptester** [comment] 2022-02-11 19:14
> I only just realized the above screen-recording doesn't show the keyboard 🤦 😄

haha yep. I tried to include one too and realized the same 😆

**Comment by guarani** [comment] 2022-03-16 17:42
Closed via https://github.com/wordpress-mobile/WordPress-iOS/pull/17938.

**Closed as completed by guarani** 2022-03-16 17:42 UTC
Labels: [Pri] High
