### ISSUE TITLE
Post List: Wrong prompt and scheduled post missing after restore from trash

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#4969] opened 2016-03-17 16:36 UTC
To reproduce:
- Open the post list to the scheduled filter
- Trash a scheduled post.
- Click the undo cell to restore the post from the trash. 
- The app will prompt that the post as restored to "Published"  rather than "Scheduled"
- The post is missing from the scheduled filtered list until the list is refreshed.

**Comment by hoverduck** [comment] 2017-01-25 16:34
Closing; Unable to reproduce on v6.8.0.20170112

**Closed by hoverduck** 2017-01-25 16:34 UTC
Labels: Posts List, [Type] Bug
