### ISSUE TITLE
Add some hints as to what a more complex password is

### ISSUE THREAD

**Issue by sendhil** [wordpress-mobile/WordPress-iOS#2497] opened 2014-10-01 09:01 UTC
If a user doesn't select a complicated enough password when creating an account they get the error message "Please try a more complex password". We should give them an example of what a more complex password is so they don't get stuck on this screen.

**Comment by koke** [comment] 2015-06-17 11:05
Is #2632 enough to close this?
Also, dupe of #1831

**Comment by allendav** [comment] 2015-10-24 15:03
Moving this to @astralbodies for reassignment

**Comment by astralbodies** [comment] 2015-10-26 19:10
Closing this as it's duplicated and this is the younger issue.

**Closed by astralbodies** 2015-10-26 19:10 UTC
Labels: General
