### ISSUE TITLE
Notifications about comments should take you to the right comment

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/WordPress-iOS#11818] opened 2019-05-30 11:55 UTC
When you receive a notification related to a comment (like, reply, mention), the header of the notification detail shows a tiny excerpt and links to the discussion. 

![35A8A75F-033E-4015-8B1C-1DF0A08E8E83](https://user-images.githubusercontent.com/8739/58631210-21a21180-82e2-11e9-9037-43c5bf870828.jpeg)

When you tap on it, you are taken to the comment list, but instead of scrolling to the right comment, the list stays at the top. 

![2A858D36-F415-423B-A421-2EC4CD1B58B1](https://user-images.githubusercontent.com/8739/58631211-21a21180-82e2-11e9-9ef1-ad2b8cae3cda.jpeg)

Sometimes it’s easy to find, but on longer threads it can feel impossible.

**Comment by designsimply** [comment] 2019-06-03 22:46
Thank you for the report! Closing as a duplicate of https://github.com/wordpress-mobile/WordPress-iOS/issues/5540.

**Comment by koke** [comment] 2019-06-04 11:27
Ah, thanks, I knew I had seen that one before, but I wasn't able to find it 😁

**Closed** 2019-06-14 00:11 UTC
Labels: Comments, Notifications, [Status] Duplicate, [Type] Enhancement
