### ISSUE TITLE
Remove ability to set post location from post settings

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-iOS#16439] opened 2021-05-06 13:38 UTC
### Expected behavior

Geotagging posts (setting their location) [is no longer supported on the web](https://wordpress.com/support/replacing-the-older-wordpress-com-editor-with-the-wordpress-block-editor/) and was [removed from WPAndroid](https://github.com/wordpress-mobile/WordPress-Android/pull/13378) about six months ago.
It's still there on WPiOS, but should be removed as well.

cc @yaelirub 

### Actual behavior

It's still possible to geotag posts on WPiOS 

### Steps to reproduce the behavior

1. Open Post Settings on a post or page
2. Notice that there is an option to set location

**Comment by startuptester** [comment] 2021-05-07 21:13
Thanks, @guarani! This is a duplicate of #16234

**Closed as completed** 2021-05-07 21:13 UTC

**Comment by guarani** [comment] 2021-05-10 13:31
> Thanks, @guarani! This is a duplicate of #16234

Thanks for catching that!
