### ISSUE TITLE
Add message content for no/weak connectivity error to stats.

### ISSUE THREAD

**Issue by yaelirub** [wordpress-mobile/WordPress-iOS#11004] opened 2019-02-12 00:07 UTC

**Comment by diegoreymendez** [comment] 2019-04-08 11:27
Is this change still needed?  Can you add a description to clarify?  Thanks!

**Comment by yaelirub** [comment] 2019-04-11 18:12
It was a suggestion by Will to add the content of the error message that is received due to no/ weak connectivity. Do you think it's necessary?

**Comment by diegoreymendez** [comment] 2019-04-12 15:47
@yaelirub - I don't have enough context to be able to answer... add the content of what error message where?

**Comment by diegoreymendez** [comment] 2019-04-12 15:52
I think part of the problem is that the issue as it is right now doesn't include enough information.

Can we have a full description of what the current situation is and what we want to change?

**Comment by yaelirub** [comment] 2019-04-12 17:39
Do we want to track the connectivity errors? @shiki, do you think there is value in that?

**Comment by shiki** [comment] 2019-04-12 18:05
@yaelirub I don't remember this being discussed. But to answer your question, I don't think there's any value to adding those. At least, not right now.

**Comment by yaelirub** [comment] 2019-04-12 18:35
I agree. I'll close this issue if there's no objection

**Comment by shiki** [comment] 2019-04-12 18:41
No objection! Closing it for you. 😄

**Closed by shiki** 2019-04-12 18:41 UTC
Labels: General, [Type] Task

**Comment by diegoreymendez** [comment] 2019-04-12 20:25
Thanks!
