### ISSUE TITLE
App Review: Unable to save draft even after reconnected to a working network source

### ISSUE THREAD

**Issue by reginabally** [wordpress-mobile/WordPress-iOS#15098] opened 2020-10-14 05:09 UTC
> If you write a draft in the app and you lose Internet connection while it’s trying to save the draft, say goodbye to it. It will endlessly try to save the post even after you reconnect and you won’t be able to stop it and use the app again. You can only force quit the app and restart it, but your draft will be gone. The draft isn’t even saved locally within the app.

Date of the review: Oct 12, 2020
WPiOS version: 15.8

**Comment by designsimply** [comment] 2020-10-14 22:54
Thanks for reporting this @reginabally!

I was unable to reproduce the problem using the following testing steps. I tested using WPAndroid 15.9-rc-2 on Pixel 3 with Android 11 using a WordPress.com Free site. It's possible the reporter was using a different setup so we should either run this test again under different scenarios or try to get additional information from the user about the problem.

1. Go to My Site > Blog Posts > Drafts > +.
1. Add a title and some content.
1. Tap More (three dots at top right) > Save.
1. Quickly turn off the network connection.
1. Observe that the new draft now has a notice on it in the Posts List that says, "We couldn't complete this action but we'll try again later."
1. Turn on the network connection again.
1. Go back to the Drafts list and observe that the draft automatically uploads.

<strong>Result:</strong> I was able to successfully save a new draft even if the internet connection is turned off while trying to save. ([1m20s](https://cloudup.com/ct8H8N6wFNA))

Go offline while draft is uploading|Post uploads after back online|Duplicate post created
---|---|---
<img src="https://user-images.githubusercontent.com/1119271/96052197-4268f980-0e3a-11eb-9055-282bc0a87e71.png" width="270" alt="Screen Shot 2020-10-14 at Oct 14 4 21 14 PM">|<img src="https://user-images.githubusercontent.com/1119271/96052195-4268f980-0e3a-11eb-8eeb-2b5f2d0e0750.png" width="270" alt="Screen Shot 2020-10-14 at Oct 14 4 21 23 PM">|<img src="https://user-images.githubusercontent.com/1119271/96052193-41d06300-0e3a-11eb-8422-c03688aa3a6f.png" width="270" alt="Screen Shot 2020-10-14 at Oct 14 4 21 31 PM">

<sup>Tested with WPAndroid 15.9-rc-2 on Pixel 3 Android 11 on a WordPress.com Free site (fuzzywuzzy.home.blog) while logged in as user design5279.</sup>

**Note:** in my test, I observed that a duplicate post was created and I'm able to reliably replicate that so I've reported it in a separate issue at https://github.com/wordpress-mobile/WordPress-Android/issues/13137.

**Comment by reginabally** [comment] 2020-10-15 07:57
I've tested this on iPhone SE, iOS 14.0.1, WPiOS 15.8 but I'm not able to replicate this issue.

Video recording: https://d.pr/v/QSmJcm/7ehXGN5P9z

**Comment by designsimply** [comment] 2020-10-16 19:54
Thank you for reporting this @reginabally!

I tried testing using my iPhone 6S and I was unable to reproduce the problem using the following steps:

1. Create a new post and add a title and some content.
1. Tap More (three dots, top right) > Save as Draft.
1. Quickly turn off the internet connection (i.e. turn on Airplane mode) while the draft is saving.
1. Observe that the draft saved locally.
1. Turn the internet connection back on.
1. Check to see whether the draft uploads.

<strong>Result:</strong> the draft uploads normally if the connection is dropped during save but a duplicate post is created. ([2m8s](https://cloudup.com/c6iHu1Jt5AE))

Connection dropped during save|Post uploaded twice after connection is restored
---|---
<img src="https://user-images.githubusercontent.com/1119271/96286550-c687c200-0f9d-11eb-9459-8c724651912e.png" width="270" alt="Screen Shot 2020-10-16 at Oct 16 10 48 47 AM">|<img src="https://user-images.githubusercontent.com/1119271/96286556-c982b280-0f9d-11eb-85e7-ffff6fadb194.png" width="270" alt="Screen Shot 2020-10-16 at Oct 16 10 49 37 AM">

<p style="clear:both;"><sup>Tested with WPiOS 15.9.0.1 TestFlight beta on iPhone 6S iOS 13.7 using a WordPress.com Free site.</sup></p>  

Note: I also tested Jetpack and self-hosted sites with the same results. ([1m7s](https://cloudup.com/c7E58bzN7gO) Jetpack, [37s](https://cloudup.com/c4jnWNpGqvB) self-hosted)

**Comment by designsimply** [comment] 2020-10-16 20:00
I responded to the review noting that we tested and were unable to replicate the problem and asking for more info if possible.

<sup>(internal reference: app-store-reviewId=6526972740)</sup>

**Comment by designsimply** [comment] 2020-10-16 20:02
Closing this issue with an ask to please re-open if it comes up again or if you find different testing steps we can try. Creating a new issue would also be fine if desired. 👍

**Closed as completed by designsimply** 2020-10-16 20:02 UTC
Labels: Posting/Editing
