### ISSUE TITLE
Posts/Pages for site sits and spins on iOS 7

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#4090] opened 2015-07-31 12:56 UTC
On iOS 7 with latest beta (release/5.5) if you log out, log back in, and then go to any site you know has posts and try to view them it sits on the Fetching posts.. screen. The network activity indicator continues to spin in the status bar but the screen never updates. The UI is actually locked at this point as well - I cannot tap on anything else.

**Comment by aerych** [comment] 2015-07-31 14:41
Booo
![screen shot 2015-07-31 at 9 40 48 am](https://cloud.githubusercontent.com/assets/1435271/9009662/4cd38100-3768-11e5-9d22-7ed07cdec386.png)

**Comment by astralbodies** [comment] 2015-07-31 14:45
Why won't anyone think of the children!?

**Comment by aerych** [comment] 2015-07-31 16:07
It looks like we have a deadlock caused by a couple of things. 

Part 1:
When the post list is accessed the table view has to calculate row height. Row heights are calculated by configuring a cell used purely for this purpose.  The cell will be configured multiple times depending on how many rows will be visible to the user.  In the current code, when the layout cell is configured, its UIImageViews are also set with the URL they should load. This kicks off an AFNetworking request to fetch the image.  However, the cells is being reusued for layout calculations so these requests never have enough time to complete.  When the layout cell is configured for the next row, the previous image's AFNetworking request is canceled in favor of the next. To cancel the request, an NSRecursiveLock is set in order to perform some thread safe clean up.  You can see all of this illustrated in the following stack trace.

![screen shot 2015-07-31 at 10 32 34 am](https://cloud.githubusercontent.com/assets/1435271/9010912/85035dfa-376f-11e5-8198-57aba2927b35.png)


Part 2:
Remember that first request to download an image? Its currently running on the AFNetworking thread, hence the reason for the NSRecursiveLock. The request is picked up by `PrivateSiteURLProtocol` in case the image is from a private blog and needs to be requested with the Bearer token. As a part of this check, we need to get the auth token and thanks to #4043 we're doing so in a thread safe fashion.  Kind of.  Here's the current code:
![screen shot 2015-07-31 at 10 36 12 am](https://cloud.githubusercontent.com/assets/1435271/9011076/a1dd2432-3770-11e5-86f5-b096fef9fd00.png)

Note that an NSRecursiveLock is already set when the AFURLConnectionOperation starts
![screen shot 2015-07-31 at 10 42 30 am](https://cloud.githubusercontent.com/assets/1435271/9011157/1484a064-3771-11e5-8ff8-23925ce842bf.png)

Also note that since we're not running on the main thread, we're fetching the auth token via a derived context via `performBlockAndWait`. Which ends up with a stack trace like so: 
![screen shot 2015-07-31 at 10 41 33 am](https://cloud.githubusercontent.com/assets/1435271/9011303/0a29925e-3772-11e5-8e33-05bb82ef3b61.png)

Freeze:
If I understand this correctly, the AFNetworking thread which started the image load is now blocked waiting on the derived context to return, and the UI is now blocked by the `NSRecursiveLock` called on the main thread when canceling the very same image load.

It seems we don't get a freeze on iOS 8 because the semaphore set by core data is being cleared property, and we do get a freeze on iOS7 because it is not. 

One way to mitigate the freeze is to avoid loading images in the layout cells, and this is an optimization that needs to be made anyway (no sense doing the work just to discard it! Patch coming!), but this doesn't fix the root cause.

Is there a better way to keep the request for the bearer token thread safe?

**Comment by aerych** [comment] 2015-07-31 16:08
cc @jleandroperez

**Comment by jleandroperez** [comment] 2015-08-03 12:29
We've got a seriously ugly bug here. Questions:

- Do we need to set the cell's image during the height calculation? (can we avoid that?) (@aerych)
- **Option A:**
  Remember #3409?. How about if we... do implement a helper. Say... `WordPressMainAccount`, could be a Singleton, or an instance referenced by the App Delegate. The bearer token would be always accessible, and we wouldn't be hitting Core Data the whole time.
- **Option B:** 
  Would be to have `PrivateSiteURLProtocol` grab the authToken once, and listen to Main Account changes. Which is.. the same thing as **A**, but encapsulated into `PrivateSiteURLProtocol`.

Opinions / Ideas?

:dancer:

**Comment by aerych** [comment] 2015-08-03 13:57
> Do we need to set the cell's image during the height calculation?

Heh heh. I mentioned the same thing in my previous comment, and is addressed in #4100 :) 

> and we wouldn't be hitting Core Data the whole time.

I am a fan of this. As for which approach to take, they both have merits but I lean toward Option A over B. Having `PrivateSiteURLProtocol` listen for acount changes seems odd to me.

**Comment by aerych** [comment] 2015-11-04 22:46
Closing as this was never broken on iOS 8 (and the app now only supports iOS9) and images are no longer fetched when calculating height.

**Closed by aerych** 2015-11-04 22:46 UTC
Labels: bug, Posts List
