### ISSUE TITLE
WordPress.com Plans Page available from "Sign up for WordPress.com" flow

### ISSUE THREAD

**Issue by jkmassel** [wordpress-mobile/WordPress-iOS#14756] opened 2020-08-25 20:50 UTC
### Expected behavior
Users can access the WordPress.com Plans Page via the "Sign Up for WordPress.com" flow.

### Actual behavior
They should not be able to do this

### Steps to reproduce the behavior
- Be logged out
- Tap "Sign up for WordPress.com" 
- Tap "Terms of Service"
- Choose "Sign Up" by scrolling to the bottom of the page, or from the "Menu" button
- Proceed with the signup flow until you see the Plans page

<img src="https://user-images.githubusercontent.com/1123407/91226378-279fc180-e6e2-11ea-8ec6-54a0d7f07406.PNG" width="256" />

**Comment by startuptester** [comment] 2021-03-06 00:10
Confirmed this is still possible in 16.8

**Comment by designsimply** [comment] 2021-07-08 16:36
Tested and confirmed that I can still reach information about plans in the sign up flow via the Terms of Service link on the login page in the WPiOS 17.7.0.3 app. In comparison, I am taken to an outside browser when I tap the Terms of service link in the WPAndroid app.

<img src="https://user-images.githubusercontent.com/1119271/124959019-03865f80-dfd8-11eb-86e0-88d8c53fc737.PNG" width="270" alt="IMG_4849"> <img src="https://user-images.githubusercontent.com/1119271/124959009-008b6f00-dfd8-11eb-881d-a94eed054541.PNG" width="270" alt="IMG_4850">

**Comment by designsimply** [comment] 2021-07-08 17:03
@chipsnyder would you be willing to take this one for a spin in the next maintenance rotation starting Jul 12?

**Comment by chipsnyder** [comment] 2021-07-08 17:23
Will do 🙂

**Comment by mokagio** [comment] 2021-07-12 01:42
@designsimply @chipsnyder I'm going to bump this to the 17.9 milestone for reporting purposes.

Although, if the fix happens to be straightforward and part of the iOS codebase (I'm not sure how it works, but it could be something that can be done on the backend, too right? E.g. when generating the ToS page, check user-agent, if iOS, don't show sign up in menu) it might be worth making it part of 17.8 to avoid Apple Review rejection because of that edge case.

**Comment by chipsnyder** [comment] 2021-07-21 21:17
I opted to take an approach on this one that mirrors the action Android is taken. A PR is available at https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/605 with some additional options/discussion that we can take if desired.

**Comment by chipsnyder** [comment] 2021-07-22 18:45
Closed by https://github.com/wordpress-mobile/WordPress-iOS/pull/16907

**Closed as completed by chipsnyder** 2021-07-22 18:45 UTC
