### ISSUE TITLE
Blue logo on launch screen on iPhone XR

### ISSUE THREAD

**Issue by jaclync** [wordpress-mobile/WordPress-iOS#11679] opened 2019-05-13 12:54 UTC
### Expected behavior
Logo should be white color on launch screen

### Actual behavior
Logo is blue on launch screen

<img src="https://user-images.githubusercontent.com/1945542/57622441-29fb0c80-75c0-11e9-8df0-1ff1ca3ede2f.PNG" width="200">

### Steps to reproduce the behavior
- Launch app
- Observe logo color on launch screen

##### Tested on [device], iOS [version], WPiOS [version]
iPhone XR, iOS 12.2, WPiOS 12.3

### Notes
* this issue does not happen on the other iOS device I have, iPad 5th gen. Also I couldn't reproduce this issue on various types of simulators including XR
* I did a quick check on `Launch Screen.storyboard`, the logo asset has white outline color while the image view has blue tint color (I think by default) and no outlet. Tint color is the only blue attribute I could find
* I couldn't build on a device, but would be happy to help test on a fix via some way like beta program :)

**Comment by designsimply** [comment] 2019-05-13 21:44
I tested on iPhone 6S, iOS 12.2, WPiOS 12.3 and the logo does look correct for me on that device.

<img src="https://user-images.githubusercontent.com/1119271/57641480-55efa100-7572-11e9-901f-1268ff2fbea9.PNG" width="270" alt="IMG_2745">

I also tried testing with the latest `develop` branch  with an iPhone XR simulator via Xcode and could see the logo there as well.

<img src="https://user-images.githubusercontent.com/1119271/57646784-9ce39380-757e-11e9-827d-452628e6f5b5.png" width="270" alt="Screen Shot 2019-05-13 at 12 47 05 PM">

**Comment by jaclync** [comment] 2019-05-14 03:16
Yea this issue cannot be reproduced on simulators and my other iOS device. I just built latest `develop` to my iPhone XR device (removed a bunch of extensions to get past issues with provisioning profiles), and was able to reproduce this issue.

I quickly looked into `Launch Screen.storyboard`, the logo image view has default blue tint color (the logo is blue in storyboard). There are two ways to fix it:
* Change the image view tint color to white
* Set `icon-wp` image's "Render as" (related to [`renderingMode`](https://developer.apple.com/documentation/uikit/uiimage/renderingmode)) from "Template Image" to "Original Image" in `AppImages.xcassets`

My guess for this issue: when an image asset's rendering mode is "Template Image", the color of the image can be updated by `UIImageView`'s `tintColor` similar to when `UIImage`'s `renderingMode` is set to `.alwaysTemplate`. When the image asset is used in storyboard, the `UIImage`'s `renderingMode` is most likely `automatic` and the actual rendering mode could be different on various types of devices.

The first fix seems more ideal, so that it does not affect other use cases of `icon-wp` in the app. What do you think?

**Comment by designsimply** [comment] 2019-05-14 20:08
@nheagy I noticed you recently opened an issue about switching to the new Classic Bright color palette at https://github.com/wordpress-mobile/WordPress-iOS/issues/11683 and I was wondering if you could chime in with some direction on this one?

**Comment by nheagy** [comment] 2019-05-14 20:53
No clue on this one. Maybe @ctarda can test it on his XR?

**Comment by ctarda** [comment] 2019-05-15 06:09
@nheagy I can reproduce it as well building and running directly on an XR

**Comment by richardmtl** [comment] 2019-05-16 20:37
I have had this FOREVER on my phone, which is a 5S; I had it on my old 5 as well. I had mentioned it to @frosty I believe a couple of years ago at least and forgot to come here to report it (sorry) :(

![IMG_1178](https://user-images.githubusercontent.com/3676359/57885391-d7586500-77f8-11e9-9997-7926271a9ac1.PNG)

I have had this through several iOS versions and WP app versions.

**Comment by nheagy** [comment] 2019-06-05 22:43
I'm seeing this on my 11 inch iPad Pro as well.

**Comment by nheagy** [comment] 2019-06-06 03:21
Update: this may be happening on iOS 13 now, as @realcarfax reports seeing it on an iPhone XS running the beta.

**Comment by jklausa** [comment] 2019-06-06 04:27
yeah, can confirm with iOS13 on my 6S Plus and 11 PRo.

**Comment by richardmtl** [comment] 2019-07-16 19:43
Sorry @danielebogo I am reopening this as I still see the issue on iOS app version 12.8. 

Oh, I can't re-open! I'll let you re-open it, then, or if you have different instructions for me, let me know.

**Comment by RealCarFax** [comment] 2019-07-16 19:56
I'm also still seeing the blue logo on blue background on my iPhone XS running iOS 13 beta 3

**Comment by jkmassel** [comment] 2019-07-16 20:03
This should be resolved by https://github.com/wordpress-mobile/WordPress-iOS/pull/12134.

It's going out in a hotfix release that's on its way to Apple now. Should be available tomorrow! 🤞

**Comment by richardmtl** [comment] 2019-07-18 21:45
Same problem still, 12.8.1. Sorry!

**Comment by jkmassel** [comment] 2019-07-18 21:47
Thanks @richardmtl – we'll investigate further!

**Comment by frosty** [comment] 2019-07-19 06:01
@richardmtl Would you mind testing with a fresh install of the app? I've seen some caching of the app's launch image going on when testing this issue (https://github.com/wordpress-mobile/WordPress-iOS/pull/12134) – upgrading users were fine, but fresh installs were missing the launch screen.

If that doesn't work, I have one more idea for a potential fix. Thanks!

**Comment by richardmtl** [comment] 2019-07-19 14:21
@frosty Reinstall fixed it! Now I need to log in again, boo ;)

**Comment by frosty** [comment] 2019-07-19 14:27
Well that's good to hear! It seems like the launch image can potentially get cached for a long time - I just found a thread on Apple's forums discussing something similar: https://forums.developer.apple.com/thread/105790

@jkmassel the only _potential_ fix I can think of would be to rename the launch storyboard, and see if that forces the new one to be used for existing users. Do you think that's worth doing?

**Comment by richardmtl** [comment] 2019-07-19 15:37
@frosty it's obviously not a critical bug, but it's annoying and is a bit of a "broken window" problem; if this doesn't work, what else is broken, you know?

**Comment by jkmassel** [comment] 2019-07-19 15:41
@frosty – I have no issue at all with adjusting the file name to fix this issue – obviously we can't get all the users to reinstall, and I'm quite inclined to agree with what @richardmtl is saying about broken windows.

If we can confirm that renaming that file invalidates the cache (I'm not convinced it will, because I could see the cache living a layer above this – whatever `.png` is generated by the storyboard could just be stored keyed by the app's name, rather than by the storyboard's name that generates it), I'd be _extremely_ happy to ship that out ASAP!

**Comment by frosty** [comment] 2019-07-19 15:50
Right, I'm not convinced it'll work either, but I guess we can see. @RealCarFax could you please confirm that you can still recreate the issue? If so, please don't uninstall / reinstall the app as we may want you to verify the fix! :)

**Comment by RealCarFax** [comment] 2019-07-19 18:25
Yes, I'm still seeing the blue WordPress logo on blue background on WordPress 2.8.1 with iOS 13 Beta 3

**Comment by RealCarFax** [comment] 2019-07-19 18:28
Wait! No I was mistaken! My phone made it seem like I was on 2.8.1 but it wasn't. Once I updated (no uninstall/reinstall) it is fixed - white WordPress logo on blue background. 💃

**Comment by frosty** [comment] 2019-07-21 18:50
Okay, thanks @RealCarFax!

**Comment by frosty** [comment] 2019-09-27 21:54
I think we can probably close this one unless it crops up again.

**Closed by frosty** 2019-09-27 21:54 UTC
Labels: General, [Type] Bug
