### ISSUE TITLE
Open a post with a remote auto-save, app must show a dialog asking to restore it

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-iOS#11650] opened 2019-05-07 13:12 UTC
When a user opens a published post with a remote auto-save, we must show a dialog “A more recent revision of this post exists. Restore?”. Like in Calypso:

<img width="422" alt="screenshot-2019-05-03-at-09 25 19" src="https://user-images.githubusercontent.com/40213/57301854-3a9c1600-70da-11e9-8b51-caace0fe6d33.png">

## Decision
we are splitting this from the discussion on [conflict resolution](https://github.com/wordpress-mobile/WordPress-Android/issues/10008).

**Implementation logic:**
hasLocalChanges == true -> ignore autosave and just open the post
hasLocalChanges == false && post.autosave == null -> just open the post
hasLocalChanges == false && post.autosave != null -> open the post and show the dialog. If the user clicks on restore, load the autosave revision and set hasLocalChanges to true.

```
The service to query the latest autosave for a post is:
GET https://public-api.wordpress.com/rest/v1.1/sites/$site_id/posts/$post_id/autosave
```

## Corresponding Android Ticket

https://github.com/wordpress-mobile/WordPress-Android/issues/9812

**Comment by designsimply** [comment] 2019-05-09 20:13
Noting that conflict resolution dialogs were added to WPAndroid 11.7 and would be good to review for consistency.

See https://github.com/wordpress-mobile/WordPress-Android/pull/8989 and https://github.com/wordpress-mobile/WordPress-Android/pull/9107.

<sub>(internal reference from beta testing: p5T066-Le-p2#comment-2418 cc @megsfulton )</sub>

**Comment by diegoreymendez** [comment] 2019-06-05 19:08
@osullivanchris - Autosaves are created when a published post is previewed, or when the user exists the editor without saving / published their changes.  The messaging sounds a bit confusing because it makes it sound like this is conflict resolution for revisions in web vs mobile.

Maybe the message could be something like: "There's an autosave, want to restore it?"?

**Comment by malinajirka** [comment] 2019-06-28 07:27
Just noting that we probably won't need to use the "GET https://public-api.wordpress.com/rest/v1.1/sites/$site_id/posts/$post_id/autosave" endpoint. More info https://github.com/wordpress-mobile/WordPress-Android/issues/9812#issuecomment-505802903

**Comment by malinajirka** [comment] 2019-06-28 07:29
Looking at it again, I feel like we might want to close this ticket as it's a duplicate of #9812. We moved the conflict resolution discussion to #10008, so #9812 is just about "unpublished revision dialog" again.

**Comment by malinajirka** [comment] 2019-06-28 07:30
Closing this as explained above - we can reopen it, if I missed something.

**Closed by malinajirka** 2019-06-28 07:30 UTC
Labels: 5, Posting/Editing, [Pri] Medium, [Type] Enhancement

**Comment by yaelirub** [comment] 2019-06-28 07:42
Hey @malinajirka,
I left this ticket open as the issue representing the decision we made on the Android ticket (look at the decision section in the description)

If we're closing this one we should open a new ticket for implementing that logic. I can do that tomorrow if you agree.

Also, the links in your latest comment open up an unrelated issues under wpios repository. Can you update those to link to the ones on WPAndroid please?

**Comment by osullivanchris** [comment] 2019-07-11 15:53
Discussion on paCBwp-bZ-p2 about this and the Android version https://github.com/wordpress-mobile/WordPress-Android/issues/9812
