### ISSUE TITLE
[GlobalStep] The button to confirm Image Editing reads “Insert 1”

### ISSUE THREAD

**Issue by wptester9845** [wordpress-mobile/WordPress-iOS#13425] opened 2020-02-12 09:54 UTC
### Description
The button to confirm the edit in an image reads “Insert 1” but it’s expected that the button should display a message like “Confirm” or “Done”.

### Reproduction Rate
4/4 100%

### Expected behavior
The button to confirm editing an image should reflect that and read something like “Confirm” or “Done”.

### Actual behavior
The button that confirms editing an image displays “Insert 1”.

### Steps to reproduce the behavior
1. Install WordPress 14.2
2. Log in to an account.
3. Press the “Add new” button.
4. Select the blog post option.
5. Type a title.
6. Insert an image.
7. Publish the post.
8. Enter edit mode for that post.
9. Select the image in the post editor and select “Edit”.
##### Tested on the following
iPhone XR (12.0.1)

#### Please see the attached screenshot for more information
<img width="270" src="https://user-images.githubusercontent.com/60415523/74323522-8bcdea00-4d7d-11ea-8ed7-8d49926e0dca.jpg" />

### Submitted by:
Luis Pimenta

**Comment by rachelmcr** [comment] 2020-02-12 17:52
Agreed that "Insert 1" is an odd label here. @leandroalonso is this the expected behavior as designed?

**Comment by leandroalonso** [comment] 2020-02-12 18:01
@mbshakti When the user is editing a single image should we just display "Done"?

**Comment by mbshakti** [comment] 2020-02-12 18:37
Good call - I think it makes sense to say "Done" here (since the user has already "inserted", and is simply editing)

**Comment by leandroalonso** [comment] 2020-02-12 19:05
Cool! I'll fix that. :)

**Comment by leandroalonso** [comment] 2020-02-13 15:42
Fixed in https://github.com/wordpress-mobile/WordPress-iOS/pull/13450

**Closed by leandroalonso** 2020-02-13 15:42 UTC
Labels: Media Editing, [Type] Discussion
