### ISSUE TITLE
Post-post displayed when a post fails to publish

### ISSUE THREAD

**Issue by frosty** [wordpress-mobile/WordPress-iOS#6697] opened 2017-02-16 14:55 UTC
I tried to publish a post whilst I had no connectivity. Post-post was presented, with the "Error occurred during publishing" HUD displayed over the top.

![img_6140](https://cloud.githubusercontent.com/assets/4780/23025925/61fb9a24-f457-11e6-8ff1-90357efdb867.PNG)

Tested with the hybrid editor, latest WPiOS internal (7.0.0.20170214), iPhone 7, iOS 10.2.1.

Similarly, Aztec just displays post-post when I try to publish with no connectivity. The HUD is not displayed.

cc @nheagy

**Comment by hoverduck** [comment] 2017-02-27 16:39
Closing as duplicate of https://github.com/wordpress-mobile/WordPress-iOS/issues/6479

**Closed by hoverduck** 2017-02-27 16:39 UTC
Labels: Posting/Editing, [Type] Bug
