### ISSUE TITLE
Upload pictures from Iphone not showing in website or in gallery

### ISSUE THREAD

**Issue by furios4you** [wordpress-mobile/WordPress-iOS#21617] opened 2023-09-21 11:03 UTC
### Expected behavior
convert heic photo to jpg and upload. In the past everyting was ok. 
<img width="1363" alt="Captură de ecran din 2023-09-21 la 14 00 22" src="https://github.com/wordpress-mobile/WordPress-iOS/assets/145669615/b42038cc-490e-4572-a976-782fedfde652">
<img width="1251" alt="Captură de ecran din 2023-09-21 la 14 00 15" src="https://github.com/wordpress-mobile/WordPress-iOS/assets/145669615/f2378d3c-6749-493a-8093-0d4b8a9ad72d">

### Actual behavior
not showing pictures  in website or Media Gallery

**Comment by twstokes** [comment] 2023-09-21 21:16
Thanks for reporting @furios4you - this may be a regression.

I tested this flow with version `23.2.1` of the Jetpack app and can confirm the issue with the following steps: 
1. Take an HEIC photo
2. Upload it to a self-hosted site using the app's Media Library view
3. Open the Media Library view on web
4. Observe that the image isn't shown

I then tested `23.1` and repeated the steps where the upload succeeded.

**Comment by kean** [comment] 2023-09-21 21:48
Workaround (iOS 17+): tap "Options" in the bottom-left corner of the native picker and select the "Most Compatible" format. It uses "Automatic" by default.

<img width="340" src="https://github.com/wordpress-mobile/WordPress-iOS/assets/1567433/f955165d-1bae-4643-a4c1-64ae8c776838">

**Comment by cometgrrl** [comment] 2023-09-27 00:36
I ran into something similar. Let me know if you'd like this filed as a different bug.

I'm using iOS 17 developer beta, iPhone 14 pro, Jetpack 23.2.2.

I uploaded an HEIC image to my dotcom site, and it shows in the media library and when creating the post, but then as a broken image on the live post. It also prevented the post from auto-sharing to Tumblr.

> Workaround (iOS 17+): tap "Options" in the bottom-left corner of the native picker and select the "Most Compatible" format. It uses "Automatic" by default.

I don't see this on my phone.

![Screenshot 2023-09-26 at 5 34 52 PM](https://github.com/wordpress-mobile/WordPress-iOS/assets/86427589/674776c8-5c6d-4e33-93b4-765caab95abe)

**Comment by twstokes** [comment] 2023-09-27 02:20
👋 @cometgrrl (and @furios4you) this fix is currently in the 23.3 beta which will be in the App Store [around October 2nd](https://github.com/wordpress-mobile/WordPress-iOS/milestone/257).

You can get the beta today if you install the TestFlight version by using [this link](https://testflight.apple.com/join/AZG7g4Bg).

**Comment by cometgrrl** [comment] 2023-09-27 23:28
I downloaded the 23.3 beta, and at first, I thought it resolved the issue, but I realized I checked the media library in Calypso, not wp-admin. It's still broken in wp-admin for me.

I uploaded a bunch of HEIC photos using 23.3 and they were not converted to jpg. I haven't tried using them in a post, since I assume they won't work.

<img width="749" alt="image" src="https://github.com/wordpress-mobile/WordPress-iOS/assets/86427589/291b1505-2c47-4ad9-95b0-b0f3bc298d7a">

**Comment by kean** [comment] 2023-09-28 00:07
The fix hasn't made it into the latest beta yet. It will be available in 23.3.0.2. I'd appreciate if you could test it again once the new beta is available.

**Comment by cometgrrl** [comment] 2023-09-28 00:09
Happy to do so!  I’ll keep an eye out for it and report back.

**Comment by twstokes** [comment] 2023-09-28 01:15
Apologies! I thought I had confirmed the fix landed.

**Comment by wlanowski** [comment] 2023-09-29 16:31
Is it possible to make a temp fix with a server-side plugin? It is really important for my projects to get this fixed soon for production environment, without beta-versions...

**Comment by mokagio** [comment] 2023-09-30 04:36
Hi @wlanowski. The app version with this fix should become available in the next few days.

If you are willing to [give the beta a try](https://testflight.apple.com/join/AkJQt8Pw), the version with the fix, 23.3.0.2 should be available there soon, too.

Let us know how you go. Thank you for your help.

**Comment by wlanowski** [comment] 2023-09-30 08:43
> Workaround (iOS 17+): tap "Options" in the bottom-left corner of the native picker and select the "Most Compatible" format. It uses "Automatic" by default.

How to get this button? We don't see it, although updated to iOS 17.

Is there a release date for 23.3.0.2? This bug is really bad for my customers. Taking photos in JPEG is no option. There should be a real quick hotfix very soon. This bug makes it impossible to use the App in the known way...

**Comment by twstokes** [comment] 2023-10-02 15:39
👋 @wlanowski `23.3` has been released in the App Store and is rolling out to all users. If it's not available yet, it should be soon.

I'm going to close this issue now that the version with the fix has been released, but please reopen if needed.

**Closed as completed by twstokes** 2023-10-02 15:39 UTC
Labels: [Pri] High, Media
