### ISSUE TITLE
Reports of Share Extension crashing when sharing from Day One Journal App

### ISSUE THREAD

**Issue by jkmassel** [wordpress-mobile/WordPress-iOS#10263] opened 2018-10-16 18:00 UTC
We've gotten a report from Day One (https://dayoneapp.com) that the share extension is crashing when sharing content.

Recording it here to track any additional instances of issues:
1495345-zen

**Comment by designsimply** [comment] 2019-05-23 00:29
Including a copy of the report sent in 1495345 for reference:

<blockquote>Hello! I work for Day One Journal support. We've received a few reports of the WordPress iOS share extension crashing when sharing journal entries from Day One to WordPress.</blockquote>

I did a search for `"Day One" sharing iOS` in Zendesk and found one additional report in 1409740-zen from Sep 2018 stating:

> I'm trying to share on my iPhone from Day One to the WordPress app using the sharing sheet. However, only WordPress.com sites appear to work with the sharing sheet. My self-hosted site otherwise works just fine in the WordPress app, but doesn't show up as an option on the sharing sheet. Is this by design? Or a bug? I'd really like to be able to publish to my self-hosted WordPress site this way.

That report doesn't mention crashing though. It does note that a request to support sharing to self-hosted sites has been filed at https://github.com/wordpress-mobile/WordPress-iOS/issues/6584 and so it may not the same issue reported in 1495345. 

Noe: it would be helpful to note the type of site someone is trying to share to for any future reports of this type of crash.

I am recommending to close this issue due to the low volume of reports and because the sharing extension has been updated recently. @nheagy may I get your opinion about whether or not to close—would your vote be to keep this open in favor of more in-depth testing?

**Comment by designsimply** [comment] 2019-10-25 15:52
Moving up in priority because Gutenberg Mobile may be working on the share extension sometime soon and it would be good to have some attention on this issue before that if we can.

**Comment by leandroalonso** [comment] 2020-02-18 16:30
I wasn't able to reproduce this crash with the version `4.7 (597)` of Day One Journal app and the WordPress `14.1` (iPhone 11 Pro - iOS 13.3.1).

**Comment by designsimply** [comment] 2020-03-26 00:04
Closing because there have been no new reports of the same problem since Oct 2018 and because we tested recently and couldn't replicate the problem.

If you find that users are still having trouble with sharing from the Day One Journal app to the WordPress app, please leave us a comment here noting the version numbers where the problem is happening and we can re-open the case for another look at that time. Thank you!

**Closed by designsimply** 2020-03-26 00:04 UTC
Labels: Sharing, [Type] Bug, [Type] Crash
