### ISSUE TITLE
Uploaded images should have the correct rotation in it's metadata

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-iOS#7259] opened 2017-05-30 09:23 UTC
### Expected behavior
When an image is added to a post, it should contain the correct rotation metadata, so it shows up in correct orientation on mobile browsers.

### Actual behavior
A user reported that her images are not oriented correctly. Here is a post with this issue, just check it on mobile safari: http://livefromrhodeisland.com/providence/

![screenshot_20170530-121527](https://cloud.githubusercontent.com/assets/662023/26576594/1512ec86-4532-11e7-9b69-52d4c9bbbf04.png)

### Steps to reproduce the behavior

I am not sure about the steps, but she said it happened for photos taken with her iPad as well as an external camera. I've also tested this on Android (in Chrome) it looks incorrect as well. 

/cc @SergioEstevao

##### Tested on iPad Air (WiFi), iOS 10.3.1, WPiOS 7.5

**Comment by designsimply** [comment] 2017-06-06 22:39
Closing as a duplicate of https://github.com/Automattic/wp-calypso/issues/13145

Please re-open if this needs to be fixed in the mobile app separately from Calypso. I wasn't sure about that!

**Closed by designsimply** 2017-06-06 22:39 UTC
Labels: Media, Posting/Editing, [Type] Bug
